/* De kerndoelen bij de leerroute. Letterlijk uit het Uitvoeringsbesluit WVO 2020,
   bijlage 1 (de vernieuwde kerndoelen Nederlands en rekenen en wiskunde, Stb. 2026,
   198, in werking sinds 1 augustus 2026). Gecontroleerd op 10 oktober 2026.

   Code: nl = Nederlands (kerndoel 1 tot en met 9), rw = rekenen en wiskunde
   (10 tot en met 17); daarna het nummer, de letter van de doelzin en na de
   punt de letter van het onderdeel ("Het gaat hierbij om: a, b, ...").
   hv: het onderdeel is een aanvulling voor havo en vwo.

   KOPPEL zegt per groep van de leerroute aan welke onderdelen hij werkt:
   liever twee raak dan zes vaag. */
window.LR_KERNDOELEN = {
  bron:'https://zoek.officielebekendmakingen.nl/stb-2026-198.html',
  wet:'https://wetten.overheid.nl/BWBR0045787/2026-08-01#Bijlage1',
  kd:{
    'nl1':'De school stimuleert de taalcompetentie van leerlingen.',
    'nl2':'De leerling begrijpt teksten.',
    'nl3':'De leerling produceert teksten.',
    'nl4':'De leerling voert gesprekken.',
    'nl5':'De leerling ontwikkelt zich als bewuste taalgebruiker.',
    'nl6':'De leerling toont inzicht in taal als systeem.',
    'nl7':'De leerling verkent het gebruik van taal.',
    'nl8':'De leerling doet ervaring op met literatuur.',
    'nl9':'De leerling toont inzicht in literatuur.',
    'rw10':'De leerling redeneert en rekent met getallen, grootheden en vergelijkingen.',
    'rw11':'De leerling interpreteert data en kansen.',
    'rw12':'De leerling toont inzicht in patronen en verbanden.',
    'rw13':'De leerling toont inzicht bij meetkundig handelen.',
    'rw14':'De leerling gebruikt wiskundige denk-werkwijzen.',
    'rw15':'De leerling gebruikt wiskundetaal en wiskundig gereedschap.',
    'rw16':'De leerling ontwikkelt een wiskundige attitude.',
    'rw17':'De leerling past wiskunde toe in bekende en nieuwe situaties.'
  },
  zin:{
    'nl1A':'De school zorgt voor een rijke taal- en leesomgeving.',
    'nl1B':'De school stimuleert de taalontwikkeling van de leerling in alle leergebieden.',
    'nl2A':'De leerling toont begrip van zakelijke en literaire teksten.',
    'nl2B':'De leerling evalueert en reflecteert op zakelijke en literaire teksten.',
    'nl2C':'De leerling verkent de betrouwbaarheid van verschillende bronnen.',
    'nl3A':'De leerling spreekt en schrijft afgestemd op doel, publiek en context.',
    'nl3B':'De leerling gebruikt taal op een creatieve manier.',
    'nl3C':'De leerling schrijft om tot kennisopbouw of begrip te komen.',
    'nl4A':'De leerling voert gesprekken afgestemd op doel, gesprekspartner(s) en context.',
    'nl4B':'De leerling voert gesprekken om tot kennisopbouw, begrip of een aanpak te komen.',
    'nl5A':'De leerling reflecteert op het proces en evalueert het product van een taalactiviteit.',
    'nl6A':'De leerling beschouwt de relatie tussen vorm en betekenis van taal.',
    'nl6B':'De leerling toont inzicht in regels en procedures voor spelling, formulering en interpunctie.',
    'nl6C':'De leerling toont inzicht in zakelijke genres.',
    'nl6D':'De leerling verkent de overtuigingskracht van teksten.',
    'nl7A':'De leerling verkent hoe je met taal uiting geeft aan identiteit.',
    'nl7B':'De leerling verkent taalvariatie en taalverandering in het Nederlandse taalgebied.',
    'nl8A':'De leerling ontwikkelt een eigen leesvoorkeur.',
    'nl8B':'De leerling verkent de waarde van literatuur.',
    'nl9A':'De leerling toont inzicht in verhalende teksten.',
    'nl9B':'De leerling toont inzicht in genrekenmerken van literatuur.',
    'nl9C':'De leerling verkent literatuur die geschreven is in verschillende periodes en contexten.',
    'nl9D':'De leerling legt verbanden tussen de inhoud van literatuur en de periode en context waarin deze is geschreven.',
    'rw10A':'De leerling redeneert en rekent met getallen en grootheden.',
    'rw10B':'De leerling gebruikt wiskundige vergelijkingen.',
    'rw11A':'De leerling interpreteert, representeert en analyseert data.',
    'rw11B':'De leerling redeneert en rekent met kansen.',
    'rw12A':'De leerling analyseert en redeneert over patronen en verbanden.',
    'rw13A':'De leerling analyseert en redeneert over de twee- en driedimensionale ruimte.',
    'rw14A':'De leerling lost wiskundige problemen en toepassings-problemen op.',
    'rw14B':'De leerling maakt en gebruikt wiskundige modellen.',
    'rw14C':'De leerling toont de juistheid van wiskundige beweringen en redeneringen aan.',
    'rw14D':'De leerling bedenkt en beschrijft algoritmes.',
    'rw15A':'De leerling gebruikt wiskundetaal en wiskundige representaties.',
    'rw15B':'De leerling gebruikt meetinstrumenten en andere wiskundige instrumenten.',
    'rw16A':'De school stimuleert de ontwikkeling van een wiskundige attitude bij leerlingen.',
    'rw17A':'De leerling herkent en gebruikt wiskunde in alledaagse, maatschappelijke en beroepsmatige situaties.',
    'rw17B':'De school ondersteunt het gebruik van wiskunde in verschillende leergebieden.'
  },
  deel:{
    'nl1A.a':'aanbieden van taalactiviteiten in betekenisvolle contexten',
    'nl1A.b':'aanbieden van een veelzijdig en actueel aanbod van jeugd- en Young Adult literatuur binnen een vaste leesroutine',
    'nl1A.c':'aanbieden van kennis en vaardigheden uit het leergebied Nederlands in onderlinge samenhang',
    'nl1A.d':'stimuleren van de leesmotivatie en de durf om te spreken en te schrijven',
    'nl1A.e':'ruimte bieden aan verschillende talen en taalvariëteiten van leerlingen',
    'nl1B.a':'stimuleren van betekenisvolle activiteiten waarin school- en vaktaal en vakspecifieke taalvaardigheden verworven kunnen worden',
    'nl1B.b':'stimuleren van het gebruiken van rijke teksten over inhoudelijke thema’s in alle leergebieden',
    'nl1B.c':'stimuleren van taalproductie en interactie in alle leergebieden',
    'nl1B.d':'stimuleren van aandacht voor taalverzorging en taalgebruik in alle leergebieden',
    'nl1B.e':'aanbieden van een schoolbrede set van aanpakken en flexibel inzetbare strategieën bij het ondersteunen van taalactiviteiten in de andere leergebieden',
    'nl2A.a':'aandachtig luisteren, kijken of aandachtig vloeiend lezen',
    'nl2A.b':'inzetten en uitbreiden van woordenschat, kennis over taal en kennis van de wereld',
    'nl2A.c':'inzetten en uitbreiden van kennis over de vorm van teksten: tekstsoorten, tekststructuren, literaire genres, verteltechnieken',
    'nl2A.d':'beschrijven van perspectieven, communicatieve doelen, publiek, context',
    'nl2A.e':'in eigen woorden weergeven van de hoofd- en bijzaken, de hoofdgedachte en betekenis van een tekst, passend bij het lees- of luisterdoel',
    'nl2A.f':'flexibel toepassen van verschillende aanpakken en begripsverhogende strategieën',
    'nl2B.a':'benoemen van inhoudelijke relaties binnen en tussen verschillende teksten',
    'nl2B.b':'benoemen van verschillen en overeenkomsten in feiten, meningen, argumentatie en perspectieven',
    'nl2B.c':'benoemen van tegenstrijdige en overeenkomstige inhoud en framing binnen en tussen teksten',
    'nl2B.d':'evalueren van bruikbaarheid van teksten',
    'nl2B.e':'reflecteren op de waarde, inhoud en vorm van teksten',
    'nl2C.a':'benoemen van kenmerken van aangereikte bronnen: maker, tekstsoort en verschijningsdatum',
    'nl2C.b':'benoemen van inhouds- en vormelementen die misleidend zijn of vragen oproepen',
    'nl2C.c':'vergelijkend beoordelen en selecteren van bronnen op basis van hun betrouwbaarheid',
    'nl3A.a':'hanteren van een passende aanpak',
    'nl3A.b':'in eigen woorden verwerken van informatie uit verschillende bronnen tot een gestructureerde tekst met bronvermelding',
    'nl3A.c':'inzetten en uitbreiden van kennis over de vorm van teksten: tekstsoorten, tekststructuren, verteltechnieken',
    'nl3A.d':'schrijven op letter-, schrift- en tekstniveau met een leesbaar handschrift en typschrift, en verstaanbaar spreken',
    'nl3A.e':'reviseren van de tekst met het oog op doelgerichte communicatie: taalgebruik en taalverzorging',
    'nl3B.a':'verkennen van creatief taalgebruik van anderen in literaire en zakelijke teksten',
    'nl3B.b':'verwoorden van eigen gedachten, ervaringen, gevoelens en fantasieën',
    'nl3B.c':'experimenteren met klanken, woorden, zinnen, literaire genres, taalregels, taalconventies en visuele vormen',
    'nl3B.d':'verkennen van kenmerken van de ontluikende eigen stijl en het talige repertoire',
    'nl3B.e':'waarderen van creatief taalgebruik',
    'nl3C.a':'weergeven van hoofd- en bijzaken, indrukken en vragen bij gelezen, bekeken of beluisterde inhoud',
    'nl3C.b':'samenvatten van gelezen inhoud',
    'nl3C.c':'verwoorden, onderbouwen en ordenen van gedachten, verworven inzichten en kennis in een tekst of schema',
    'nl3C.d':'inzetten en uitbreiden van school- en vaktaal',
    'nl3C.e':'schrijven op letter-, schrift- en tekstniveau met een leesbaar handschrift en typschrift',
    'nl4A.a':'inzetten en uitbreiden van vaardigheden om gesprekken constructief te laten verlopen: luisteren, herkennen van signalen en passend reageren op de gesprekspartner(s)',
    'nl4A.b':'actief deelnemen aan gesprekken',
    'nl4A.c':'afstemmen van taalgebruik, stemgebruik en non-verbale communicatie op communicatief doel en on- en offline context',
    'nl4A.d':'verwerven en gebruiken van informatie afgestemd op kennis, achtergrond, standpunt en perspectief van de gesprekspartner(s)',
    'nl4A.e':'toepassen van gespreks- en taalconventies, passend bij de gespreksvorm',
    'nl4B.a':'verwoorden van kennis, ideeën en standpunten met onderbouwing',
    'nl4B.b':'vragen om toelichting, verklaring of bevestiging',
    'nl4B.c':'luisteren naar, doorvragen op en ter discussie stellen van de ideeën en perspectieven van gesprekspartners',
    'nl4B.d':'accepteren of verwerpen van andermans ideeën met argumenten',
    'nl4B.e':'samenvatten van inzichten, verwoorden van oplossingen of trekken van conclusies',
    'nl5A.a':'ontvangen en geven van feedback',
    'nl5A.b':'reflecteren op het proces: de gemaakte keuzes in aanpak en strategieën tijdens en na de uitvoering van een taalactiviteit',
    'nl5A.c':'beoordelen van het product van de taalactiviteit aan de hand van aangereikte criteria',
    'nl5A.d':'formuleren van leerdoelen voor proces en product bij toekomstige taalactiviteiten',
    'nl6A.a':'verkennen hoe letterklanken, klemtoon, intonatie en ritme samenhangen met de betekenis van taal',
    'nl6A.b':'inzicht tonen in de opbouw van complexe woorden om de betekenis af te leiden',
    'nl6A.c':'beschrijven hoe de betekenis in complexe zinnen bepaald wordt door de woordvolgorde en de zinsdelen',
    'nl6A.d':'verkennen hoe register, stijlmiddelen en opbouw van teksten een relatie hebben met het communicatieve doel',
    'nl6A.e':'functioneel gebruiken van taalkundige begrippen en taalbeschouwingsstrategieën bij het redeneren over de spelling en grammatica',
    'nl6B.a':'correct formuleren op woord-, zins- en tekstniveau',
    'nl6B.b':'verbinden van vorm en betekenis om de correcte spelling te achterhalen',
    'nl6B.c':'ontwikkelen van spellingbewustzijn en spellinggeweten',
    'nl6B.d':'reflecteren op gemaakte keuzes in woorden en zinnen',
    'nl6B.e':'inzetten van hulpmiddelen en bronnen om regels en procedures correct toe te passen en teksten te redigeren',
    'nl6C.a':'benoemen van kenmerken met betrekking tot context, doel, inhoud en vorm, passend bij een genre',
    'nl6C.b':'herkennen van genrespecifieke kenmerken van taalgebruik',
    'nl6C.c':'reflecteren op gebruik van genrekenmerken in relatie tot het communicatieve doel',
    'nl6D.a':'herkennen van standpunt en argumenten in teksten',
    'nl6D.b':'herkennen van de context waarin de argumentatie plaatsvindt',
    'nl6D.c':'verkennen van de geloofwaardigheid van de spreker of schrijver',
    'nl6D.d':'beschrijven hoe gevoelens worden opgeroepen bij het publiek',
    'nl7A.a':'verkennen van het eigen talige repertoire in relatie tot hoe je wilt overkomen en tot welke groepen je wilt behoren: talen en taalvariëteiten, gebaren, lichaamstaal',
    'nl7A.b':'experimenteren met het eigen talige repertoire in relatie tot publiek, doel en context',
    'nl7A.c':'reflecteren op hoe je overkomt op anderen op basis van bewuste keuzes in het eigen talige repertoire',
    'nl7A.d':'reflecteren op hoe andere mensen hun talige repertoire benutten om uiting te geven aan hun identiteit',
    'nl7A.e':'waarderen van het eigen talige repertoire',
    'nl7B.a':'verkennen van verschillende taalvariëteiten van het Nederlands: school- en vaktaal, groeps- en streektalen en talen in beroepscontexten',
    'nl7B.b':'vergelijken van de contexten waarin verschillende talen en taalvariëteiten worden gebruikt',
    'nl7B.c':'benoemen van overeenkomsten en verschillen tussen het Nederlands en andere talen en taalvariëteiten op klank-, woord- en zinsniveau',
    'nl7B.d':'reflecteren op overtuigingen over verschillende talen en taalvariëteiten',
    'nl7B.e':'verkennen van veranderingen in taalgebruik onder invloed van tijd, media en maatschappelijke ontwikkelingen',
    'nl8A.a':'lezen en beluisteren van boeken en teksten, van verschillende schrijvers en literaire genres',
    'nl8A.b':'geven van een waardeoordeel over gelezen of beluisterde boeken en teksten op basis van literaire genres, eigen interesse en belevingswereld',
    'nl8A.c':'aangaan van nieuwe leesuitdagingen op basis van eerdere lees-, luister- en kijkervaringen',
    'nl8A.d':'beargumenteren van persoonlijke voorkeur op basis van reflectie op ervaringen met literatuur',
    'nl8B.a':'verwoorden van persoonlijke leeservaring en -beleving na het lezen van literatuur',
    'nl8B.b':'verwoorden van opgedane inzichten en kennis over zichzelf op basis van literatuur',
    'nl8B.c':'verwoorden van opgedane inzichten en kennis over anderen op basis van literatuur',
    'nl8B.d':'verwoorden van opgedane inzichten en kennis over de wereld en culturen op basis van literatuur',
    'nl9A.a':'beschrijven welk probleem of welke wens van een hoofdpersoon de motor van het verhaal is en hoe het verhaal zich ontwikkelt',
    'nl9A.b':'beschrijven van de verschillende rollen van personages, hun karakter en ontwikkeling',
    'nl9A.c':'beschrijven hoe een schrijver verschillende verteltechnieken gebruikt om bepaalde effecten te bereiken',
    'nl9A.d':'beschrijven hoe tijd, plaats en omstandigheden het verhaal beïnvloeden',
    'nl9B.a':'onderscheiden van poëzie-, proza- en dramateksten op basis van genrekenmerken',
    'nl9B.b':'benoemen van het effect op de leesbeleving van verschillende genrekenmerken',
    'nl9B.c':'analyseren van kenmerkend taalgebruik in literaire genres: figuurlijk taalgebruik, stijlfiguren, rijm en ritme',
    'nl9B.d':'analyseren van kenmerkende visuele elementen in literaire genres: illustraties, vormgeving, typografie',
    'nl9C.a':'lezen, bekijken of beluisteren van literatuur uit verschillende tijden',
    'nl9C.b':'verkennen van de tijd en context waarin het verhaal geschreven is',
    'nl9C.c':'verwoorden van verschillen en overeenkomsten tussen historische teksten en de eigen tijd, leef- en belevingswereld',
    'nl9C.d':'verwoorden van universele thema’s in literatuur door de tijd heen',
    'nl9D.a':'beschrijven van verschillen en overeenkomsten tussen oudere en hedendaagse literatuur',
    'nl9D.b':'beschrijven van verschillen en overeenkomsten tussen versies van literaire teksten',
    'nl9D.c':'beschrijven van relaties tussen de periode en context waarin de tekst is geschreven en het wereldbeeld van de schrijver',
    'nl9D.d':'beschrijven van opgedane inzichten over historische tijdvakken',
    'nl9D.e':'herkennen van literair-culturele sporen in literatuur uit heden en verleden',
    'rw10A.a':'optellen, aftrekken, vermenigvuldigen, delen, machtsverheffen en worteltrekken',
    'rw10A.b':'wendbaar en met inzicht gebruiken van getallen en hun eigenschappen, en enkelvoudige en samengestelde grootheden en eenheden',
    'rw10A.c':'wendbaar en met inzicht gebruiken van en rekenen met verhoudingen',
    'rw10A.d':'relaties leggen tussen grootheden en eenheden, tussen grootheden onderling en tussen eenheden onderling',
    'rw10A.e':'bepalen van afmetingen en inhoud van meetkundige figuren',
    'rw10A.f':'rekenen met standaardprocedures en eigenschappen van bewerkingen',
    'rw10A.g':'herleiden van algebraïsche uitdrukkingen',
    'rw10A.h':'gebruiken van de wetenschappelijke notatie van grote en kleine getallen',
    'rw10A.i':'meten van grootheden en daarbij meet(on)nauwkeurigheid en effecten daarvan bepalen',
    'rw10B.a':'interpreteren van wiskundige vergelijkingen en gevonden oplossingen',
    'rw10B.b':'opstellen van vergelijkingen bij situaties',
    'rw10B.c':'relaties leggen tussen gegeven vergelijkingen en situaties',
    'rw10B.d':'oplossen van lineaire vergelijkingen',
    'rw10B.e':'oplossen van lineaire, kwadratische en machtsvergelijkingen',
    'rw10B.f':'oplossen van een stelsel lineaire vergelijkingen',
    'rw10B.g':'oplossen van ongelijkheden',
    'rw11A.a':'opstellen van tabellen bij data',
    'rw11A.b':'beredeneerd kiezen, berekenen en interpreteren van gemiddelde, modus en mediaan en berekenen en interpreteren van spreidingsbreedte',
    'rw11A.c':'maken van grafische representaties van data en daaruit conclusies trekken',
    'rw11A.d':'beredeneerd kiezen van representaties',
    'rw11A.e':'interpreteren van grafische representaties en beredeneren of daarbij gepresenteerde conclusies wel, niet of deels kloppen',
    'rw11A.f':'grafische representaties: diagrammen, grafieken en infographics',
    'rw11A.g':'analyseren van univariate en bivariate datasets',
    'rw11A.h':'beredeneerd kiezen en gebruiken van meetniveaus: nominaal, ordinaal, interval en ratio',
    'rw11A.i':'beredeneerd kiezen, berekenen en interpreteren van spreidingsbreedte en interkwartielafstand',
    'rw11A.j':'vergelijken van twee datasets',
    'rw11A.k':'onderscheiden van correlatie en causaliteit',
    'rw11B.a':'kansen weergeven als breuk, verhouding, percentage en decimaal getal',
    'rw11B.b':'op basis van kansen inschatten hoe waarschijnlijk het is dat gebeurtenissen plaatsvinden',
    'rw11B.c':'berekenen van verwachtingswaardes',
    'rw11B.d':'berekenen van kansen met behulp van kansregels en combinatoriek',
    'rw11B.e':'interpreteren van empirische en theoretische kansen',
    'rw12A.a':'herkennen, beschrijven en voortzetten van patronen in rijen getallen en figuren',
    'rw12A.b':'identificeren van patronen en verbanden in datasets',
    'rw12A.c':'identificeren en beschrijven van verbanden tussen grootheden',
    'rw12A.d':'weergeven van patronen en verbanden in een beschrijving, tabel, grafiek en formule, en deze weergaven in elkaar omzetten',
    'rw12A.e':'beschrijven en interpreteren van standaardverbanden in verschillende representaties',
    'rw12A.f':'beschrijven van een patroon in een rij getallen met een formule',
    'rw12A.g':'uitleggen wanneer een verband een functie is',
    'rw12A.h':'beschrijven van het veranderingsgedrag van een functie',
    'rw12A.i':'herkennen en beschrijven van standaardverbanden in verschillende representaties',
    'rw12A.j':'gebruiken van de eigenschappen van standaardverbanden',
    'rw13A.a':'redeneren met en over eigenschappen van meetkundige figuren en begrippen en deze eigenschappen gebruiken in berekeningen en constructies',
    'rw13A.b':'redeneren met kijklijnen',
    'rw13A.c':'construeren en interpreteren van tweedimensionale representaties van driedimensionale figuren en relaties leggen tussen twee- en driedimensionale representaties van figuren',
    'rw13A.d':'meetkundige transformaties: verschuiven, draaien, spiegelen, vergroten en verkleinen van figuren',
    'rw13A.e':'redeneren met hoeken en eigenschappen van hoeken in meetkundige figuren',
    'rw13A.f':'berekenen van hoeken en afmetingen van rechthoekige driehoeken met goniometrische verhoudingen',
    'rw14A.a':'analyseren hoe een probleem met wiskunde kan worden opgelost',
    'rw14A.b':'bedenken en uitvoeren van een aanpak voor een niet-routinematig oplosbaar probleem',
    'rw14A.c':'gebruiken van heuristieken',
    'rw14A.d':'bewerken van de uitkomsten van berekeningen tot een oplossing van een probleem',
    'rw14A.e':'reflecteren op aanpak, uitvoering en oplossing',
    'rw14B.a':'weergeven van een situatie, ook met gebruik van ICT',
    'rw14B.b':'selecteren van relevante kenmerken en weglaten van niet relevante kenmerken',
    'rw14B.c':'beredeneerd kiezen van een geschikt model en evalueren van deze keuze',
    'rw14B.d':'gebruiken van abstracte modellen om rekenaanpakken te laten zien, situaties te interpreteren en problemen op te lossen',
    'rw14B.e':'wiskundig modelleren volgens een modelleercyclus',
    'rw14C.a':'formuleren van vermoedens en beweringen',
    'rw14C.b':'gebruiken van logische redeneerprincipes en daarmee conclusies trekken',
    'rw14C.c':'gebruiken van wiskundetaal en wiskundige representaties bij het formuleren en onderbouwen van een redenering',
    'rw14C.d':'kritisch evalueren van eigen en andermans wiskundige redeneringen',
    'rw14C.e':'wiskundig bewijzen van een bewering',
    'rw14C.f':'verantwoorden van een redeneeraanpak in formele stappen',
    'rw14D.a':'algoritmes met een beperkt aantal stappen',
    'rw14D.b':'beschrijven hoe een algoritme tot een vast resultaat leidt',
    'rw14D.c':'beoordelen van het resultaat van een doorlopen algoritme',
    'rw14D.d':'bedenken van een algoritme voor de aanpak van een probleem',
    'rw14D.e':'beschrijven van mogelijkheden en beperkingen in de bruikbaarheid van algoritmes',
    'rw14D.f':'verbeteren van een algoritme door een aanpassing te bedenken',
    'rw14D.g':'schematisch beschrijven van een algoritme',
    'rw15A.a':'gebruiken van wiskundige symbolen, notaties en begrippen',
    'rw15A.b':'leesbaar weergeven van berekeningen en probleemaanpakken',
    'rw15A.c':'kiezen en bedenken van representaties om berekeningen en wiskundige redeneringen weer te geven en uit te wisselen',
    'rw15A.d':'kritisch beoordelen van een representatie',
    'rw15A.e':'relaties leggen tussen verschillende representaties van een wiskundig concept',
    'rw15B.a':'beredeneerd kiezen voor gebruik van een instrument op basis van de mogelijkheden, beperkingen en meetnauwkeurigheid',
    'rw15B.b':'vooraf schatten van meetresultaten en uitkomsten',
    'rw15B.c':'gebruiken van een instrument en de bijbehorende wiskundetaal',
    'rw15B.d':'bepalen, interpreteren en beoordelen van het resultaat',
    'rw15B.e':'uitvoeren van berekeningen met een digitaal instrument, en aangeven van de mate van nauwkeurigheid van de verkregen uitkomst',
    'rw16A.a':'laten zien van het nut en de kracht van wiskunde in uiteenlopende toepassingen',
    'rw16A.b':'stimuleren van een onderzoekende en kritische houding ten aanzien van getallen en andere wiskundige informatie',
    'rw16A.c':'laten reflecteren op eigen en andermans rekenwijze en overig wiskundig handelen',
    'rw16A.d':'inzicht bieden in hoe leerlingen wiskunde kunnen inzetten in de bovenbouw en het verdere leven',
    'rw17A.a':'gebruiken van getallen en andere wiskundige concepten in concrete, voor de leerling relevante dagelijkse en beroepsmatige situaties',
    'rw17A.b':'gebruiken van wiskundige instrumenten bij meten en andere praktische handelingen',
    'rw17A.c':'wiskunde gebruiken bij het nemen van beslissingen en het oplossen van problemen',
    'rw17A.d':'herkennen en beschrijven dat met grafische representaties een bepaalde boodschap wordt overgebracht of benadrukt',
    'rw17A.e':'gebruiken en beoordelen van wiskundige informatie uit de samenleving en de media bij het vormen van een mening',
    'rw17A.f':'herkennen en beschrijven hoe wiskunde in allerlei beroepen op uiteenlopende manieren een rol speelt',
    'rw17B.a':'aanbieden van wiskundige concepten en denk-werkwijzen in onderlinge samenhang',
    'rw17B.b':'laten zien hoe verschillende leergebieden wiskundetaal en wiskundige representaties gebruiken',
    'rw17B.c':'afstemmen hoe rekenaanpakken en andere wiskundige aanpakken bij verschillende leergebieden worden uitgevoerd',
    'rw17B.d':'laten gebruiken van wiskundige modellen, wiskundige instrumenten, algoritmes en formules in verschillende leergebieden'
  },
  hv:{
    'nl6C.a':1,
    'nl6C.b':1,
    'nl6C.c':1,
    'nl6D.a':1,
    'nl6D.b':1,
    'nl6D.c':1,
    'nl6D.d':1,
    'nl9D.a':1,
    'nl9D.b':1,
    'nl9D.c':1,
    'nl9D.d':1,
    'nl9D.e':1,
    'rw10A.f':1,
    'rw10A.g':1,
    'rw10A.h':1,
    'rw10A.i':1,
    'rw10B.e':1,
    'rw10B.f':1,
    'rw10B.g':1,
    'rw11A.g':1,
    'rw11A.h':1,
    'rw11A.i':1,
    'rw11A.j':1,
    'rw11A.k':1,
    'rw11B.d':1,
    'rw11B.e':1,
    'rw12A.f':1,
    'rw12A.g':1,
    'rw12A.h':1,
    'rw12A.i':1,
    'rw12A.j':1,
    'rw13A.e':1,
    'rw13A.f':1,
    'rw14B.e':1,
    'rw14C.e':1,
    'rw14C.f':1,
    'rw14D.f':1,
    'rw14D.g':1,
    'rw15B.e':1
  },
  koppel:{
    /* rekenen: getallen */
    'getal-begrip':['rw10A.b', 'rw15A.a'],
    'splits-tien':['rw10A.a', 'rw10A.b'],
    'plus20':['rw10A.a', 'rw15A.c'],
    'min20':['rw10A.a', 'rw15A.c'],
    'plus100':['rw10A.a', 'rw10A.b', 'rw15A.c'],
    'min100':['rw10A.a', 'rw10A.b', 'rw15A.c'],
    'plus1000':['rw10A.a', 'rw10A.b', 'rw15A.c'],
    'keer-begrip':['rw10A.a', 'rw15A.e'],
    'tafel-trucs':['rw10A.a', 'rw10A.b'],
    'deel-tafel':['rw10A.a', 'rw17A.a'],
    'keer-groot':['rw10A.a', 'rw10A.b', 'rw15A.c'],
    'deel-groot':['rw10A.a', 'rw10A.b', 'rw15A.c'],
    'groot-getal':['rw10A.b', 'rw17A.e'],
    'cijf-plusmin':['rw10A.a', 'rw15A.b', 'rw14D.b'],
    'cijf-keer':['rw10A.a', 'rw15A.b', 'rw14D.b'],
    'cijf-deel':['rw10A.a', 'rw15A.b', 'rw14D.b'],
    'komma-basis':['rw10A.b', 'rw15A.a'],
    'schat-basis':['rw15B.b', 'rw17A.c'],
    'komma-reken':['rw10A.a', 'rw10A.b'],
    'neg-basis':['rw10A.a', 'rw10A.b'],
    'volg-regels':['rw10A.a', 'rw15A.a', 'rw10A.f'],
    'macht-basis':['rw10A.a'],
    'macht-delers':['rw10A.b'],
    'macht-sci':['rw10A.b', 'rw10A.h'],
    /* rekenen: verhoudingen */
    'breuk-begrip':['rw10A.c', 'rw15A.e'],
    'breuk-om':['rw10A.c', 'rw15A.e'],
    'verh-tabel':['rw10A.c', 'rw14B.d'],
    'proc-basis':['rw10A.c'],
    'breuk-reken':['rw10A.a', 'rw10A.c'],
    'proc-reken':['rw10A.c', 'rw17A.a'],
    'verh-vergelijk':['rw10A.c', 'rw17A.c'],
    'schaal-basis':['rw10A.c', 'rw10A.d'],
    'proc-verander':['rw10A.c', 'rw17A.e'],
    'schaal-opp':['rw10A.c', 'rw13A.d'],
    /* rekenen: meten en meetkunde */
    'tijd-klok':['rw10A.b', 'rw15B.c'],
    'geld-basis':['rw17A.a'],
    'maat-om':['rw10A.d', 'rw15B.b'],
    'opp-basis':['rw10A.e', 'rw13A.a'],
    'opp-reken':['rw10A.e', 'rw13A.a'],
    'inh-reken':['rw10A.d', 'rw10A.e'],
    'snel-basis':['rw10A.b', 'rw10A.d'],
    'snel-om':['rw10A.b', 'rw10A.d', 'rw10A.e'],
    /* rekenen: verbanden */
    'graf-lezen':['rw11A.e'],
    'graf-reken':['rw11A.c', 'rw11A.d', 'rw12A.d'],
    'gem-basis':['rw11A.b'],
    'form-basis':['rw12A.d', 'rw10B.c'],
    'form-om':['rw10B.a', 'rw10B.d'],
    /* Nederlands: spelling en werkwoorden */
    'spel-klank':['nl6A.a', 'nl6B.b'],
    'spel-dubbel':['nl6B.b', 'nl6A.e'],
    'spel-klank2':['nl6B.b', 'nl6B.c'],
    'spel-uitgang':['nl6B.b', 'nl6A.b'],
    'spel-samen':['nl6A.b', 'nl6B.b'],
    'hoofd-regels':['nl6B.b', 'nl6B.c'],
    'spel-teken':['nl6B.b', 'nl6B.c'],
    'spel-leen':['nl6B.b', 'nl7B.c'],
    'spel-moeilijk':['nl6B.b', 'nl6B.c'],
    'ww-basis':['nl6A.e', 'nl6A.c'],
    'ww-ott':['nl6B.b', 'nl6A.e'],
    'ww-ovt':['nl6B.b', 'nl6A.e'],
    'ww-vd':['nl6B.b', 'nl6A.e'],
    'ww-bijzonder':['nl6B.b', 'nl6A.e'],
    'ww-lastig':['nl6B.b', 'nl6B.a'],
    /* Nederlands: grammatica */
    'ws-basis':['nl6A.e'],
    'zd-basis':['nl6A.c', 'nl6A.e'],
    'zd-gezegde':['nl6A.c', 'nl6A.e'],
    'zd-rest':['nl6A.c', 'nl6A.e'],
    'ws-meer':['nl6A.e', 'nl6B.a'],
    'gram-zin':['nl6A.c', 'nl6B.a'],
    'gram-lastig':['nl6A.c', 'nl6B.a'],
    /* Nederlands: woordenschat en lezen */
    'woord-strategie':['nl2A.b', 'nl6A.b'],
    'woord-taal':['nl2A.b', 'nl3C.d'],
    'lees-geheel':['nl2A.c', 'nl2A.d', 'nl2A.f'],
    'lees-alinea':['nl2A.e'],
    'lees-signaal':['nl2A.c', 'nl2B.a'],
    'lees-signaal-2f':['nl2A.c', 'nl2B.a'],
    'lees-verwijs':['nl2A.b', 'nl2B.a'],
    'lees-argument':['nl2B.b', 'nl6D.a'],
    'lees-structuur':['nl2A.c'],
    'lees-samenvat':['nl2A.e', 'nl3C.b'],
    'lees-drog':['nl2B.b', 'nl6D.a', 'nl6D.c'],
    /* Nederlands: verhalen en gedichten */
    'fic-verhaal':['nl9A.b', 'nl9A.c', 'nl9A.d'],
    'fic-verhaal-2f':['nl9A.a', 'nl9A.c'],
    'fic-beeld':['nl9B.a', 'nl9B.c'],
    /* Nederlands: leestekens, schrijven en spreken */
    'teken-eind':['nl6B.a'],
    'teken-komma':['nl6B.a', 'nl6A.c'],
    'teken-rede':['nl6B.a'],
    'teken-ander':['nl6B.a'],
    'schrijf-zin':['nl6B.a', 'nl3A.e'],
    'schrijf-alinea':['nl3A.c', 'nl3C.c'],
    'schrijf-mail':['nl3A.a', 'nl3A.c', 'nl6C.a'],
    'schrijf-register':['nl6A.d', 'nl3A.a'],
    'schrijf-betoog':['nl3C.c', 'nl6D.a'],
    'spreek-gesprek':['nl4A.a', 'nl4B.a', 'nl4B.c', 'nl4B.e']
  }
};
