/* De vragen van dit vak. Dit bestand wordt pas opgehaald als iemand dit vak
   kiest; bank.js weet welke er zijn en haalt ze erbij. */
(function(){
var NED = [
  {v:'Hij ___ morgen tien jaar.', o:['word','wordt','words','wort'], g:1, u:'Stam word + t, want hij is een hij-vorm. Alleen bij ik hoort word zonder t.', t:'werkwoordspelling'},
  {v:'Ik ___ het antwoord al.', o:['weet','weett','wet','weed'], g:0, u:'Bij ik komt er nooit een t achter de stam.', t:'werkwoordspelling'},
  {v:'Gisteren ___ ik naar de markt.', o:['fietste','fietsde','fietzte','fietstte'], g:0, u:'De stam fiets eindigt op een s, dat hoort bij t kofschip, dus te.', t:'werkwoordspelling'},
  {v:'Wij hebben lang ___.', o:['gewandelt','gewandeld','gewandelde','wandelde'], g:1, u:'De stam wandel eindigt niet op een letter uit t kofschip, dus d.', t:'werkwoordspelling'},
  {v:'Wat is er gisteren ___?', o:['gebeurt','gebeurd','gebeurdt','gebeurde'], g:1, u:'Voltooid deelwoord van gebeuren: de stam eindigt op r, dus een d.', t:'spelling'},
  {v:'Wat is een synoniem van snel?', o:['langzaam','rap','stil','zwaar'], g:1, u:'Rap betekent hetzelfde als snel. Langzaam is juist het tegenovergestelde.', t:'synoniemen'},
  {v:'Wat is een synoniem van bang?', o:['angstig','dapper','boos','blij'], g:0, u:'Angstig en bang betekenen hetzelfde.', t:'synoniemen'},
  {v:'Wat is een synoniem van beginnen?', o:['stoppen','starten','wachten','denken'], g:1, u:'Starten en beginnen betekenen hetzelfde.', t:'synoniemen'},
  {v:'Wat betekent globaal?', o:['in het groot, niet precies','tot op de komma nauwkeurig','erg snel','onder de grond'], g:0, u:'Globaal betekent in grote lijnen, dus niet tot in detail.', t:'betekenis'},
  {v:'Wat betekent een neutrale mening?', o:['fel voor','fel tegen, zonder enige twijfel','geen kant kiezen','onbekend'], g:2, u:'Neutraal betekent dat je geen partij kiest.', t:'betekenis'},
  {v:'Wat betekent het woord tijdvak?', o:['een klok','een periode in de geschiedenis','een lokaal','een agenda waarin de lessen staan'], g:1, u:'Een tijdvak is een afgebakende periode in de tijd.', t:'betekenis'},
  {v:'Welke zin heeft de leestekens goed?', o:['Kom je mee, vroeg hij.','Kom je mee? vroeg hij','"Kom je mee?" vroeg hij.','Kom je mee "vroeg hij".'], g:2, u:'Een vraag binnen aanhalingstekens houdt zijn vraagteken, daarna volgt de rest van de zin.', t:'leestekens'},
  {v:'Waar hoort de komma?', o:['Omdat het regende, bleven we binnen.','Omdat het regende bleven, we binnen.','Omdat, het regende bleven we binnen.','Er hoort geen komma in.'], g:0, u:'Na een bijzin vooraan de zin zet je een komma.', t:'leestekens'},
  {v:'Wat is het meervoud van kanon?', o:['kanons','kanonnen','kanonen','kanonne'], g:1, u:'De klinker blijft kort, dus verdubbelt de n: kanonnen.', t:'meervoud'},
  {v:'Wat is het meervoud van museum?', o:['museums','musea','museumen','museae'], g:1, u:'Museum komt uit het Latijn en krijgt musea, net als gymnasium en gymnasia.', t:'meervoud'},
  {v:'Wat is het meervoud van pagina?', o:['paginas','pagina&#39;s','paginaas','paginae'], g:1, u:'Bij een woord dat eindigt op een losse a zet je een apostrof voor de s.', t:'meervoud'},
  {v:'Hij ___ zijn jas op.', o:['hangt','hangd','hant','hangdt'], g:0, u:'Stam hang plus t. Je hoort de t niet altijd, maar hij staat er wel.', t:'werkwoordspelling'},
  {v:'Zij heeft de deur ___.', o:['geverft','geverfd','geverfde','verfde'], g:1, u:'Let op: kijk naar het hele werkwoord verven, met een v. De v zit niet in t kofschip, dus een d. Je schrijft verf met een f omdat een woord niet op een v mag eindigen, maar dat verandert de regel niet.', t:'spelling'},
  {v:'Wat is een synoniem van moeilijk?', o:['lastig','vervelend','laag','lang'], g:0, u:'Lastig en moeilijk betekenen hetzelfde.', t:'synoniemen'},
  {v:'Wat is het meervoud van kind?', o:['kinden','kinders','kinderen','kindens'], g:2, u:'Kind krijgt er in het meervoud een hele lettergroep bij: kinderen.', t:'meervoud'},
  {v:'Wat betekent een chronologisch verhaal?', o:['op tijd verteld','in de juiste tijdsorde','met heel veel details erin','zonder einde'], g:1, u:'Chronologisch betekent in de volgorde van de tijd.', t:'betekenis'},
  {v:'Hij ___ het boek al gelezen.', o:['heb','heeft','hebt','heefd'], g:1, u:'Bij hij hoort heeft.', t:'werkwoordspelling'},
  ];
var NED_N = [1,1,2,2,3,1,1,1,3,3,2,4,3,2,4,2,1,3,1,3,1,4,1,2];
var NED2 = [
{v:'Ik ___ elke dag naar school.',o:['fiets','fietst','fietsen','fietse'],g:0,u:'Bij ik gebruik je de stam, dus zonder t. De stam van fietsen is fiets.',t:'werkwoordspelling'},
{v:'Hij ___ de deur voor mij open.',o:['doet','doed','doete','doedt'],g:0,u:'Bij hij, zij of het komt er een t achter de stam. In de tegenwoordige tijd is dat altijd een t, nooit een d.',t:'werkwoordspelling'},
{v:'Wij ___ morgen naar Zwolle.',o:['gaan','gaat','gaandt','gaante'],g:0,u:'Bij wij, jullie en zij meervoud schrijf je het hele werkwoord: gaan.',t:'werkwoordspelling'},
{v:'De hond ___ de hele nacht.',o:['blaft','blafd','blaften','blafte'],g:0,u:'De hond is een hij, dus stam plus t. In de tegenwoordige tijd hoor je nooit een d achter de stam.',t:'werkwoordspelling'},
{v:'Ik ___ morgen vijftien.',o:['word','wordt','worde','worden'],g:0,u:'De stam van worden is word. Bij ik komt er niets achter, dus word zonder t.',t:'werkwoordspelling'},
{v:'Hij ___ steeds bozer.',o:['word','wordt','wordten','wordte'],g:1,u:'Stam word plus t is wordt. Dat de stam al op een d eindigt maakt niet uit, de t komt er gewoon achter.',t:'werkwoordspelling'},
{v:'___ jij ook uitgenodigd?',o:['Word','Wordt','Worde','Worden'],g:0,u:'Staat jij achter het werkwoord, dan valt de t weg. Vergelijk: jij wordt uitgenodigd, maar word jij uitgenodigd?',t:'werkwoordspelling'},
{v:'Wat ___ jij daarvan?',o:['vind','vindt','vint','vinde'],g:0,u:'Jij staat achter het werkwoord, dus geen t. Wel: jij vindt daar iets van.',t:'werkwoordspelling'},
{v:'Jij ___ dat altijd goed.',o:['doet','doe','doete','doeten'],g:0,u:'Staat jij voor het werkwoord, dan komt de t er gewoon bij.',t:'werkwoordspelling'},
{v:'Mijn zus ___ op haar fiets naar school.',o:['rijdt','rijd','rijdte','rijddt'],g:0,u:'Mijn zus is een zij. De stam van rijden is rijd, daar komt een t achter.',t:'werkwoordspelling'},
{v:'Hij ___ nooit op mijn berichten.',o:['antwoordt','antwoord','antwoordten','antwoordte'],g:0,u:'De stam van antwoorden is antwoord. Bij hij komt daar een t achter, ook al ziet dat er raar uit.',t:'werkwoordspelling'},
{v:'Ik ___ je vanavond.',o:['antwoord','antwoordt','antwoorde','antwoort'],g:0,u:'Bij ik gebruik je alleen de stam: antwoord.',t:'werkwoordspelling'},
{v:'De leerlingen ___ het lokaal binnen.',o:['lopen','loopt','lopendt','lopend'],g:0,u:'De leerlingen zijn er meer dan een, dus het hele werkwoord: lopen.',t:'werkwoordspelling'},
{v:'___ je even mee naar buiten?',o:['Loop','Loopt','Loopd','Loopte'],g:0,u:'Ook bij je in plaats van jij valt de t weg als het achter het werkwoord staat.',t:'werkwoordspelling'},
{v:'Het ___ me dat je er bent.',o:['verbaast','verbaasd','verbaaste','verbaasdt'],g:0,u:'Hier is verbazen een gewoon werkwoord in de tegenwoordige tijd: stam verbaas plus t.',t:'werkwoordspelling'},
{v:'Wij ___ de hele middag aan ons verslag. (verleden tijd)',o:['werkten','werkden','werktene','werktenen'],g:0,u:'Werken eindigt op ken. De k zit in \'t kofschip, dus verleden tijd met ten.',t:'werkwoordspelling'},
{v:'Hij ___ zijn huiswerk al voor het eten. (verleden tijd)',o:['maakte','maakde','maaktee','maakt'],g:0,u:'Maken eindigt op ken. De k zit in \'t kofschip, dus te.',t:'werkwoordspelling'},
{v:'Ik ___ de hele avond naar muziek. (verleden tijd)',o:['luisterde','luisterte','luisterdt','luisterdeen'],g:0,u:'Luisteren eindigt op ren. De r zit niet in \'t kofschip, dus de.',t:'werkwoordspelling'},
{v:'Zij ___ de deur voorzichtig. (verleden tijd)',o:['opende','opente','opendt','opend'],g:0,u:'Openen eindigt op nen. De n zit niet in \'t kofschip, dus de.',t:'werkwoordspelling'},
{v:'De hond ___ de hele nacht. (verleden tijd)',o:['blafte','blafde','blafd','blafdt'],g:0,u:'Blaffen eindigt op fen. De f zit in \'t kofschip, dus te.',t:'werkwoordspelling'},
{v:'Wij ___ vroeger in Emmeloord. (verleden tijd)',o:['woonden','woonten','woonte','woondt'],g:0,u:'Wonen eindigt op nen, dus den. Je hoort het ook: woonden.',t:'werkwoordspelling'},
{v:'Ik ___ de bal over de schutting. (verleden tijd)',o:['gooide','gooite','gooid','gooided'],g:0,u:'Gooien eindigt op ien. Die letters zitten niet in \'t kofschip, dus de.',t:'werkwoordspelling'},
{v:'De juf ___ de les precies op tijd. (verleden tijd)',o:['startte','starte','starttee','startteen'],g:0,u:'De stam is start en die eindigt al op een t. Daar komt te achter, dus twee keer t: startte.',t:'werkwoordspelling'},
{v:'Hij ___ een hoger cijfer. (verleden tijd)',o:['verwachtte','verwachte','verwachtted','verwachtteen'],g:0,u:'De stam is verwacht. Daar komt te achter, dus verwachtte met twee keer t.',t:'werkwoordspelling'},
{v:'Wij ___ vorig jaar naar een ander huis. (verleden tijd)',o:['verhuisden','verhuisten','verhuiste','verhuist'],g:0,u:'Verhuizen eindigt op zen, en de z zit niet in \'t kofschip. Kijk dus naar het hele werkwoord, niet naar de stam verhuis.',t:'werkwoordspelling'},
{v:'Ik ___ de vraag van de docent. (verleden tijd)',o:['beantwoordde','beantwoorde','beantwoorddeen','beantwoordte'],g:0,u:'De stam is beantwoord en eindigt al op een d. Daar komt de achter: beantwoordde.',t:'werkwoordspelling'},
{v:'Hij ___ zich de hele les. (verleden tijd)',o:['verveelde','verveelte','verveelded','verveelt'],g:0,u:'Vervelen eindigt op len. De l zit niet in \'t kofschip, dus de.',t:'werkwoordspelling'},
{v:'De klas ___ het antwoord meteen. (verleden tijd)',o:['raadde','raadte','raadd','raaddeen'],g:0,u:'Raden eindigt op den, dus de. De stam raad eindigt al op een d: raadde.',t:'werkwoordspelling'},
{v:'Ik ___ gisteren naar school. (verleden tijd)',o:['fietste','fietsde','fietsd','fietsdt'],g:0,u:'Fietsen eindigt op sen. De s zit in \'t kofschip, dus te.',t:'werkwoordspelling'},
{v:'Wij ___ gisteren de hele middag buiten. (verleden tijd)',o:['speelden','speelten','speelt','speelte'],g:0,u:'Spelen eindigt op len. De l zit niet in \'t kofschip, dus den.',t:'werkwoordspelling'},
{v:'Zij ___ hard om de grap. (verleden tijd)',o:['lachte','lachde','lachtee','lachd'],g:0,u:'Lachen eindigt op chen. De ch zit in \'t kofschip, dus te.',t:'werkwoordspelling'},
{v:'Ik ___ mijn kamer op zaterdag. (verleden tijd)',o:['poetste','poetsde','poetsteen','poetsd'],g:0,u:'Poetsen eindigt op sen, en de s zit in \'t kofschip. Dus te.',t:'werkwoordspelling'},
{v:'Hij ___ de bal over de schutting. (verleden tijd)',o:['gooide','gooiden','gooided','gooid'],g:0,u:'De vorm met de is goed, want hij is een persoon. Gooiden gebruik je bij wij of zij meervoud.',t:'werkwoordspelling'},
{v:'Ik heb de hele dag hard ___. (voltooid deelwoord)',o:['gewerkt','gewerkd','gewerkte','gewerktd'],g:0,u:'Werken eindigt op ken en de k zit in \'t kofschip, dus ge plus stam plus t.',t:'werkwoordspelling'},
{v:'Wij hebben het samen ___. (voltooid deelwoord)',o:['gemaakt','gemaakd','gemaakte','gemaakten'],g:0,u:'Maken hoort bij \'t kofschip, dus gemaakt met een t.',t:'werkwoordspelling'},
{v:'Hij heeft de deur al ___. (voltooid deelwoord)',o:['geopend','geopent','geopende','geopenden'],g:0,u:'Openen eindigt op nen. De n zit niet in \'t kofschip, dus een d: geopend.',t:'werkwoordspelling'},
{v:'Zij is naar huis ___. (voltooid deelwoord)',o:['gefietst','gefietsd','gefietste','gefietsten'],g:0,u:'Fietsen eindigt op sen. De s zit in \'t kofschip, dus een t.',t:'werkwoordspelling'},
{v:'Hij heeft nog steeds niet ___. (voltooid deelwoord)',o:['geantwoord','geantwoordt','geantwoort','geantwoorde'],g:0,u:'De stam is antwoord en eindigt al op een d. Er komt niets meer bij: geantwoord. Een voltooid deelwoord krijgt nooit dt.',t:'werkwoordspelling'},
{v:'Ik heb de hele week ___. (voltooid deelwoord)',o:['geleerd','geleert','geleerdd','geleerte'],g:0,u:'Leren eindigt op ren. De r zit niet in \'t kofschip, dus een d.',t:'werkwoordspelling'},
{v:'Ik heb je bericht gisteren ___. (voltooid deelwoord)',o:['ontvangen','ontvangd','ontvangenen','ontvangend'],g:0,u:'Ontvangen is een sterk werkwoord met een onbeklemtoond voorvoegsel. Er komt geen ge voor en geen t of d achter.',t:'werkwoordspelling'},
{v:'Ze heeft haar pas ___. (voltooid deelwoord)',o:['verloren','verliesd','verlorene','verlorenen'],g:0,u:'Verliezen verandert van klank in het voltooid deelwoord: verloren. Bij sterke werkwoorden helpt het kofschip je niet.',t:'werkwoordspelling'},
{v:'Het pakketje wordt vandaag ___. (voltooid deelwoord)',o:['bezorgd','bezorgt','bezorgte','bezorgde'],g:0,u:'Bezorgen eindigt op gen. De g zit niet in \'t kofschip, dus een d. Let op: wordt bezorgd is een voltooid deelwoord, geen persoonsvorm.',t:'werkwoordspelling'},
{v:'Hij heeft zich de hele les ___. (voltooid deelwoord)',o:['verveeld','verveelt','verveelte','verveeldt'],g:0,u:'Vervelen eindigt op len, dus een d. Na heeft staat altijd een voltooid deelwoord.',t:'werkwoordspelling'},
{v:'Ik heb de hele middag buiten ___. (voltooid deelwoord)',o:['gespeeld','gespeelt','gespeelde','gespeeldd'],g:0,u:'Spelen eindigt op len. De l zit niet in \'t kofschip, dus een d.',t:'werkwoordspelling'},
{v:'Zij heeft haar kamer ___. (voltooid deelwoord)',o:['gepoetst','gepoetsd','gepoetste','gepoetsten'],g:0,u:'Poetsen hoort bij \'t kofschip, dus gepoetst met een t.',t:'werkwoordspelling'},
{v:'Hij ___ de bal naar mij.',o:['gooit','gooid','gooitd','gooidt'],g:0,u:'Dit is de persoonsvorm bij hij: stam plus t. Vervang het door lopen: hij loopt.',t:'werkwoordspelling'},
{v:'De bal is naar mij ___.',o:['gegooid','gegooit','gegooide','gegooite'],g:0,u:'Na is komt een voltooid deelwoord. Vervang het door lopen: het is gelopen. Dus gegooid.',t:'werkwoordspelling'},
{v:'Wat ___ er allemaal?',o:['gebeurt','gebeurd','gebeurdt','gebeurten'],g:0,u:'Hier is gebeuren de persoonsvorm in de tegenwoordige tijd. Vervang het door lopen: wat loopt er. Je hoort een t.',t:'werkwoordspelling'},
{v:'Er is iets ergs ___.',o:['gebeurd','gebeurt','gebeurde','gebeurdd'],g:0,u:'Na is, was, heeft of hebben komt een voltooid deelwoord. Vervang het door lopen: er is iets gelopen. Dus gebeurd met een d.',t:'werkwoordspelling'},
{v:'Hij ___ zich tijdens de uitleg.',o:['verveelt','verveeld','verveelte','verveeltd'],g:0,u:'Dit is de persoonsvorm bij hij: stam plus t. Vervang het door lopen: hij loopt.',t:'werkwoordspelling'},
{v:'Hij heeft zich vreselijk ___.',o:['verveeld','verveelt','verveelde','verveelden'],g:0,u:'Na heeft komt een voltooid deelwoord. Vervang het door lopen: hij heeft gelopen. Dus verveeld.',t:'werkwoordspelling'},
{v:'De postbode ___ het pakket om vier uur.',o:['bezorgt','bezorgd','bezorgte','bezorgdt'],g:0,u:'De postbode is een hij, dus stam plus t. Vervang het door lopen: de postbode loopt.',t:'werkwoordspelling'},
{v:'Het pakket is al ___.',o:['bezorgd','bezorgt','bezorgte','bezorgde'],g:0,u:'Na is komt een voltooid deelwoord. Vervang het door lopen: het is gelopen. Dus bezorgd.',t:'werkwoordspelling'},
{v:'De brief is vanmorgen ___.',o:['verstuurd','verstuurt','verstuurdd','verstuurte'],g:0,u:'Na is komt een voltooid deelwoord: verstuurd met een d.',t:'werkwoordspelling'},
{v:'Hij ___ de brief vanmorgen.',o:['verstuurt','verstuurd','verstuurte','verstuurten'],g:0,u:'Hier is versturen de persoonsvorm bij hij: stam plus t.',t:'werkwoordspelling'},
{v:'Dat had ik niet ___.',o:['verwacht','verwachtte','verwachdt','verwachte'],g:0,u:'Na had komt een voltooid deelwoord: verwacht. Verwachtte is verleden tijd, en die past hier niet.',t:'werkwoordspelling'},
{v:'Ik ___ dat het zou lukken.',o:['verwachtte','verwacht','verwachttee','verwachtteen'],g:0,u:'Hier vertel je over vroeger, dus verleden tijd. Stam verwacht plus te wordt verwachtte.',t:'werkwoordspelling'},
{v:'De les wordt door hem ___.',o:['gegeven','geeft','gegevend','gegevent'],g:0,u:'Na wordt komt een voltooid deelwoord. Wordt is hier de persoonsvorm, gegeven hoort erbij.',t:'werkwoordspelling'},
{v:'Het ___ mij dat niemand iets zei.',o:['verbaasde','verbaasd','verbaasdt','verbaasded'],g:0,u:'Verbazen eindigt op zen en de z zit niet in \'t kofschip, dus de. Zonder is of heeft ervoor is het geen deelwoord.',t:'werkwoordspelling'},
{v:'Wat is een synoniem van eerlijk?',o:['oprecht','zuinig','luid','vroeg'],g:0,u:'Oprecht betekent hetzelfde als eerlijk.',t:'synoniemen'},
{v:'Wat is een synoniem van blij?',o:['vrolijk','moe','streng','zwaar'],g:0,u:'Vrolijk en blij betekenen hetzelfde.',t:'synoniemen'},
{v:'Wat is een synoniem van praten?',o:['spreken','lopen','kijken','wachten'],g:0,u:'Spreken en praten betekenen hetzelfde.',t:'synoniemen'},
{v:'Wat is een synoniem van groot?',o:['enorm','smal','kort','dun'],g:0,u:'Enorm betekent heel groot.',t:'synoniemen'},
{v:'Wat is een synoniem van boos?',o:['kwaad','bang','blij','stil'],g:0,u:'Kwaad en boos betekenen hetzelfde.',t:'synoniemen'},
{v:'Wat is een synoniem van kopen?',o:['aanschaffen','verkopen','lenen','geven'],g:0,u:'Aanschaffen is een deftig woord voor kopen. Verkopen is juist het tegenovergestelde.',t:'synoniemen'},
{v:'Wat is een synoniem van proberen?',o:['pogen','slagen','stoppen','weten'],g:0,u:'Pogen betekent proberen. Slagen betekent dat het gelukt is.',t:'synoniemen'},
{v:'Wat is een synoniem van verbieden?',o:['tegenhouden','toestaan','vragen','vergeten'],g:0,u:'Toestaan is het tegenovergestelde van verbieden.',t:'synoniemen'},
{v:'Wat is een synoniem van rijk?',o:['welvarend','arm','gierig','duur'],g:0,u:'Welvarend betekent rijk. Gierig gaat over hoe je met geld omgaat, niet hoeveel je hebt.',t:'synoniemen'},
{v:'Wat is een synoniem van belangrijk?',o:['essentieel','handig','nieuw','duidelijk'],g:0,u:'Essentieel betekent onmisbaar, dus heel belangrijk.',t:'synoniemen'},
{v:'Wat betekent een bron kritisch bekijken?',o:['nagaan of je hem kunt geloven','hem hardop voorlezen','hem overschrijven','hem afkeuren'],g:0,u:'Kritisch kijken is niet hetzelfde als afkeuren: je onderzoekt of je de bron kunt vertrouwen.',t:'betekenis'},
{v:'Wat betekent het woord oorzaak?',o:['waardoor iets gebeurt','wat er daarna gebeurt','hoe lang iets duurt','wie het opschreef'],g:0,u:'De oorzaak komt eerst, het gevolg komt daarna.',t:'betekenis'},
{v:'Wat betekent het woord gevolg?',o:['wat er daarna gebeurt','waardoor iets begon','een andere mening','een korte samenvatting'],g:0,u:'Eerst de oorzaak, dan het gevolg.',t:'betekenis'},
{v:'Wat betekent het woord bevolking?',o:['alle mensen die ergens wonen','alle gebouwen in een stad','het bestuur van een land','de mensen die stemmen'],g:0,u:'De bevolking is iedereen die er woont, ook wie niet mag stemmen.',t:'betekenis'},
{v:'Wat betekent het woord verplicht?',o:['het moet','het mag','het kan','het is verboden'],g:0,u:'Verplicht is sterker dan mogen: het moet.',t:'betekenis'},
{v:'Wat betekent het woord toevallig?',o:['zonder dat het gepland was','met opzet','al heel lang','precies op tijd'],g:0,u:'Toevallig betekent dat niemand het zo bedoeld heeft.',t:'betekenis'},
{v:'Wat betekent het woord vooroordeel?',o:['een mening zonder de feiten te kennen','een goed onderbouwde mening','een oordeel van een rechter','een eerste indruk die klopt'],g:0,u:'Een vooroordeel is een oordeel vooraf, zonder dat je het onderzocht hebt.',t:'betekenis'},
{v:'Wat betekent het woord standpunt?',o:['wat iemand ergens van vindt','waar iemand staat','een bewijs','een feit'],g:0,u:'Een standpunt is een mening, geen feit.',t:'betekenis'},
{v:'Wat betekent het woord gelijkwaardig?',o:['evenveel waard','precies hetzelfde','goedkoper','ouder'],g:0,u:'Gelijkwaardig betekent evenveel waard, niet dat het hetzelfde is.',t:'betekenis'},
{v:'Wat betekent het woord invoeren?',o:['van buiten het land halen','naar buiten het land brengen','zelf maken','weggooien'],g:0,u:'Invoeren is importeren, uitvoeren is exporteren.',t:'betekenis'},
{v:'Wat is het meervoud van glas?',o:['glazen','glassen','glasen','glases'],g:0,u:'De s wordt een z en de a wordt lang: glazen.',t:'meervoud'},
{v:'Wat is het meervoud van huis?',o:['huizen','huisen','huissen','huizes'],g:0,u:'De s wordt een z: huizen.',t:'meervoud'},
{v:'Wat is het meervoud van bus?',o:['bussen','busen','buzen','busses'],g:0,u:'Korte klank, dus de s verdubbelt: bussen.',t:'meervoud'},
{v:'Wat is het meervoud van raam?',o:['ramen','ramen die','raamen','rammen'],g:0,u:'De lange aa wordt een a in een open lettergreep: ramen. Rammen zijn mannetjesschapen.',t:'meervoud'},
{v:'Wat is het meervoud van eend?',o:['eenden','eendes','eendden','eenders'],g:0,u:'Gewoon en erachter: eenden.',t:'meervoud'},
{v:'Wat is het meervoud van foto?',o:['foto\'s','fotos','fotoos','fotoen'],g:0,u:'Bij een klinker aan het eind komt er een apostrof: foto\'s.',t:'meervoud'},
{v:'Wat is het meervoud van hobby?',o:['hobby\'s','hobbys','hobbies','hobbyen'],g:0,u:'In het Nederlands met een apostrof: hobby\'s. Hobbies is Engels.',t:'meervoud'},
{v:'Wat is het meervoud van collega?',o:['collega\'s','collegas','collegaas','collegae'],g:0,u:'Klinker aan het eind, dus apostrof: collega\'s.',t:'meervoud'},
{v:'Wat is het meervoud van stad?',o:['steden','stads','stadden','staden'],g:0,u:'Een uitzondering die je uit je hoofd moet kennen: stad wordt steden.',t:'meervoud'},
{v:'Wat is het meervoud van schip?',o:['schepen','schippen','schipen','schips'],g:0,u:'Ook een uitzondering: schip wordt schepen.',t:'meervoud'},
{v:'Welke zin heeft de komma goed?',o:['Ik ga naar huis, want het regent.','Ik ga naar huis want, het regent.','Ik ga, naar huis want het regent.','Ik ga naar huis want het, regent.'],g:0,u:'Voor een verbindingswoord als want komt een komma.',t:'leestekens'},
  {v:'Waar hoort het vraagteken?',o:['Kom je vanavond nog langs?','Kom je vanavond nog langs.','Kom je? vanavond nog langs','Kom je vanavond, nog langs'],g:0,u:'Een vraag eindigt op een vraagteken.',t:'leestekens'},
{v:'Welke zin heeft de aanhalingstekens goed?',o:['Zij zei: "Ik kom eraan."','Zij zei "Ik kom eraan".','Zij zei: Ik kom eraan.','Zij zei: "Ik kom eraan'],g:0,u:'Dubbele punt, dan de aanhalingstekens om precies wat er gezegd is.',t:'leestekens'},
{v:'Welke zin gebruikt de dubbele punt goed?',o:['Je hebt drie dingen nodig: papier, pen en tijd.','Je hebt drie dingen nodig, papier: pen en tijd.','Je hebt: drie dingen nodig papier, pen en tijd.','Je hebt drie dingen: nodig papier pen en tijd.'],g:0,u:'Een dubbele punt kondigt een opsomming aan.',t:'leestekens'},
{v:'Wat is de verleden tijd van gebeuren?',o:['gebeurde','gebeurdde','gebeurdte','gebeurtte'],g:0,u:'Verleden tijd van gebeuren: de stam eindigt op r, dus de.',t:'spelling'},
{v:'Hoe schrijf je dit goed?',o:['ik verwacht','ik verwagt','ik ferwacht','ik verwachtt'],g:0,u:'Verwachten schrijf je met cht, net als wachten.',t:'spelling'},
{v:'Welke zin is goed geschreven?',o:['het gebeurt vaak','het gebeurd vaak','het gebeurdt vaak','het gebeurte vaak'],g:0,u:'Tegenwoordige tijd, derde persoon: stam plus t.',t:'spelling'},
{v:'Hoe schrijf je de periode van ridders en kastelen?',o:['middeleeuwen','middeleeuwe','midden eeuwen','middeleuwen'],g:0,u:'Een woord, met eeuw erin: middeleeuwen.',t:'spelling'},
  {v:'Hij heeft het boek ___ (verleden tijd, voltooid).',o:['gelezen','geleesd','geleest','gelezd'],g:0,u:'Lezen is sterk: lezen, las, gelezen. Geen d of t.',t:'werkwoordspelling'},
{v:'Wij ___ gisteren de hele dag.',o:['fietsten','fietsden','fiesten','fietste'],g:0,u:'Fiets eindigt op s, uit t kofschip, dus ten in het meervoud.',t:'werkwoordspelling'},
{v:'Zij ___ het antwoord al voordat ik het zei.',o:['wist','weette','weete','wiste'],g:0,u:'Weten is onregelmatig: weten, wist, geweten.',t:'werkwoordspelling'},
{v:'Het pakket is gisteren ___.',o:['bezorgd','bezorgt','bezorgd geweest','bezorgde'],g:0,u:'Voltooid deelwoord van bezorgen: de stam eindigt op g, dus d.',t:'werkwoordspelling'},
{v:'Dat ___ me niets uit.',o:['maakt','maak','maakte','maakd'],g:0,u:'Derde persoon enkelvoud in de tegenwoordige tijd: stam plus t.',t:'werkwoordspelling'},
{v:'Word of wordt? Ik ___ morgen zestien.',o:['word','wordt','wordd','worde'],g:0,u:'Bij ik nooit een t erachter, ook niet bij worden.',t:'werkwoordspelling'},
{v:'Word of wordt? ___ jij morgen zestien?',o:['Word','Wordt','Wordd','Worde'],g:0,u:'Staat jij achter het werkwoord, dan valt de t weg.',t:'werkwoordspelling'},
{v:'Hoe schrijf je een samenstelling van twee woorden?',o:['de gemeentesecretaris','de gemeente secretaris','de gemeentensecretaris','de gemeente-secretaris'],g:0,u:'Samenstellingen schrijf je in het Nederlands aan elkaar.',t:'spelling'},
{v:'Welk woord heeft de tussen-n goed?',o:['pannenkoek','pannekoek','pannen koek','panne-koek'],g:0,u:'Sinds 1995 met een tussen-n: pannenkoek.',t:'spelling'},
{v:'Waarom staat hier geen tussen-n?',o:['zonnestraal','zonnenstraal','zonne straal','zonstraal'],g:0,u:'Geen tussen-n, want er is maar een zon.',t:'spelling'},
{v:'Welke hoofdletters horen hier?',o:['de Tweede Wereldoorlog','de tweede wereldoorlog','de Tweede wereldoorlog','de tweede Wereldoorlog'],g:0,u:'Namen van historische gebeurtenissen krijgen hoofdletters.',t:'spelling'},
{v:'Krijgt Nederlandse een hoofdletter?',o:['een Nederlandse stad','een nederlandse stad','een Nederlandsestad','een neder-landse stad'],g:0,u:'Bijvoeglijke naamwoorden van een land krijgen een hoofdletter.',t:'spelling'},
{v:'Wat is goed als je als laatste bedoelt?',o:['ten slotte','tenslotte betekent iets anders','ten-slotte','tenslote'],g:0,u:'Ten slotte betekent als laatste. Tenslotte betekent immers.',t:'spelling'},
{v:'Wat is het onderwerp in: De koning opende de vergadering?',o:['de koning','de vergadering','opende','de koning opende'],g:0,u:'Vraag: wie opende? De koning. Dat is het onderwerp.',t:'zinsdelen'},
{v:'Wat is het lijdend voorwerp in: De boer verkocht zijn land?',o:['zijn land','de boer','verkocht','de boer verkocht'],g:0,u:'Vraag: wat verkocht hij? Zijn land. Dat is het lijdend voorwerp.',t:'zinsdelen'},
{v:'Wat is de persoonsvorm in: Morgen komt de nieuwe docent?',o:['komt','morgen','de nieuwe docent','docent'],g:0,u:'De persoonsvorm verandert als je de zin in een andere tijd zet: kwam.',t:'zinsdelen'},
{v:'Welk woord is een bijvoeglijk naamwoord?',o:['zwaar','zwaarte','verzwaren','zwaarder worden'],g:0,u:'Zwaar zegt iets over een zelfstandig naamwoord: een zware tas.',t:'zinsdelen'},
{v:'Welk woord is een voorzetsel?',o:['tussen','tussenpersoon','tussendoor eten','tussenkomst'],g:0,u:'Een voorzetsel geeft een plaats of tijd aan: tussen de bomen.',t:'zinsdelen'},
{v:'Welk signaalwoord geeft een tegenstelling aan?',o:['echter','bovendien','daardoor','bijvoorbeeld'],g:0,u:'Echter zet twee dingen tegenover elkaar. Bovendien telt juist op.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een oorzaak aan?',o:['doordat','hoewel','ondertussen','ten slotte'],g:0,u:'Doordat noemt de oorzaak. Hoewel is een tegenstelling.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een gevolg aan?',o:['daardoor','omdat','terwijl','zoals'],g:0,u:'Daardoor wijst vooruit naar het gevolg, omdat wijst terug naar de oorzaak.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een voorbeeld?',o:['zoals','dus','maar','toch'],g:0,u:'Zoals kondigt een voorbeeld aan.',t:'tekstverbanden'},
{v:'Wat betekent de uitdrukking de kat uit de boom kijken?',o:['eerst afwachten','ruzie zoeken','iets snel doen','iemand betrappen'],g:0,u:'Je wacht af hoe iets loopt voordat je zelf iets doet.',t:'uitdrukkingen'},
{v:'Wat betekent iets onder de knie hebben?',o:['het goed kunnen','het vergeten zijn','er genoeg van hebben','het verstoppen'],g:0,u:'Je beheerst het.',t:'uitdrukkingen'},
{v:'Wat betekent de puntjes op de i zetten?',o:['het helemaal afmaken','ergens mee stoppen','iemand corrigeren','opnieuw beginnen'],g:0,u:'De laatste details afwerken.',t:'uitdrukkingen'},
{v:'Wat betekent boter bij de vis?',o:['meteen betalen','eerlijk delen','goed eten','snel werken'],g:0,u:'Direct afrekenen, niet op de pof.',t:'uitdrukkingen'},
{v:'Wat betekent het kind van de rekening zijn?',o:['degene die ervoor opdraait','de jongste van het gezin','degene die betaalt met munten','de winnaar'],g:0,u:'Jij draait op voor iets waar je niets aan kon doen.',t:'uitdrukkingen'},
{v:'Waar verwijst hij naar in: De koning riep de raad bijeen. Hij was boos.?',o:['de koning','de raad','de vergadering','onduidelijk, allebei kan'],g:0,u:'Hij is enkelvoud en mannelijk, dus het verwijst naar de koning.',t:'verwijswoorden'},
{v:'Welk verwijswoord hoort hier: De steden kregen rechten. ___ mochten zelf besturen.',o:['Zij','Hij','Het','Die van hen'],g:0,u:'Steden is meervoud, dus zij.',t:'verwijswoorden'},
{v:'Wat betekent het woord neutraal?',o:['geen partij kiezen','tegen iets zijn','ergens veel van weten','iets nieuws'],g:0,u:'Neutraal is aan geen van beide kanten staan.',t:'betekenis'},
{v:'Wat betekent het woord bevooroordeeld?',o:['met een mening vooraf','goed geinformeerd','zonder mening','streng'],g:0,u:'Je oordeelt al voordat je de feiten kent.',t:'betekenis'},
{v:'Wat betekent het woord aannemelijk?',o:['waarschijnlijk waar','zeker bewezen','onmogelijk','aangenomen personeel'],g:0,u:'Aannemelijk is niet hetzelfde als bewezen: het is goed mogelijk.',t:'betekenis'},
{v:'Wat betekent het woord ingrijpend?',o:['met grote gevolgen','snel gebeurd','moeilijk te begrijpen','door de politie gedaan'],g:0,u:'Een ingrijpende verandering verandert veel.',t:'betekenis'},
{v:'Wat betekent het woord toenemen?',o:['groter worden','kleiner worden','gelijk blijven','erbij nemen'],g:0,u:'Toenemen is stijgen, afnemen is dalen.',t:'betekenis'},
{v:'Wat is het tegenovergestelde van tijdelijk?',o:['blijvend','kortdurend','snel','vroeger'],g:0,u:'Tijdelijk duurt even, blijvend duurt voort.',t:'betekenis'},
  {v:'Wat is het meervoud van kalf?',o:['kalveren','kalfs','kalven','kalfen'],g:0,u:'Een uitzondering met eren: kalf wordt kalveren.',t:'meervoud'},
{v:'Wat is het meervoud van gelegenheid?',o:['gelegenheden','gelegenheiden','gelegenheidsen','gelegenheids'],g:0,u:'Woorden op heid krijgen heden: gelegenheden.',t:'meervoud'},
{v:'Wat is het meervoud van paraplu?',o:['paraplu\'s','paraplus','parapluen','paraplui'],g:0,u:'Klinker aan het eind, dus apostrof: paraplu\'s.',t:'meervoud'},
{v:'Waar hoort de komma bij een bijzin vooraan?',o:['Omdat het regende, bleven we binnen.','Omdat het regende bleven, we binnen.','Omdat, het regende bleven we binnen.','Omdat het, regende bleven we binnen.'],g:0,u:'Na een bijzin vooraan komt een komma.',t:'leestekens'},
{v:'Welke zin heeft de puntkomma goed?',o:['Het was laat; toch bleef hij werken.','Het was laat, toch; bleef hij werken.','Het was; laat toch bleef hij werken.','Het was laat toch bleef; hij werken.'],g:0,u:'Een puntkomma verbindt twee zinnen die bij elkaar horen.',t:'leestekens'},
{v:'Waar hoort het weglatingsteken?',o:['\'s Ochtends vertrok hij.','s Ochtends vertrok hij.','\' s Ochtends vertrok hij.','s\' Ochtends vertrok hij.'],g:0,u:'\'s Ochtends is een afkorting van des ochtends.',t:'leestekens'},
{v:'Wat is het gezegde in: De ridders vochten dapper?',o:['vochten','de ridders','dapper','ridders vochten'],g:0,u:'Het gezegde is wat er gebeurt: vochten.',t:'zinsdelen'},
{v:'Wat is het meewerkend voorwerp in: Hij gaf zijn broer een boek?',o:['zijn broer','een boek','hij','gaf'],g:0,u:'Vraag: aan wie gaf hij het? Aan zijn broer.',t:'zinsdelen'},
{v:'Wat is de bijwoordelijke bepaling in: Morgen begint de les?',o:['morgen','de les','begint','begint de les'],g:0,u:'Morgen zegt wanneer het gebeurt.',t:'zinsdelen'},
{v:'Welk woord is een zelfstandig naamwoord?',o:['vrijheid','vrij','bevrijden','vrijelijk'],g:0,u:'Vrijheid is een ding of begrip, daar kan de of het voor.',t:'zinsdelen'},
{v:'Welk woord is een werkwoord?',o:['besturen','bestuur','bestuurder','bestuurlijk'],g:0,u:'Besturen kun je vervoegen: ik bestuur, hij bestuurde.',t:'zinsdelen'},
{v:'Welk woord is een bijwoord?',o:["snel in hij loopt snel","snelle in de snelle auto","snelheid in een hoge snelheid","versnellen in hij gaat versnellen"], g:0,u:'Een bijwoord zegt iets over het werkwoord: hoe loopt hij? Snel.',t:'zinsdelen'},
  {v:'Welk woord is een voegwoord?',o:['omdat','ondanks','onder','omhoog'],g:0,u:'Een voegwoord verbindt zinnen: omdat, want, maar.',t:'zinsdelen'},
{v:'Wat is het onderwerp in: In 1568 begon de Opstand?',o:['de Opstand','in 1568','begon','1568'],g:0,u:'Vraag: wat begon? De Opstand.',t:'zinsdelen'},
{v:'Hoeveel persoonsvormen staan er in: Hij las het boek en zij keek toe?',o:['twee','een','drie','geen'],g:0,u:'Las en keek zijn allebei persoonsvorm, dus twee zinnen.',t:'zinsdelen'},
{v:'Welk signaalwoord geeft een opsomming aan?',o:['bovendien','echter','doordat','kortom'],g:0,u:'Bovendien telt iets op bij wat er al stond.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een samenvatting aan?',o:['kortom','bijvoorbeeld','hoewel','sinds'],g:0,u:'Kortom vat samen wat er hiervoor stond.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een tijdsvolgorde aan?',o:['vervolgens','daarom','namelijk','ondanks'],g:0,u:'Vervolgens zegt wat er daarna gebeurde.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een voorwaarde aan?',o:['als','ook','dus','verder'],g:0,u:'Als het regent, dan blijven we binnen.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een toegeving aan?',o:['hoewel','doordat','zodat','namelijk'],g:0,u:'Hoewel geeft toe dat iets anders ook waar is.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een vergelijking aan?',o:['evenals','ondanks','doordat','ten slotte'],g:0,u:'Evenals zet twee dingen naast elkaar.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een doel aan?',o:['om te','omdat','ondanks','terwijl'],g:0,u:'Hij spaarde om te reizen: dat is het doel.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een uitleg aan?',o:['namelijk','maar','hoewel','later'],g:0,u:'Namelijk legt uit wat er net stond.',t:'tekstverbanden'},
{v:'Waar verwijst die naar in: De boeren kregen grond. Die was arm?',o:['de grond','de boeren','het dorp','onduidelijk'],g:0,u:'Die is enkelvoud en verwijst naar het laatste enkelvoud: de grond.',t:'verwijswoorden'},
{v:'Welk verwijswoord hoort hier: Het leger trok op. ___ was groot.',o:['Het','Hij','Zij','Die'],g:0,u:'Het leger is onzijdig, dus het.',t:'verwijswoorden'},
{v:'Welk verwijswoord hoort hier: De gilden hadden regels. ___ golden voor iedereen.',o:['Die','Dat','Hij','Het'],g:0,u:'Regels is meervoud, dus die.',t:'verwijswoorden'},
{v:'Waar verwijst hij naar in: De koopman sprak de schipper aan. Hij had haast?',o:['dat is onduidelijk','de koopman','de schipper','allebei'],g:0,u:'Twee mannelijke personen, dus je kunt niet zien wie hij is. Zulke zinnen schrijf je beter anders.',t:'verwijswoorden'},
{v:'Welk verwijswoord hoort hier: Ik zag twee schepen. ___ lagen in de haven.',o:['Ze','Het','Hij','Dat'],g:0,u:'Twee schepen is meervoud, dus ze of die.',t:'verwijswoorden'},
{v:'Wat is fout aan: De stad bouwde een muur, dat kostte veel geld?',o:['dat moet wat zijn','er hoort geen komma','muur moet muren zijn','er ontbreekt een punt'],g:0,u:'Je verwijst naar de hele zin, en dan gebruik je wat.',t:'verwijswoorden'},
{v:'Wat betekent de kogel is door de kerk?',o:['de knoop is doorgehakt','er is geschoten','de kerk is stuk','het is mislukt'],g:0,u:'Er is eindelijk een besluit genomen.',t:'uitdrukkingen'},
{v:'Wat betekent iemand de hand boven het hoofd houden?',o:['iemand beschermen','iemand groeten','iemand meten','iemand tegenhouden'],g:0,u:'Je neemt het voor iemand op.',t:'uitdrukkingen'},
{v:'Wat betekent van de regen in de drup?',o:['van kwaad tot erger','van droog naar nat','net op tijd','met veel geluk'],g:0,u:'Je ontsnapt aan het ene probleem en komt in het volgende.',t:'uitdrukkingen'},
{v:'Wat betekent het roer omgooien?',o:['het helemaal anders aanpakken','een schip besturen','iets kapotmaken','terugkeren'],g:0,u:'Een andere koers kiezen.',t:'uitdrukkingen'},
{v:'Wat betekent met twee maten meten?',o:["niet iedereen gelijk behandelen","heel precies te werk gaan","twee keer achter elkaar meten","alles eerlijk verdelen"], g:0,u:'Voor de een geldt een andere regel dan voor de ander.',t:'uitdrukkingen'},
{v:'Wat betekent de dans ontspringen?',o:["aan iets vervelends ontkomen","gaan dansen op een feest","te laat zijn voor de les","de leiding in handen nemen"], g:0,u:'Je ontsnapt net aan straf of gevaar.',t:'uitdrukkingen'},
{v:'Wat betekent water bij de wijn doen?',o:['toegeven','verdunnen om te besparen','beter maken','ruzie maken'],g:0,u:'Je laat een deel van je eis vallen.',t:'uitdrukkingen'},
{v:'Wat betekent op de bres staan voor iets?',o:['ergens voor opkomen','ergens boven staan','iets breken','wachten'],g:0,u:'Een bres is een gat in een stadsmuur; daar verdedigde je de stad.',t:'uitdrukkingen'},
{v:'Welke zin heeft de dubbele punt goed?',o:['Er waren drie oorzaken: honger, oorlog en ziekte.','Er waren drie oorzaken, honger: oorlog en ziekte.','Er waren: drie oorzaken honger, oorlog en ziekte.','Er waren drie: oorzaken honger oorlog en ziekte.'],g:0,u:'De dubbele punt kondigt de opsomming aan.',t:'leestekens'},
{v:'Welke zin heeft het koppelteken goed?',o:['de zeventiende-eeuwse schilder','de zeventiende eeuwse schilder','de zeventiendeeeuwse schilder','de zeventiende eeuw se schilder'],g:0,u:'Bij drie dezelfde klinkers achter elkaar komt een streepje.',t:'leestekens'},
{v:'Welke zin gebruikt de komma goed bij een opsomming?',o:['Hij kocht brood, kaas en melk.','Hij kocht brood, kaas, en melk.','Hij kocht, brood kaas en melk.','Hij kocht brood kaas, en melk.'],g:0,u:'Geen komma voor het laatste en.',t:'leestekens'},
{v:'Waar hoort het vraagteken in een indirecte vraag: Hij vroeg of ik meeging?',o:['er hoort een punt, geen vraagteken','achter meeging','achter vroeg','er hoort een uitroepteken'],g:0,u:'Een indirecte vraag is geen vraag meer, dus een punt.',t:'leestekens'},
{v:'Waar hoort het vraagteken bij een citaat?',o:['"Kom je?" vroeg zij.','"Kom je"? vroeg zij.','"Kom je? vroeg zij."','Kom je? "vroeg zij".'],g:0,u:'Het vraagteken hoort bij de vraag, dus binnen de aanhalingstekens.',t:'leestekens'},
{v:'Welke zin heeft de komma goed bij een aanspreking?',o:['Sanne, kun je even helpen?','Sanne kun je, even helpen?','Sanne kun je even, helpen?','Sanne kun je even helpen,?'],g:0,u:'Na wie je aanspreekt komt een komma.',t:'leestekens'},
  {v:'Wat is een synoniem van vertellen?',o:['verhalen','verhullen','verhuizen','verhuren'],g:0,u:'Verhalen is een deftig woord voor vertellen.',t:'synoniemen'},
{v:'Wat is een synoniem van veranderen?',o:['wijzigen','wegen','wijzen','wennen'],g:0,u:'Wijzigen betekent veranderen.',t:'synoniemen'},
  {v:'Wat is een synoniem van genoeg?',o:['voldoende','volledig','volgend','vervolgens'],g:0,u:'Voldoende is genoeg.',t:'synoniemen'},
  {v:'Wat is het tegenovergestelde van toestaan?',o:['verbieden','toegeven','toevoegen','tegenkomen'],g:0,u:'Verbieden is het tegenovergestelde van toestaan.',t:'synoniemen'},
{v:'Wat is het tegenovergestelde van toenemen?',o:['afnemen','aannemen','opnemen','innemen'],g:0,u:'Toenemen is stijgen, afnemen is dalen.',t:'synoniemen'},
{v:'Wat betekent het woord bewind?',o:['het bestuur','de wind','een bewijs','een gewoonte'],g:0,u:'Onder het bewind van iemand betekent onder zijn bestuur.',t:'betekenis'},
{v:'Wat betekent het woord welvaart?',o:['rijkdom van een land','een snelle vaart','gezondheid','een goede reis'],g:0,u:'Welvaart gaat over hoeveel een land te besteden heeft.',t:'betekenis'},
{v:'Wat betekent het woord tolerantie?',o:["anderen laten denken wat ze willen","onverschillig zijn over alles","vriendelijk zijn tegen iedereen","gehoorzaam doen wat er gevraagd wordt"], g:0,u:'Tolerantie is verdraagzaamheid.',t:'betekenis'},
{v:'Wat betekent het woord gezag?',o:["het recht om te bevelen","een gezegde uit de oude doos","een leger onder één bevel","een verzoek om iets te doen"], g:0,u:'Wie gezag heeft, mag beslissen en wordt gehoorzaamd.',t:'betekenis'},
{v:'Wat betekent het woord onafhankelijk?',o:['niet onder een ander','alleenstaand','zonder geld','niet te vertrouwen'],g:0,u:'Een onafhankelijk land bepaalt zelf wat het doet.',t:'betekenis'},
{v:'Wat betekent het woord verdrag?',o:['een afspraak tussen landen','een vertraging','een verdrietig bericht','een wet'],g:0,u:'Een verdrag sluiten landen met elkaar.',t:'betekenis'},
{v:'Hoe schrijf je het zelfstandig naamwoord van gebeuren?',o:['gebeurtenis','gebeurdtenis','gebeurtenies','gebeurtnis'],g:0,u:'Van gebeuren: gebeurtenis, met t.',t:'spelling'},
{v:'Hoeveel keer een k in dit woord?',o:['ontwikkeling','ontwikeling','ontwikkelling','onwikkeling'],g:0,u:'Twee keer een k, van ontwikkelen.',t:'spelling'},
{v:'Wat is het meervoud van gebeurtenis?',o:['gebeurtenissen','gebeurtenisen','gebeurtenissn','gebeurtenises'],g:0,u:'Korte klank, dus dubbele s in het meervoud.',t:'spelling'},
{v:'Wat schrijf je als je althans bedoelt?',o:['tenminste','ten minste betekent iets anders','ten-minste','tenminst'],g:0,u:'Tenminste betekent althans, ten minste betekent minimaal.',t:'spelling'},
{v:'Hoe schrijf je dit uit het Duits geleende woord?',o:['sowieso','souwieso','zowiezo','so wie so'],g:0,u:'Het komt uit het Duits en blijft sowieso.',t:'spelling'},
{v:'Welke schrijfwijze van dit tijdwoord klopt?',o:['sinds','sints','sinds dat','sindt'],g:0,u:'Sinds, altijd met ds.',t:'spelling'},
  {v:'Wat is het meervoud van ei?',o:['eieren','eien','eis','eiers'],g:0,u:'Ook eren: ei wordt eieren.',t:'meervoud'},
{v:'Wat is het meervoud van lid?',o:['leden','lidden','lids','liden'],g:0,u:'Lid wordt leden, net als schip en schepen.',t:'meervoud'},
{v:'Wat is het meervoud van koe?',o:['koeien','koes','koeen','koe\'s'],g:0,u:'Koe wordt koeien met een tussen-i.',t:'meervoud'},
{v:'Wat is het meervoud van dief?',o:['dieven','diefs','dieffen','diefen'],g:0,u:'De f wordt een v: dieven.',t:'meervoud'},
{v:'Wat is het meervoud van kans?',o:['kansen','kanzen','kanssen','kans'],g:0,u:'Gewoon en erachter, de s blijft: kansen.',t:'meervoud'},
{v:'Welk verwijswoord hoort hier: Het verdrag was klaar. ___ werd in 1648 getekend.',o:['Het','Hij','Die','Ze'],g:0,u:'Het verdrag is onzijdig, dus het.',t:'verwijswoorden'},
{v:'Welk verwijswoord hoort hier: De ridder kreeg land. ___ moest daarvoor vechten.',o:['Hij','Het','Ze','Die van hem'],g:0,u:'De ridder is mannelijk enkelvoud.',t:'verwijswoorden'},
{v:'Waar verwijst dat naar in: De pest kwam in 1348. Dat veranderde alles.',o:['de komst van de pest','het jaar 1348','de stad','de bevolking'],g:0,u:'Dat verwijst naar de hele gebeurtenis uit de vorige zin.',t:'verwijswoorden'},
{v:'Welk woord verwijst terug in: De boeren en hun kinderen werkten mee. Zij hadden het zwaar.',o:['zij','hun','de','en'],g:0,u:'Zij verwijst terug naar de boeren en hun kinderen.',t:'verwijswoorden'},
{v:'Wat is beter: De koning sprak met de bisschop. Hij was boos.',o:['schrijf op wie je bedoelt','laat het zo staan','maak er zij van','maak er het van'],g:0,u:'Bij twee mannelijke personen is hij onduidelijk; noem de naam.',t:'verwijswoorden'},
{v:'Welk verwijswoord hoort hier: De wetten waren streng. ___ golden voor iedereen.',o:['Ze','Het','Hij','Dat'],g:0,u:'Wetten is meervoud, dus ze of die.',t:'verwijswoorden'},
{v:'Welk verwijswoord hoort hier: Ik zag het schip. ___ lag in de haven.',o:['Het','Hij','Ze','Die'],g:0,u:'Het schip is onzijdig.',t:'verwijswoorden'},
{v:'Welk signaalwoord past: Hij had geen geld. ___ kon hij niets kopen.',o:['Daarom','Hoewel','Bijvoorbeeld','Toch'],g:0,u:'Daarom noemt het gevolg.',t:'tekstverbanden'},
{v:'Welk signaalwoord past: ___ het regende, gingen we toch fietsen.',o:['Hoewel','Doordat','Zodat','Omdat'],g:0,u:'Hoewel geeft een tegenstelling aan.',t:'tekstverbanden'},
{v:'Welk signaalwoord past: De stad groeide, ___ er kwam werk in de fabrieken.',o:['want','maar','hoewel','toch'],g:0,u:'Want geeft de reden.',t:'tekstverbanden'},
{v:'Welk signaalwoord past: Eerst kwam de landbouw. ___ ontstonden de steden.',o:['Daarna','Daarom','Namelijk','Hoewel'],g:0,u:'Daarna geeft de volgorde in de tijd aan.',t:'tekstverbanden'},
{v:'Welk signaalwoord past: Er waren veel doden, ___ door honger en ziekte.',o:['vooral','ondanks','hoewel','tenzij'],g:0,u:'Vooral benadrukt het belangrijkste deel.',t:'tekstverbanden'},
{v:'Welk signaalwoord past: ___ je op tijd bent, mag je mee.',o:['Mits','Ondanks','Hoewel','Terwijl'],g:0,u:'Mits geeft een voorwaarde aan.',t:'tekstverbanden'},
{v:'Welk signaalwoord past: Hij was arm. ___ gaf hij nog geld weg.',o:['Toch','Daarom','Dus','Namelijk'],g:0,u:'Toch zet er iets onverwachts tegenover.',t:'tekstverbanden'},
{v:'Welk signaalwoord past: ___ waren er drie oorzaken van de opstand.',o:['Kortom','Bijvoorbeeld','Toch','Mits'],g:0,u:'Kortom vat samen.',t:'tekstverbanden'},
{v:'Wat betekent het hoofd koel houden?',o:['rustig blijven','een muts dragen','nadenken over school','ziek worden'],g:0,u:'Niet in paniek raken.',t:'uitdrukkingen'},
{v:'Wat betekent de handen ineenslaan?',o:['gaan samenwerken','klappen','bidden','opgeven'],g:0,u:'Samen aan de slag gaan.',t:'uitdrukkingen'},
{v:'Wat betekent iets in de kiem smoren?',o:['iets stoppen voor het begint','een plant water geven','iets verstoppen','iets langzaam doen'],g:0,u:'Een opstand in de kiem smoren is hem meteen neerslaan.',t:'uitdrukkingen'},
{v:'Wat betekent de knoop doorhakken?',o:['een besluit nemen','een touw kapotmaken','ruzie beslechten','iets opgeven'],g:0,u:'Na lang twijfelen eindelijk kiezen.',t:'uitdrukkingen'},
{v:'Wat betekent met de deur in huis vallen?',o:['meteen ter zake komen','onbeleefd binnenkomen','struikelen','onaangekondigd langsgaan'],g:0,u:'Zonder omhaal zeggen waar het om gaat.',t:'uitdrukkingen'},
{v:'Wat betekent het onderspit delven?',o:['verliezen','graven','winnen','wachten'],g:0,u:'Je legt het af tegen de ander.',t:'uitdrukkingen'},
{v:'Wat betekent tegen de stroom in gaan?',o:['tegen de meerderheid ingaan','moeilijk zwemmen','langzaam werken','verdwalen'],g:0,u:'Je doet iets anders dan wat gebruikelijk is.',t:'uitdrukkingen'},
{v:'Wat is de persoonsvorm in: De steden groeiden snel?',o:['groeiden','de steden','snel','steden groeiden'],g:0,u:'Zet de zin in een andere tijd: groeien wordt groeiden. Dat is de persoonsvorm.',t:'zinsdelen'},
{v:'Wat is het onderwerp in: Aan de rivier lag een haven?',o:['een haven','aan de rivier','lag','de rivier'],g:0,u:'Vraag: wat lag daar? Een haven.',t:'zinsdelen'},
{v:'Welk woord is een telwoord?',o:['zeven','zeker','zelden','zelfs'],g:0,u:'Een telwoord geeft een aantal aan.',t:'zinsdelen'},
{v:'Welk woord is een voornaamwoord?',o:['zij','ziek','zelden','zoals'],g:0,u:'Zij vervangt een zelfstandig naamwoord.',t:'zinsdelen'},
{v:'Wat is het lijdend voorwerp in: De monniken kopieerden boeken?',o:['boeken','de monniken','kopieerden','de monniken kopieerden'],g:0,u:'Vraag: wat kopieerden ze? Boeken.',t:'zinsdelen'},
{v:'Hoeveel zinsdelen telt: Gisteren kocht hij brood?',o:['vier','drie','twee','vijf'],g:0,u:'Gisteren, kocht, hij, brood. Dat zijn vier zinsdelen: bepaling, persoonsvorm, onderwerp en lijdend voorwerp.',t:'zinsdelen'},
{v:'Welk woord is een bijvoeglijk naamwoord in: De rijke koopman kocht een groot schip?',o:['rijke','koopman','kocht','schip'],g:0,u:'Rijke zegt iets over de koopman.',t:'zinsdelen'},
{v:'Welke zin is een bijzin?',o:['omdat het regende','het regende','het regent hard','regende het?'],g:0,u:'Een bijzin kan niet alleen staan en begint met een voegwoord.',t:'zinsdelen'},
{v:'Welke zin heeft de komma goed bij een tussenzin?',o:['De koning, die ziek was, bleef thuis.','De koning die ziek was bleef, thuis.','De koning die, ziek was, bleef thuis.','De koning, die ziek was bleef thuis.'],g:0,u:'Een tussenzin staat tussen twee kommas.',t:'leestekens'},
{v:'Waar hoort de komma in: Ja ik kom eraan?',o:['Ja, ik kom eraan.','Ja ik, kom eraan.','Ja ik kom, eraan.','Ja ik kom eraan,'],g:0,u:'Na ja of nee komt een komma.',t:'leestekens'},
{v:'Welke zin heeft de punt goed?',o:['Hij las het boek uit.','Hij las het boek uit','Hij las. het boek uit','Hij. las het boek uit'],g:0,u:'De punt staat aan het eind van de zin.',t:'leestekens'},
{v:'Zij ___ een brief aan haar oma.',o:['schrijft','schrijfd','schrijf','schrijvt'],g:0,u:'Hij, zij, het: stam + t. De stam van schrijven is schrijf.',t:'werkwoordspelling'},
{v:'___ jij morgen elf?',o:['Wort','Wordd','Word','Wordt'],g:2,u:'Staat jij achter het werkwoord, dan valt de t weg: word jij.',t:'werkwoordspelling'},
{v:'Gisteren ___ ik de hele dag in de tuin.',o:['werkde','werkte','werkten','werkt'],g:1,u:'Verleden tijd: de stam werk eindigt op een k, een letter uit \'t kofschip, dus -te.',t:'werkwoordspelling'},
{v:'Vorige week ___ wij een film in de klas.',o:['kijkte','keekten','keken','kijkten'],g:2,u:'Kijken is een sterk werkwoord: de klinker verandert (kijk, keek, gekeken). Meervoud verleden tijd: keken.',t:'werkwoordspelling'},
{v:'Het heeft de hele nacht ___.',o:['gereegend','geregend','geregent','geregendt'],g:1,u:'Voltooid deelwoord van regenen: de stam regen eindigt op een n, niet in \'t kofschip, dus -d.',t:'werkwoordspelling'},
{v:'De boot ___ langzaam de haven binnen.',o:['vaart','vaar','vaard','vaardt'],g:0,u:'Hij-vorm: stam vaar + t. Ook al hoor je een d in varen, de stam is vaar.',t:'werkwoordspelling'},
{v:'Wat ___ er gisteren precies op het plein?',o:['gebeurte','gebeurd','gebeurdde','gebeurde'],g:3,u:'Verleden tijd van gebeuren: de stam gebeur eindigt op een r, niet in \'t kofschip, dus -de.',t:'werkwoordspelling'},
{v:'De ___ auto stond nog in de garage.',o:['beschadigdde','beschadigte','beschadigt','beschadigde'],g:3,u:'Als bijvoeglijk naamwoord: het voltooid deelwoord beschadigd krijgt een e erachter.',t:'werkwoordspelling'},
{v:'Hij heeft zich ___ voor zijn gedrag.',o:['verontschuldigd','verontschuldigdt','verontschuldig','verontschuldigt'],g:0,u:'Voltooid deelwoord van verontschuldigen: stam op een g, niet in \'t kofschip, dus -d. Geen ge-, want ver- is al een voorvoegsel.',t:'werkwoordspelling'},
{v:'Toen hij binnenkwam, ___ de vergadering al.',o:['begonnen','beginde','begon','begint'],g:2,u:'Enkelvoud verleden tijd van beginnen: begon. Een sterk werkwoord, dus geen -de.',t:'werkwoordspelling'},
{v:'De ___ spullen liggen bij de conciërge.',o:['gevonden','gevonde','gevondene','gevindde'],g:0,u:'Het voltooid deelwoord gevonden als bijvoeglijk naamwoord: het eindigt al op -en, dus er komt geen extra e bij.',t:'werkwoordspelling'},
  {v:'Welke is goed?',o:['ik find','ik vint','ik vind','ik vindt'],g:2,u:'Bij ik nooit een t: ik vind. Vindt is voor hij, zij en het.',t:'spelling'},
  {v:'Hoe schrijf je het goed?',o:['gefeliciteerd','gefeliciteerdt','gefeliciteert','gefelicieteerd'],g:0,u:'Voltooid deelwoord van feliciteren: stam feliciteer + d, want de r staat niet in \'t kofschip.',t:'spelling'},
  {v:'Wat is het meervoud van idee?',o:['ideën','idees','ideeën','ideeen'],g:2,u:'Idee, ideeën. Het trema voorkomt dat je -eeen als één klank leest.',t:'meervoud'},
{v:'Wat is het meervoud van politicus?',o:['politicusen','politicus\'s','politici','politicussen'],g:2,u:'Politicus, politici, uit het Latijn. Net als musicus, musici.',t:'meervoud'},
{v:'Wat is het meervoud van bacterie?',o:['bacteriën','bacterieën','bacterien','bacteries'],g:0,u:'Bacterie, bacteriën: een trema op de e, omdat -ie + -en anders als één klank gelezen wordt.',t:'meervoud'},
{v:'Wat is het onderwerp in: De hond blaft naar de postbode.',o:['blaft','naar de postbode','de hond','de postbode'],g:2,u:'Wie of wat blaft? De hond.',t:'zinsdelen'},
{v:'Wat is de persoonsvorm in: Morgen gaan wij naar de dierentuin.',o:['wij','morgen','gaan','de dierentuin'],g:2,u:'Zet de zin in een andere tijd: Morgen gingen wij. Het woord dat verandert, is de persoonsvorm.',t:'zinsdelen'},
{v:'Wat is het lijdend voorwerp in: Mijn zus koopt een nieuwe fiets.',o:['een nieuwe fiets','koopt','nieuwe','mijn zus'],g:0,u:'Wat koopt mijn zus? Een nieuwe fiets.',t:'zinsdelen'},
{v:'Wat is het meewerkend voorwerp in: De juf geeft de leerlingen huiswerk.',o:['de leerlingen','geeft','huiswerk','de juf'],g:0,u:'Aan wie geeft de juf huiswerk? Aan de leerlingen. Je kunt er aan voor zetten.',t:'zinsdelen'},
{v:'Wat is het naamwoordelijk gezegde in: Mijn broer is kapper.',o:['is','mijn broer','is kapper','kapper'],g:2,u:'Zijn, worden en blijven vormen met een naamwoord een naamwoordelijk gezegde: is kapper.',t:'zinsdelen'},
{v:'Welke zinsdelen zijn bijwoordelijke bepalingen in: Na de les fietsten we snel naar huis.',o:["na de les, snel en naar huis","de les, als lijdend voorwerp","fietsten, als de persoonsvorm","we, als het onderwerp"], g:0,u:'Bepalingen van tijd (na de les), wijze (snel) en plaats (naar huis) zijn alle drie bijwoordelijke bepalingen.',t:'zinsdelen'},
{v:'Het meisje zegt dat ___ moe is.',o:['hem','ze','het','hij'],g:1,u:'Meisje is een het-woord, maar je verwijst naar een persoon: ze of zij.',t:'verwijswoorden'},
{v:'De regering heeft ___ plannen bekendgemaakt.',o:['hun','haar','hen','zijn'],g:1,u:'Regering is vrouwelijk, dus haar. Woorden op -ing zijn vrijwel altijd vrouwelijk.',t:'verwijswoorden'},
{v:'Het boek ___ ik gisteren kocht, is spannend.',o:['die','dat','wat','welk'],g:1,u:'Het boek is een het-woord, dus het betrekkelijk voornaamwoord is dat.',t:'verwijswoorden'},
{v:'Ik heb ___ gisteren nog gezien.',o:['hen','zij','ze hun','hun'],g:0,u:'Hen is de vorm voor het lijdend voorwerp. Hun gebruik je als meewerkend voorwerp zonder aan (ik geef hun een boek) of als bezittelijk voornaamwoord.',t:'verwijswoorden'},
{v:'Welk woord geeft een tegenstelling aan? Ik wilde gaan, ___ ik was ziek.',o:['dus','en','maar','want'],g:2,u:'Maar zet twee dingen tegenover elkaar.',t:'tekstverbanden'},
{v:'Welk verband geeft omdat aan?',o:["oorzaak en gevolg","een opsomming van dingen","een moment in de tijd","een tegenstelling tussen twee"], g:0,u:'Omdat geeft een reden of oorzaak: Ik bleef thuis omdat ik ziek was.',t:'tekstverbanden'},
{v:'Ik was moe, ___ ging ik vroeg naar bed.',o:['hoewel','maar','want','dus'],g:3,u:'Dus geeft een gevolg of conclusie aan.',t:'tekstverbanden'},
{v:'Welk signaalwoord hoort bij een voorbeeld?',o:['bijvoorbeeld','vervolgens','daarom','hoewel'],g:0,u:'Bijvoorbeeld, zoals en ter illustratie kondigen een voorbeeld aan.',t:'tekstverbanden'},
{v:'Welk verband geeft hoewel aan?',o:["een toegeving","een opsomming van punten","een doel dat je wilt bereiken","een vergelijking tussen twee"], g:0,u:'Hoewel het regende, gingen we toch. Iets gebeurt ondanks iets anders: een toegevend verband.',t:'tekstverbanden'},
{v:'Wat betekent: iemand een hart onder de riem steken?',o:['iemand een cadeau geven','iemand pijn doen','iemand uitlachen','iemand moed geven'],g:3,u:'Je steunt iemand die het moeilijk heeft.',t:'uitdrukkingen'},
{v:'Wat betekent: de kat uit de boom kijken?',o:['heel goed opletten in de klas','niet durven kijken','afwachten voordat je iets doet','een dier redden'],g:2,u:'Je kijkt eerst hoe iets loopt voordat je zelf meedoet.',t:'uitdrukkingen'},
{v:'Wat betekent: iets door de vingers zien?',o:['iets kwijtraken','iets goed bekijken','iets stiekem stelen','een fout oogluikend toestaan'],g:3,u:'Je doet alsof je een fout niet ziet.',t:'uitdrukkingen'},
{v:'Wat betekent: met de deur in huis vallen?',o:['onaangekondigd op bezoek komen','ruzie maken bij de voordeur','meteen ter zake komen','struikelen bij binnenkomst'],g:2,u:'Zonder inleiding direct zeggen waar het om gaat.',t:'uitdrukkingen'},
{v:'Wat betekent: een storm in een glas water?',o:['een groot probleem','een ruzie die uit de hand loopt','veel drukte om iets kleins','slecht weer op zee'],g:2,u:'Er wordt veel ophef gemaakt over iets dat eigenlijk onbelangrijk is.',t:'uitdrukkingen'},
{v:'Wat is een synoniem van gigantisch?',o:['klein','mooi','enorm','gevaarlijk'],g:2,u:'Gigantisch en enorm betekenen allebei heel groot.',t:'synoniemen'},
{v:'Wat is een synoniem van bescheiden?',o:['zeer trots','erg rijk','onbeleefd','niet opschepperig'],g:3,u:'Wie bescheiden is, loopt niet met zichzelf te koop.',t:'synoniemen'},
{v:'Wat is een synoniem van consequent?',o:["steeds op dezelfde manier","heel streng voor anderen","maar af en toe een keer","uitzonderlijk voor die tijd"], g:0,u:'Consequent handelen is steeds volgens dezelfde lijn handelen.',t:'synoniemen'},
{v:'Wat betekent verwoesten?',o:['wegjagen','opnieuw opbouwen','schoonmaken','helemaal kapotmaken'],g:3,u:'Een verwoeste stad is een stad die kapotgemaakt is.',t:'betekenis'},
{v:'Wat betekent unaniem?',o:['de helft is het ermee eens','iedereen is het ermee eens','het is nog niet besloten','niemand is het ermee eens'],g:1,u:'Een unaniem besluit is door iedereen gesteund.',t:'betekenis'},
{v:'Wat betekent nuanceren?',o:["iets minder scherp stellen","iets nog eens herhalen","iets in een andere taal vertalen","iets flink overdrijven"], g:0,u:'Wie nuanceert, voegt toe dat het ook anders kan liggen.',t:'betekenis'},
{v:'Wat betekent ambivalent?',o:["tegenstrijdige gevoelens hebben","heel ambitieus ingesteld zijn","onverschillig tegenover alles","heel zeker van je zaak zijn"], g:0,u:'Je voelt twee kanten tegelijk: je wilt het wel en niet.',t:'betekenis'}
];
var NED2_N = [1,1,1,1,1,1,2,2,2,2,2,2,2,3,3,2,2,2,2,2,2,2,3,3,3,3,3,3,1,1,1,1,2,1,1,2,2,2,2,3,3,3,3,1,1,1,1,1,1,2,2,2,2,3,3,3,3,3,3,1,1,1,1,1,2,2,2,2,3,2,1,1,1,1,2,3,2,3,2,1,1,1,2,1,2,2,2,2,2,2,1,1,3,2,1,1,2,2,2,2,3,2,3,1,2,3,3,3,4,3,2,4,2,3,2,2,2,3,3,3,2,3,2,3,4,4,3,2,3,4,4,3,2,3,4,3,3,2,3,4,4,2,4,3,2,2,4,1,3,3,4,2,3,2,2,4,4,3,3,4,2,3,4,2,4,4,4,3,3,4,4,4,4,2,4,2,4,4,2,1,3,3,3,2,1,2,2,4,3,4,3,2,2,2,2,2,4,3,2,1,1,3,2,2,2,2,1,3,2,4,2,2,2,3,2,2,3,4,3,3,2,3,4,2,3,4,3,2,3,2,2,3,4,2,4,4,1,1,1,1,2,2,2,2,3,3,3,4,4,1,1,2,2,2,3,3,4,2,3,3,1,2,2,3,3,4,1,2,3,4,1,2,2,3,4,1,2,2,3,4,2,3,4,1,2,3,4];
var NED3 = [
{v:'Mijn broer ___ elke dag op de bus.',o:['wacht','wachtt','wagt','wachd'],g:0,u:'De stam van wachten is wacht en die eindigt al op een t. Er komt geen tweede t bij.',t:'werkwoordspelling'},
{v:'___ jij vanavond mee?',o:['Eet','Eett','Eed','Eten'],g:0,u:'Jij staat achter het werkwoord, dus alleen de stam: eet.',t:'werkwoordspelling'},
{v:'De kinderen ___ in de tuin.',o:['spelen','speelt','speelen','spelend'],g:0,u:'De kinderen zijn meervoud, dus het hele werkwoord: spelen. Let op: eén e in spelen, want de klank is lang en de lettergreep is open.',t:'werkwoordspelling'},
{v:'Ik ___ gisteren een film. (verleden tijd)',o:['keek','kijkte','keekte','keke'],g:0,u:'Kijken is een sterk werkwoord: de klinker verandert. Kijken, keek, gekeken.',t:'werkwoordspelling'},
{v:'Hij heeft zijn fiets ___.',o:['gerepareerd','gerepareert','gereparreerd','gerepareerdt'],g:0,u:'Voltooid deelwoord: repareren, ik repareer, stam repareer. De r staat niet in ’t kofschip, dus een d.',t:'werkwoordspelling'},
{v:'De trein ___ om acht uur. (verleden tijd)',o:['vertrok','vertrokte','vertrekte','vertrekt'],g:0,u:'Vertrekken is sterk: vertrekken, vertrok, vertrokken.',t:'werkwoordspelling'},
{v:'Zij ___ het cadeau meteen. (verleden tijd)',o:['pakte','pakde','paktte','pakt'],g:0,u:'Pakken: de stam pak eindigt op een k uit ’t kofschip, dus te. Een t erbij en niet twee.',t:'werkwoordspelling'},
{v:'Welke zin is goed gespeld?',o:['Het verbaasde niemand dat hij won.','Het verbaasdde niemand dat hij won.','Het verbaaste niemand dat hij won.','Het verbaasd niemand dat hij won.'],g:0,u:'Verleden tijd van verbazen: de stam is verbaas (van verbazen, met een z), en de z staat niet in ’t kofschip, dus de: verbaasde.',t:'werkwoordspelling'},
{v:'Het bericht werd meteen ___.',o:['verspreid','verspreidt','verspreidd','verspreide'],g:0,u:'Voltooid deelwoord van verspreiden: de stam verspreid eindigt al op een d, en daar komt niets bij. Verspreidt is de tegenwoordige tijd bij hij.',t:'werkwoordspelling'},
  {v:'Welke schrijfwijze is goed?',o:['de auto’s','de autos','de auto’s’','de autoos'],g:0,u:'Een woord dat eindigt op een losse o krijgt in het meervoud een apostrof voor de s, anders zou je autos lezen met een korte o.',t:'spelling'},
  {v:'Welk woord is goed gespeld?',o:['privileges','privilleges','priviliges','privilegies'],g:0,u:'Privilege: p-r-i-v-i-l-e-g-e. Alle klinkers zijn een i of een e, zonder dubbele letters.',t:'spelling'},
{v:'Wat is een synoniem van mooi?',o:['prachtig','lelijk','groot','oud'],g:0,u:'Prachtig en mooi betekenen hetzelfde; lelijk is het tegenovergestelde.',t:'synoniemen'},
{v:'Wat is een synoniem van kwaad?',o:['boos','blij','bang','lief'],g:0,u:'Kwaad en boos betekenen hetzelfde.',t:'synoniemen'},
{v:'Wat is een synoniem van kiezen?',o:['uitzoeken','weggooien','vergeten','vragen'],g:0,u:'Kiezen en uitzoeken betekenen hetzelfde: je bepaalt welke je wilt.',t:'synoniemen'},
{v:'Wat is een synoniem van vermoeid?',o:['moe','uitgerust','fit','wakker'],g:0,u:'Vermoeid is een deftiger woord voor moe.',t:'synoniemen'},
{v:'Wat is een synoniem van zeldzaam?',o:['uniek','gewoon','goedkoop','vaak'],g:0,u:'Zeldzaam en uniek: iets wat je bijna nergens vindt.',t:'synoniemen'},
{v:'Wat is een synoniem van bondig?',o:['kort en krachtig','lang en uitgebreid','onduidelijk','vriendelijk'],g:0,u:'Een bondig antwoord zegt veel in weinig woorden.',t:'synoniemen'},
{v:'Wat is een synoniem van ambivalent?',o:["met tegenstrijdige gevoelens","overtuigd van je gelijk","onverschillig over alles","vijandig tegen anderen"], g:0,u:'Wie ambivalent is, voelt twee kanten tegelijk: hij wil het wel en niet.',t:'synoniemen'},
{v:'Wat betekent het woord voordeel?',o:["iets wat gunstig voor je is","iets wat juist slecht uitpakt","een soort deur in een huis","een cadeau dat je krijgt"], g:0,u:'Een voordeel is iets goeds; het tegenovergestelde is een nadeel.',t:'betekenis'},
{v:'Wat betekent vermijden?',o:['ergens uit de buurt blijven','iets opzoeken','iets kopen','ergens naartoe gaan'],g:0,u:'Als je iets vermijdt, zorg je dat je er niet mee te maken krijgt.',t:'betekenis'},
{v:'Wat betekent het woord fragment?',o:['een stukje van een groter geheel','een heel boek','een fout in een tekst','een soort brief'],g:0,u:'Een fragment is een deel, bijvoorbeeld een stukje uit een film of een tekst.',t:'betekenis'},
{v:'Wat betekent het woord conclusie?',o:['wat je aan het eind uit iets afleidt','het begin van een verhaal','een vraag','een voorbeeld'],g:0,u:'Een conclusie is de slotsom: wat je na alle argumenten vaststelt.',t:'betekenis'},
{v:'Wat betekent objectief?',o:['zonder eigen mening, gebaseerd op feiten','met een sterke eigen mening','onduidelijk','overdreven'],g:0,u:'Objectief is het tegenovergestelde van subjectief: je kijkt naar de feiten, niet naar je gevoel.',t:'betekenis'},
{v:'Wat betekent het woord ironie?',o:["het tegenovergestelde zeggen","een heel groot compliment","een ernstige waarschuwing","een geheim dat niemand kent"], g:0,u:'Lekker weer, zeg je in de stromende regen: dat is ironie.',t:'betekenis'},
{v:'Wat betekent een paradox?',o:["tegenstrijdig, maar toch waar","een lange zin zonder werkwoord","een woord met twee betekenissen","een oud spreekwoord uit het boek"], g:0,u:'Bijvoorbeeld: minder is meer. Het lijkt onzin, maar er zit een waarheid in.',t:'betekenis'},
{v:'Wat betekent relativeren?',o:["iets minder zwaar maken","iets erger maken dan het is","iets steeds maar blijven herhalen","iets helemaal verbieden"], g:0,u:'Wie relativeert, zegt: het is vervelend, maar er zijn ergere dingen.',t:'betekenis'},
{v:'Welk leesteken hoort aan het eind van een vraag?',o:['een vraagteken','een punt','een komma','een uitroepteken'],g:0,u:'Kom je morgen? Een vraag eindigt op een vraagteken.',t:'leestekens'},
{v:'Welk leesteken hoort na: Pas op',o:['een uitroepteken','een komma','een punt','een vraagteken'],g:0,u:'Pas op! is een waarschuwing, een uitroep. Daar hoort een uitroepteken achter.',t:'leestekens'},
{v:'Welke zin heeft de komma op de goede plek?',o:['Als je klaar bent, mag je gaan.','Als je, klaar bent mag je gaan.','Als je klaar, bent mag je gaan.','Als je klaar bent mag, je gaan.'],g:0,u:'Na een bijzin die vooraan staat, komt een komma: daar botsen twee werkwoorden (bent en mag).',t:'leestekens'},
  {v:'Waar hoort de dubbele punt?',o:['Hij zei: dat is genoeg.','Hij zei dat: is genoeg.','Hij: zei dat is genoeg.','Hij zei dat is: genoeg.'],g:0,u:'Een dubbele punt kondigt aan wat iemand zegt of wat er volgt.',t:'leestekens'},
  {v:'Wat is het meervoud van boek?',o:['boeken','boeks','boekken','boeke'],g:0,u:'Boek krijgt gewoon en: boeken. Eén e, want de klank blijft lang.',t:'meervoud'},
{v:'Wat is het meervoud van lied?',o:['liederen','lieds','liedes','lieden'],g:0,u:'Lied krijgt er een hele lettergroep bij, net als kind en kinderen: liederen.',t:'meervoud'},
{v:'Wat is het meervoud van brief?',o:['brieven','briefs','briefen','brieve'],g:0,u:'De f wordt een v: brief, brieven. Zo ook duif en duiven.',t:'meervoud'},
{v:'Wat is het meervoud van reis?',o:['reizen','reisen','reissen','reize'],g:0,u:'De s wordt een z: reis, reizen. Zo ook huis en huizen.',t:'meervoud'},
{v:'Wat is het meervoud van datum?',o:['data','datums','datumen','datae'],g:0,u:'Datum komt uit het Latijn en krijgt data. Datums mag tegenwoordig ook, maar data is het klassieke meervoud.',t:'meervoud'},
{v:'Wat is het meervoud van medicus?',o:['medici','medicussen','medicusen','medicus’'],g:0,u:'Woorden op -us uit het Latijn krijgen vaak -i: medicus, medici; politicus, politici.',t:'meervoud'},
{v:'Wat is het meervoud van zee?',o:['zeeën','zees','zeeen','zeën'],g:0,u:'Zee eindigt op een dubbele e. Daar komt en achter, met een trema op de derde e: zeeën.',t:'meervoud'},
{v:'Wat is het onderwerp in: De hond blaft hard?',o:['de hond','blaft','hard','blaft hard'],g:0,u:'Wie of wat blaft? De hond. Dat is het onderwerp.',t:'zinsdelen'},
{v:'Wat is het onderwerp in: Morgen komt oma op bezoek?',o:['oma','morgen','bezoek','komt'],g:0,u:'Wie komt op bezoek? Oma. Het onderwerp hoeft niet vooraan in de zin te staan.',t:'zinsdelen'},
{v:'Wat is de persoonsvorm in: Morgen gaan wij naar Amsterdam?',o:['gaan','morgen','wij','Amsterdam'],g:0,u:'Maak de zin vragend: Gaan wij morgen naar Amsterdam? Het werkwoord dat vooraan komt is de persoonsvorm.',t:'zinsdelen'},
{v:'Wat is het gezegde in: De bus vertrekt om acht uur?',o:['vertrekt','de bus','om acht uur','acht'],g:0,u:'Het gezegde bestaat uit alle werkwoorden in de zin. Hier is dat alleen vertrekt.',t:'zinsdelen'},
{v:'Wat is het lijdend voorwerp in: Sara leest een spannend boek?',o:['een spannend boek','Sara','leest','spannend'],g:0,u:'Wat leest Sara? Een spannend boek. Het lijdend voorwerp vind je met de vraag wat of wie plus het gezegde plus het onderwerp.',t:'zinsdelen'},
{v:'Wat is het meewerkend voorwerp in: Ik geef mijn zus een cadeau?',o:['mijn zus','een cadeau','ik','geef'],g:0,u:'Aan wie geef ik een cadeau? Aan mijn zus. Je kunt er aan voor zetten, dus meewerkend voorwerp.',t:'zinsdelen'},
{v:'Wat is het naamwoordelijk gezegde in: Mijn oom is timmerman geworden?',o:['is timmerman geworden','is geworden','timmerman','mijn oom is'],g:0,u:'Worden is een koppelwerkwoord. Het naamwoordelijk gezegde bestaat uit de werkwoorden en het naamwoordelijk deel: is timmerman geworden.',t:'zinsdelen'},
{v:'Welk woord is een voegwoord in: Ik blijf thuis, omdat het regent?',o:['omdat','ik','thuis','regent'],g:0,u:'Omdat verbindt de hoofdzin met de bijzin. Andere voegwoorden zijn dat, als, terwijl en hoewel.',t:'zinsdelen'},
{v:'Welk woord geeft een tegenstelling aan?',o:['maar','en','daarna','dus'],g:0,u:'Ik wil komen, maar ik kan niet. Maar laat zien dat het tweede tegen het eerste ingaat.',t:'tekstverbanden'},
{v:'Welk signaalwoord geeft een reden aan?',o:['omdat','maar','daarna','bovendien'],g:0,u:'Omdat geeft de reden: ik blijf thuis, omdat ik ziek ben. Ook want en doordat geven een reden of oorzaak.',t:'tekstverbanden'},
{v:'Welk verband geeft het woord daardoor aan?',o:['oorzaak en gevolg','tegenstelling','opsomming','tijd'],g:0,u:'Het regende, daardoor werd het veld nat. Daardoor wijst naar het gevolg.',t:'tekstverbanden'},
{v:'Welk verband geeft het woord bijvoorbeeld aan?',o:["een voorbeeld bij een uitspraak","een tegenstelling tussen twee dingen","een conclusie aan het einde","een reden waarom iets zo is"], g:0,u:'Na bijvoorbeeld volgt een concreet geval dat de uitspraak ervoor uitlegt.',t:'tekstverbanden'},
{v:'Welk verband geeft het woord hoewel aan?',o:["een toegeving","een gevolg van iets anders","een opsomming van punten","een samenvatting achteraf"], g:0,u:'Hoewel het regende, gingen we toch. Het eerste zou je iets anders laten verwachten dan wat er gebeurt.',t:'tekstverbanden'},
{v:'Welk verband geeft de zin aan: Kortom, het plan is te duur?',o:["een conclusie","een voorwaarde vooraf","een voorbeeld ter illustratie","een volgorde in de tijd"], g:0,u:'Kortom, al met al en samengevat kondigen een samenvattende conclusie aan.',t:'tekstverbanden'},
{v:'Wat betekent: iets onder de knie hebben?',o:['iets goed kunnen','iets verstoppen','pijn hebben','iets vergeten'],g:0,u:'Als je iets onder de knie hebt, beheers je het.',t:'uitdrukkingen'},
{v:'Wat betekent: het hoofd boven water houden?',o:["het net redden, met geld","leren zwemmen in het diepe","heel trots zijn op jezelf","iets voor een ander verbergen"], g:0,u:'Wie het hoofd boven water houdt, redt het net, vaak met moeite.',t:'uitdrukkingen'},
{v:'Wat betekent: iets op de lange baan schuiven?',o:['iets steeds uitstellen','hard trainen','iets weggooien','snel beslissen'],g:0,u:'Op de lange baan schuiven is uitstellen tot een onbepaald moment.',t:'uitdrukkingen'},
{v:'Wat betekent: een oogje in het zeil houden?',o:["iets in de gaten houden","heel slecht kunnen zien","gaan zeilen op het meer","iets voor een ander verstoppen"], g:0,u:'Een oogje in het zeil houden: opletten dat het goed gaat.',t:'uitdrukkingen'},
{v:'Wat betekent: door de mand vallen?',o:["ontmaskerd worden","zakken voor je examen","ergens van schrikken","iets uit je handen laten vallen"], g:0,u:'Wie door de mand valt, wordt betrapt op een leugen of smoes.',t:'uitdrukkingen'},
{v:'Wat betekent: iets met een korreltje zout nemen?',o:["het niet te letterlijk nemen","iets zorgvuldig bewaren","een gerecht op smaak brengen","iets zonder nadenken geloven"], g:0,u:'Zijn verhalen moet je met een korreltje zout nemen: hij overdrijft graag.',t:'uitdrukkingen'},
{v:'Naar wie verwijst zij in: Anna is ziek, daarom blijft zij thuis?',o:['Anna','de dokter','de moeder','niemand'],g:0,u:'Zij verwijst terug naar Anna, de enige persoon in de zin.',t:'verwijswoorden'},
{v:'Welk verwijswoord hoort bij het meisje?',o:['dat','die','wie','welke'],g:0,u:'Het meisje is een het-woord, dus je verwijst met dat: het meisje dat daar loopt.',t:'verwijswoorden'},
{v:'Welk verwijswoord hoort bij de jongen?',o:['die','dat','wat','welk'],g:0,u:'De jongen is een de-woord, dus die: de jongen die daar loopt.',t:'verwijswoorden'},
{v:'Welke zin verwijst goed?',o:['Het team heeft zijn wedstrijd gewonnen.','Het team heeft hun wedstrijd gewonnen.','Het team hebben zijn wedstrijd gewonnen.','Het team heeft haar wedstrijd gewonnen.'],g:0,u:'Team is een het-woord en enkelvoud, dus je verwijst met zijn, niet met hun of haar.',t:'verwijswoorden'},
{v:'Wat is goed?',o:['De regering heeft haar besluit uitgesteld.','De regering heeft zijn besluit uitgesteld.','De regering heeft hun besluit uitgesteld.','De regering hebben hun besluit uitgesteld.'],g:0,u:'Regering is een vrouwelijk de-woord (op -ing), dus haar.',t:'verwijswoorden'},
{v:'Welke zin is goed?',o:['Het bedrijf waarvan ik de naam vergeten ben, bestaat nog.','Het bedrijf waarvan ik de naam vergeten ben bestaat, nog.','Het bedrijf waarvan zijn naam ik vergeten ben, bestaat nog.','Het bedrijf wie zijn naam ik vergeten ben, bestaat nog.'],g:0,u:'Waarvan verwijst naar het bedrijf: de naam van het bedrijf. Na de bijzin komt een komma.',t:'verwijswoorden'},
  /* ---- erbij, 2026: meer vragen per onderdeel en per niveau ---- */
  {v:'Welk woord gebruik je om iets erbij te vertellen?', o:['ook','maar','omdat','hoewel'], g:0, u:'Ook telt op. Maar en hoewel zetten juist iets tegenover elkaar.', t:'tekstverbanden'},
  {v:'Welk woord geeft een gevolg aan?', o:['dus','want','of','hoewel'], g:0, u:'Dus noemt het gevolg: Het regende, dus we bleven binnen.', t:'tekstverbanden'},
  {v:'Welk signaalwoord hoort bij een opsomming?', o:['ten eerste','daardoor','toch','tenzij'], g:0, u:'Ten eerste, ten tweede en ten slotte zetten punten op een rij.', t:'tekstverbanden'},
  {v:'Wat betekent een handje helpen?', o:['even meehelpen','iemand slaan','weglopen','iets weggeven'], g:0, u:'Je geeft iemand een hand: je helpt even mee.', t:'uitdrukkingen'},
  {v:'Wat betekent het is op?', o:['er is niets meer over','het ligt bovenop','het is kapot','het staat rechtop'], g:0, u:'Op betekent hier: helemaal gebruikt of gegeten.', t:'uitdrukkingen'},
  {v:'Wat betekent de draad kwijt zijn?', o:["niet meer weten waar je was","geen naald kunnen vinden","je jas ergens kwijt zijn","ruzie hebben met iemand"], g:0, u:'De draad is het verhaal dat je volgt; die kun je kwijtraken.', t:'uitdrukkingen'},
  {v:'Wat is het werkwoord in: Sanne fietst naar school?', o:['fietst','Sanne','school','naar'], g:0, u:'Het werkwoord zegt wat er gebeurt: fietsen.', t:'zinsdelen'},
  {v:'Wat is het onderwerp in: De hond blaft?', o:['de hond','blaft','de','er is geen onderwerp'], g:0, u:'Vraag: wie of wat blaft? De hond.', t:'zinsdelen'},
  {v:'Welk woord is een lidwoord?', o:['het','loopt','snel','morgen'], g:0, u:'Nederlands heeft drie lidwoorden: de, het en een.', t:'zinsdelen'},
  {v:'Waar verwijst hij naar in: De bal rolde weg. Hij lag in de sloot?', o:['de bal','de sloot','de jongen','niets'], g:0, u:'De bal is een de-woord, dus verwijs je met hij.', t:'verwijswoorden'},
  {v:'Wat past er: Ik zag een vogel. ___ vloog weg.', o:['Hij','Het','Ze','Die van mij'], g:0, u:'Vogel is een de-woord: hij.', t:'verwijswoorden'},
  {v:'Wat betekent het woord enorm?', o:['heel groot','heel klein','heel snel','heel duur'], g:0, u:'Enorm is een ander woord voor reusachtig of heel groot.', t:'betekenis'},
  {v:'Hoe schrijf je het meervoud van tafel?', o:['tafels','tafelen','tafeles','tafel\'s'], g:0, u:'Woorden die eindigen op -el krijgen -s: tafels, lepels, sleutels.', t:'spelling'},
  {v:'Wat is goed: de zaak is ___ door de rechter?', o:['behandeld','behandelt','behandelde','behandeldt'], g:0, u:'Voltooid deelwoord: stam behandel eindigt niet op een letter uit t kofschip, dus -d.', t:'werkwoordspelling'},
  {v:'Wat is een synoniem van pertinent?', o:['stellig, beslist','twijfelend','beleefd','toevallig'], g:0, u:'Iets pertinent ontkennen is het stellig ontkennen.', t:'synoniemen'},
  {v:'Wat is een synoniem van nuanceren?', o:["fijner onderscheiden","flink overdrijven","nog eens herhalen","kort samenvatten"], g:0, u:'Wie nuanceert, brengt aan dat iets niet helemaal zwart-wit is.', t:'synoniemen'},
  {v:'Wat is het meervoud van crisis?', o:['crises','crisissen','crisisen','crisis\'s'], g:0, u:'Woorden op -is uit het Grieks of Latijn krijgen vaak -es: crisis, crises; analyse, analyses.', t:'meervoud'},
  {v:'Wat is het meervoud van datum in de betekenis gegeven?', o:['data','datums','datumen','datae'], g:0, u:'Datum betekent gegeven; het meervoud daarvan is data. Bij een kalenderdatum zeg je datums.', t:'meervoud'},
  {v:'Welke meervoudsvorm is in vakteksten gebruikelijk bij index?', o:['indices','indexs','indexi','indexa'], g:0, u:'In gewoon Nederlands mag indexen; in vakteksten schrijft men indices.', t:'meervoud'},
  {v:'Wat betekent impliciet?', o:["niet gezegd, wel bedoeld","duidelijk uitgesproken","onmogelijk uit te voeren","tegenstrijdig met de rest"], g:0, u:'Het tegenovergestelde is expliciet: met zoveel woorden gezegd.', t:'betekenis'},
  {v:'Wat betekent paradoxaal?', o:["schijnbaar tegenstrijdig","heel logisch te volgen","bijzonder zeldzaam","erg duur in aanschaf"], g:0, u:'Een paradox lijkt zichzelf tegen te spreken maar bevat toch waarheid: haast je langzaam.', t:'betekenis'},
  {v:'Welk signaalwoord kondigt een conclusie aan?', o:['kortom','bijvoorbeeld','daarentegen','ondertussen'], g:0, u:'Kortom en dus vatten samen of trekken de conclusie.', t:'tekstverbanden'},
  {v:'Welk verband legt het woord mits?', o:['een voorwaarde','een tegenstelling','een tijd','een oorzaak'], g:0, u:'Mits betekent op voorwaarde dat; tenzij noemt juist de uitzondering.', t:'tekstverbanden'},
  {v:'Wat is het lijdend voorwerp in: De commissie heeft het rapport aan de minister aangeboden?', o:['het rapport','de commissie','aan de minister','heeft aangeboden'], g:0, u:'Vraag: wie of wat wordt aangeboden? Het rapport. Aan de minister is meewerkend voorwerp.', t:'zinsdelen'},
  {v:'Welke zin bevat een bijwoordelijke bepaling van tijd?', o:['Na de vergadering vertrok hij meteen.','Hij vertrok met de trein.','Hij vertrok omdat hij moe was.','De vergadering was lang.'], g:0, u:'Na de vergadering zegt wanneer; met de trein is middel, omdat hij moe was is reden.', t:'zinsdelen'},
  {v:'Wat is er mis met: Het bestuur nam hun besluit?', o:['bestuur is enkelvoud, dus zijn besluit','er is niets mis mee','besluit moet besluiten zijn','nam moet namen zijn'], g:0, u:'Verzamelnamen als bestuur, team en kabinet zijn enkelvoud; congruentiefouten met hun zijn heel gewoon.', t:'verwijswoorden'},
  {v:'Waar verwijst dat naar in: Hij zweeg lang, en dat verraste iedereen?', o:["naar de hele vorige zin","naar hij, het onderwerp","naar iedereen in de zin","naar lang, de bepaling"], g:0, u:'Dat kan naar een hele zin verwijzen; dit heet een zinsverwijzing.', t:'verwijswoorden'},
  {v:'Welke zin heeft de puntkomma correct?', o:['De uitslag was duidelijk; niemand betwistte hem.','De uitslag was duidelijk; en niemand betwistte hem.','De uitslag was duidelijk; omdat niemand hem betwistte.','De uitslag; was duidelijk niemand betwistte hem.'], g:0, u:'Een puntkomma verbindt twee zinnen die zelfstandig kunnen staan, zonder voegwoord.', t:'leestekens'},
  {v:'Wat betekent iets met een korreltje zout nemen?', o:["het niet letterlijk geloven","het juist heel serieus nemen","het gerecht lekkerder maken","er heel boos om worden"], g:0, u:'Je houdt er rekening mee dat het overdreven kan zijn.', t:'uitdrukkingen'},
  {v:'Wat betekent de kool en de geit sparen?', o:['proberen beide partijen tevreden te houden','zuinig leven','een keuze uitstellen tot het te laat is','iemand voortrekken'], g:0, u:'Je wilt niemand tegen je in het harnas jagen en kiest daardoor geen kant.', t:'uitdrukkingen'},
  {v:'Hoe schrijf je het juist?', o:['een sociaaleconomisch probleem','een sociaal-economisch probleem','een sociaal economisch probleem','een sociaalEconomisch probleem'], g:0, u:'Twee bijvoeglijke naamwoorden die samen één begrip vormen, schrijf je aaneen.', t:'spelling'}
];
var NED3_N = [1,1,1,1,2,2,2,3,3,4,1,1,2,2,2,3,3,4,1,1,1,2,2,3,4,1,1,2,2,3,3,4,4,1,1,2,2,3,4,1,1,2,2,3,3,4,1,1,2,2,3,3,4,4,1,2,2,3,3,4,1,2,2,3,3,4,1,2,2,3,3,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,3];
BRONNEN.ned = NED.concat(NED2, NED3);
NIVOS.ned = NED_N.concat(NED2_N, NED3_N);
})();
