/* The words and sentences for the English dictation. n is the level:
   1 = vmbo-bb (A1-A2), 2 = vmbo-kgt en tl (A2), 3 = havo en vwo (B1).
   A level gets its own items and those below it.

   woorden: a single word with a sentence, so you hear what it is.
   zinnen: type the whole sentence (capitals and punctuation do not count).
   getallen: numbers, times and dates read out; type them as figures.
   paren: minimal pairs (ship/sheep): the word in a sentence, type the word.
   uit is the explanation, in Dutch, shown after the answer. */
window.DICTATION_OPGAVEN = {
  woorden: [
    { n:1, w:'because', zin:'I stayed home because it was raining.', uit:'be-cause: geen z, en au in het midden' },
    { n:1, w:'beautiful', zin:'What a beautiful day!', uit:'beau-ti-ful: eau zoals in het Frans, en een l aan het eind' },
    { n:1, w:'Wednesday', zin:'We have PE on Wednesday.', uit:'Wed-nes-day: de d hoor je niet, maar schrijf je wel; dagen met een hoofdletter' },
    { n:1, w:'February', zin:'My birthday is in February.', uit:'Feb-ru-ary: de eerste r hoor je bijna niet' },
    { n:1, w:'friend', zin:'She is my best friend.', uit:'ie, niet ei: friend' },
    { n:1, w:'school', zin:'Our school starts at half past eight.', uit:'sch en dubbele o' },
    { n:1, w:'people', zin:'There were a lot of people in the park.', uit:'peo-ple: eo klinkt als ie' },
    { n:1, w:'different', zin:'We are all different.', uit:'dubbele f, dan er-ent' },
    { n:1, w:'favourite', zin:'Blue is my favourite colour.', uit:'Britse spelling: fa-vour-ite, met ou' },
    { n:1, w:'always', zin:'He always forgets his keys.', uit:'al-ways: een l' },
    { n:1, w:'through', zin:'We walked through the forest.', uit:'thr-ough: ough klinkt hier als oe' },
    { n:1, w:'which', zin:'Which book do you want?', uit:'wh aan het begin, ch aan het eind' },
    { n:1, w:'tomorrow', zin:'See you tomorrow!', uit:'to-mor-row: een m, dubbele r' },
    { n:1, w:'holiday', zin:'We went to Spain on holiday.', uit:'ho-li-day' },
    { n:1, w:'minute', zin:'Wait a minute, please.', uit:'mi-nute, met een stomme e' },
    { n:2, w:'receive', zin:'Did you receive my message?', uit:'i before e, except after c: re-ceive' },
    { n:2, w:'necessary', zin:'Is it necessary to bring a coat?', uit:'een c, dubbele s: ne-ces-sa-ry' },
    { n:2, w:'separate', zin:'Keep the two lists separate.', uit:'sep-a-rate: een a in het midden, geen e' },
    { n:2, w:'definitely', zin:'I will definitely come.', uit:'de-fi-nite-ly: geen a' },
    { n:2, w:'environment', zin:'We must protect the environment.', uit:'en-vi-ron-ment: de n voor de m' },
    { n:2, w:'government', zin:'The government made a new law.', uit:'go-vern-ment: de n voor de m' },
    { n:2, w:'restaurant', zin:'We ate at an Italian restaurant.', uit:'res-tau-rant: Frans, met au' },
    { n:2, w:'library', zin:'The library closes at six.', uit:'li-bra-ry: twee keer een r' },
    { n:2, w:'foreign', zin:'She speaks three foreign languages.', uit:'for-eign: eign zoals in reign' },
    { n:2, w:'business', zin:'My uncle runs a small business.', uit:'bu-si-ness: een s, dan dubbele s' },
    { n:2, w:'answer', zin:'Please answer the question.', uit:'an-swer: de w hoor je niet' },
    { n:2, w:'comfortable', zin:'This chair is very comfortable.', uit:'com-for-ta-ble' },
    { n:2, w:'weather', zin:'The weather was terrible.', uit:'wea-ther, niet whether (of)' },
    { n:2, w:'straight', zin:'Go straight on and turn left.', uit:'str-aight, met aigh' },
    { n:2, w:'surprise', zin:'It was a big surprise.', uit:'sur-prise: sur, niet sup' },
    { n:3, w:'accommodation', zin:'We booked our accommodation online.', uit:'dubbele c en dubbele m' },
    { n:3, w:'embarrassed', zin:'He was embarrassed by the mistake.', uit:'dubbele r en dubbele s' },
    { n:3, w:'conscience', zin:'She has a clear conscience.', uit:'con-science: science erin' },
    { n:3, w:'occasionally', zin:'We occasionally go to the cinema.', uit:'dubbele c, een s, dubbele l' },
    { n:3, w:'rhythm', zin:'The song has a good rhythm.', uit:'rhy-thm: geen klinker behalve de y' },
    { n:3, w:'privilege', zin:'It is a privilege to be here.', uit:'pri-vi-lege: geen d' },
    { n:3, w:'immediately', zin:'Call me immediately.', uit:'dubbele m, dan e-di-ate-ly' },
    { n:3, w:'knowledge', zin:'Knowledge is power.', uit:'know-ledge: stomme k, en dg' },
    { n:3, w:'guarantee', zin:'The phone comes with a two-year guarantee.', uit:'gua-ran-tee' },
    { n:3, w:'achievement', zin:'Winning the cup was a great achievement.', uit:'a-chieve-ment: ie' },
    { n:3, w:'exaggerate', zin:'Don’t exaggerate, it wasn’t that bad.', uit:'ex-ag-ge-rate: dubbele g' },
    { n:3, w:'colleague', zin:'My mum’s colleague is from Ireland.', uit:'col-league: dubbele l, ea, gue' },
    { n:3, w:'queue', zin:'We waited in a long queue.', uit:'q-u-e-u-e: klinkt als kjoe' },
    { n:3, w:'vegetable', zin:'Carrot is my favourite vegetable.', uit:'ve-ge-ta-ble' },
    { n:3, w:'thorough', zin:'The police did a thorough search.', uit:'tho-rough: ough aan het eind' }
  ],
  zinnen: [
    { n:1, zin:'I have got two brothers and one sister.', uit:'have got voor bezit; brothers en sister meervoud en enkelvoud' },
    { n:1, zin:'She likes pizza but she does not like fish.', uit:'she likes met een s; does not like zonder s' },
    { n:1, zin:'We go to school by bike every day.', uit:'by bike: geen lidwoord' },
    { n:1, zin:'My father is a teacher at a big school.', uit:'a teacher: het lidwoord a bij een beroep' },
    { n:1, zin:'There are three cats in the garden.', uit:'there are bij meervoud' },
    { n:1, zin:'Can you open the window, please?', uit:'can you voor een verzoek' },
    { n:1, zin:'It is cold today, so wear a coat.', uit:'so na de komma: dus' },
    { n:1, zin:'They are playing football in the park.', uit:'present continuous: are playing' },
    { n:1, zin:'I do not understand this question.', uit:'do not (don’t) understand' },
    { n:1, zin:'Where is the bus stop?', uit:'where is: vraag met vraagwoord' },
    { n:1, zin:'Our dog is very old but still happy.', uit:'but: tegenstelling' },
    { n:1, zin:'What time does the film start?', uit:'does the film start: does bij it/he/she in een vraag' },
    { n:2, zin:'Last summer we went to London for a week.', uit:'went: verleden tijd van go' },
    { n:2, zin:'I am going to visit my grandmother on Sunday.', uit:'going to voor een plan' },
    { n:2, zin:'She was watching TV when the phone rang.', uit:'was watching (bezig) en rang (plotseling)' },
    { n:2, zin:'This is the most expensive shop in town.', uit:'the most expensive: overtreffende trap van een lang woord' },
    { n:2, zin:'My brother is taller than me.', uit:'taller than: vergrotende trap' },
    { n:2, zin:'Did you see the match yesterday?', uit:'did you see: vraag in de verleden tijd' },
    { n:2, zin:'We have never been to Paris.', uit:'have never been: present perfect' },
    { n:2, zin:'You should drink more water.', uit:'should: advies' },
    { n:2, zin:'If it rains, we will stay at home.', uit:'if + present, will in de hoofdzin' },
    { n:2, zin:'There was not enough time to finish.', uit:'there was not enough' },
    { n:2, zin:'He usually gets up at seven o’clock.', uit:'usually voor het werkwoord; gets up met s' },
    { n:2, zin:'How many people came to the party?', uit:'how many bij telbare dingen; came' },
    { n:3, zin:'I have been learning English for six years.', uit:'present perfect continuous met for' },
    { n:3, zin:'If I were you, I would tell the truth.', uit:'second conditional: were, would' },
    { n:3, zin:'The book, which was written in 1950, is still popular.', uit:'relative clause met which tussen komma’s; was written: passief' },
    { n:3, zin:'She asked me whether I had finished my homework.', uit:'indirect speech: whether en past perfect' },
    { n:3, zin:'By the time we arrived, the concert had already started.', uit:'past perfect: had started' },
    { n:3, zin:'The bridge was built more than a hundred years ago.', uit:'passief: was built' },
    { n:3, zin:'Although it was late, they kept on working.', uit:'although: hoewel; kept on: bleven' },
    { n:3, zin:'You must not use your phone during the exam.', uit:'must not: verbod' },
    { n:3, zin:'Neither of the answers was correct.', uit:'neither of + enkelvoud' },
    { n:3, zin:'The teacher whose car was stolen called the police.', uit:'whose: van wie' },
    { n:3, zin:'I wish I had studied harder for the test.', uit:'wish + past perfect: spijt' },
    { n:3, zin:'Hardly anyone knew the answer to the last question.', uit:'hardly anyone: bijna niemand' }
  ],
  getallen: [
    { n:1, spreek:'thirteen', antwoord:['13', 'thirteen'], uit:'thirteen is 13; thirty is 30: let op teen en ty' },
    { n:1, spreek:'thirty', antwoord:['30', 'thirty'], uit:'thirty is 30; de klemtoon ligt op thir' },
    { n:1, spreek:'fifteen', antwoord:['15', 'fifteen'], uit:'fifteen is 15' },
    { n:1, spreek:'fifty', antwoord:['50', 'fifty'], uit:'fifty is 50' },
    { n:1, spreek:'It is half past seven.', antwoord:['7:30', '7.30', '07:30', '19:30', 'half past seven'], uit:'half past seven is half acht: 7:30' },
    { n:1, spreek:'It is quarter past three.', antwoord:['3:15', '3.15', '03:15', '15:15', 'quarter past three'], uit:'quarter past three is kwart over drie: 3:15' },
    { n:1, spreek:'It is quarter to five.', antwoord:['4:45', '4.45', '04:45', '16:45', 'quarter to five'], uit:'quarter to five is kwart voor vijf: 4:45' },
    { n:1, spreek:'It is ten o’clock.', antwoord:['10:00', '10.00', '10', 'ten o’clock', 'ten oclock'], uit:'ten o’clock is 10:00' },
    { n:1, spreek:'twelve', antwoord:['12', 'twelve'], uit:'twelve is 12' },
    { n:1, spreek:'eighty', antwoord:['80', 'eighty'], uit:'eighty is 80' },
    { n:2, spreek:'one hundred and twenty-five', antwoord:['125', 'one hundred and twenty-five', 'one hundred and twenty five'], uit:'hundred and: 125' },
    { n:2, spreek:'two thousand and six', antwoord:['2006', 'two thousand and six'], uit:'2006' },
    { n:2, spreek:'nineteen eighty-four', antwoord:['1984', 'nineteen eighty-four', 'nineteen eighty four'], uit:'jaartallen in tweetallen: 19 84' },
    { n:2, spreek:'It is twenty past nine.', antwoord:['9:20', '9.20', '09:20', '21:20', 'twenty past nine'], uit:'twenty past nine: 9:20' },
    { n:2, spreek:'It is five to twelve.', antwoord:['11:55', '11.55', '23:55', 'five to twelve'], uit:'five to twelve: 11:55' },
    { n:2, spreek:'the fourteenth of March', antwoord:['14 March', '14 march', 'March 14', 'march 14', '14/3', '14-3', 'the fourteenth of March', 'fourteenth of March'], uit:'the fourteenth of March: 14 maart' },
    { n:2, spreek:'the first of May', antwoord:['1 May', '1 may', 'May 1', 'may 1', '1/5', '1-5', 'the first of May', 'first of May'], uit:'the first of May: 1 mei' },
    { n:2, spreek:'the twenty-second of August', antwoord:['22 August', '22 august', 'August 22', 'august 22', '22/8', '22-8', 'the twenty-second of August', 'twenty-second of August'], uit:'the twenty-second of August: 22 augustus' },
    { n:2, spreek:'three point five', antwoord:['3.5', '3,5', 'three point five'], uit:'point is de komma: 3,5' },
    { n:2, spreek:'seventy percent', antwoord:['70%', '70 %', '70 percent', 'seventy percent'], uit:'70%' },
    { n:3, spreek:'one thousand three hundred and forty-two', antwoord:['1342', '1.342', '1,342', 'one thousand three hundred and forty-two'], uit:'1342' },
    { n:3, spreek:'twelve thousand', antwoord:['12000', '12.000', '12,000', 'twelve thousand'], uit:'12 000' },
    { n:3, spreek:'two point seven five', antwoord:['2.75', '2,75', 'two point seven five'], uit:'2,75' },
    { n:3, spreek:'It is twenty-five to eight.', antwoord:['7:35', '7.35', '19:35', 'twenty-five to eight', 'twenty five to eight'], uit:'twenty-five to eight: 7:35' },
    { n:3, spreek:'the thirty-first of December, twenty twenty-five', antwoord:['31 December 2025', '31 december 2025', 'December 31 2025', 'December 31, 2025', '31-12-2025', '31/12/2025'], uit:'31 december 2025' },
    { n:3, spreek:'a quarter of a million', antwoord:['250000', '250.000', '250,000', 'a quarter of a million'], uit:'a quarter of a million: 250 000' },
    { n:3, spreek:'three quarters', antwoord:['3/4', '0.75', '0,75', 'three quarters'], uit:'three quarters: driekwart' },
    { n:3, spreek:'nought point five', antwoord:['0.5', '0,5', 'nought point five'], uit:'nought is nul: 0,5' },
    { n:3, spreek:'minus fifteen degrees', antwoord:['-15', '-15 degrees', 'minus fifteen degrees', 'minus 15'], uit:'minus fifteen: -15' },
    { n:3, spreek:'one and a half hours', antwoord:['1.5 hours', '1,5 hours', '1.5', '1,5', '90 minutes', 'one and a half hours'], uit:'anderhalf uur: 1,5' }
  ],
  paren: [
    { n:1, w:'ship', zin:'The ship sailed at dawn.', ander:'sheep', uit:'korte i: ship (schip); lange ie: sheep (schaap)' },
    { n:1, w:'sheep', zin:'The sheep are in the field.', ander:'ship', uit:'lange ie: sheep (schaap)' },
    { n:1, w:'three', zin:'I have three sisters.', ander:'tree', uit:'th met je tong tussen je tanden: three' },
    { n:1, w:'tree', zin:'There is a bird in the tree.', ander:'three', uit:'gewone t: tree (boom)' },
    { n:1, w:'live', zin:'I live in Utrecht.', ander:'leave', uit:'korte i: live (wonen)' },
    { n:1, w:'leave', zin:'We leave at nine.', ander:'live', uit:'lange ie: leave (vertrekken)' },
    { n:1, w:'bad', zin:'That was a bad idea.', ander:'bed', uit:'a-klank: bad (slecht)' },
    { n:1, w:'bed', zin:'I go to bed at ten.', ander:'bad', uit:'e-klank: bed' },
    { n:1, w:'man', zin:'The man is waiting outside.', ander:'men', uit:'man: enkelvoud' },
    { n:1, w:'men', zin:'Two men are waiting outside.', ander:'man', uit:'men: meervoud' },
    { n:2, w:'thing', zin:'What is that thing?', ander:'think', uit:'thing eindigt op ng' },
    { n:2, w:'think', zin:'I think you are right.', ander:'thing', uit:'think eindigt op nk' },
    { n:2, w:'full', zin:'The bus was full.', ander:'fool', uit:'korte oe: full (vol)' },
    { n:2, w:'fool', zin:'Don’t be a fool.', ander:'full', uit:'lange oe: fool (dwaas)' },
    { n:2, w:'walk', zin:'We walk to school.', ander:'work', uit:'walk klinkt als wook' },
    { n:2, w:'work', zin:'They work in a shop.', ander:'walk', uit:'work klinkt als wurk' },
    { n:2, w:'cat', zin:'Our cat is black.', ander:'cut', uit:'a-klank: cat' },
    { n:2, w:'cut', zin:'Be careful, don’t cut yourself.', ander:'cat', uit:'u-klank: cut' },
    { n:2, w:'sit', zin:'Please sit down.', ander:'seat', uit:'korte i: sit' },
    { n:2, w:'seat', zin:'Is this seat free?', ander:'sit', uit:'lange ie: seat (zitplaats)' },
    { n:2, w:'their', zin:'They lost their keys.', ander:'there', uit:'their: van hen (bezit)' },
    { n:2, w:'there', zin:'There is a cat on the roof.', ander:'their', uit:'there: er / daar' },
    { n:3, w:'thought', zin:'I thought you were at home.', ander:'taught', uit:'th: thought (dacht)' },
    { n:3, w:'taught', zin:'She taught us French.', ander:'thought', uit:'t: taught (gaf les)' },
    { n:3, w:'whether', zin:'I don’t know whether he is coming.', ander:'weather', uit:'whether: of' },
    { n:3, w:'weather', zin:'The weather is lovely today.', ander:'whether', uit:'weather: het weer' },
    { n:3, w:'quite', zin:'The film was quite good.', ander:'quiet', uit:'quite: nogal; quiet: stil' },
    { n:3, w:'quiet', zin:'Please be quiet in the library.', ander:'quite', uit:'quiet: stil; qui-et, twee lettergrepen' },
    { n:3, w:'lose', zin:'Don’t lose your ticket.', ander:'loose', uit:'lose: verliezen, een o' },
    { n:3, w:'loose', zin:'This shirt is too loose.', ander:'lose', uit:'loose: los, dubbele o' },
    { n:3, w:'affect', zin:'The weather can affect your mood.', ander:'effect', uit:'affect: werkwoord, beïnvloeden' },
    { n:3, w:'effect', zin:'The medicine had no effect.', ander:'affect', uit:'effect: zelfstandig naamwoord, het gevolg' },
    { n:3, w:'desert', zin:'Camels live in the desert.', ander:'dessert', uit:'desert: woestijn, een s' },
    { n:3, w:'dessert', zin:'We had ice cream for dessert.', ander:'desert', uit:'dessert: toetje, dubbele s' }
  ]
};
