/* De woorden en zinnen van het dictee. n is het niveau: 1 = vmbo-bb,
   2 = vmbo-kgt en tl, 3 = havo en vwo. Een niveau krijgt zijn eigen items en
   die van de niveaus eronder.

   werkwoorden: de zin wordt voorgelezen, de leerling typt alleen het werkwoord
   (de zin staat met een gat in beeld). regel is wat er na het antwoord staat.
   woorden: een los woord, met een zin erbij zodat je hoort wat het is.
   leestekens: de hele zin typen, met hoofdletters en leestekens.
   leenwoorden: Engelse leenwoorden in Nederlandse spelling (havo en vwo). */
window.DICTEE_OPGAVEN = {
  werkwoorden: [
    { n:1, zin:'Hij vindt het leuk.', woord:'vindt', regel:'hij/zij/het in de tegenwoordige tijd: stam + t. De stam is vind, dus vindt.' },
    { n:1, zin:'Ik word morgen dertien.', woord:'word', regel:'ik in de tegenwoordige tijd: alleen de stam. Ik word, zonder t.' },
    { n:1, zin:'Zij wordt elke dag om zeven uur wakker.', woord:'wordt', regel:'zij: stam + t. Wordt, met dt, want de stam eindigt al op een d.' },
    { n:1, zin:'Word jij ook zo moe van die herrie?', woord:'word', regel:'staat jij achter het werkwoord, dan valt de t weg: word jij.' },
    { n:1, zin:'Mijn vader rijdt elke dag naar zijn werk.', woord:'rijdt', regel:'hij: stam + t. De stam is rijd, dus rijdt.' },
    { n:1, zin:'Wij fietsen samen naar school.', woord:'fietsen', regel:'wij: het hele werkwoord.' },
    { n:1, zin:'Gisteren speelde ik buiten.', woord:'speelde', regel:'verleden tijd van spelen: stam + de, want de l staat niet in ’t kofschip.' },
    { n:1, zin:'De hond blafte de hele nacht.', woord:'blafte', regel:'verleden tijd: stam + te, want de f staat in ’t kofschip.' },
    { n:1, zin:'Ik heb mijn huiswerk gemaakt.', woord:'gemaakt', regel:'voltooid deelwoord: ge + stam + t, want de k staat in ’t kofschip.' },
    { n:1, zin:'Zij heeft haar kamer opgeruimd.', woord:'opgeruimd', regel:'voltooid deelwoord: ruim + d, want de m staat niet in ’t kofschip.' },
    { n:1, zin:'De kat vangt een muis.', woord:'vangt', regel:'hij/zij/het: stam + t.' },
    { n:1, zin:'Wat zegt de juf?', woord:'zegt', regel:'de juf is een zij: stam + t.' },
    { n:1, zin:'Het regent al de hele dag.', woord:'regent', regel:'het: stam + t. Regen + t.' },
    { n:1, zin:'Antwoord jij even op die vraag?', woord:'antwoord', regel:'jij achter het werkwoord: geen t.' },
    { n:1, zin:'Zij lachten om de grap.', woord:'lachten', regel:'verleden tijd meervoud: stam + ten, want de ch staat in ’t kofschip.' },
    { n:2, zin:'Hij heeft zich vergist in de datum.', woord:'vergist', regel:'voltooid deelwoord zonder ge: vergis + t, want de s staat in ’t kofschip.' },
    { n:2, zin:'De trein vertrekt om kwart over acht.', woord:'vertrekt', regel:'hij: stam + t.' },
    { n:2, zin:'Zij verhuisde vorig jaar naar Groningen.', woord:'verhuisde', regel:'verleden tijd: verhuis + de. De s in verhuizen is eigenlijk een z, en die staat niet in ’t kofschip.' },
    { n:2, zin:'Ik heb dat boek geleend van de bibliotheek.', woord:'geleend', regel:'voltooid deelwoord: ge + leen + d, want de n staat niet in ’t kofschip.' },
    { n:2, zin:'Het geplande feest gaat niet door.', woord:'geplande', regel:'voltooid deelwoord als bijvoeglijk naamwoord: gepland + e.' },
    { n:2, zin:'De verbrande toast smaakte bitter.', woord:'verbrande', regel:'verbrand + e: het voltooid deelwoord verbrand krijgt een e als het voor een zelfstandig naamwoord staat.' },
    { n:2, zin:'Zij beantwoordt elke vraag rustig.', woord:'beantwoordt', regel:'zij: stam + t. De stam is beantwoord, dus dt.' },
    { n:2, zin:'De leraar verbood mobieltjes in de klas.', woord:'verbood', regel:'verleden tijd van verbieden: onregelmatig, verbood.' },
    { n:2, zin:'Gisteren verbaasde hij iedereen.', woord:'verbaasde', regel:'verleden tijd: de stam verbaas eindigt op een s die eigenlijk een z is (verbazen), dus + de.' },
    { n:2, zin:'Heb je het pakketje al besteld?', woord:'besteld', regel:'voltooid deelwoord: bestel + d, want de l staat niet in ’t kofschip.' },
    { n:2, zin:'De verwachte storm bleef uit.', woord:'verwachte', regel:'verwacht + e als bijvoeglijk naamwoord.' },
    { n:2, zin:'Zij hoopten op mooi weer.', woord:'hoopten', regel:'verleden tijd meervoud: hoop + ten, want de p staat in ’t kofschip.' },
    { n:2, zin:'Hij wordt volgend jaar zestien.', woord:'wordt', regel:'hij: stam + t: wordt.' },
    { n:2, zin:'De burgemeester opent het nieuwe zwembad.', woord:'opent', regel:'hij: stam + t.' },
    { n:2, zin:'Ik heb me gisteren verslapen.', woord:'verslapen', regel:'voltooid deelwoord van verslapen: gelijk aan het hele werkwoord.' },
    { n:3, zin:'Het geüpdatete programma werkt sneller.', woord:'geüpdatete', regel:'Engels werkwoord: ge + update + te (de t van ’t kofschip) en als bijvoeglijk naamwoord nog een e; het trema scheidt de e en de u.' },
    { n:3, zin:'De vergrote foto hing aan de muur.', woord:'vergrote', regel:'vergroot + e: bij een bijvoeglijk gebruikt voltooid deelwoord valt een dubbele o weg voor de e.' },
    { n:3, zin:'Zij heeft haar excuses aangeboden.', woord:'aangeboden', regel:'voltooid deelwoord van aanbieden: onregelmatig, aangeboden.' },
    { n:3, zin:'Het geraffineerde plan mislukte toch.', woord:'geraffineerde', regel:'raffineer + d + e: de r staat niet in ’t kofschip.' },
    { n:3, zin:'Ze racete de hele middag door de wijk.', woord:'racete', regel:'racen eindigt op een s-klank: stam race + te, de stomme e blijft staan.' },
    { n:3, zin:'De gefaxte brief kwam onleesbaar aan.', woord:'gefaxte', regel:'fax + te: de x staat in ’t kofschip (klinkt als ks).' },
    { n:3, zin:'Wie gelooft er nog in die belofte?', woord:'gelooft', regel:'wie is enkelvoud: stam + t.' },
    { n:3, zin:'Hij heeft de uitslag verkeerd voorspeld.', woord:'voorspeld', regel:'voorspel + d, de l staat niet in ’t kofschip.' },
    { n:3, zin:'De bedreigde diersoort keerde terug.', woord:'bedreigde', regel:'bedreigd + e; de g staat niet in ’t kofschip.' },
    { n:3, zin:'Zij verwedt er haar zakgeld op.', woord:'verwedt', regel:'zij: stam verwed + t.' },
    { n:3, zin:'Het volk verzette zich tegen de koning.', woord:'verzette', regel:'verleden tijd van verzetten: verzet + te.' },
    { n:3, zin:'Men zegt dat het morgen gaat sneeuwen.', woord:'zegt', regel:'men is enkelvoud: stam + t.' }
  ],
  woorden: [
    { n:1, w:'onmiddellijk', zin:'Kom onmiddellijk hier!', uit:'dubbele d en dubbele l: on-mid-del-lijk' },
    { n:1, w:'interessant', zin:'Dat is een interessant verhaal.', uit:'met een t na de in en dubbele s' },
    { n:1, w:'cadeau', zin:'Ik kreeg een cadeau voor mijn verjaardag.', uit:'Frans woord: c-a-d-e-a-u' },
    { n:1, w:'chocolade', zin:'Ik lust graag chocolade.', uit:'ch aan het begin, een l in het midden' },
    { n:1, w:'natuurlijk', zin:'Natuurlijk kom ik naar je feest.', uit:'natuur + lijk' },
    { n:1, w:'gebeurt', zin:'Wat gebeurt hier?', uit:'gebeur + t, want het: stam + t' },
    { n:1, w:'moeilijk', zin:'Deze som is moeilijk.', uit:'oei en lijk' },
    { n:1, w:'vakantie', zin:'In de vakantie ga ik kamperen.', uit:'tie klinkt als tsie, maar je schrijft t-i-e' },
    { n:1, w:'politie', zin:'De politie kwam snel.', uit:'ook hier tie: politie' },
    { n:1, w:'bibliotheek', zin:'Ik leen boeken in de bibliotheek.', uit:'bi-bli-o-theek, met th' },
    { n:1, w:'eigenlijk', zin:'Eigenlijk wilde ik thuisblijven.', uit:'ei-gen-lijk' },
    { n:1, w:'weinig', zin:'Er is nog maar weinig melk.', uit:'ei en ig' },
    { n:1, w:'stiekem', zin:'Hij at stiekem een koekje.', uit:'ie en e-m' },
    { n:1, w:'december', zin:'In december is het vroeg donker.', uit:'maanden schrijf je met een kleine letter' },
    { n:1, w:'koffie', zin:'Mijn moeder drinkt koffie.', uit:'dubbele f en ie' },
    { n:2, w:'enquête', zin:'We vulden een enquête in over pauzes.', uit:'Frans: en-qu-ê-te, met een dakje op de e' },
    { n:2, w:'parallel', zin:'De twee lijnen lopen parallel.', uit:'een r, dubbele l aan het eind' },
    { n:2, w:'accu', zin:'De accu van de fiets is leeg.', uit:'dubbele c' },
    { n:2, w:'brommer', zin:'Mijn broer heeft een nieuwe brommer.', uit:'dubbele m' },
    { n:2, w:'hobby', zin:'Mijn hobby is gamen.', uit:'dubbele b, y aan het eind' },
    { n:2, w:'faillissement', zin:'De winkel ging failliet en vroeg faillissement aan.', uit:'dubbele l, dubbele s, ment' },
    { n:2, w:'medicijn', zin:'De dokter schreef een medicijn voor.', uit:'c voor de i klinkt als s; ijn' },
    { n:2, w:'onmiddellijk', zin:'Ga onmiddellijk naar huis.', uit:'dubbele d en dubbele l' },
    { n:2, w:'gigantisch', zin:'De golf was gigantisch.', uit:'isch aan het eind, zoals in logisch' },
    { n:2, w:'kantine', zin:'We eten in de kantine.', uit:'een n, ine' },
    { n:2, w:'directeur', zin:'De directeur opende het feest.', uit:'c voor de t, eur aan het eind' },
    { n:2, w:'temperatuur', zin:'De temperatuur stijgt.', uit:'tem-pe-ra-tuur' },
    { n:2, w:'agressief', zin:'De hond werd agressief.', uit:'een g, dubbele s, ief' },
    { n:2, w:'commentaar', zin:'Iedereen had commentaar op de scheidsrechter.', uit:'dubbele m, aar' },
    { n:2, w:'sowieso', zin:'Ik ga sowieso mee.', uit:'so-wie-so, uit het Duits' },
    { n:3, w:'acquisitie', zin:'Het bedrijf doet aan acquisitie.', uit:'ac-qui-si-tie' },
    { n:3, w:'ambivalent', zin:'Ze stond er ambivalent tegenover.', uit:'am-bi-va-lent' },
    { n:3, w:'consequent', zin:'Hij is heel consequent in zijn regels.', uit:'con-se-quent' },
    { n:3, w:'privacy', zin:'Iedereen heeft recht op privacy.', uit:'Engels leenwoord: pri-va-cy' },
    { n:3, w:'bureaucratie', zin:'De bureaucratie maakte alles traag.', uit:'bu-reau-cra-tie' },
    { n:3, w:'hiërarchie', zin:'In het leger is de hiërarchie streng.', uit:'trema op de e, ch in het midden' },
    { n:3, w:'geïnteresseerd', zin:'Zij is geïnteresseerd in techniek.', uit:'trema op de i, dubbele s' },
    { n:3, w:'ideë', zin:'Dat is een goed idee, en je hebt vast nog meer ideeën.', uit:'meervoud: ideeën met trema', antwoordLijst:['ideeën'], spreek:'Ideeën. Zij heeft altijd goede ideeën.' },
    { n:3, w:'onmiddellijk', zin:'Reageer onmiddellijk.', uit:'dubbele d, dubbele l' },
    { n:3, w:'rendement', zin:'Het rendement van de zonnepanelen valt mee.', uit:'ren-de-ment' },
    { n:3, w:'symbool', zin:'De duif is een symbool van vrede.', uit:'y na de s, dubbele o' },
    { n:3, w:'fysiotherapeut', zin:'De fysiotherapeut hielp met de blessure.', uit:'fy-si-o-the-ra-peut' },
    { n:3, w:'exclusief', zin:'De prijs is exclusief btw.', uit:'x, ief' },
    { n:3, w:'millennium', zin:'We leven in het derde millennium.', uit:'dubbele l en dubbele n' },
    { n:3, w:'accessoires', zin:'De winkel verkoopt accessoires.', uit:'dubbele c, dubbele s, oires' }
  ],
  leestekens: [
    { n:1, zin:'Morgen gaan we naar Amsterdam.', uit:'Hoofdletter aan het begin van de zin en bij de plaatsnaam Amsterdam; een punt aan het eind.' },
    { n:1, zin:'Kom je ook naar het feest van Sanne?', uit:'Een vraag eindigt op een vraagteken; de naam Sanne krijgt een hoofdletter.' },
    { n:1, zin:'Wat een prachtig doelpunt!', uit:'Een uitroep eindigt op een uitroepteken.' },
    { n:1, zin:'Ik heb een hond, een kat en twee konijnen.', uit:'Komma’s tussen de delen van een opsomming, geen komma voor en.' },
    { n:1, zin:'In juni gaan we op vakantie naar Frankrijk.', uit:'Maanden met een kleine letter, landen met een hoofdletter.' },
    { n:1, zin:'Mijn oma woont in Rotterdam.', uit:'Plaatsnaam met een hoofdletter.' },
    { n:1, zin:'Ga je mee zwemmen?', uit:'Vraagteken aan het eind.' },
    { n:1, zin:'Op maandag begint de school om half negen.', uit:'Dagen van de week met een kleine letter.' },
    { n:2, zin:'Toen het begon te regenen, gingen we naar binnen.', uit:'Een komma tussen de twee delen van de zin, na de bijzin.' },
    { n:2, zin:'Ik wilde meedoen, maar ik was te laat.', uit:'Een komma voor maar tussen twee zinnen.' },
    { n:2, zin:'Mijn buurman, een oude visser, vertelt mooie verhalen.', uit:'De uitleg over de buurman staat tussen twee komma’s.' },
    { n:2, zin:'De Tweede Wereldoorlog eindigde in 1945.', uit:'Namen van historische gebeurtenissen krijgen hoofdletters.' },
    { n:2, zin:'Weet jij hoe laat de bus vertrekt?', uit:'De hele zin is een vraag: vraagteken.' },
    { n:2, zin:'De Nederlandse ploeg won met 3-1 van België.', uit:'Nederlandse en België met een hoofdletter, de uitslag met een streepje.' },
    { n:2, zin:'Ze zei dat ze morgen zou komen.', uit:'Geen komma nodig na zei dat: het is een korte zin met een bijzin erin.' },
    { n:2, zin:'Als je klaar bent, mag je naar huis.', uit:'Komma na de bijzin die vooraan staat.' },
    { n:2, zin:'Hij kocht appels, peren, druiven en bananen.', uit:'Komma’s in de opsomming, niet voor en.' },
    { n:2, zin:'We vieren Kerstmis bij mijn opa en oma.', uit:'Feestdagen met een hoofdletter.' },
    { n:3, zin:'Hoewel het koud was, gingen ze toch zwemmen.', uit:'Komma na de bijzin die met hoewel begint.' },
    { n:3, zin:'“Kom je nog?”, riep mijn moeder.', uit:'Aanhalingstekens om wat er gezegd wordt; het vraagteken staat erbinnen, de komma erna.' },
    { n:3, zin:'De minister-president sprak de Tweede Kamer toe.', uit:'Minister-president met een streepje en een kleine letter; Tweede Kamer met hoofdletters.' },
    { n:3, zin:'Mijn vader, die arts is, werkt vaak in het weekend.', uit:'De bijzin die arts is staat tussen komma’s.' },
    { n:3, zin:'Het is een lange, saaie en warme middag geweest.', uit:'Komma tussen twee bijvoeglijke naamwoorden, geen komma voor en.' },
    { n:3, zin:'Wist je dat de Nijl de langste rivier van Afrika is?', uit:'Hoofdletters bij Nijl en Afrika; de zin is een vraag.' },
    { n:3, zin:'Ze had honger, dus ze maakte een boterham.', uit:'Komma voor dus tussen twee zinnen.' },
    { n:3, zin:'Op 5 mei vieren we Bevrijdingsdag.', uit:'Bevrijdingsdag met een hoofdletter; mei met een kleine letter.' },
    { n:3, zin:'Hij vroeg zich af of het nog zin had.', uit:'Geen komma en geen vraagteken: het is een mededeling over een vraag.' },
    { n:3, zin:'Sommige mensen, vooral kinderen, zijn bang voor onweer.', uit:'De toevoeging vooral kinderen staat tussen komma’s.' }
  ],
  leenwoorden: [
    { n:3, w:'gedownload', zin:'Ik heb het spel gedownload.', uit:'voltooid deelwoord van downloaden: ge + download, met een d, want de d staat niet in ’t kofschip' },
    { n:3, w:'geüpdatet', zin:'De app is geüpdatet.', uit:'ge + update + t: de t van ’t kofschip, en een trema tussen de e en de u' },
    { n:3, w:'cameraatje', zin:'Ze kocht een cameraatje.', uit:'camera + tje: de a wordt verdubbeld en er komt geen apostrof' },
    { n:3, w:'baby’s', zin:'De baby’s sliepen allebei.', uit:'meervoud van een woord op y: apostrof + s' },
    { n:3, w:'gecheckt', zin:'Heb je je mail gecheckt?', uit:'ge + check + t: de k-klank staat in ’t kofschip' },
    { n:3, w:'gedeletet', zin:'Ik heb het bericht gedeletet.', uit:'ge + delete + t: de stomme e blijft staan, en de t van ’t kofschip erachter' },
    { n:3, w:'gesaved', zin:'Heb je het bestand gesaved?', uit:'ge + save + d: de v-klank staat niet in ’t kofschip' },
    { n:3, w:'hobby’s', zin:'Mijn hobby’s zijn tekenen en gamen.', uit:'meervoud op y: apostrof + s' },
    { n:3, w:'racete', zin:'Hij racete naar huis.', uit:'verleden tijd van racen: race + te, de s-klank staat in ’t kofschip' },
    { n:3, w:'gemaild', zin:'Ik heb de docent gemaild.', uit:'ge + mail + d: de l staat niet in ’t kofschip' },
    { n:3, w:'gegoogeld', zin:'Ik heb het even gegoogeld.', uit:'ge + googel + d: het werkwoord is googelen, vernederlandst' },
    { n:3, w:'timede', zin:'De juf timede de sprint.', uit:'verleden tijd van timen: time + de; de stomme e blijft staan' },
    { n:3, w:'auto’s', zin:'Er stonden drie auto’s voor de deur.', uit:'meervoud op een losse klinker: apostrof + s' },
    { n:3, w:'gestrest', zin:'Voor de toets was ze gestrest.', uit:'ge + stress + t: dubbele s wordt een enkele voor de t' },
    { n:3, w:'gefinisht', zin:'Zij is als eerste gefinisht.', uit:'ge + finish + t: de sj-klank staat in ’t kofschip' },
    { n:3, w:'gecrasht', zin:'Mijn laptop is gecrasht.', uit:'ge + crash + t' },
    { n:3, w:'getraind', zin:'We hebben hard getraind.', uit:'ge + train + d: de n staat niet in ’t kofschip' },
    { n:3, w:'gescoord', zin:'Hij heeft twee keer gescoord.', uit:'ge + scoor + d: dubbele o, want je hoort een lange oo' },
    { n:3, w:'geshopt', zin:'We hebben de hele middag geshopt.', uit:'ge + shop + t: de p staat in ’t kofschip' },
    { n:3, w:'gefotoshopt', zin:'Die foto is gefotoshopt.', uit:'ge + fotoshop + t' }
  ]
};
