/* De woorden, zinnen en teksten van het dictee. n is het niveau: 1 = vmbo-bb,
   2 = vmbo-kgt en tl, 3 = havo en vwo. Elk onderdeel heeft per niveau minstens
   dertig eigen items; dictee.html neemt vooral die van het eigen niveau en af
   en toe een van een niveau lager.

   werkwoorden: de zin wordt voorgelezen, de leerling typt alleen het werkwoord
   (de zin staat met een gat in beeld). regel is wat er na het antwoord staat.
   woorden: een los woord, met een zin erbij zodat je hoort wat het is.
   leestekens: de hele zin typen, met hoofdletters en leestekens. Alleen
   leestekens die je kunt horen of die een vaste regel volgen; geen
   uitroeptekens (die hoor je niet) en geen cijfers (drie of 3?).
   leenwoorden: Engelse en Franse leenwoorden in Nederlandse spelling (kgt, hv).
   antwoordLijst: als er echt twee goede schrijfwijzen zijn, staan ze er allebei.

   teksten: het doorlopende dictee. Een tekst van tien zinnen met een vast id
   (t-bb-01), zodat een docent hem kan klaarzetten (?tekst=t-bb-01). Tot en met
   week 40 van 2026 waren het er vijf of zes; oud is hoeveel, zodat het dictee
   van die weken hetzelfde blijft (zie weektekst). Het dictee van de week neemt
   vanaf week 41 de eerste zeven zinnen; een tekst die een docent zelf kiest, heeft ze alle tien.
   Elke zin heeft een korte uitleg bij het lastigste woord. Geen cijfers, geen
   aanhalingstekens en geen uitroeptekens: alles wat je typt moet je kunnen
   horen.

   Nagekeken met de Woordenlijst (het Groene Boekje) en de adviezen van de
   Taalunie: werkwoorden als racete, gesaved, geliket en gegamed staan er zo in. */
window.DICTEE_OPGAVEN = {
  werkwoorden: [
    /* ---------- vmbo-bb: stam, stam + t, jij erachter, ’t kofschip ---------- */
    { n:1, zin:'Hij vindt het leuk.', woord:'vindt', regel:'Hij in de tegenwoordige tijd: stam + t. De stam is vind (ik vind), dus hij vindt.' },
    { n:1, zin:'Ik word morgen dertien.', woord:'word', regel:'Ik in de tegenwoordige tijd: alleen de stam. Ik word, zonder t.' },
    { n:1, zin:'Zij wordt elke dag om zeven uur wakker.', woord:'wordt', regel:'Zij: stam + t. De stam word eindigt al op een d, en daar komt de t achter: wordt.' },
    { n:1, zin:'Word jij ook zo moe van die herrie?', woord:'word', regel:'Staat jij achter het werkwoord, dan krijgt het werkwoord geen t: word jij. Staat jij ervoor, dan wel: jij wordt.' },
    { n:1, zin:'Mijn vader rijdt elke dag naar zijn werk.', woord:'rijdt', regel:'Mijn vader is een hij: stam + t. De stam is rijd (ik rijd), dus hij rijdt.' },
    { n:1, zin:'Gisteren speelde ik buiten.', woord:'speelde', regel:'Verleden tijd van spelen: stam speel + de, want de l zit niet in ’t kofschip.' },
    { n:1, zin:'De hond blafte de hele nacht.', woord:'blafte', regel:'Verleden tijd van blaffen: stam blaf + te, want de f zit in ’t kofschip.' },
    { n:1, zin:'Ik heb mijn huiswerk gemaakt.', woord:'gemaakt', regel:'Voltooid deelwoord: ge + stam + t, want de k van maak zit in ’t kofschip.' },
    { n:1, zin:'Zij heeft haar kamer opgeruimd.', woord:'opgeruimd', regel:'Voltooid deelwoord van opruimen: op + ge + ruim + d, want de m zit niet in ’t kofschip.' },
    { n:1, zin:'De kat vangt een muis.', woord:'vangt', regel:'De kat is een hij of zij: stam vang + t.' },
    { n:1, zin:'Wat zegt de juf?', woord:'zegt', regel:'De juf is een zij: stam zeg + t.' },
    { n:1, zin:'Het regent al de hele dag.', woord:'regent', regel:'Het: stam regen + t.' },
    { n:1, zin:'Antwoord jij even op die vraag?', woord:'antwoord', regel:'Jij staat achter het werkwoord, dus geen t: antwoord jij.' },
    { n:1, zin:'Zij lachten om de grap.', woord:'lachten', regel:'Verleden tijd, meervoud: stam lach + ten, want de ch zit in ’t kofschip.' },
    { n:1, zin:'Jij vindt dit vast een saaie film.', woord:'vindt', regel:'Jij staat vóór het werkwoord: stam + t. Jij vindt.' },
    { n:1, zin:'Ik zet de fiets in het rek.', woord:'zet', regel:'Ik: alleen de stam. De stam van zetten is zet.' },
    { n:1, zin:'Hij zet zijn tas op de grond.', woord:'zet', regel:'Hij: stam + t. De stam zet eindigt al op een t; er komt geen tweede t bij.' },
    { n:1, zin:'Ik vind die trui mooi.', woord:'vind', regel:'Ik: alleen de stam, dus vind zonder t.' },
    { n:1, zin:'Vind jij die trui ook mooi?', woord:'vind', regel:'Jij staat achter het werkwoord: geen t. Vind jij.' },
    { n:1, zin:'Wat vindt u van deze jas?', woord:'vindt', regel:'Bij u krijgt het werkwoord stam + t, ook als u erachter staat: vindt u.' },
    { n:1, zin:'De bus stopt voor de school.', woord:'stopt', regel:'De bus is een hij: stam stop + t.' },
    { n:1, zin:'Mijn broer praat heel hard.', woord:'praat', regel:'Hij: stam + t. De stam praat eindigt al op een t, dus er komt geen t bij.' },
    { n:1, zin:'Gisteren wachtten wij een uur op de bus.', woord:'wachtten', regel:'Verleden tijd, meervoud: stam wacht + ten, want de t zit in ’t kofschip. Daarom twee keer t: wachtten.' },
    { n:1, zin:'Ik heb de hele dag gewerkt.', woord:'gewerkt', regel:'Voltooid deelwoord: ge + werk + t, want de k zit in ’t kofschip.' },
    { n:1, zin:'We hebben lang op je gewacht.', woord:'gewacht', regel:'Voltooid deelwoord: ge + wacht + t. De stam eindigt al op een t, dus er komt geen t bij.' },
    { n:1, zin:'De juf belde naar mijn moeder.', woord:'belde', regel:'Verleden tijd van bellen: stam bel + de, want de l zit niet in ’t kofschip.' },
    { n:1, zin:'Hij woonde vroeger in Utrecht.', woord:'woonde', regel:'Verleden tijd van wonen: stam woon + de, want de n zit niet in ’t kofschip.' },
    { n:1, zin:'Ik hoorde een vreemd geluid.', woord:'hoorde', regel:'Verleden tijd van horen: stam hoor + de, want de r zit niet in ’t kofschip.' },
    { n:1, zin:'Ze fietste snel naar huis.', woord:'fietste', regel:'Verleden tijd van fietsen: stam fiets + te, want de s zit in ’t kofschip.' },
    { n:1, zin:'Mijn zus werkte vroeger in een winkel.', woord:'werkte', regel:'Verleden tijd van werken: stam werk + te, want de k zit in ’t kofschip.' },
    { n:1, zin:'We hebben het hele weekend gevoetbald.', woord:'gevoetbald', regel:'Voltooid deelwoord van voetballen: ge + voetbal + d, want de l zit niet in ’t kofschip.' },
    { n:1, zin:'Heb jij je fiets al gerepareerd?', woord:'gerepareerd', regel:'Voltooid deelwoord van repareren: ge + repareer + d, want de r zit niet in ’t kofschip.' },
    { n:1, zin:'Zij antwoordt altijd heel snel.', woord:'antwoordt', regel:'Zij: stam + t. De stam is antwoord, dus zij antwoordt.' },
    { n:1, zin:'Het kind wordt steeds groter.', woord:'wordt', regel:'Het kind is een het: stam word + t = wordt.' },
    { n:1, zin:'Wat gebeurt er in de klas?', woord:'gebeurt', regel:'Tegenwoordige tijd, het onderwerp is wat: stam gebeur + t. Gebeurd met een d is het voltooid deelwoord: het is gebeurd.' },
    { n:1, zin:'Er is iets geks gebeurd.', woord:'gebeurd', regel:'Voltooid deelwoord: gebeur + d, want de r zit niet in ’t kofschip. Er komt geen ge voor, want gebeuren begint al met ge.' },
    { n:1, zin:'Hij houdt van pizza.', woord:'houdt', regel:'Hij: stam + t. De stam is houd (ik houd), dus hij houdt.' },

    /* ---------- vmbo-kgt: verleden tijd, voltooid deelwoord, bijvoeglijk gebruikt, stam op d of t ---------- */
    { n:2, zin:'Hij heeft zich vergist in de datum.', woord:'vergist', regel:'Voltooid deelwoord van zich vergissen: vergis + t, want de s zit in ’t kofschip. Geen ge ervoor, want het begint met ver.' },
    { n:2, zin:'De trein vertrekt om kwart over acht.', woord:'vertrekt', regel:'De trein is een hij: stam vertrek + t.' },
    { n:2, zin:'Zij verhuisde vorig jaar naar Groningen.', woord:'verhuisde', regel:'Verleden tijd: kijk naar het hele werkwoord verhuizen. Daar hoor je een z, en die zit niet in ’t kofschip: verhuis + de.' },
    { n:2, zin:'Ik heb dat boek geleend van de bibliotheek.', woord:'geleend', regel:'Voltooid deelwoord: ge + leen + d, want de n zit niet in ’t kofschip.' },
    { n:2, zin:'Het geplande feest gaat niet door.', woord:'geplande', regel:'Het voltooid deelwoord is gepland (plan + d). Staat het voor een zelfstandig naamwoord, dan komt er een e achter: geplande.' },
    { n:2, zin:'De verbrande taart smaakte bitter.', woord:'verbrande', regel:'Het voltooid deelwoord verbrand staat voor een zelfstandig naamwoord en krijgt een e: verbrande. Niet verwarren met verbrandde, de verleden tijd.' },
    { n:2, zin:'Zij beantwoordt elke vraag rustig.', woord:'beantwoordt', regel:'Zij: stam + t. De stam is beantwoord, dus zij beantwoordt.' },
    { n:2, zin:'Gisteren verbaasde hij iedereen.', woord:'verbaasde', regel:'Verleden tijd: het hele werkwoord is verbazen, met een z. Die zit niet in ’t kofschip: verbaas + de.' },
    { n:2, zin:'Heb je het pakketje al besteld?', woord:'besteld', regel:'Voltooid deelwoord: bestel + d, want de l zit niet in ’t kofschip. Geen ge ervoor, want het begint met be.' },
    { n:2, zin:'De verwachte storm bleef uit.', woord:'verwachte', regel:'Het voltooid deelwoord verwacht staat voor een zelfstandig naamwoord en krijgt een e: verwachte. Met tt is het de verleden tijd: hij verwachtte.' },
    { n:2, zin:'Zij hoopten op mooi weer.', woord:'hoopten', regel:'Verleden tijd, meervoud: hoop + ten, want de p zit in ’t kofschip.' },
    { n:2, zin:'Hij wordt volgend jaar zestien.', woord:'wordt', regel:'Hij: stam + t. Word + t = wordt.' },
    { n:2, zin:'De burgemeester opent het nieuwe zwembad.', woord:'opent', regel:'De burgemeester is een hij of zij: stam open + t.' },
    { n:2, zin:'Gisteren verbrandde hij zijn hand aan de pan.', woord:'verbrandde', regel:'Verleden tijd: verbrand + de, want de d zit niet in ’t kofschip. Zo krijg je dd: verbrandde.' },
    { n:2, zin:'Wordt jouw broer ook zestien?', woord:'wordt', regel:'Het onderwerp is jouw broer, niet jij. De regel dat de t wegvalt, geldt alleen voor jij en je achter het werkwoord. Dus stam + t: wordt.' },
    { n:2, zin:'Vind je het goed als ik later kom?', woord:'vind', regel:'Je betekent hier jij en staat achter het werkwoord: geen t. Vind je.' },
    { n:2, zin:'Mijn moeder zette de vaas op tafel.', woord:'zette', regel:'Verleden tijd van zetten: zet + te, want de t zit in ’t kofschip.' },
    { n:2, zin:'Ik wed dat hij te laat komt.', woord:'wed', regel:'Ik: alleen de stam. De stam van wedden is wed.' },
    { n:2, zin:'De gebruikte boeken gaan naar de kringloop.', woord:'gebruikte', regel:'Het voltooid deelwoord is gebruikt (de k zit in ’t kofschip). Voor een zelfstandig naamwoord komt er een e bij: gebruikte.' },
    { n:2, zin:'De leraar legde de opdracht nog een keer uit.', woord:'legde', regel:'Verleden tijd van uitleggen: leg + de, want de g zit niet in ’t kofschip.' },
    { n:2, zin:'Hij verhuurt zijn fiets aan toeristen.', woord:'verhuurt', regel:'Tegenwoordige tijd, hij: stam verhuur + t.' },
    { n:2, zin:'Het huis is al verhuurd.', woord:'verhuurd', regel:'Voltooid deelwoord: verhuur + d, want de r zit niet in ’t kofschip.' },
    { n:2, zin:'We hebben de hele avond gekletst.', woord:'gekletst', regel:'Voltooid deelwoord: ge + klets + t, want de s zit in ’t kofschip.' },
    { n:2, zin:'Zij beloofde dat ze zou komen.', woord:'beloofde', regel:'Verleden tijd: kijk naar het hele werkwoord beloven. De v zit niet in ’t kofschip: beloof + de.' },
    { n:2, zin:'Ik heb de ramen gelapt.', woord:'gelapt', regel:'Voltooid deelwoord: ge + lap + t, want de p zit in ’t kofschip.' },
    { n:2, zin:'De juf antwoordde niet op mijn vraag.', woord:'antwoordde', regel:'Verleden tijd: antwoord + de. De stam eindigt al op een d, dus dd.' },
    { n:2, zin:'De bestelde pizza kwam te laat.', woord:'bestelde', regel:'Het voltooid deelwoord besteld staat voor een zelfstandig naamwoord en krijgt een e: bestelde.' },
    { n:2, zin:'Ik heb me erg verveeld.', woord:'verveeld', regel:'Voltooid deelwoord van zich vervelen: verveel + d, want de l zit niet in ’t kofschip.' },
    { n:2, zin:'Gebeurt dat vaker?', woord:'gebeurt', regel:'Tegenwoordige tijd, het onderwerp is dat: stam gebeur + t.' },
    { n:2, zin:'Wat is er gisteren gebeurd?', woord:'gebeurd', regel:'Voltooid deelwoord (na is): gebeur + d, want de r zit niet in ’t kofschip.' },
    { n:2, zin:'Hij baalde van de slechte uitslag.', woord:'baalde', regel:'Verleden tijd van balen: baal + de, want de l zit niet in ’t kofschip.' },
    { n:2, zin:'Het ingevulde formulier ligt op je bureau.', woord:'ingevulde', regel:'Het voltooid deelwoord is ingevuld (vul + d). Voor een zelfstandig naamwoord komt er een e bij: ingevulde.' },
    { n:2, zin:'Zij verkleedde zich als piraat.', woord:'verkleedde', regel:'Verleden tijd van verkleden: verkleed + de. De stam eindigt al op een d, dus dd.' },
    { n:2, zin:'Wie wordt de nieuwe voorzitter?', woord:'wordt', regel:'Wie is enkelvoud: stam + t.' },
    { n:2, zin:'Hij raadde het antwoord meteen.', woord:'raadde', regel:'Verleden tijd van raden: raad + de. De stam eindigt op een d, dus dd.' },
    { n:2, zin:'De vliegtuigen landden precies op tijd.', woord:'landden', regel:'Verleden tijd, meervoud: land + den. De stam eindigt op een d, dus dd.' },

    /* ---------- havo en vwo: Engelse werkwoorden, u, je en jouw, leiden en lijden ---------- */
    { n:3, zin:'Het geüpdatete programma werkt sneller.', woord:'geüpdatete', regel:'Updaten: de stam update eindigt op een t-klank, dus het voltooid deelwoord is geüpdatet. Voor een zelfstandig naamwoord komt er een e bij: geüpdatete. Het trema scheidt de e en de u.' },
    { n:3, zin:'Het geraffineerde plan mislukte toch.', woord:'geraffineerde', regel:'Raffineren: raffineer + d, want de r zit niet in ’t kofschip. Geraffineerd, en voor een zelfstandig naamwoord met een e.' },
    { n:3, zin:'Ze racete de hele middag door de wijk.', woord:'racete', regel:'Racen: de stam race eindigt op een s-klank, en die zit in ’t kofschip: race + te. De e van race blijft staan.' },
    { n:3, zin:'Wie gelooft er nog in die belofte?', woord:'gelooft', regel:'Wie is enkelvoud: stam geloof + t.' },
    { n:3, zin:'Hij heeft de uitslag verkeerd voorspeld.', woord:'voorspeld', regel:'Voltooid deelwoord van voorspellen: voorspel + d, want de l zit niet in ’t kofschip.' },
    { n:3, zin:'De bedreigde diersoort keerde terug.', woord:'bedreigde', regel:'Het voltooid deelwoord is bedreigd (de g zit niet in ’t kofschip). Voor een zelfstandig naamwoord met een e: bedreigde.' },
    { n:3, zin:'Zij verwedt er haar zakgeld op.', woord:'verwedt', regel:'Zij: stam verwed + t.' },
    { n:3, zin:'Het volk verzette zich tegen de koning.', woord:'verzette', regel:'Verleden tijd van zich verzetten: verzet + te, want de t zit in ’t kofschip.' },
    { n:3, zin:'Men zegt dat het morgen gaat sneeuwen.', woord:'zegt', regel:'Men is enkelvoud: stam zeg + t.' },
    { n:3, zin:'U wordt verzocht uw jas op te hangen.', woord:'wordt', regel:'U: stam + t.' },
    { n:3, zin:'Vindt u het goed als ik het raam opendoe?', woord:'vindt', regel:'Bij u blijft de t staan, ook als u achter het werkwoord staat: vindt u. De t valt alleen weg bij jij en je.' },
    { n:3, zin:'Wordt u al geholpen?', woord:'wordt', regel:'U achter het werkwoord: de t blijft staan. Wordt u.' },
    { n:3, zin:'Hij heeft het bestand per ongeluk gedeletet.', woord:'gedeletet', regel:'Deleten: de stam delete eindigt op een t-klank, die in ’t kofschip zit: ge + delete + t. De e van delete blijft staan.' },
    { n:3, zin:'Zij heeft de afspraak gecanceld.', woord:'gecanceld', regel:'Cancelen: de stam cancel eindigt op een l, die niet in ’t kofschip zit: ge + cancel + d.' },
    { n:3, zin:'De coach timede elke ronde.', woord:'timede', regel:'Timen: de stam time eindigt op een m-klank, die niet in ’t kofschip zit: time + de.' },
    { n:3, zin:'We hebben de hele avond gegamed.', woord:'gegamed', regel:'Gamen: de stam game eindigt op een m-klank, die niet in ’t kofschip zit: ge + game + d.' },
    { n:3, zin:'Heb je die foto al geliket?', woord:'geliket', regel:'Liken: de stam like eindigt op een k-klank, die in ’t kofschip zit: ge + like + t.' },
    { n:3, zin:'Ze appten elke avond met elkaar.', woord:'appten', regel:'Appen: de stam is app, en de p zit in ’t kofschip. Verleden tijd meervoud: app + ten.' },
    { n:3, zin:'Het gerecyclede plastic wordt een nieuwe tas.', woord:'gerecyclede', regel:'Recyclen: de stam recycle eindigt op een l-klank, die niet in ’t kofschip zit: gerecycled. Voor een zelfstandig naamwoord met een e: gerecyclede.' },
    { n:3, zin:'Hij surfte de hele vakantie.', woord:'surfte', regel:'Verleden tijd van surfen: surf + te, want de f zit in ’t kofschip.' },
    { n:3, zin:'De gemailde uitnodiging kwam nooit aan.', woord:'gemailde', regel:'Mailen: de l zit niet in ’t kofschip, dus gemaild. Voor een zelfstandig naamwoord met een e: gemailde.' },
    { n:3, zin:'Hij verwachtte een cadeau, maar kreeg niets.', woord:'verwachtte', regel:'Verleden tijd: verwacht + te, want de t zit in ’t kofschip. Zo krijg je tt: verwachtte.' },
    { n:3, zin:'De geleverde spullen waren beschadigd.', woord:'geleverde', regel:'Leveren: lever + d, want de r zit niet in ’t kofschip. Geleverd, en voor een zelfstandig naamwoord met een e.' },
    { n:3, zin:'Zij realiseerde zich dat ze te laat was.', woord:'realiseerde', regel:'Verleden tijd van zich realiseren: realiseer + de, want de r zit niet in ’t kofschip.' },
    { n:3, zin:'Het geanalyseerde water bleek schoon.', woord:'geanalyseerde', regel:'Analyseren: analyseer + d, want de r zit niet in ’t kofschip. Geanalyseerd, en voor een zelfstandig naamwoord met een e.' },
    { n:3, zin:'Hij bestudeerde de kaart zorgvuldig.', woord:'bestudeerde', regel:'Verleden tijd van bestuderen: bestudeer + de, want de r zit niet in ’t kofschip.' },
    { n:3, zin:'Word je morgen opgehaald?', woord:'word', regel:'Je betekent hier jij en staat achter het werkwoord: geen t. Word je.' },
    { n:3, zin:'Wordt je broer morgen opgehaald?', woord:'wordt', regel:'Je broer betekent jouw broer, en dat is een hij. De regel voor jij en je achter het werkwoord geldt hier niet: stam + t.' },
    { n:3, zin:'Ik heb het filmpje gisteren geüpload.', woord:'geüpload', regel:'Uploaden: de stam upload eindigt al op een d, dus ge + upload zonder extra d. Het trema scheidt de e en de u.' },
    { n:3, zin:'Zij uploadde de foto’s naar haar laptop.', woord:'uploadde', regel:'Verleden tijd: upload + de. De stam eindigt al op een d, dus dd.' },
    { n:3, zin:'Het gedownloade bestand staat in je map.', woord:'gedownloade', regel:'Downloaden: de stam download eindigt al op een d, dus gedownload. Voor een zelfstandig naamwoord met een e: gedownloade.' },
    { n:3, zin:'De voorzitter leidt de vergadering.', woord:'leidt', regel:'Leiden (de baas zijn over iets): hij leidt, stam leid + t. Niet verwarren met lijden (pijn of last hebben): hij lijdt.' },
    { n:3, zin:'Hij lijdt aan hooikoorts.', woord:'lijdt', regel:'Lijden (last hebben van iets): hij lijdt, stam lijd + t. Leiden met ei is de baas zijn.' },
    { n:3, zin:'De vergrote foto hing aan de muur.', woord:'vergrote', regel:'Het voltooid deelwoord is vergroot. Met een e erachter eindigt de lettergreep op de klinker, dus één o: ver-gro-te.' },
    { n:3, zin:'Het ingeleverde werkstuk was keurig verzorgd.', woord:'ingeleverde', regel:'Inleveren: lever + d, want de r zit niet in ’t kofschip. Ingeleverd, en voor een zelfstandig naamwoord met een e.' }
  ],
  woorden: [
    /* ---------- vmbo-bb ---------- */
    { n:1, w:'misschien', zin:'Misschien kom ik morgen.', uit:'mis + schien: twee keer een s, want het is mis-schien' },
    { n:1, w:'gezellig', zin:'Het was een gezellig feest.', uit:'dubbele l na de korte e, en ig aan het eind' },
    { n:1, w:'belangrijk', zin:'Dit is een belangrijk bericht.', uit:'be-lang-rijk: aan het eind rijk met ij' },
    { n:1, w:'eigenlijk', zin:'Eigenlijk wilde ik thuisblijven.', uit:'ei-gen-lijk: eerst ei, aan het eind lijk met ij' },
    { n:1, w:'altijd', zin:'Hij is altijd op tijd.', uit:'al + tijd: met ij en een d aan het eind, net als tijden' },
    { n:1, w:'tijdens', zin:'Tijdens de les is het stil.', uit:'tijd + ens: de d van tijd blijft staan' },
    { n:1, w:'verjaardag', zin:'Morgen is mijn verjaardag.', uit:'ver + jaar + dag' },
    { n:1, w:'boterham', zin:'Ik neem een boterham met kaas.', uit:'bo-ter-ham: één t, want de o is lang' },
    { n:1, w:'tandarts', zin:'Vandaag moet ik naar de tandarts.', uit:'tand + arts: met de d van tand' },
    { n:1, w:'paard', zin:'Mijn nicht heeft een paard.', uit:'je hoort een t, maar het is paard met een d: paarden' },
    { n:1, w:'ijsje', zin:'Ik wil een ijsje met aardbei.', uit:'ijs + je: met ij, en een s voor de je' },
    { n:1, w:'meisje', zin:'Het meisje fietst naar school.', uit:'mei + sje: met ei' },
    { n:1, w:'vrouw', zin:'De vrouw lacht naar de baby.', uit:'ouw aan het eind' },
    { n:1, w:'blauw', zin:'Mijn jas is blauw.', uit:'auw aan het eind' },
    { n:1, w:'koud', zin:'Het is koud buiten.', uit:'ou, en een d aan het eind: kouder' },
    { n:1, w:'pauze', zin:'In de pauze eet ik een appel.', uit:'au, en een z in het midden' },
    { n:1, w:'trouwens', zin:'Trouwens, heb jij mijn pen gezien?', uit:'trouw + ens: met ouw' },
    { n:1, w:'chocolade', zin:'Ik lust graag chocolade.', uit:'ch aan het begin, een l in het midden' },
    { n:1, w:'cadeau', zin:'Ik kreeg een cadeau voor mijn verjaardag.', uit:'Frans woord: c-a-d-e-a-u, eau klinkt als oo' },
    { n:1, w:'natuurlijk', zin:'Natuurlijk kom ik naar je feest.', uit:'natuur + lijk' },
    { n:1, w:'moeilijk', zin:'Deze som is moeilijk.', uit:'moei + lijk' },
    { n:1, w:'vakantie', zin:'In de vakantie ga ik kamperen.', uit:'tie klinkt als tsie, maar je schrijft t-i-e' },
    { n:1, w:'politie', zin:'De politie kwam snel.', uit:'ook hier tie: po-li-tie' },
    { n:1, w:'bibliotheek', zin:'Ik leen boeken in de bibliotheek.', uit:'bi-bli-o-theek, met th' },
    { n:1, w:'weinig', zin:'Er is nog maar weinig melk.', uit:'ei, en ig aan het eind' },
    { n:1, w:'stiekem', zin:'Hij at stiekem een koekje.', uit:'stie-kem: ie, en em aan het eind' },
    { n:1, w:'koffie', zin:'Mijn moeder drinkt koffie.', uit:'dubbele f, en ie aan het eind' },
    { n:1, w:'februari', zin:'In februari is het vaak koud.', uit:'fe-bru-a-ri: let op de r na de b' },
    { n:1, w:'gewoon', zin:'Ik doe gewoon mijn best.', uit:'ge + woon' },
    { n:1, w:'hoofdpijn', zin:'Ik heb last van hoofdpijn.', uit:'hoofd met een d, pijn met ij' },
    { n:1, w:'handschoen', zin:'Ik ben mijn handschoen kwijt.', uit:'hand met een d, dan schoen met sch' },
    { n:1, w:'middag', zin:'De middag duurde lang.', uit:'mid + dag: twee keer d' },
    { n:1, w:'wedstrijd', zin:'We winnen de wedstrijd.', uit:'wed + strijd: strijd met ij en een d' },
    { n:1, w:'interessant', zin:'Dat is een interessant verhaal.', uit:'in-te-res-sant: één r, dubbele s' },

    /* ---------- vmbo-kgt ---------- */
    { n:2, w:'enquête', zin:'We vulden een enquête in over de pauzes.', uit:'Frans: en-quê-te, met qu en een dakje op de e' },
    { n:2, w:'parallel', zin:'De twee lijnen lopen parallel.', uit:'pa-ral-lel: één r, twee keer dubbele l' },
    { n:2, w:'accu', zin:'De accu van de fiets is leeg.', uit:'dubbele c' },
    { n:2, w:'hobby', zin:'Mijn hobby is tekenen.', uit:'dubbele b, en een y aan het eind' },
    { n:2, w:'medicijn', zin:'De dokter schreef een medicijn voor.', uit:'me-di-cijn: de c voor de i klinkt als s, en ijn aan het eind' },
    { n:2, w:'gigantisch', zin:'De golf was gigantisch.', uit:'isch aan het eind, zoals in logisch' },
    { n:2, w:'kantine', zin:'We eten in de kantine.', uit:'kan-ti-ne: één n in het midden' },
    { n:2, w:'directeur', zin:'De directeur opende het feest.', uit:'di-rec-teur: een c voor de t, en eur aan het eind' },
    { n:2, w:'temperatuur', zin:'De temperatuur stijgt.', uit:'tem-pe-ra-tuur' },
    { n:2, w:'agressief', zin:'De hond werd agressief.', uit:'één g, dubbele s, en ief aan het eind' },
    { n:2, w:'commentaar', zin:'Iedereen had commentaar op de scheidsrechter.', uit:'dubbele m, en aar aan het eind' },
    { n:2, w:'sowieso', zin:'Ik ga sowieso mee.', uit:'so-wie-so, aan elkaar' },
    { n:2, w:'ingewikkeld', zin:'Die opdracht is best ingewikkeld.', uit:'in-ge-wik-keld: dubbele k, en een d aan het eind' },
    { n:2, w:'eventueel', zin:'We kunnen eventueel later beginnen.', uit:'e-ven-tu-eel' },
    { n:2, w:'gemakkelijk', zin:'Deze toets was gemakkelijk.', uit:'ge-mak-ke-lijk: dubbele k en lijk' },
    { n:2, w:'tegenwoordig', zin:'Tegenwoordig heeft iedereen een telefoon.', uit:'te-gen-woor-dig: een d en ig aan het eind' },
    { n:2, w:'verantwoordelijk', zin:'Jij bent verantwoordelijk voor de sleutel.', uit:'ver-ant-woor-de-lijk' },
    { n:2, w:'absoluut', zin:'Dat is absoluut niet waar.', uit:'ab-so-luut: een b voor de s, en uut aan het eind' },
    { n:2, w:'definitief', zin:'De uitslag is nu definitief.', uit:'de-fi-ni-tief' },
    { n:2, w:'precies', zin:'Het is precies acht uur.', uit:'pre-cies: de c voor de ie klinkt als s' },
    { n:2, w:'centrum', zin:'We gaan naar het centrum van de stad.', uit:'de c voor de e klinkt als s' },
    { n:2, w:'cijfer', zin:'Ik haalde een goed cijfer.', uit:'de c voor de ij klinkt als s' },
    { n:2, w:'gymnastiek', zin:'Na de pauze hebben we gymnastiek.', uit:'gym-nas-tiek: met een y' },
    { n:2, w:'apotheek', zin:'Het medicijn haal je bij de apotheek.', uit:'a-po-theek, met th' },
    { n:2, w:'officieel', zin:'De opening is pas morgen officieel.', uit:'of-fi-ci-eel: dubbele f, en een c voor de i' },
    { n:2, w:'commissie', zin:'Een commissie regelt het schoolfeest.', uit:'dubbele m en dubbele s' },
    { n:2, w:'discussie', zin:'We hadden een discussie over huiswerk.', uit:'dis-cus-sie: een c, dubbele s' },
    { n:2, w:'verschrikkelijk', zin:'Het weer was verschrikkelijk.', uit:'ver-schrik-ke-lijk: dubbele k' },
    { n:2, w:'hoofdstuk', zin:'Lees hoofdstuk drie voor morgen.', uit:'hoofd met een d, en dan stuk' },
    { n:2, w:'fantastisch', zin:'Het concert was fantastisch.', uit:'isch aan het eind' },
    { n:2, w:'typisch', zin:'Dat is typisch iets voor hem.', uit:'ty-pisch: een y, en isch aan het eind' },
    { n:2, w:'onmiddellijk', zin:'Kom onmiddellijk hier.', uit:'on-mid-del-lijk: dubbele d en dubbele l' },
    { n:2, w:'illegaal', zin:'Het is illegaal om zonder rijbewijs auto te rijden.', uit:'dubbele l, één g, aal aan het eind' },

    /* ---------- havo en vwo ---------- */
    { n:3, w:'acquisitie', zin:'Het bedrijf doet aan acquisitie.', uit:'ac-qui-si-tie: cq, en tie aan het eind' },
    { n:3, w:'ambivalent', zin:'Ze stond er ambivalent tegenover.', uit:'am-bi-va-lent' },
    { n:3, w:'consequent', zin:'Hij is heel consequent in zijn regels.', uit:'con-se-quent: qu klinkt als kw' },
    { n:3, w:'privacy', zin:'Iedereen heeft recht op privacy.', uit:'Engels leenwoord: pri-va-cy, met c en y' },
    { n:3, w:'bureaucratie', zin:'De bureaucratie maakte alles traag.', uit:'bu-reau-cra-tie: eau zoals in bureau' },
    { n:3, w:'hiërarchie', zin:'In het leger is de hiërarchie streng.', uit:'trema op de e, zodat je hi-e hoort; ch in het midden' },
    { n:3, w:'geïnteresseerd', zin:'Zij is geïnteresseerd in techniek.', uit:'trema op de i na ge, één r, dubbele s' },
    { n:3, w:'ideeën', zin:'Zij heeft altijd goede ideeën.', uit:'meervoud van idee: ideeën, met een trema op de derde e' },
    { n:3, w:'rendement', zin:'Het rendement van de zonnepanelen valt mee.', uit:'ren-de-ment' },
    { n:3, w:'symbool', zin:'De duif is een symbool van vrede.', uit:'y na de s, dubbele o' },
    { n:3, w:'fysiotherapeut', zin:'De fysiotherapeut hielp met de blessure.', uit:'fy-si-o-the-ra-peut: y en th' },
    { n:3, w:'exclusief', zin:'De prijs is exclusief btw.', uit:'ex-clu-sief: x, en ief aan het eind' },
    { n:3, w:'millennium', zin:'We leven in het derde millennium.', uit:'dubbele l en dubbele n' },
    { n:3, w:'accessoires', zin:'De winkel verkoopt accessoires.', uit:'dubbele c, dubbele s, oires' },
    { n:3, w:'faillissement', zin:'De winkel moest faillissement aanvragen.', uit:'fail-lis-se-ment: dubbele l, dubbele s' },
    { n:3, w:'onafhankelijk', zin:'De krant is onafhankelijk.', uit:'on-af-han-ke-lijk' },
    { n:3, w:'dichtstbijzijnde', zin:'Waar is de dichtstbijzijnde bushalte?', uit:'dichtst + bij + zijnde: let op de st en de twee keer ij' },
    { n:3, w:'psychologie', zin:'Ze wil later psychologie studeren.', uit:'psy-cho-lo-gie: ps aan het begin, y, ch' },
    { n:3, w:'chronologisch', zin:'Vertel het verhaal chronologisch.', uit:'chro-no-lo-gisch: ch aan het begin klinkt als k' },
    { n:3, w:'enthousiast', zin:'De klas was enthousiast over het plan.', uit:'en-thou-si-ast: th en ou' },
    { n:3, w:'respectievelijk', zin:'Ze werden respectievelijk eerste en tweede.', uit:'res-pec-tie-ve-lijk' },
    { n:3, w:'desalniettemin', zin:'Het regende, desalniettemin gingen we wandelen.', uit:'des + al + niet + te + min: aan elkaar, met dubbele t' },
    { n:3, w:'hypothese', zin:'Eerst stel je een hypothese op.', uit:'hy-po-the-se: y en th' },
    { n:3, w:'coöperatie', zin:'De boeren werken samen in een coöperatie.', uit:'trema op de tweede o, zodat je co-o hoort' },
    { n:3, w:'reünie', zin:'Mijn ouders gaan naar een reünie van hun oude school.', uit:'trema op de u: re-u-nie' },
    { n:3, w:'financieel', zin:'Het bedrijf staat er financieel slecht voor.', uit:'fi-nan-ci-eel: een c voor de i' },
    { n:3, w:'efficiënt', zin:'Zo werk je efficiënt.', uit:'ef-fi-ci-ënt: dubbele f, c, en een trema op de e' },
    { n:3, w:'ingrediënt', zin:'Welk ingrediënt ontbreekt er nog?', uit:'in-gre-di-ënt: trema op de e' },
    { n:3, w:'hygiëne', zin:'In een keuken is hygiëne belangrijk.', uit:'hy-gi-ë-ne: y, en een trema op de e' },
    { n:3, w:'naïef', zin:'Dat was nogal naïef van hem.', uit:'na-ief: trema op de i, zodat je a-i hoort en geen ai' },
    { n:3, w:'sceptisch', zin:'De wetenschapper bleef sceptisch.', uit:'scep-tisch: sc klinkt als sk' },
    { n:3, w:'synoniem', zin:'Blij is een synoniem van vrolijk.', uit:'sy-no-niem: met een y' },
    { n:3, w:'labyrint', zin:'We verdwaalden in het labyrint.', uit:'la-by-rint: met een y, en een t aan het eind' },
    { n:3, w:'chaotisch', zin:'Het was chaotisch op het station.', uit:'cha-o-tisch: ch klinkt als k' }
  ],
  leestekens: [
    /* ---------- vmbo-bb: hoofdletter aan het begin, namen, punt en vraagteken ---------- */
    { n:1, zin:'Morgen gaan we naar Amsterdam.', uit:'Een hoofdletter aan het begin van de zin en bij de plaatsnaam Amsterdam, een punt aan het eind.' },
    { n:1, zin:'Kom je ook naar het feest van Sanne?', uit:'Een vraag eindigt op een vraagteken. De naam Sanne krijgt een hoofdletter.' },
    { n:1, zin:'Mijn oma woont in Rotterdam.', uit:'Een plaatsnaam krijgt een hoofdletter.' },
    { n:1, zin:'Ga je mee zwemmen?', uit:'Het is een vraag, dus een vraagteken aan het eind.' },
    { n:1, zin:'Op maandag begint de school om half negen.', uit:'Dagen van de week schrijf je met een kleine letter.' },
    { n:1, zin:'In juni gaan we op vakantie naar Frankrijk.', uit:'Maanden met een kleine letter, landen met een hoofdletter.' },
    { n:1, zin:'Mijn beste vriend heet Daan.', uit:'Namen van mensen krijgen een hoofdletter.' },
    { n:1, zin:'Waar woon jij?', uit:'Een vraag met waar: een vraagteken aan het eind.' },
    { n:1, zin:'Emma heeft een nieuwe fiets.', uit:'De zin begint met een naam: die heeft al een hoofdletter.' },
    { n:1, zin:'Hoe laat begint de film?', uit:'Een vraag met hoe laat: vraagteken.' },
    { n:1, zin:'Wij wonen in Zwolle.', uit:'Plaatsnaam met een hoofdletter, punt aan het eind.' },
    { n:1, zin:'Heb je Lucas gezien?', uit:'Een vraag, en de naam Lucas met een hoofdletter.' },
    { n:1, zin:'De trein naar Utrecht is te laat.', uit:'Utrecht is een plaatsnaam: hoofdletter.' },
    { n:1, zin:'Mijn tante komt uit Marokko.', uit:'Een land krijgt een hoofdletter.' },
    { n:1, zin:'Wanneer ben je jarig?', uit:'Een vraag met wanneer: vraagteken.' },
    { n:1, zin:'Sam en Noor zitten in dezelfde klas.', uit:'Twee namen, allebei met een hoofdletter.' },
    { n:1, zin:'Is Groningen ver weg?', uit:'Een vraag, en Groningen met een hoofdletter.' },
    { n:1, zin:'Mijn opa is geboren in Suriname.', uit:'Een land krijgt een hoofdletter.' },
    { n:1, zin:'Wat eet je het liefst?', uit:'Een vraag met wat: vraagteken.' },
    { n:1, zin:'In de zomer zwemmen we in de Noordzee.', uit:'De Noordzee is een naam: hoofdletter. Zomer niet, want seizoenen krijgen een kleine letter.' },
    { n:1, zin:'Kun je mij helpen?', uit:'Het is een vraag: vraagteken.' },
    { n:1, zin:'Mijn nicht woont in Duitsland.', uit:'Duitsland is een land: hoofdletter.' },
    { n:1, zin:'Het concert is op zaterdag.', uit:'Zaterdag is een dag van de week: kleine letter.' },
    { n:1, zin:'Ben jij al eens in Parijs geweest?', uit:'Een vraag, en de stad Parijs met een hoofdletter.' },
    { n:1, zin:'Onze hond heet Max.', uit:'Ook de naam van een dier krijgt een hoofdletter.' },
    { n:1, zin:'Waarom ben je zo laat?', uit:'Een vraag met waarom: vraagteken.' },
    { n:1, zin:'Fatima speelt op zondag voetbal.', uit:'Een naam met een hoofdletter, zondag met een kleine letter.' },
    { n:1, zin:'We gaan met de bus naar Den Haag.', uit:'Den Haag: allebei de woorden van de naam met een hoofdletter.' },
    { n:1, zin:'Hoe heet jouw kat?', uit:'Een vraag met hoe: vraagteken.' },
    { n:1, zin:'In april is het vaak nog koud.', uit:'Maanden schrijf je met een kleine letter: april.' },
    { n:1, zin:'Ik heb een hond, een kat en twee konijnen.', uit:'Een komma tussen de dingen die je opnoemt, maar geen komma voor en.' },

    /* ---------- vmbo-kgt: komma’s, feestdagen, namen van gebouwen, gebeurtenissen en talen ---------- */
    { n:2, zin:'Toen het begon te regenen, gingen we naar binnen.', uit:'De bijzin Toen het begon te regenen staat vooraan. Daarna komt een komma, voor de persoonsvorm gingen.' },
    { n:2, zin:'Ik wilde meedoen, maar ik was te laat.', uit:'Een komma voor maar als er twee zinnen aan elkaar staan.' },
    { n:2, zin:'Mijn buurman, een oude visser, vertelt mooie verhalen.', uit:'De uitleg over de buurman (een oude visser) staat tussen twee komma’s.' },
    { n:2, zin:'Mijn opa vertelt vaak over de Tweede Wereldoorlog.', uit:'Namen van historische gebeurtenissen krijgen hoofdletters: de Tweede Wereldoorlog.' },
    { n:2, zin:'Weet jij hoe laat de bus vertrekt?', uit:'De hele zin is een vraag: vraagteken.' },
    { n:2, zin:'Als je klaar bent, mag je naar huis.', uit:'Een komma na de bijzin die vooraan staat, tussen bent en mag.' },
    { n:2, zin:'Hij kocht appels, peren, druiven en bananen.', uit:'Komma’s in de opsomming, niet voor en.' },
    { n:2, zin:'We vieren Kerstmis bij mijn opa en oma.', uit:'Feestdagen krijgen een hoofdletter: Kerstmis.' },
    { n:2, zin:'Op Koningsdag verkopen we oude spullen op de vrijmarkt.', uit:'Koningsdag is een feestdag: hoofdletter. Vrijmarkt is een gewoon woord.' },
    { n:2, zin:'Mijn broer spreekt Engels, Duits en een beetje Spaans.', uit:'Talen krijgen een hoofdletter, en komma’s in de opsomming.' },
    { n:2, zin:'Omdat het glad was, fietste ik heel voorzichtig.', uit:'Een komma na de bijzin met omdat, tussen was en fietste.' },
    { n:2, zin:'Na de les gaan we naar het Rijksmuseum.', uit:'De naam van een museum krijgt een hoofdletter.' },
    { n:2, zin:'Mijn zus studeert in Leiden, maar ze woont nog thuis.', uit:'Plaatsnaam met een hoofdletter, en een komma voor maar tussen twee zinnen.' },
    { n:2, zin:'Hoewel ik moe was, maakte ik mijn huiswerk af.', uit:'Een komma na de bijzin met hoewel.' },
    { n:2, zin:'De Rijn stroomt door Duitsland en Nederland.', uit:'Rivieren en landen krijgen een hoofdletter.' },
    { n:2, zin:'Tijdens de Olympische Spelen keken we elke avond sport.', uit:'De Olympische Spelen is een naam: twee hoofdletters.' },
    { n:2, zin:'Onze juf, mevrouw De Vries, geeft ook Frans.', uit:'De naam staat tussen komma’s. Zonder voornaam krijgt De in De Vries een hoofdletter. Frans is een taal: hoofdletter.' },
    { n:2, zin:'Kun je morgen, als je tijd hebt, even langskomen?', uit:'Het stukje als je tijd hebt staat midden in de zin tussen twee komma’s. Het is een vraag: vraagteken.' },
    { n:2, zin:'Wij eten op vrijdag vaak pizza, friet of pannenkoeken.', uit:'Vrijdag met een kleine letter; komma’s in de opsomming, geen komma voor of.' },
    { n:2, zin:'Ik neem een boek, een pen en mijn laptop mee.', uit:'Komma’s tussen de dingen die je opnoemt, niet voor en.' },
    { n:2, zin:'Is de Eiffeltoren hoger dan de Euromast?', uit:'Namen van gebouwen krijgen een hoofdletter, en het is een vraag.' },
    { n:2, zin:'Nadat de bel was gegaan, liep iedereen naar buiten.', uit:'Een komma na de bijzin met nadat.' },
    { n:2, zin:'Mijn tante woont in het zuiden van Spanje.', uit:'Een windstreek als het zuiden krijgt een kleine letter; Spanje wel een hoofdletter.' },
    { n:2, zin:'Met Pasen zoeken de kinderen eieren in de tuin.', uit:'Pasen is een feestdag: hoofdletter.' },
    { n:2, zin:'Het was koud, dus ik trok mijn dikke jas aan.', uit:'Een komma voor dus als er twee zinnen aan elkaar staan.' },
    { n:2, zin:'De Nederlandse ploeg speelde gelijk tegen België.', uit:'Nederlandse komt van Nederland: hoofdletter. België met een hoofdletter en een trema.' },
    { n:2, zin:'Wil je het raam dichtdoen, want het tocht?', uit:'Een komma voor want tussen twee zinnen, en een vraagteken want het is een vraag.' },
    { n:2, zin:'Mijn neef, die in Canada woont, komt deze zomer logeren.', uit:'Het stukje die in Canada woont vertelt meer over de neef en staat tussen komma’s.' },
    { n:2, zin:'Hij houdt van voetbal, tennis en zwemmen.', uit:'Komma’s in de opsomming, niet voor en.' },
    { n:2, zin:'Wanneer begint de zomervakantie in Noord-Holland?', uit:'Noord-Holland: twee hoofdletters met een streepje ertussen. Zomervakantie met een kleine letter.' },

    /* ---------- havo en vwo: aanhalingstekens, windstreken, samengestelde namen, lastige hoofdletters ---------- */
    { n:3, zin:'Hoewel het koud was, gingen ze toch zwemmen.', uit:'Een komma na de bijzin met hoewel, tussen de twee werkwoorden was en gingen.' },
    { n:3, zin:'“Kom je nog?” riep mijn moeder.', antwoordLijst:['“Kom je nog?” riep mijn moeder.', '‘Kom je nog?’ riep mijn moeder.'], uit:'Wat iemand letterlijk zegt, staat tussen aanhalingstekens (dubbele of enkele). Het vraagteken staat binnen de aanhalingstekens; daarna komt geen komma meer.' },
    { n:3, zin:'De minister-president sprak de Tweede Kamer toe.', uit:'Minister-president met een streepje en een kleine letter; de Tweede Kamer met hoofdletters.' },
    { n:3, zin:'Mijn vader, die arts is, werkt vaak in het weekend.', uit:'De bijzin die arts is staat tussen komma’s.' },
    { n:3, zin:'Het is een lange, saaie en warme middag geweest.', uit:'Een komma tussen de bijvoeglijke naamwoorden die je opnoemt, geen komma voor en.' },
    { n:3, zin:'Wist je dat de Nijl door Egypte stroomt?', uit:'Hoofdletters bij Nijl en Egypte; de zin is een vraag.' },
    { n:3, zin:'Ze had honger, dus ze maakte een boterham.', uit:'Een komma voor dus tussen twee zinnen.' },
    { n:3, zin:'Hij vroeg zich af of het nog zin had.', uit:'Geen komma en geen vraagteken: dit is een mededeling over een vraag.' },
    { n:3, zin:'Sommige mensen, vooral kinderen, zijn bang voor onweer.', uit:'De toevoeging vooral kinderen staat tussen komma’s.' },
    { n:3, zin:'In de middeleeuwen woonden de meeste mensen op het platteland.', uit:'Een tijdperk als de middeleeuwen schrijf je met een kleine letter.' },
    { n:3, zin:'Na de ramadan vieren veel families het Suikerfeest.', uit:'De ramadan is een periode en krijgt een kleine letter; het Suikerfeest is een feestdag en krijgt een hoofdletter.' },
    { n:3, zin:'De Verenigde Staten liggen ten westen van de Atlantische Oceaan.', uit:'Namen van landen en zeeën krijgen hoofdletters. Een windstreek als ten westen van niet.' },
    { n:3, zin:'Mijn oom woont in Zuid-Frankrijk, vlak bij de Middellandse Zee.', uit:'Zuid-Frankrijk is een aardrijkskundige naam: hoofdletters en een streepje. De Middellandse Zee met twee hoofdletters.' },
    { n:3, zin:'Mijn tante, een echte Amsterdamse, praat heel snel.', uit:'Een inwoner van een stad krijgt een hoofdletter; de uitleg staat tussen komma’s.' },
    { n:3, zin:'Omdat de trein vertraging had, kwam ik pas om tien uur aan.', uit:'Een komma na de bijzin met omdat.' },
    { n:3, zin:'De Chinese Muur is duizenden kilometers lang.', uit:'De Chinese Muur is een naam: twee hoofdletters.' },
    { n:3, zin:'Tijdens de Gouden Eeuw was Amsterdam een rijke stad.', uit:'De Gouden Eeuw is de naam van een periode en krijgt hoofdletters, anders dan de middeleeuwen.' },
    { n:3, zin:'In het oosten van het land ligt de Veluwe.', uit:'Het oosten is een windstreek: kleine letter. De Veluwe is een naam: hoofdletter.' },
    { n:3, zin:'Hij speelt gitaar, zij speelt piano en ik zing.', uit:'Drie zinnetjes na elkaar: komma’s ertussen, maar geen komma voor en.' },
    { n:3, zin:'Wanneer je de brug over bent, zie je het station al liggen.', uit:'Een komma na de bijzin die vooraan staat.' },
    { n:3, zin:'De Franse Revolutie begon in Parijs.', uit:'De Franse Revolutie is een historische gebeurtenis: twee hoofdletters.' },
    { n:3, zin:'Mijn opa, die vroeger zeeman was, heeft de hele wereld gezien.', uit:'De bijzin die vroeger zeeman was staat tussen komma’s.' },
    { n:3, zin:'Heb jij het boek van Thea Beckman gelezen?', uit:'De naam van een schrijver met hoofdletters; het is een vraag.' },
    { n:3, zin:'Het koude, natte weer duurde de hele week.', uit:'Een komma tussen twee bijvoeglijke naamwoorden die allebei iets over het weer zeggen.' },
    { n:3, zin:'Zodra de zon onderging, werd het stil in het bos.', uit:'Een komma na de bijzin met zodra.' },
    { n:3, zin:'Kent u de weg naar het Centraal Station?', uit:'U met een kleine letter; het Centraal Station is een naam met hoofdletters. Het is een vraag.' },
    { n:3, zin:'Op Tweede Kerstdag gaan we naar mijn tante in Brabant.', uit:'Tweede Kerstdag is een feestdag: twee hoofdletters. Brabant ook.' },
    { n:3, zin:'In de winter gaan veel Nederlanders skiën in de Alpen.', uit:'Nederlanders en de Alpen krijgen een hoofdletter; skiën een trema, winter een kleine letter.' },
    { n:3, zin:'Het Nederlands en het Fries zijn allebei officiële talen in Nederland.', uit:'Namen van talen krijgen een hoofdletter; officiële heeft een trema.' },
    { n:3, zin:'Vorige zomer fietsten we van Maastricht naar Den Helder.', uit:'Plaatsnamen met een hoofdletter, ook allebei de delen van Den Helder.' },
    { n:3, zin:'Mijn nichtje woont in Zuid-Afrika, maar ze studeert in Gent.', uit:'Zuid-Afrika: hoofdletters voor en na het streepje. Een komma voor maar tussen twee zinnen.' }
  ],
  leenwoorden: [
    /* ---------- vmbo-kgt: veelgebruikte Engelse en Franse woorden ---------- */
    { n:2, w:'weekend', zin:'Het weekend was veel te kort.', uit:'Engels woord: week + end, aan elkaar' },
    { n:2, w:'computer', zin:'De computer in de klas is traag.', uit:'Engels: com-pu-ter, met een c en een u' },
    { n:2, w:'laptop', zin:'Ik neem mijn laptop mee naar school.', uit:'lap + top, zoals in het Engels' },
    { n:2, w:'printer', zin:'De printer is leeg.', uit:'print + er' },
    { n:2, w:'smartphone', zin:'Zijn smartphone viel op de grond.', uit:'smart + phone: ph voor de f-klank' },
    { n:2, w:'website', zin:'De school heeft een nieuwe website.', uit:'web + site, aan elkaar' },
    { n:2, w:'e-mail', zin:'Ik stuur je vanavond een e-mail.', uit:'met een streepje: e-mail. Zonder streepje is email iets anders: een laag glazuur' },
    { n:2, w:'selfie', zin:'We maakten een selfie bij de fontein.', uit:'self + ie aan het eind' },
    { n:2, w:'deadline', zin:'De deadline voor het werkstuk is vrijdag.', uit:'dead + line: de laatste dag dat het af moet zijn' },
    { n:2, w:'feedback', zin:'De docent gaf feedback op mijn verslag.', uit:'feed + back, aan elkaar' },
    { n:2, w:'festival', zin:'Deze zomer gaan we naar een festival.', uit:'fes-ti-val, met een v' },
    { n:2, w:'T-shirt', zin:'Hij draagt een blauw T-shirt.', uit:'met een streepje, en officieel met een hoofdletter T' },
    { n:2, w:'sandwich', zin:'Ik neem een sandwich met kaas.', uit:'sand + wich' },
    { n:2, w:'milkshake', zin:'Ze bestelde een milkshake met aardbei.', uit:'milk + shake, aan elkaar' },
    { n:2, w:'skateboard', zin:'Mijn broer gaat met zijn skateboard naar school.', uit:'skate + board' },
    { n:2, w:'keeper', zin:'De keeper stopte de bal.', uit:'Engels: keeper met ee. In het Nederlands zeg je ook doelman' },
    { n:2, w:'coach', zin:'De coach gaf ons aanwijzingen.', uit:'c-oa-ch: de oa klinkt als oo, de ch als tsj' },
    { n:2, w:'puzzel', zin:'Oma maakt elke dag een puzzel.', uit:'Engels puzzle, maar in het Nederlands puzzel: met el aan het eind' },
    { n:2, w:'biefstuk', zin:'Bij het eten was er biefstuk.', uit:'van het Engelse beefsteak, in het Nederlands geschreven als bief + stuk' },
    { n:2, w:'cake', zin:'Mijn moeder bakte een cake.', uit:'Engels woord: je zegt keek, maar schrijft cake' },
    { n:2, w:'baby’s', zin:'De baby’s in de crèche sliepen.', uit:'Meervoud van een woord op een y na een medeklinker: apostrof + s' },
    { n:2, w:'hobby’s', zin:'Mijn hobby’s zijn tekenen en gamen.', uit:'Meervoud van hobby: y na een medeklinker, dus apostrof + s' },
    { n:2, w:'cowboys', zin:'In de film reden de cowboys door de woestijn.', uit:'Na oy komt in het meervoud alleen een s, zonder apostrof: de y staat na een klinker' },
    { n:2, w:'restaurant', zin:'We aten in een Italiaans restaurant.', uit:'Frans woord: res-tau-rant, met au en een t aan het eind' },
    { n:2, w:'bureau', zin:'Mijn bureau staat bij het raam.', uit:'Frans: eau klinkt als oo' },
    { n:2, w:'niveau', zin:'Dit boek is precies van mijn niveau.', uit:'ni-veau: ook hier eau' },
    { n:2, w:'trottoir', zin:'Fiets niet op het trottoir.', uit:'Frans: dubbele t, en oir aan het eind' },
    { n:2, w:'chauffeur', zin:'De chauffeur remde op tijd.', uit:'Frans: ch klinkt als sj, au als oo, dubbele f, eur aan het eind' },
    { n:2, w:'horloge', zin:'Ik kreeg een horloge voor mijn verjaardag.', uit:'hor-lo-ge: de g klinkt als zj' },
    { n:2, w:'paraplu', zin:'Neem een paraplu mee.', uit:'Frans woord met een u aan het eind: pa-ra-plu' },
    { n:2, w:'douche', zin:'Na het sporten gaan we onder de douche.', uit:'Frans: ou klinkt als oe, en che aan het eind' },
    { n:2, w:'garage', zin:'De auto staat in de garage.', uit:'ga-ra-ge: de tweede g klinkt als zj' },
    { n:2, w:'bagage', zin:'Onze bagage paste niet in de kofferbak.', uit:'ba-ga-ge: de laatste g klinkt als zj' },
    { n:2, w:'portemonnee', zin:'Ik ben mijn portemonnee kwijt.', uit:'Frans woord in Nederlandse spelling: porte + monnee. Portemonnaie mag ook', antwoordLijst:['portemonnee', 'portemonnaie'] },
    { n:2, w:'mayonaise', zin:'Wil je mayonaise bij je friet?', uit:'In het Nederlands met één n: mayonaise' },
    { n:2, w:'kroket', zin:'Ik haal een kroket bij de snackbar.', uit:'van het Franse croquette, in het Nederlands met k’s: kroket' },
    { n:2, w:'sjaal', zin:'Doe je sjaal om, het is koud.', uit:'Nederlandse spelling voor de sj-klank: sjaal' },
    { n:2, w:'souvenir', zin:'We kochten een souvenir in Parijs.', uit:'sou-ve-nir: ou klinkt als oe' },
    { n:2, w:'menu', zin:'Wat staat er op het menu?', uit:'Frans: menu, met een u aan het eind' },
    { n:2, w:'abonnement', zin:'Ik heb een abonnement op een tijdschrift.', uit:'a-bon-ne-ment: dubbele n' },
    { n:2, w:'champignon', zin:'Er ligt een grote champignon op de pizza.', uit:'cham-pig-non: ch klinkt als sj, gn als nj' },

    /* ---------- havo en vwo: Engelse werkwoorden, apostrof en accenten ---------- */
    { n:3, w:'gedownload', zin:'Ik heb het spel gedownload.', uit:'Downloaden: de stam download eindigt al op een d, dus ge + download zonder extra d' },
    { n:3, w:'geüpdatet', zin:'De app is geüpdatet.', uit:'ge + update + t: de t van ’t kofschip, en een trema tussen de e en de u' },
    { n:3, w:'gecheckt', zin:'Heb je je mail gecheckt?', uit:'ge + check + t: de k-klank zit in ’t kofschip' },
    { n:3, w:'gedeletet', zin:'Ik heb het bericht gedeletet.', uit:'ge + delete + t: de e van delete blijft staan, en de t van ’t kofschip erachter' },
    { n:3, w:'gesaved', zin:'Heb je het bestand gesaved?', uit:'Saven: de stam save eindigt op een v-klank, die niet in ’t kofschip zit: ge + save + d' },
    { n:3, w:'gemaild', zin:'Ik heb de docent gemaild.', uit:'ge + mail + d: de l zit niet in ’t kofschip' },
    { n:3, w:'gegoogeld', zin:'Ik heb het even gegoogeld.', uit:'Het werkwoord is googelen, in Nederlandse spelling: ge + googel + d' },
    { n:3, w:'gestrest', zin:'Voor de toets was ze gestrest.', uit:'Stressen: de stam is stres (één s aan het eind), en de s zit in ’t kofschip: ge + stres + t' },
    { n:3, w:'gefinisht', zin:'Zij is als eerste gefinisht.', uit:'Finishen: de sj-klank zit in ’t kofschip: ge + finish + t' },
    { n:3, w:'gecrasht', zin:'Mijn laptop is gecrasht.', uit:'Crashen: de sj-klank zit in ’t kofschip: ge + crash + t' },
    { n:3, w:'gescoord', zin:'Hij heeft twee keer gescoord.', uit:'Scoren: de stam scoor heeft een lange o, en de r zit niet in ’t kofschip: ge + scoor + d' },
    { n:3, w:'geshopt', zin:'We hebben de hele middag geshopt.', uit:'Shoppen: de stam shop, en de p zit in ’t kofschip: ge + shop + t' },
    { n:3, w:'gefotoshopt', zin:'Die foto is gefotoshopt.', uit:'Fotoshoppen: ge + fotoshop + t, want de p zit in ’t kofschip' },
    { n:3, w:'gerelaxt', zin:'Na de toetsweek hebben we lekker gerelaxt.', uit:'Relaxen: de x klinkt als ks, en de s zit in ’t kofschip: ge + relax + t' },
    { n:3, w:'gebarbecued', zin:'Gisteren hebben we in de tuin gebarbecued.', uit:'Barbecueën: de stam barbecue eindigt op een klinker, en die zit niet in ’t kofschip: ge + barbecue + d' },
    { n:3, w:'gechat', zin:'We hebben de hele avond gechat.', uit:'Chatten: de stam chat eindigt al op een t, dus ge + chat zonder extra t' },
    { n:3, w:'gebrainstormd', zin:'We hebben in groepjes gebrainstormd.', uit:'Brainstormen: de m zit niet in ’t kofschip: ge + brainstorm + d' },
    { n:3, w:'gecoacht', zin:'Ons team wordt gecoacht door een oud-speler.', uit:'Coachen: de tsj-klank zit in ’t kofschip: ge + coach + t' },
    { n:3, w:'sprintte', zin:'Hij sprintte naar de finish.', uit:'Verleden tijd van sprinten: de stam sprint eindigt op een t, en die zit in ’t kofschip: sprint + te' },
    { n:3, w:'gescand', zin:'Ik heb mijn huiswerk gescand.', uit:'Scannen: de stam scan, en de n zit niet in ’t kofschip: ge + scan + d' },
    { n:3, w:'cameraatje', zin:'Ze kocht een klein cameraatje.', uit:'camera + tje: de a wordt verdubbeld en er komt geen apostrof' },
    { n:3, w:'baby’tje', zin:'Wat een lief baby’tje.', uit:'Verkleinwoord van baby: apostrof + tje, zodat je de y blijft lezen als ie' },
    { n:3, w:'sms’je', zin:'Ik stuur je straks een sms’je.', uit:'Verkleinwoord van een afkorting: apostrof + je' },
    { n:3, w:'e-mailtje', zin:'Stuur me even een e-mailtje.', uit:'e-mail + tje: het streepje blijft staan' },
    { n:3, w:'party’s', zin:'Deze zomer zijn er veel party’s.', uit:'Meervoud van party: y na een medeklinker, dus apostrof + s' },
    { n:3, w:'cd’s', zin:'Mijn vader heeft nog honderden cd’s.', uit:'Meervoud van een afkorting: apostrof + s, en cd met kleine letters' },
    { n:3, w:'crème brûlée', zin:'Als toetje nam ze crème brûlée.', uit:'Frans gerecht: è in crème, een dakje op de û en é aan het eind' },
    { n:3, w:'déjà vu', zin:'Ik had even een déjà vu.', uit:'Frans: é in déjà, à aan het eind, en twee losse woorden' },
    { n:3, w:'rendez-vous', zin:'Ze hadden een rendez-vous bij de fontein.', uit:'Frans: twee delen met een streepje ertussen' },
    { n:3, w:'première', zin:'De première van de film was in Amsterdam.', uit:'Frans: pre-miè-re, met è' },
    { n:3, w:'carrière', zin:'Ze maakte carrière als journalist.', uit:'Frans: dubbele r, en è' },
    { n:3, w:'tête-à-tête', zin:'Ze hadden een tête-à-tête in het café.', uit:'Frans: een dakje op elke ê, à in het midden, streepjes ertussen' },
    { n:3, w:'reçu', zin:'Bewaar het reçu van de garderobe.', uit:'Frans: een c met een haakje (ç), zodat hij klinkt als s' },
    { n:3, w:'café’s', zin:'In de binnenstad zijn veel café’s.', uit:'Meervoud van café: het eindigt op een klinker met een accent, dus apostrof + s' },
    { n:3, w:'jus d’orange', zin:'Bij het ontbijt drink ik jus d’orange.', uit:'Frans: jus, en dan d’orange met een apostrof' }
  ],
  /* ---------- het doorlopende dictee: acht teksten per niveau ---------- */
  teksten: [
    { id:'t-bb-01', oud:5, n:1, titel:'De eerste schooldag', zinnen:[
      { z:'Vandaag begint het nieuwe schooljaar.', u:'begint: het schooljaar is een het, dus stam + t.' },
      { z:'Ik fiets samen met Daan naar school.', u:'fiets: bij ik alleen de stam. Daan is een naam: hoofdletter.' },
      { z:'Bij de ingang wacht onze mentor.', u:'wacht: de stam eindigt al op een t, dus er komt geen t bij.' },
      { z:'Zij geeft iedereen een hand.', u:'geeft: zij, dus stam + t. De stam is geef, met een f.' },
      { z:'Wordt dit een leuk jaar?', u:'Wordt: het onderwerp is dit, niet jij. Dus stam + t. Een vraag: vraagteken.' },
      { z:'Ik denk van wel, want onze mentor is heel aardig.', u:'Een komma voor want. aardig: ig aan het eind.' },
      { z:'In de pauze eet ik mijn brood op het plein.', u:'eet: bij ik alleen de stam. brood met een d, want het meervoud is broden.' },
      { z:'Daar ontmoet ik een jongen uit Utrecht.', u:'ontmoet: de stam eindigt al op een t. Utrecht is een plaatsnaam: hoofdletter.' },
      { z:'Hij heet Yusuf en zit ook in mijn klas.', u:'heet en zit: de stam eindigt al op een t. Yusuf is een naam: hoofdletter.' },
      { z:'Na school fietsen we samen naar huis.', u:'fietsen: bij we het hele werkwoord.' } ] },
    { id:'t-bb-02', oud:5, n:1, titel:'Op de voetbalclub', zinnen:[
      { z:'Mijn broer voetbalt bij een club in Almere.', u:'voetbalt: hij, dus stam + t. Almere is een plaatsnaam: hoofdletter.' },
      { z:'Elke zaterdag speelt hij een wedstrijd.', u:'zaterdag met een kleine letter; wedstrijd met ij en een d.' },
      { z:'Vorige week scoorde hij twee keer.', u:'scoorde: de r zit niet in ’t kofschip, dus scoor + de.' },
      { z:'Mijn vader stond langs de lijn en juichte hard.', u:'juichte: de ch zit in ’t kofschip, dus juich + te.' },
      { z:'Vind jij voetbal ook zo leuk?', u:'Vind: jij staat achter het werkwoord, dus geen t.' },
      { z:'Ik vind het eigenlijk nog leuker om te kijken.', u:'vind: bij ik alleen de stam. eigenlijk met ei en lijk.' },
      { z:'Na de wedstrijd drinken we limonade in de kantine.', u:'limonade: li-mo-na-de. kantine met ine aan het eind.' },
      { z:'De trainer geeft elke speler een compliment.', u:'geeft: de trainer is een hij, dus stam + t. compliment met een c.' },
      { z:'Volgend jaar word ik misschien zelf lid.', u:'word: bij ik alleen de stam. lid met een d, want het meervoud is leden.' },
      { z:'Dan krijg ik een shirt met mijn eigen nummer.', u:'shirt: een Engels woord. krijg: bij ik alleen de stam.' } ] },
    { id:'t-bb-03', oud:5, n:1, titel:'Een dag naar het strand', zinnen:[
      { z:'Gisteren was het heel warm en zonnig.', u:'zonnig: dubbele n na de korte o, en ig aan het eind.' },
      { z:'Wij gingen met de trein naar Zandvoort.', u:'Zandvoort is een plaatsnaam: hoofdletter. Zand schrijf je met een d.' },
      { z:'Mijn zusje bouwde een groot zandkasteel.', u:'bouwde: de w zit niet in ’t kofschip, dus bouw + de.' },
      { z:'Ik zwom in de zee en at een ijsje.', u:'ijsje: met ij, en het verkleinwoord van ijs.' },
      { z:'Om zes uur reden we met de trein terug naar huis.', u:'reden: de verleden tijd van rijden is onregelmatig. Wij reden.' },
      { z:'In de trein viel mijn zusje in slaap.', u:'viel: de verleden tijd van vallen.' },
      { z:'Thuis zat er nog overal zand in mijn tas.', u:'zat: de verleden tijd van zitten. zand met een d.' },
      { z:'Mijn moeder schudde alles uit in de tuin.', u:'schudde: de stam schud eindigt op een d, en daar komt de achter: schudde.' },
      { z:'Daarna aten we patat met appelmoes.', u:'patat met een t aan het eind. appelmoes: dubbele p.' },
      { z:'Volgend weekend willen we weer naar zee.', u:'weekend: een Engels woord met ee. zee met ee.' } ] },
    { id:'t-bb-04', oud:5, n:1, titel:'Mijn hond Bobby', zinnen:[
      { z:'Wij hebben een hond die Bobby heet.', u:'heet: de stam van heten eindigt al op een t, dus geen extra t. Bobby is een naam.' },
      { z:'Hij is bruin met een witte vlek op zijn kop.', u:'witte: dubbele t, want wit heeft een korte i: wit-te.' },
      { z:'Elke ochtend loopt mijn moeder een rondje met hem.', u:'loopt: mijn moeder is een zij, dus stam + t.' },
      { z:'Als het regent, wordt Bobby helemaal vies.', u:'regent en wordt: het en Bobby zijn allebei enkelvoud, dus stam + t.' },
      { z:'Daarna moet hij in bad.', u:'bad: je hoort een t, maar je schrijft een d, want het meervoud is baden.' },
      { z:'Dat vindt hij helemaal niet leuk.', u:'vindt: hij, dus stam vind + t.' },
      { z:'Hij rent dan snel weg en verstopt zich onder de tafel.', u:'rent en verstopt: hij, dus stam + t.' },
      { z:'Mijn broer lokt hem met een koekje.', u:'lokt: stam lok + t. koekje met oe.' },
      { z:'Na het bad schudt Bobby zich helemaal uit.', u:'schudt: Bobby is een hij, dus stam schud + t.' },
      { z:'Dan is iedereen in de badkamer nat.', u:'badkamer: bad + kamer, aan elkaar. nat met één t.' } ] },
    { id:'t-bb-05', oud:5, n:1, titel:'De verjaardag van oma', zinnen:[
      { z:'Mijn oma werd gisteren zeventig jaar.', u:'werd: de verleden tijd van worden, altijd met een d.' },
      { z:'We vierden het feest in een restaurant in Deventer.', u:'vierden: vier + den, want de r zit niet in ’t kofschip. Deventer is een plaatsnaam.' },
      { z:'Mijn neefje Sem zong een liedje voor haar.', u:'Sem is een naam: hoofdletter. Liedje met ie en een d.' },
      { z:'Oma kreeg een mooie bos bloemen en een cadeau.', u:'cadeau: een Frans woord, eau klinkt als oo.' },
      { z:'Ze vond het een heel gezellige dag.', u:'gezellige: dubbele l, en ig + e.' },
      { z:'Na het eten hield opa een korte toespraak.', u:'hield: de verleden tijd van houden, met een d.' },
      { z:'Hij vertelde hoe hij oma had leren kennen.', u:'vertelde: vertel + de, want de l zit niet in ’t kofschip.' },
      { z:'Dat was op een dansfeest in Zwolle.', u:'Zwolle is een plaatsnaam: hoofdletter.' },
      { z:'Iedereen klapte hard en oma moest een beetje huilen.', u:'klapte: klap + te, want de p zit in ’t kofschip.' },
      { z:'Om tien uur brachten we haar naar huis.', u:'brachten: de verleden tijd van brengen is onregelmatig.' } ] },
    { id:'t-bb-06', oud:5, n:1, titel:'Ziek thuis', zinnen:[
      { z:'Vanochtend voelde ik me helemaal niet lekker.', u:'voelde: de l zit niet in ’t kofschip, dus voel + de.' },
      { z:'Mijn moeder belde naar school.', u:'belde: de l zit niet in ’t kofschip, dus bel + de.' },
      { z:'Ik bleef de hele dag in bed liggen.', u:'bed: met een d, want het meervoud is bedden.' },
      { z:'Mijn vriendin Lotte bracht me een tijdschrift.', u:'Lotte is een naam: hoofdletter. Tijdschrift met ij en een d.' },
      { z:'Morgen word ik hopelijk weer beter.', u:'word: bij ik alleen de stam, ook als ik achter het werkwoord staat.' },
      { z:'Vanavond kookt mijn vader soep voor me.', u:'kookt: mijn vader is een hij, dus stam + t. soep met een p.' },
      { z:'Ik drink ook veel thee met honing.', u:'drink: bij ik alleen de stam. thee met th.' },
      { z:'De dokter zei dat ik griep heb.', u:'zei: de verleden tijd van zeggen. griep met ie.' },
      { z:'Ik moet vooral veel slapen en rusten.', u:'slapen met één a, want sla-pen: de a staat aan het eind van de lettergreep.' },
      { z:'Hopelijk kan ik vrijdag weer naar school.', u:'vrijdag met een kleine letter en ij.' } ] },
    { id:'t-bb-07', oud:5, n:1, titel:'Naar de dierentuin', zinnen:[
      { z:'Onze klas ging vorige week naar de dierentuin in Emmen.', u:'Emmen is een plaatsnaam: hoofdletter.' },
      { z:'We zagen olifanten, apen en een ijsbeer.', u:'ijsbeer: ijs met ij. Komma’s tussen wat je opnoemt, niet voor en.' },
      { z:'De leeuw lag lui in de zon.', u:'leeuw: eeuw aan het eind.' },
      { z:'Bij de apen moesten we heel hard lachen.', u:'lachen: met ch.' },
      { z:'Wanneer gaan we weer?', u:'Een vraag: vraagteken aan het eind.' },
      { z:'De juf zei dat we volgend jaar misschien weer gaan.', u:'misschien: mis + schien.' },
      { z:'In de bus terug zongen we liedjes.', u:'zongen: de verleden tijd van zingen. liedjes met ie.' },
      { z:'Mijn vriend Ravi viel onderweg in slaap.', u:'Ravi is een naam: hoofdletter. viel: de verleden tijd van vallen.' },
      { z:'Thuis vertelde ik alles over de leeuw.', u:'vertelde: vertel + de. leeuw met eeuw.' },
      { z:'Ik wil later dierenverzorger worden.', u:'wil: bij ik alleen de stam. dierenverzorger aan elkaar.' } ] },
    { id:'t-bb-08', oud:5, n:1, titel:'Koken met papa', zinnen:[
      { z:'Op woensdag kookt mijn vader altijd.', u:'woensdag met een kleine letter; kookt: stam + t.' },
      { z:'Vandaag maakt hij pannenkoeken met spek.', u:'pannenkoeken: pannen + koeken.' },
      { z:'Ik help hem met het beslag.', u:'help: bij ik alleen de stam.' },
      { z:'De eerste pannenkoek mislukte helemaal.', u:'mislukte: de k zit in ’t kofschip, dus misluk + te.' },
      { z:'Gelukkig smaakte de rest heerlijk.', u:'gelukkig: dubbele k. smaakte: smaak + te. heerlijk: lijk met ij.' },
      { z:'Mijn zus doet er altijd stroop op.', u:'doet: mijn zus is een zij, dus stam + t.' },
      { z:'Ik eet ze het liefst met poedersuiker.', u:'poedersuiker: poeder + suiker, aan elkaar.' },
      { z:'Na het eten ruimen we samen de keuken op.', u:'ruimen: bij we het hele werkwoord.' },
      { z:'Mijn vader wast af en ik droog de pannen.', u:'wast: stam was + t. droog: bij ik alleen de stam.' },
      { z:'Volgende week wil ik zelf pannenkoeken bakken.', u:'bakken: dubbele k, want de a is kort.' } ] },

    { id:'t-kgt-01', oud:6, n:2, titel:'Het schoolkamp', zinnen:[
      { z:'In september gingen we met de hele klas op kamp naar Texel.', u:'september met een kleine letter, Texel met een hoofdletter.' },
      { z:'Toen we aankwamen, regende het ontzettend hard.', u:'regende: regen + de. ontzettend: dubbele t.' },
      { z:'Gelukkig had onze mentor extra regenjassen geregeld.', u:'geregeld: ge + regel + d, want de l zit niet in ’t kofschip.' },
      { z:'De volgende dag scheen de zon en fietsten we over het eiland.', u:'fietsten: verleden tijd meervoud, fiets + ten. eiland met ei.' },
      { z:'’s Avonds vertelde iemand een spannend verhaal bij het kampvuur.', u:'Begint de zin met ’s, dan krijgt het woord erna de hoofdletter: ’s Avonds. vertelde: vertel + de.' },
      { z:'Wordt het volgend jaar weer Texel?', u:'Wordt: het onderwerp is het, niet jij. Dus stam + t.' },
      { z:'Onze mentor weet het nog niet, maar ik hoop het wel.', u:'weet: de stam eindigt al op een t. Een komma voor maar.' },
      { z:'Op de laatste avond organiseerden we een bonte avond.', u:'organiseerden: organiseer + den, want de r zit niet in ’t kofschip.' },
      { z:'Twee jongens uit mijn klas deden onze leraar na.', u:'deden: de verleden tijd van doen.' },
      { z:'Iedereen lag dubbel van het lachen, ook de leraar zelf.', u:'dubbel met dubbele b. Een komma voor wat er nog bij komt: ook de leraar zelf.' } ] },
    { id:'t-kgt-02', oud:6, n:2, titel:'Een bijbaantje', zinnen:[
      { z:'Sinds de zomer werk ik op zaterdag in een supermarkt.', u:'werk: bij ik alleen de stam. zaterdag met een kleine letter.' },
      { z:'Ik vul de schappen en help klanten die iets zoeken.', u:'vul en help: bij ik alleen de stam.' },
      { z:'Vorige week vroeg een oudere meneer waar de koffie stond.', u:'koffie: dubbele f en ie.' },
      { z:'Ik liep met hem mee en wees het pak koffie aan.', u:'wees: de verleden tijd van aanwijzen is onregelmatig: ik wees aan.' },
      { z:'Hij bedankte me en zei dat ik erg behulpzaam was.', u:'bedankte: de k zit in ’t kofschip, dus bedank + te.' },
      { z:'Het verdiende geld spaar ik voor een scooter.', u:'verdiende: het voltooid deelwoord verdiend met een e. spaar: bij ik alleen de stam.' },
      { z:'Ik heb al bijna genoeg gespaard.', u:'gespaard: ge + spaar + d, want de r zit niet in ’t kofschip.' },
      { z:'Mijn ouders betalen de helft van de verzekering.', u:'betalen: meervoud, het hele werkwoord. verzekering met een z.' },
      { z:'Wel moet ik eerst mijn rijbewijs halen.', u:'rijbewijs: rij en wijs, allebei met ij.' },
      { z:'Het examen doe ik in de kerstvakantie.', u:'examen met een x. kerstvakantie aan elkaar en met een kleine letter.' } ] },
    { id:'t-kgt-03', oud:5, n:2, titel:'De zoekgeraakte sleutel', zinnen:[
      { z:'Toen Mila gisteren thuiskwam, kon ze haar sleutel niet vinden.', u:'Mila is een naam: hoofdletter. thuiskwam: aan elkaar.' },
      { z:'Ze zocht in haar tas, in haar jaszak en zelfs in haar schoenen.', u:'zocht: de verleden tijd van zoeken is onregelmatig. Komma’s in de opsomming.' },
      { z:'Haar ouders werkten nog tot zes uur.', u:'werkten: werk + ten, want de k zit in ’t kofschip.' },
      { z:'Daarom belde ze haar buurvrouw, die een reservesleutel had.', u:'belde: bel + de. buurvrouw met ouw.' },
      { z:'De gezochte sleutel lag de volgende ochtend gewoon op haar bureau.', u:'gezochte: gezocht + e. bureau: een Frans woord met eau.' },
      { z:'Ze had hem daar zelf neergelegd en was het vergeten.', u:'neergelegd: neer + ge + leg + d, want de g zit niet in ’t kofschip.' },
      { z:'Haar broer vond het heel grappig.', u:'vond: de verleden tijd van vinden. grappig: dubbele p.' },
      { z:'Nu hangt er een haakje naast de voordeur.', u:'hangt: stam hang + t. voordeur aan elkaar.' },
      { z:'Daar hangt Mila haar sleutel elke dag aan.', u:'hangt: Mila is een zij, dus stam + t.' },
      { z:'Zo raakt ze hem hopelijk nooit meer kwijt.', u:'raakt: stam raak + t. kwijt met ij.' } ] },
    { id:'t-kgt-04', oud:6, n:2, titel:'Een uitstapje naar Brussel', zinnen:[
      { z:'Vorig jaar reisden we met de trein naar Brussel.', u:'reisden: het hele werkwoord is reizen, met een z. Die zit niet in ’t kofschip, dus reis + den.' },
      { z:'Mijn vader had de reis maanden van tevoren gepland.', u:'gepland: ge + plan + d. van tevoren: twee woorden.' },
      { z:'In het centrum bezochten we een museum over stripverhalen.', u:'centrum: de c klinkt hier als s. museum: mu-se-um.' },
      { z:'Daarna aten we echte Belgische wafels op een terras.', u:'Belgische komt van België: hoofdletter.' },
      { z:'Mijn zusje kocht een doos bonbons voor oma.', u:'bonbons: Frans woord, bon + bons.' },
      { z:'Wanneer gaan we weer naar België?', u:'België: hoofdletter en een trema op de e.' },
      { z:'Mijn moeder wil volgend jaar naar Antwerpen.', u:'wil: willen krijgt bij hij of zij geen t. Antwerpen is een plaatsnaam: hoofdletter.' },
      { z:'Daar schijnt een prachtig station te zijn.', u:'schijnt: stam schijn + t. prachtig met ig.' },
      { z:'Mijn broertje wil vooral naar de dierentuin daar.', u:'broertje: broer + tje. dierentuin aan elkaar.' },
      { z:'Ik hoop dat we er met de trein naartoe gaan.', u:'naartoe: aan elkaar. hoop: bij ik alleen de stam.' } ] },
    { id:'t-kgt-05', oud:6, n:2, titel:'Een spreekbeurt', zinnen:[
      { z:'Vorige week hield ik een spreekbeurt over haaien.', u:'hield: de verleden tijd van houden, met een d.' },
      { z:'Ik had me goed voorbereid, maar toch was ik zenuwachtig.', u:'voorbereid: de stam bereid eindigt al op een d, dus geen extra d.' },
      { z:'Mijn stem trilde een beetje toen ik begon.', u:'trilde: de l zit niet in ’t kofschip, dus tril + de.' },
      { z:'Gelukkig luisterde de klas heel aandachtig.', u:'luisterde: luister + de. aandachtig: aan + dacht + ig.' },
      { z:'Na afloop stelden mijn klasgenoten veel vragen.', u:'stelden: stel + den, want de l zit niet in ’t kofschip.' },
      { z:'De juf vond het een geslaagde presentatie.', u:'geslaagde: geslaagd + e.' },
      { z:'Ik kreeg een acht en was daar erg blij mee.', u:'kreeg: de verleden tijd van krijgen.' },
      { z:'Thuis vertelde ik mijn ouders hoe het was gegaan.', u:'vertelde: vertel + de, want de l zit niet in ’t kofschip.' },
      { z:'Mijn vader had vroeger ook een spreekbeurt over haaien gehouden.', u:'gehouden: het voltooid deelwoord van houden.' },
      { z:'Volgend jaar kies ik een onderwerp over walvissen.', u:'walvissen: dubbele s, want de i is kort. kies: bij ik alleen de stam.' } ] },
    { id:'t-kgt-06', oud:6, n:2, titel:'De verhuizing', zinnen:[
      { z:'Vorige maand verhuisden wij naar een huis in Amersfoort.', u:'verhuisden: verhuizen heeft een z, die niet in ’t kofschip zit: verhuis + den.' },
      { z:'Mijn oom had een grote bus gehuurd.', u:'gehuurd: ge + huur + d, want de r zit niet in ’t kofschip.' },
      { z:'Alle dozen waren binnen een ochtend ingeladen.', u:'ingeladen: het voltooid deelwoord van laden is geladen.' },
      { z:'Mijn nieuwe kamer is groter dan de oude.', u:'groter: gro-ter, één o want de lettergreep eindigt op de o.' },
      { z:'Ik heb de muren zelf lichtblauw geverfd.', u:'geverfd: het hele werkwoord is verven, met een v. Die zit niet in ’t kofschip: ge + verf + d.' },
      { z:'De buren lijken heel aardig.', u:'lijken: met ij.' },
      { z:'Ze brachten ons de eerste dag een taart.', u:'brachten: de verleden tijd van brengen is onregelmatig.' },
      { z:'Hun dochter zit bij mij op school.', u:'zit: de stam eindigt al op een t, dus er komt geen t bij.' },
      { z:'We fietsen nu elke ochtend samen.', u:'fietsen: bij we het hele werkwoord.' },
      { z:'Ik mis mijn oude buurt, maar ik voel me hier al thuis.', u:'mis en voel: bij ik alleen de stam. Een komma voor maar.' } ] },
    { id:'t-kgt-07', oud:6, n:2, titel:'De sportdag', zinnen:[
      { z:'Op de laatste vrijdag voor de vakantie hadden we een sportdag.', u:'vrijdag met een kleine letter. vakantie met tie.' },
      { z:'Er werden allerlei wedstrijden gehouden op het veld achter de school.', u:'wedstrijden: wed + strijden, met ij.' },
      { z:'Mijn team won het touwtrekken met gemak.', u:'touwtrekken: touw met ouw, en dubbele k.' },
      { z:'Bij de estafette struikelde Jesse vlak voor de finish.', u:'estafette: dubbele t. struikelde: struikel + de. Jesse is een naam.' },
      { z:'Hij krabbelde snel op en rende toch nog als eerste over de streep.', u:'rende: ren + de, want de n zit niet in ’t kofschip.' },
      { z:'De behaalde medaille hangt nu boven zijn bed.', u:'behaalde: behaald + e. medaille: dubbele l.' },
      { z:'Zijn ouders waren ontzettend trots op hem.', u:'ontzettend: dubbele t. trots met ts.' },
      { z:'Aan het eind van de dag kregen we allemaal een ijsje.', u:'kregen: de verleden tijd van krijgen. ijsje met ij.' },
      { z:'Onze gymleraar bedankte iedereen voor de inzet.', u:'bedankte: bedank + te, want de k zit in ’t kofschip.' },
      { z:'Volgend jaar doe ik zeker weer mee.', u:'doe: bij ik alleen de stam.' } ] },
    { id:'t-kgt-08', oud:6, n:2, titel:'Een lekke band', zinnen:[
      { z:'Op weg naar school kreeg ik een lekke band.', u:'lekke: dubbele k, want lek heeft een korte e.' },
      { z:'Ik belde meteen mijn vader, want ik wilde niet te laat komen.', u:'belde: bel + de. Een komma voor want.' },
      { z:'Hij bracht me met de auto en nam mijn fiets mee.', u:'bracht: de verleden tijd van brengen is onregelmatig.' },
      { z:'’s Middags plakte hij de band in de schuur.', u:'Begint de zin met ’s, dan krijgt het woord erna de hoofdletter: ’s Middags. plakte: plak + te.' },
      { z:'Nu rijdt mijn fiets weer als nieuw.', u:'rijdt: mijn fiets is een hij, dus stam rijd + t.' },
      { z:'Heb jij al eens een band geplakt?', u:'geplakt: ge + plak + t, want de k zit in ’t kofschip.' },
      { z:'Het is makkelijker dan je denkt.', u:'makkelijker: dubbele k. denkt: je staat vóór het werkwoord, dus stam + t.' },
      { z:'Je zoekt eerst het gaatje met een emmer water.', u:'zoekt: je staat vóór het werkwoord, dus stam + t. emmer met dubbele m.' },
      { z:'Daarna maak je de band droog en plak je er een pleister op.', u:'maak je en plak je: je staat achter het werkwoord, dus geen t.' },
      { z:'Mijn vader heeft beloofd dat hij het me leert.', u:'beloofd: het hele werkwoord is beloven, met een v. Die zit niet in ’t kofschip: be + loof + d.' } ] },

    { id:'t-hv-01', oud:6, n:3, titel:'De Gouden Eeuw', zinnen:[
      { z:'In de zeventiende eeuw behoorde de Republiek tot de rijkste landen van Europa.', u:'zeventiende eeuw met kleine letters; de Republiek is de naam van het land toen: hoofdletter.' },
      { z:'Schepen van de VOC voeren naar Azië om specerijen te halen.', u:'voeren: de verleden tijd meervoud van varen. Azië met een trema. specerijen met ij.' },
      { z:'Rijke families in Amsterdam verdienden er enorm veel geld mee.', u:'verdienden: verdien + den, want de n zit niet in ’t kofschip.' },
      { z:'Tegelijkertijd leefden veel mensen in armoede.', u:'leefden: het hele werkwoord is leven, met een v. Die zit niet in ’t kofschip: leef + den.' },
      { z:'Schilders als Rembrandt en Vermeer werden wereldberoemd.', u:'wereldberoemd: wereld met een d, en beroemd met een d.' },
      { z:'Wordt die periode terecht de Gouden Eeuw genoemd?', u:'Wordt: het onderwerp is die periode, dus stam + t. De Gouden Eeuw krijgt hoofdletters.' },
      { z:'Veel historici vinden die naam tegenwoordig te rooskleurig.', u:'historici: het meervoud van historicus. rooskleurig: roos + kleurig.' },
      { z:'De rijkdom was namelijk deels gebaseerd op slavenhandel.', u:'gebaseerd: ge + baseer + d, want de r zit niet in ’t kofschip.' },
      { z:'Daarom spreken musea nu liever over de zeventiende eeuw.', u:'musea: het meervoud van museum.' },
      { z:'Zo wordt ook de schaduwkant van die tijd zichtbaar.', u:'wordt: het onderwerp is de schaduwkant, dus stam + t. zichtbaar: zicht + baar.' } ] },
    { id:'t-hv-02', oud:6, n:3, titel:'Een debat in de klas', zinnen:[
      { z:'Tijdens de les maatschappijleer hielden we een debat over mobiele telefoons.', u:'maatschappijleer met ij. hielden: de verleden tijd van houden.' },
      { z:'De ene groep vond dat telefoons op school verboden moesten worden.', u:'verboden: het voltooid deelwoord van verbieden.' },
      { z:'De andere groep beweerde dat je ze juist goed kunt gebruiken bij het leren.', u:'beweerde: beweer + de, want de r zit niet in ’t kofschip.' },
      { z:'Iedereen bereidde zijn argumenten zorgvuldig voor.', u:'bereidde: de stam bereid eindigt al op een d; in de verleden tijd komt daar de achter: bereidde.' },
      { z:'Uiteindelijk stemde de klas over het beste betoog.', u:'uiteindelijk: ui, ei en lijk. stemde: stem + de.' },
      { z:'Het verschil bleek maar twee stemmen te zijn.', u:'verschil: één l aan het eind, stemmen met dubbele m.' },
      { z:'De verliezende groep accepteerde de uitslag sportief.', u:'accepteerde: accepteer + de. sportief met een f.' },
      { z:'Onze docent prees vooral de goed onderbouwde argumenten.', u:'prees: de verleden tijd van prijzen. onderbouwde: onderbouwd + e.' },
      { z:'Volgens haar hadden beide groepen serieus onderzoek gedaan.', u:'serieus met eu. onderzoek aan elkaar.' },
      { z:'Volgende maand debatteren we over het klimaatbeleid.', u:'debatteren: dubbele t. klimaatbeleid aan elkaar.' } ] },
    { id:'t-hv-03', oud:6, n:3, titel:'De watersnood', zinnen:[
      { z:'Tijdens de watersnood stroomden grote delen van Zeeland onder.', u:'stroomden: stroom + den. Zeeland is een naam: hoofdletter.' },
      { z:'De dijken waren niet sterk genoeg en braken op tientallen plaatsen door.', u:'dijken met ij.' },
      { z:'Veel mensen vluchtten naar de zolder of het dak van hun huis.', u:'vluchtten: de stam vlucht eindigt op een t, en in de verleden tijd komt daar ten achter: vluchtten.' },
      { z:'Hulpverleners uit het hele land schoten te hulp.', u:'hulpverleners: aan elkaar.' },
      { z:'Daarna besloot de regering om de kust beter te beschermen.', u:'besloot: de verleden tijd van besluiten is onregelmatig.' },
      { z:'Zo ontstonden de Deltawerken.', u:'De Deltawerken is een naam: hoofdletter.' },
      { z:'Het duurde tientallen jaren voordat alles klaar was.', u:'duurde: duur + de. tientallen: dubbele l.' },
      { z:'De Oosterscheldekering is misschien wel het bekendste onderdeel.', u:'Oosterscheldekering is een naam: hoofdletter, en aan elkaar.' },
      { z:'Bij zware storm kunnen de schuiven daar worden gesloten.', u:'gesloten: het voltooid deelwoord van sluiten.' },
      { z:'Ingenieurs uit de hele wereld komen het bouwwerk bestuderen.', u:'ingenieurs: in-ge-nieurs, met ie en eu.' } ] },
    { id:'t-hv-04', oud:6, n:3, titel:'Een stage in het ziekenhuis', zinnen:[
      { z:'Tijdens mijn maatschappelijke stage werkte ik twee weken in een ziekenhuis.', u:'maatschappelijke: ij in maatschappij en in lijk.' },
      { z:'Ik bracht patiënten koffie en praatte met hen als ze zich verveelden.', u:'patiënten met een trema. praatte: praat + te. verveelden: verveel + den.' },
      { z:'Een oudere mevrouw vertelde me over haar jeugd in Indonesië.', u:'vertelde: vertel + de. Indonesië met een hoofdletter en een trema.' },
      { z:'Ze was als kind met de boot naar Nederland gekomen.', u:'Nederland met een hoofdletter.' },
      { z:'Haar verhaal heeft me erg aan het denken gezet.', u:'gezet: de stam zet eindigt al op een t, dus geen extra t.' },
      { z:'Wordt dit misschien later mijn beroep?', u:'Wordt: het onderwerp is dit, dus stam + t. misschien: mis + schien.' },
      { z:'Ik twijfel nog tussen verpleegkundige en fysiotherapeut.', u:'twijfel: bij ik alleen de stam. fysiotherapeut met y en th.' },
      { z:'Mijn mentor raadde me aan om een open dag te bezoeken.', u:'raadde: de stam raad eindigt op een d, en daar komt de achter: raadde.' },
      { z:'Die heb ik inmiddels voor volgende maand gepland.', u:'gepland: ge + plan + d. inmiddels: dubbele d.' },
      { z:'Ik ben benieuwd wat ik daar allemaal zal ontdekken.', u:'benieuwd: be + nieuw + d. ontdekken: dubbele k.' } ] },
    { id:'t-hv-05', oud:6, n:3, titel:'De boekdrukkunst', zinnen:[
      { z:'In de vijftiende eeuw ontwikkelde Johannes Gutenberg een drukpers met losse letters.', u:'ontwikkelde: ontwikkel + de. vijftiende eeuw met kleine letters.' },
      { z:'Daarvoor werden boeken met de hand overgeschreven.', u:'overgeschreven: het voltooid deelwoord van overschrijven.' },
      { z:'Dat kostte veel tijd, dus boeken waren erg duur.', u:'kostte: de stam kost eindigt op een t, dus kost + te.' },
      { z:'Dankzij de drukpers verspreidden nieuwe ideeën zich snel door Europa.', u:'verspreidden: verspreid + den. ideeën met een trema.' },
      { z:'Sommige machthebbers vonden dat gevaarlijk.', u:'gevaarlijk: lijk met ij.' },
      { z:'Toch was de ontwikkeling niet meer tegen te houden.', u:'ontwikkeling: dubbele k.' },
      { z:'Binnen enkele decennia stonden er drukkerijen in honderden steden.', u:'decennia: het meervoud van decennium, met dubbele n. drukkerijen met ij.' },
      { z:'Ook Maarten Luther maakte handig gebruik van de nieuwe techniek.', u:'Maarten Luther is een naam: hoofdletters. techniek met ch en iek.' },
      { z:'Zijn pamfletten werden overal in Duitsland gelezen.', u:'pamfletten: dubbele t. Duitsland met een hoofdletter.' },
      { z:'Zo veranderde een uitvinding de hele geschiedenis van Europa.', u:'veranderde: verander + de, want de r zit niet in ’t kofschip.' } ] },
    { id:'t-hv-06', oud:6, n:3, titel:'Vrijwilligerswerk', zinnen:[
      { z:'Elke woensdagmiddag help ik bij een huiswerkklas in de bibliotheek.', u:'help: bij ik alleen de stam. woensdagmiddag met een kleine letter.' },
      { z:'De kinderen die daar komen, zitten meestal in groep zes of zeven.', u:'Een komma tussen komen en zitten: twee werkwoorden naast elkaar.' },
      { z:'Laatst worstelde een meisje met een ingewikkelde rekensom.', u:'worstelde: worstel + de. ingewikkelde: dubbele k.' },
      { z:'Ik legde haar uit hoe je breuken vereenvoudigt.', u:'vereenvoudigt: je staat hier vóór het werkwoord, dus stam + t.' },
      { z:'Toen ze het antwoord vond, straalde ze helemaal.', u:'straalde: straal + de, want de l zit niet in ’t kofschip.' },
      { z:'Zulke momenten maken het werk de moeite waard.', u:'waard: met een d, want het komt van waarde.' },
      { z:'Soms is het ook best vermoeiend.', u:'vermoeiend: oei in het midden, en een d aan het eind.' },
      { z:'Sommige kinderen zijn na een lange schooldag onrustig.', u:'onrustig: on + rustig. schooldag aan elkaar.' },
      { z:'Dan bedenk ik een spelletje zodat ze weer kunnen opletten.', u:'bedenk: bij ik alleen de stam. spelletje: dubbele l.' },
      { z:'Volgend jaar wil ik er zeker mee doorgaan.', u:'doorgaan: aan elkaar.' } ] },
    { id:'t-hv-07', oud:6, n:3, titel:'Een reis door Scandinavië', zinnen:[
      { z:'Afgelopen zomer maakten we een rondreis door Noorwegen en Zweden.', u:'maakten: maak + ten. Landen met een hoofdletter.' },
      { z:'We sliepen in een tent en kookten op een klein gasstel.', u:'kookten: kook + ten, want de k zit in ’t kofschip.' },
      { z:'De fjorden waren indrukwekkender dan ik had verwacht.', u:'indrukwekkender: dubbele k. verwacht: de stam eindigt al op een t.' },
      { z:'Op een avond zagen we het noorderlicht boven het water.', u:'noorderlicht met een kleine letter, net als de windstreken.' },
      { z:'Mijn vader fotografeerde het urenlang.', u:'fotografeerde: fotografeer + de.' },
      { z:'De foto’s die hij toen maakte, hangen nu in onze woonkamer.', u:'foto’s: apostrof + s, want foto eindigt op een o.' },
      { z:'In Stockholm bezochten we een museum over een oud oorlogsschip.', u:'bezochten: de verleden tijd van bezoeken. Stockholm met ck.' },
      { z:'Het schip was vlak na de bouw al gezonken.', u:'gezonken: het voltooid deelwoord van zinken.' },
      { z:'Pas eeuwen later werd het van de zeebodem gehaald.', u:'werd: altijd met een d. eeuwen met eeuw.' },
      { z:'Ik vond het de interessantste dag van de hele vakantie.', u:'interessantste: interessant + ste. vakantie met tie.' } ] },
    { id:'t-hv-08', oud:6, n:3, titel:'De eerste mensen op de maan', zinnen:[
      { z:'Ruim vijftig jaar geleden landde er voor het eerst een ruimteschip met mensen op de maan.', u:'landde: land + de, dus dd. maan met een kleine letter.' },
      { z:'Miljoenen mensen over de hele wereld keken ademloos naar de beelden.', u:'miljoenen: lj, net als miljoen.' },
      { z:'Neil Armstrong zette als eerste een voet op het stoffige oppervlak.', u:'zette: zet + te. stoffige: dubbele f.' },
      { z:'Zijn collega volgde hem even later.', u:'volgde: volg + de, want de g zit niet in ’t kofschip.' },
      { z:'Ze verzamelden stenen en plaatsten een Amerikaanse vlag.', u:'plaatsten: plaats + ten. Amerikaanse met een hoofdletter.' },
      { z:'Het ruimtevaartuig keerde daarna veilig terug naar de aarde.', u:'keerde: keer + de. aarde met een kleine letter.' },
      { z:'Sommige mensen geloven nog steeds dat de landing nep was.', u:'geloven: meervoud, het hele werkwoord. nep met één p.' },
      { z:'Wetenschappers hebben die theorie echter vaak weerlegd.', u:'wetenschappers: dubbele p. weerlegd: weer + leg + d.' },
      { z:'Op de maan liggen bijvoorbeeld nog steeds spiegels van de missie.', u:'bijvoorbeeld: bij + voor + beeld. missie met dubbele s.' },
      { z:'Daarmee meten onderzoekers tot op de centimeter hoe ver de maan weg is.', u:'meten: meervoud, het hele werkwoord. centimeter: de c klinkt als s.' } ] }
  ]
};

/* Een tekst op id, en de tekst van deze week: per niveau, vast voor iedereen
   in dezelfde ISO-week, zodat een docent kan zeggen "maak het dictee van deze
   week" en de hele klas dezelfde tekst krijgt. */
(function(D){
  'use strict';
  var NIV = { bb:1, kgt:2, hv:3 };
  D.WEEKZINNEN = 7;   /* zo lang is het dictee van de week */
  D.tekst = function(id){ return D.teksten.filter(function(t){ return t.id === id; })[0] || null; };
  D.isoWeek = function(datum){
    var d0 = datum instanceof Date ? datum : (datum ? new Date(datum) : new Date());
    var d = new Date(Date.UTC(d0.getFullYear(), d0.getMonth(), d0.getDate()));
    var dag = d.getUTCDay() || 7;
    d.setUTCDate(d.getUTCDate() + 4 - dag);
    var begin = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
    return { jaar: d.getUTCFullYear(), week: Math.ceil(((d - begin) / 86400000 + 1) / 7) };
  };
  D.weektekst = function(niveau, datum){
    var n = NIV[niveau] || (typeof niveau === 'number' ? niveau : 2);
    var lijst = D.teksten.filter(function(t){ return t.n === n; }).sort(function(a, b){ return a.id < b.id ? -1 : 1; });
    if (!lijst.length) return null;
    var w = D.isoWeek(datum), t = lijst[(w.jaar * 53 + w.week) % lijst.length];
    /* vanaf week 41 van 2026 de eerste zeven zinnen (tien was te lang voor een les); de weken ervoor houden hun
       korte tekst, anders klopt een oude uitslag niet meer */
    var oud = t.oud && (w.jaar < 2026 || (w.jaar === 2026 && w.week < 41)), aantal = oud ? t.oud : D.WEEKZINNEN;
    if (t.zinnen.length > aantal) t = Object.assign({}, t, { zinnen: t.zinnen.slice(0, aantal) });
    return t;
  };
})(window.DICTEE_OPGAVEN);
