/* De oefenstof van Phrasal verbs en collocations (phrasal.html). Alleen
   inhoud, geen spel: zo is het na te lezen en aan te vullen.

   PHRASAL: elk werkwoord heeft
     v     het phrasal verb
     nl    de Nederlandse betekenis (kort, voor koppelen en meerkeuze)
     n     het laagste niveau waarop het meedoet: bb, kgt of hv
     ico   het pictogram (zie ICONEN in phrasal.html)
     sep   true als het werkwoord scheidbaar is (turn the light on)
     z     voorbeeldzinnen met het phrasal verb tussen <b> en </b>; bij een
           gat-opgave valt het partikel (of het hele werkwoord) weg
     fp    drie partikels die in die zinnen fout zijn (voor de gat-opgave)
     uit   de uitleg in het Nederlands
   Brits Engels, overal. */
window.PHRASAL_OPGAVEN = {
  verbs: [
    /* ---------- bb: de twintig meest voorkomende ---------- */
    { v:'get up', nl:'opstaan', n:'bb', ico:'zon', sep:false, fp:['on', 'off', 'in'],
      z:['I <b>get up</b> at seven o\'clock every day.', 'She <b>got up</b> late on Sunday.'],
      uit:'<b>get up</b> = opstaan (uit bed). Niet te verwarren met <i>wake up</i> (wakker worden): je kunt wakker zijn en nog in bed liggen.' },
    { v:'look for', nl:'zoeken', n:'bb', ico:'loep', sep:false, fp:['at', 'up', 'after'],
      z:['I am <b>looking for</b> my keys. Have you seen them?', 'We <b>looked for</b> a good place to sit.'],
      uit:'<b>look for</b> = zoeken naar. <i>Look at</i> is kijken naar en <i>look after</i> is zorgen voor: het partikel maakt het verschil.' },
    { v:'turn on', nl:'aanzetten', n:'bb', ico:'schakelaar', sep:true, fp:['up', 'in', 'over'],
      z:['It is dark in here. Can you <b>turn on</b> the light?', 'He <b>turned on</b> the TV to watch the news.'],
      uit:'<b>turn on</b> = aanzetten (licht, tv, kraan). Het tegenovergestelde is <i>turn off</i>. Scheidbaar: <i>turn the light on</i> mag ook.' },
    { v:'turn off', nl:'uitzetten', n:'bb', ico:'schakelaar', sep:true, fp:['down', 'out', 'in'],
      z:['Please <b>turn off</b> your phone before the film starts.', 'Don\'t forget to <b>turn off</b> the tap.'],
      uit:'<b>turn off</b> = uitzetten. <i>Turn down</i> is zachter zetten, <i>turn off</i> is helemaal uit.' },
    { v:'give up', nl:'opgeven', n:'bb', ico:'pijl-omhoog', sep:true, fp:['in', 'out', 'off'],
      z:['The puzzle was hard, but I didn\'t <b>give up</b>.', 'My dad <b>gave up</b> smoking last year.'],
      uit:'<b>give up</b> = opgeven, stoppen met iets. Ook bij gewoontes: <i>give up smoking</i> is stoppen met roken.' },
    { v:'find out', nl:'erachter komen', n:'bb', ico:'loep', sep:true, fp:['up', 'in', 'for'],
      z:['I want to <b>find out</b> what time the shop opens.', 'She <b>found out</b> that the party was cancelled.'],
      uit:'<b>find out</b> = erachter komen, ontdekken. Je vindt geen ding, maar informatie.' },
    { v:'pick up', nl:'oppakken, ophalen', n:'bb', ico:'hand', sep:true, fp:['in', 'on', 'at'],
      z:['Can you <b>pick up</b> that pen from the floor?', 'Mum will <b>pick up</b> my sister from school.'],
      uit:'<b>pick up</b> = oppakken (van de grond) of ophalen (iemand met de auto). Twee betekenissen, een werkwoord.' },
    { v:'put on', nl:'aantrekken', n:'bb', ico:'shirt', sep:true, fp:['in', 'up', 'off'],
      z:['It is cold. <b>Put on</b> your coat.', 'He <b>put on</b> his shoes and went outside.'],
      uit:'<b>put on</b> = aantrekken (kleren), opzetten (een pet). Het tegenovergestelde is <i>take off</i>.' },
    { v:'take off', nl:'uittrekken', n:'bb', ico:'shirt', sep:true, fp:['on', 'up', 'in'],
      z:['<b>Take off</b> your wet shoes, please.', 'She <b>took off</b> her jacket because it was warm.'],
      uit:'<b>take off</b> = uittrekken (kleren). Bij een vliegtuig betekent het opstijgen: <i>the plane takes off</i>.' },
    { v:'go on', nl:'doorgaan', n:'bb', ico:'pijl-vooruit', sep:false, fp:['in', 'up', 'out'],
      z:['The teacher said: "<b>Go on</b>, you\'re doing well."', 'The concert <b>went on</b> until midnight.'],
      uit:'<b>go on</b> = doorgaan, verdergaan. Ook: gebeuren, zoals in <i>What\'s going on?</i> (Wat is er aan de hand?).' },
    { v:'come back', nl:'terugkomen', n:'bb', ico:'pijl-terug', sep:false, fp:['in', 'up', 'on'],
      z:['I will <b>come back</b> at five o\'clock.', 'They <b>came back</b> from holiday yesterday.'],
      uit:'<b>come back</b> = terugkomen. <i>Go back</i> is teruggaan: het hangt ervan af waar de spreker is.' },
    { v:'sit down', nl:'gaan zitten', n:'bb', ico:'stoel', sep:false, fp:['up', 'in', 'on'],
      z:['Please <b>sit down</b> and open your books.', 'We <b>sat down</b> on the grass.'],
      uit:'<b>sit down</b> = gaan zitten. Het tegenovergestelde is <i>stand up</i>.' },
    { v:'stand up', nl:'opstaan (van je stoel)', n:'bb', ico:'pijl-omhoog', sep:false, fp:['on', 'in', 'out'],
      z:['<b>Stand up</b> when the head teacher comes in.', 'Everyone <b>stood up</b> and clapped.'],
      uit:'<b>stand up</b> = opstaan van je stoel, gaan staan. <i>Get up</i> is opstaan uit bed.' },
    { v:'wake up', nl:'wakker worden', n:'bb', ico:'klok', sep:true, fp:['on', 'in', 'out'],
      z:['I <b>wake up</b> at six because of the birds.', 'The noise <b>woke up</b> the baby.'],
      uit:'<b>wake up</b> = wakker worden, of wakker maken. <i>Get up</i> is uit bed komen.' },
    { v:'look at', nl:'kijken naar', n:'bb', ico:'oog', sep:false, fp:['for', 'up', 'after'],
      z:['<b>Look at</b> the board, please.', 'She <b>looked at</b> the photo for a long time.'],
      uit:'<b>look at</b> = kijken naar. In het Engels hoort <i>at</i> erbij; <i>look for</i> is zoeken.' },
    { v:'come in', nl:'binnenkomen', n:'bb', ico:'deur', sep:false, fp:['up', 'on', 'out'],
      z:['<b>Come in</b> and close the door.', 'A cat <b>came in</b> through the window.'],
      uit:'<b>come in</b> = binnenkomen. <i>Go out</i> is naar buiten gaan, uitgaan.' },
    { v:'go out', nl:'uitgaan, naar buiten gaan', n:'bb', ico:'deur', sep:false, fp:['in', 'up', 'on'],
      z:['Let\'s <b>go out</b> and play football.', 'We <b>went out</b> for pizza on Friday.'],
      uit:'<b>go out</b> = naar buiten gaan, uitgaan. Ook <i>go out with someone</i>: verkering hebben.' },
    { v:'hurry up', nl:'opschieten', n:'bb', ico:'klok', sep:false, fp:['on', 'in', 'off'],
      z:['<b>Hurry up</b>, the bus is leaving!', 'If we <b>hurry up</b>, we can still catch the train.'],
      uit:'<b>hurry up</b> = opschieten. Het is bijna altijd een aansporing: <i>Hurry up!</i>' },
    { v:'write down', nl:'opschrijven', n:'bb', ico:'pen', sep:true, fp:['up', 'on', 'in'],
      z:['<b>Write down</b> the homework in your diary.', 'I <b>wrote down</b> her phone number.'],
      uit:'<b>write down</b> = opschrijven, noteren. Zonder <i>down</i> is het gewoon schrijven.' },
    { v:'throw away', nl:'weggooien', n:'bb', ico:'prullenbak', sep:true, fp:['up', 'on', 'in'],
      z:['Don\'t <b>throw away</b> that box, I need it.', 'He <b>threw away</b> the old newspapers.'],
      uit:'<b>throw away</b> = weggooien. <i>Away</i> zegt dat iets weggaat.' },

    /* ---------- kgt: twintig erbij ---------- */
    { v:'look after', nl:'zorgen voor', n:'kgt', ico:'hart', sep:false, fp:['for', 'at', 'up'],
      z:['Can you <b>look after</b> my dog this weekend?', 'She <b>looks after</b> her little brother on Fridays.'],
      uit:'<b>look after</b> = zorgen voor, passen op. Vergelijk <i>look for</i> (zoeken) en <i>look at</i> (kijken naar).' },
    { v:'look up', nl:'opzoeken', n:'kgt', ico:'loep', sep:true, fp:['for', 'after', 'on'],
      z:['<b>Look up</b> the word in a dictionary.', 'I <b>looked up</b> the train times online.'],
      uit:'<b>look up</b> = opzoeken (in een woordenboek of op internet). Scheidbaar: <i>look it up</i>.' },
    { v:'get on', nl:'instappen (bus, trein)', n:'kgt', ico:'bus', sep:false, fp:['in', 'up', 'at'],
      z:['We <b>got on</b> the bus at the station.', '<b>Get on</b> quickly, the train is about to leave.'],
      uit:'<b>get on</b> = instappen in een bus, trein of vliegtuig. Bij een auto zeg je <i>get in</i>.' },
    { v:'get off', nl:'uitstappen', n:'kgt', ico:'bus', sep:false, fp:['out', 'down', 'in'],
      z:['<b>Get off</b> at the next stop.', 'They <b>got off</b> the plane in Madrid.'],
      uit:'<b>get off</b> = uitstappen (bus, trein, fiets). Bij een auto is het <i>get out</i>.' },
    { v:'grow up', nl:'opgroeien', n:'kgt', ico:'plant', sep:false, fp:['on', 'in', 'out'],
      z:['I <b>grew up</b> in a small village.', 'When I <b>grow up</b>, I want to be a vet.'],
      uit:'<b>grow up</b> = opgroeien, volwassen worden. <i>Grow</i> alleen is groeien.' },
    { v:'hang up', nl:'ophangen (telefoon)', n:'kgt', ico:'telefoon', sep:true, fp:['on', 'off', 'in'],
      z:['Don\'t <b>hang up</b>, I\'m not finished yet!', 'She said goodbye and <b>hung up</b>.'],
      uit:'<b>hang up</b> = ophangen, het gesprek beëindigen. Ook: een jas ophangen.' },
    { v:'call back', nl:'terugbellen', n:'kgt', ico:'telefoon', sep:true, fp:['up', 'in', 'on'],
      z:['I\'m busy now. Can I <b>call</b> you <b>back</b> later?', 'He never <b>called back</b>.'],
      uit:'<b>call back</b> = terugbellen. Scheidbaar: <i>call you back</i>, het voornaamwoord staat ertussen.' },
    { v:'run away', nl:'weglopen', n:'kgt', ico:'rennen', sep:false, fp:['out', 'off', 'up'],
      z:['The dog <b>ran away</b> when it heard the fireworks.', 'Don\'t <b>run away</b> from your problems.'],
      uit:'<b>run away</b> = weglopen, wegrennen. <i>Away</i> zegt dat iemand ervandoor gaat.' },
    { v:'fill in', nl:'invullen', n:'kgt', ico:'pen', sep:true, fp:['up', 'on', 'out'],
      z:['Please <b>fill in</b> the form with your name and address.', 'I <b>filled in</b> the missing words.'],
      uit:'<b>fill in</b> = invullen (Brits). Amerikanen zeggen <i>fill out</i>. Scheidbaar: <i>fill it in</i>.' },
    { v:'turn up', nl:'harder zetten', n:'kgt', ico:'klok', sep:true, fp:['on', 'in', 'over'],
      z:['I can\'t hear the music. <b>Turn</b> it <b>up</b>!', 'Can you <b>turn up</b> the heating? It\'s cold.'],
      uit:'<b>turn up</b> = harder zetten (geluid) of hoger zetten (verwarming). Het betekent ook: opdagen.' },
    { v:'turn down', nl:'zachter zetten', n:'kgt', ico:'klok', sep:true, fp:['off', 'in', 'on'],
      z:['<b>Turn down</b> the TV, the baby is sleeping.', 'He <b>turned down</b> the volume.'],
      uit:'<b>turn down</b> = zachter zetten. Ook: afwijzen (<i>turn down an offer</i>).' },
    { v:'put away', nl:'opruimen', n:'kgt', ico:'doos', sep:true, fp:['on', 'up', 'in'],
      z:['<b>Put away</b> your books, the lesson is over.', 'She <b>put away</b> the clean plates.'],
      uit:'<b>put away</b> = opruimen, op zijn plek leggen. <i>Away</i>: weg uit het zicht.' },
    { v:'set off', nl:'vertrekken', n:'kgt', ico:'pijl-vooruit', sep:false, fp:['up', 'in', 'on'],
      z:['We <b>set off</b> early to avoid the traffic.', 'The hikers <b>set off</b> at six in the morning.'],
      uit:'<b>set off</b> = vertrekken, op weg gaan. Verleden tijd is ook <i>set off</i>.' },
    { v:'break down', nl:'kapotgaan (auto, machine)', n:'kgt', ico:'auto', sep:false, fp:['up', 'off', 'in'],
      z:['Our car <b>broke down</b> on the motorway.', 'The lift <b>breaks down</b> all the time.'],
      uit:'<b>break down</b> = kapotgaan, het begeven (auto, machine). Bij mensen: instorten van verdriet.' },
    { v:'carry on', nl:'doorgaan', n:'kgt', ico:'pijl-vooruit', sep:false, fp:['up', 'in', 'out'],
      z:['<b>Carry on</b> with your work while I\'m away.', 'They <b>carried on</b> talking after the bell.'],
      uit:'<b>carry on</b> = doorgaan, verdergaan. Betekent hetzelfde als <i>go on</i>.' },
    { v:'work out', nl:'uitrekenen, oplossen', n:'kgt', ico:'rekenmachine', sep:true, fp:['up', 'on', 'in'],
      z:['Can you <b>work out</b> how much we owe?', 'I finally <b>worked out</b> the answer.'],
      uit:'<b>work out</b> = uitrekenen, uitvogelen. Ook: sporten (<i>I work out at the gym</i>).' },
    { v:'show up', nl:'opdagen', n:'kgt', ico:'deur', sep:false, fp:['on', 'in', 'off'],
      z:['He didn\'t <b>show up</b> for the meeting.', 'Only ten people <b>showed up</b> at the party.'],
      uit:'<b>show up</b> = opdagen, komen. Vaak met een beetje verwijt: <i>he didn\'t show up</i>.' },
    { v:'give back', nl:'teruggeven', n:'kgt', ico:'pijl-terug', sep:true, fp:['up', 'in', 'on'],
      z:['<b>Give back</b> my pen when you\'re done.', 'She <b>gave back</b> the money she had borrowed.'],
      uit:'<b>give back</b> = teruggeven. Scheidbaar: <i>give it back</i>.' },
    { v:'try on', nl:'passen (kleren)', n:'kgt', ico:'shirt', sep:true, fp:['up', 'in', 'out'],
      z:['Can I <b>try on</b> these jeans?', 'She <b>tried on</b> five dresses and bought none.'],
      uit:'<b>try on</b> = passen, aantrekken om te kijken of het past. <i>Try out</i> is uitproberen.' },
    { v:'take back', nl:'terugbrengen', n:'kgt', ico:'pijl-terug', sep:true, fp:['up', 'off', 'in'],
      z:['I have to <b>take back</b> these library books.', 'He <b>took back</b> the shirt because it was too small.'],
      uit:'<b>take back</b> = terugbrengen naar de winkel of de bibliotheek. Ook: terugnemen wat je zei.' },

    /* ---------- hv: minder frequent, en drie woorden ---------- */
    { v:'put up with', nl:'verdragen', n:'hv', ico:'hand', sep:false, fp:['put on', 'take after', 'give up'],
      z:['I can\'t <b>put up with</b> this noise any longer.', 'How do you <b>put up with</b> his bad jokes?'],
      uit:'<b>put up with</b> = verdragen, tolereren. Drie woorden en niet scheidbaar: <i>put up with it</i>.' },
    { v:'look forward to', nl:'uitkijken naar', n:'hv', ico:'kalender', sep:false, fp:['look after', 'come up with', 'get over'],
      z:['I am <b>looking forward to</b> the holidays.', 'We <b>look forward to</b> seeing you again.'],
      uit:'<b>look forward to</b> = uitkijken naar. Let op: na <i>to</i> komt een zelfstandig naamwoord of -ing: <i>looking forward to seeing you</i>.' },
    { v:'run out of', nl:'zonder komen te zitten', n:'hv', ico:'doos', sep:false, fp:['run away', 'give up', 'cut down on'],
      z:['We have <b>run out of</b> milk. Can you buy some?', 'The printer <b>ran out of</b> paper again.'],
      uit:'<b>run out of</b> = opraken, niets meer hebben van. <i>We ran out of time</i>: de tijd was op.' },
    { v:'come up with', nl:'bedenken', n:'hv', ico:'lamp', sep:false, fp:['come back', 'go through', 'turn out'],
      z:['She <b>came up with</b> a brilliant plan.', 'Can you <b>come up with</b> a better name?'],
      uit:'<b>come up with</b> = bedenken, op de proppen komen met (een idee, een plan).' },
    { v:'get along with', nl:'goed overweg kunnen met', n:'hv', ico:'hart', sep:false, fp:['put up with', 'look down on', 'take after'],
      z:['I <b>get along with</b> my new classmates.', 'Do you <b>get along with</b> your sister?'],
      uit:'<b>get along with</b> = goed overweg kunnen met, goed kunnen opschieten met. Brits ook: <i>get on with</i>.' },
    { v:'get over', nl:'overheen komen', n:'hv', ico:'hart', sep:false, fp:['get off', 'give up', 'break down'],
      z:['It took him months to <b>get over</b> the break-up.', 'She has <b>got over</b> her cold.'],
      uit:'<b>get over</b> = ergens overheen komen (verdriet, ziekte). Niet scheidbaar: <i>get over it</i>.' },
    { v:'bring up', nl:'opvoeden', n:'hv', ico:'plant', sep:true, fp:['grow up', 'pick up', 'give up'],
      z:['His grandparents <b>brought</b> him <b>up</b>.', 'It is not easy to <b>bring up</b> three children.'],
      uit:'<b>bring up</b> = opvoeden, grootbrengen. Ook: een onderwerp ter sprake brengen. Scheidbaar.' },
    { v:'turn out', nl:'blijken', n:'hv', ico:'lamp', sep:false, fp:['turn up', 'find out', 'work out'],
      z:['The film <b>turned out</b> to be really good.', 'It <b>turned out</b> that she was right.'],
      uit:'<b>turn out</b> = blijken, uitpakken. <i>It turned out that…</i>: het bleek dat…' },
    { v:'take after', nl:'lijken op (familie)', n:'hv', ico:'hart', sep:false, fp:['take off', 'look after', 'bring up'],
      z:['He <b>takes after</b> his father: they both love music.', 'Who do you <b>take after</b>, your mum or your dad?'],
      uit:'<b>take after</b> = lijken op (in karakter of uiterlijk), alleen bij familie. Niet scheidbaar.' },
    { v:'figure out', nl:'uitvogelen', n:'hv', ico:'rekenmachine', sep:true, fp:['find out', 'give up', 'turn out'],
      z:['I can\'t <b>figure out</b> how this app works.', 'We <b>figured out</b> the answer together.'],
      uit:'<b>figure out</b> = uitvogelen, begrijpen hoe iets zit. Lijkt op <i>work out</i>.' },
    { v:'let down', nl:'teleurstellen', n:'hv', ico:'pijl-omlaag', sep:true, fp:['let in', 'turn down', 'put off'],
      z:['Don\'t <b>let</b> me <b>down</b>, I\'m counting on you.', 'The team <b>let down</b> their fans.'],
      uit:'<b>let down</b> = teleurstellen, in de steek laten. Scheidbaar: <i>let me down</i>.' },
    { v:'make up', nl:'verzinnen', n:'hv', ico:'lamp', sep:true, fp:['come up with', 'figure out', 'give up'],
      z:['He <b>made up</b> an excuse for being late.', 'Don\'t <b>make up</b> stories, tell the truth.'],
      uit:'<b>make up</b> = verzinnen. Ook: het goedmaken na ruzie (<i>they made up</i>).' },
    { v:'go through', nl:'doormaken', n:'hv', ico:'deur', sep:false, fp:['go on', 'get over', 'carry on'],
      z:['She is <b>going through</b> a difficult time.', 'We <b>went through</b> the plan step by step.'],
      uit:'<b>go through</b> = doormaken (iets moeilijks) of doornemen (een plan, een tekst).' },
    { v:'cut down on', nl:'minderen met', n:'hv', ico:'pijl-omlaag', sep:false, fp:['give up', 'run out of', 'put off'],
      z:['The doctor told him to <b>cut down on</b> sugar.', 'I want to <b>cut down on</b> screen time.'],
      uit:'<b>cut down on</b> = minderen met, minder gebruiken van. Niet helemaal stoppen: dat is <i>give up</i>.' },
    { v:'keep up with', nl:'bijhouden', n:'hv', ico:'rennen', sep:false, fp:['catch up', 'put up with', 'carry on'],
      z:['I can\'t <b>keep up with</b> all the homework.', 'She walks so fast that I can\'t <b>keep up with</b> her.'],
      uit:'<b>keep up with</b> = bijhouden, hetzelfde tempo houden als. Bij nieuws: op de hoogte blijven.' },
    { v:'get away with', nl:'ermee wegkomen', n:'hv', ico:'rennen', sep:false, fp:['run away', 'get over', 'go through'],
      z:['He cheated and <b>got away with</b> it.', 'You won\'t <b>get away with</b> lying to the teacher.'],
      uit:'<b>get away with</b> = ergens mee wegkomen, geen straf krijgen voor iets.' },
    { v:'put off', nl:'uitstellen', n:'hv', ico:'kalender', sep:true, fp:['put on', 'turn off', 'call off'],
      z:['Don\'t <b>put off</b> your homework until Sunday evening.', 'The match was <b>put off</b> because of the rain.'],
      uit:'<b>put off</b> = uitstellen. Scheidbaar: <i>put it off</i>. Vergelijk <i>call off</i>: afgelasten.' },
    { v:'look down on', nl:'neerkijken op', n:'hv', ico:'pijl-omlaag', sep:false, fp:['look after', 'look up to', 'look forward to'],
      z:['Some people <b>look down on</b> others because of their clothes.', 'Don\'t <b>look down on</b> him just because he is younger.'],
      uit:'<b>look down on</b> = neerkijken op, minachten. Het tegenovergestelde is <i>look up to</i>: opkijken tegen.' },
    { v:'back up', nl:'steunen', n:'hv', ico:'hand', sep:true, fp:['bring up', 'give up', 'set up'],
      z:['My friends <b>backed</b> me <b>up</b> when I told the truth.', 'Always <b>back up</b> your files.'],
      uit:'<b>back up</b> = steunen (iemand) of een reservekopie maken (bestanden). Scheidbaar.' },
    { v:'drop out', nl:'stoppen (school, cursus)', n:'hv', ico:'deur', sep:false, fp:['drop off', 'set off', 'get off'],
      z:['He <b>dropped out</b> of university after one year.', 'Too many students <b>drop out</b> before their exams.'],
      uit:'<b>drop out</b> = voortijdig stoppen met school of een cursus. Zelfstandig naamwoord: <i>a dropout</i>.' }
  ],

  /* de partikels die in de gat-opgave als foute keus mogen komen (bb en kgt) */
  partikels: ['up', 'down', 'on', 'off', 'in', 'out', 'for', 'after', 'back', 'away', 'at', 'over'],

  /* Collocations: twee werkwoorden, een zin, de vaste combinatie.
     a en b zijn de twee keuzes, goed is de goede, n het laagste niveau. */
  collocations: [
    /* make of do */
    { a:'make', b:'do', goed:'do', n:'bb', zin:'I have to ___ my homework before dinner.', combi:'do your homework', uit:'<b>do</b> bij taken en werk: do your homework, do the dishes.' },
    { a:'make', b:'do', goed:'make', n:'bb', zin:'Shall I ___ a cup of tea for you?', combi:'make a cup of tea', uit:'<b>make</b> als je iets maakt of klaarmaakt: make tea, make dinner.' },
    { a:'make', b:'do', goed:'make', n:'bb', zin:'Don\'t ___ a mess in the kitchen.', combi:'make a mess', uit:'<b>make a mess</b> is de vaste combinatie: een rommel maken.' },
    { a:'make', b:'do', goed:'do', n:'bb', zin:'Can you ___ the dishes tonight?', combi:'do the dishes', uit:'<b>do the dishes</b>: afwassen is een klus, en bij klussen hoort do.' },
    { a:'make', b:'do', goed:'make', n:'bb', zin:'I ___ my bed every morning.', combi:'make your bed', uit:'<b>make your bed</b> is de vaste combinatie, ook al is het een klus.' },
    { a:'make', b:'do', goed:'make', n:'bb', zin:'Can you ___ me a sandwich, please?', combi:'make a sandwich', uit:'<b>make</b> bij eten dat je klaarmaakt: make a sandwich, make a cake.' },
    { a:'make', b:'do', goed:'do', n:'bb', zin:'I always ___ my best in tests.', combi:'do your best', uit:'<b>do your best</b>: je best doen, net als in het Nederlands.' },
    { a:'make', b:'do', goed:'make', n:'bb', zin:'Let\'s ___ a cake for her birthday.', combi:'make a cake', uit:'<b>make a cake</b>: bakken is maken, dus make.' },
    { a:'make', b:'do', goed:'do', n:'bb', zin:'Who is going to ___ the washing-up?', combi:'do the washing-up', uit:'<b>do the washing-up</b> (Brits): afwassen is een klus, en bij klussen hoort do.' },
    { a:'make', b:'do', goed:'make', n:'kgt', zin:'Everybody ___s mistakes sometimes.', combi:'make a mistake', uit:'<b>make a mistake</b>: fouten maak je, in het Engels net als in het Nederlands.' },
    { a:'make', b:'do', goed:'do', n:'kgt', zin:'You should ___ some exercise every day.', combi:'do exercise', uit:'<b>do exercise</b>, <b>do sport</b>: activiteiten doe je.' },
    { a:'make', b:'do', goed:'make', n:'kgt', zin:'Let\'s ___ a decision: pizza or pasta?', combi:'make a decision', uit:'<b>make a decision</b>: een beslissing nemen is in het Engels make.' },
    { a:'make', b:'do', goed:'do', n:'kgt', zin:'I still have to ___ the shopping.', combi:'do the shopping', uit:'<b>do the shopping</b>: boodschappen doen, een klus.' },
    { a:'make', b:'do', goed:'make', n:'kgt', zin:'She ___ a lot of new friends at camp.', combi:'make friends', uit:'<b>make friends</b> is de vaste combinatie: vrienden maken.' },
    { a:'make', b:'do', goed:'do', n:'kgt', zin:'Could you ___ me a favour and close the window?', combi:'do someone a favour', uit:'<b>do someone a favour</b>: iemand een plezier doen.' },
    { a:'make', b:'do', goed:'make', n:'hv', zin:'The teacher asked us to ___ an effort.', combi:'make an effort', uit:'<b>make an effort</b>: je best doen heet in het Engels make.' },
    { a:'make', b:'do', goed:'do', n:'hv', zin:'We ___ a lot of research before the presentation.', combi:'do research', uit:'<b>do research</b>: onderzoek doen.' },
    { a:'make', b:'do', goed:'make', n:'hv', zin:'It doesn\'t ___ sense to leave now.', combi:'make sense', uit:'<b>make sense</b>: logisch zijn, ergens op slaan.' },
    { a:'make', b:'do', goed:'do', n:'hv', zin:'Our school ___es a lot for charity.', combi:'do something for charity', uit:'<b>do</b> bij algemene activiteiten: do a lot, do nothing, do your best.' },
    { a:'make', b:'do', goed:'make', n:'hv', zin:'Can you ___ some room on the table?', combi:'make room', uit:'<b>make room</b>: ruimte maken.' },
    { a:'make', b:'do', goed:'make', n:'hv', zin:'I hope we ___ progress this term.', combi:'make progress', uit:'<b>make progress</b>: vooruitgang boeken.' },
    /* take of have */
    { a:'take', b:'have', goed:'have', n:'bb', zin:'We ___ breakfast at half past seven.', combi:'have breakfast', uit:'<b>have</b> bij eten en drinken: have breakfast, have lunch, have a drink.' },
    { a:'take', b:'have', goed:'take', n:'bb', zin:'Can you ___ a photo of us?', combi:'take a photo', uit:'<b>take a photo</b>: een foto maken is in het Engels take.' },
    { a:'take', b:'have', goed:'have', n:'bb', zin:'Did you ___ a good time at the party?', combi:'have a good time', uit:'<b>have a good time</b>: het naar je zin hebben.' },
    { a:'take', b:'have', goed:'take', n:'bb', zin:'I ___ the bus to school every day.', combi:'take the bus', uit:'<b>take the bus</b>, take the train: vervoer neem je.' },
    { a:'take', b:'have', goed:'have', n:'bb', zin:'I ___ a shower every morning.', combi:'have a shower', uit:'<b>have a shower</b> (Brits). Amerikanen zeggen ook <i>take a shower</i>, maar op school houden we Brits aan.' },
    { a:'take', b:'have', goed:'have', n:'bb', zin:'Let\'s ___ lunch together at one o\'clock.', combi:'have lunch', uit:'<b>have lunch</b>: bij maaltijden hoort have.' },
    { a:'take', b:'have', goed:'take', n:'bb', zin:'Please ___ a seat, the doctor will be here soon.', combi:'take a seat', uit:'<b>take a seat</b>: plaatsnemen, gaan zitten.' },
    { a:'take', b:'have', goed:'have', n:'bb', zin:'We always ___ fun at the beach.', combi:'have fun', uit:'<b>have fun</b>: plezier hebben.' },
    { a:'take', b:'have', goed:'take', n:'bb', zin:'___ an umbrella, it is going to rain.', combi:'take an umbrella', uit:'<b>take</b> als je iets meeneemt: take an umbrella, take your bag.' },
    { a:'take', b:'have', goed:'take', n:'kgt', zin:'___ your time, there is no hurry.', combi:'take your time', uit:'<b>take your time</b>: rustig aan doen.' },
    { a:'take', b:'have', goed:'have', n:'kgt', zin:'Let\'s ___ a break for ten minutes.', combi:'have a break', uit:'<b>have a break</b> (Brits): pauze houden. <i>Take a break</i> hoor je ook.' },
    { a:'take', b:'have', goed:'take', n:'kgt', zin:'We ___ a test every Friday.', combi:'take a test', uit:'<b>take a test</b>, take an exam: een toets maken.' },
    { a:'take', b:'have', goed:'have', n:'kgt', zin:'I ___ a headache, so I\'m going home.', combi:'have a headache', uit:'<b>have</b> bij klachten: have a headache, have a cold.' },
    { a:'take', b:'have', goed:'take', n:'kgt', zin:'___ off your shoes before you come in.', combi:'take off', uit:'<b>take off</b> = uittrekken. Een phrasal verb, geen have.' },
    { a:'take', b:'have', goed:'have', n:'kgt', zin:'Can I ___ a look at your notes?', combi:'have a look', uit:'<b>have a look</b>: even kijken. Brits; Amerikanen zeggen <i>take a look</i>.' },
    { a:'take', b:'have', goed:'take', n:'hv', zin:'Who is going to ___ care of the plants?', combi:'take care of', uit:'<b>take care of</b>: zorgen voor.' },
    { a:'take', b:'have', goed:'take', n:'hv', zin:'She decided to ___ part in the competition.', combi:'take part in', uit:'<b>take part in</b>: meedoen aan.' },
    { a:'take', b:'have', goed:'have', n:'hv', zin:'I ___ no idea what she means.', combi:'have no idea', uit:'<b>have no idea</b>: geen idee hebben.' },
    { a:'take', b:'have', goed:'take', n:'hv', zin:'Don\'t ___ it personally, he is just tired.', combi:'take something personally', uit:'<b>take it personally</b>: het persoonlijk opvatten.' },
    { a:'take', b:'have', goed:'have', n:'hv', zin:'We ___ an argument about the music.', combi:'have an argument', uit:'<b>have an argument</b>: ruzie hebben. Ook: have a chat, have a conversation.' },
    /* say of tell */
    { a:'say', b:'tell', goed:'tell', n:'bb', zin:'Can you ___ me the time, please?', combi:'tell someone the time', uit:'<b>tell</b> als er een persoon na komt: tell me, tell him.' },
    { a:'say', b:'tell', goed:'say', n:'bb', zin:'What did she ___ to you?', combi:'say something to someone', uit:'<b>say</b> zonder persoon erachter; wil je de persoon noemen, dan met <i>to</i>: say to you.' },
    { a:'say', b:'tell', goed:'say', n:'bb', zin:'___ hello to your mum from me.', combi:'say hello', uit:'<b>say hello</b>, say goodbye, say sorry: vaste combinaties met say.' },
    { a:'say', b:'tell', goed:'tell', n:'bb', zin:'Grandad likes to ___ stories about the old days.', combi:'tell a story', uit:'<b>tell a story</b>, tell a joke: vertellen is tell.' },
    { a:'say', b:'tell', goed:'say', n:'bb', zin:'___ goodbye to grandma before we leave.', combi:'say goodbye', uit:'<b>say goodbye</b>: gedag zeggen, een vaste combinatie met say.' },
    { a:'say', b:'tell', goed:'tell', n:'bb', zin:'Please ___ me your name.', combi:'tell someone your name', uit:'<b>tell</b> als er een persoon na komt: tell me, tell her.' },
    { a:'say', b:'tell', goed:'tell', n:'bb', zin:'Don\'t ___ lies, it always comes out.', combi:'tell a lie', uit:'<b>tell a lie</b>, tell lies: liegen is in het Engels tell.' },
    { a:'say', b:'tell', goed:'say', n:'bb', zin:'What do you ___ when someone gives you a present?', combi:'say thank you', uit:'<b>say thank you</b>: bedanken, zonder persoon erachter, dus say.' },
    { a:'say', b:'tell', goed:'say', n:'kgt', zin:'He didn\'t ___ anything during the meeting.', combi:'say anything', uit:'<b>say</b> als er geen persoon bij staat: say something, say nothing.' },
    { a:'say', b:'tell', goed:'tell', n:'kgt', zin:'Always ___ the truth, even when it is hard.', combi:'tell the truth', uit:'<b>tell the truth</b> en <b>tell a lie</b>: vaste combinaties met tell.' },
    { a:'say', b:'tell', goed:'say', n:'kgt', zin:'She ___ sorry for being late.', combi:'say sorry', uit:'<b>say sorry</b>: sorry zeggen.' },
    { a:'say', b:'tell', goed:'tell', n:'kgt', zin:'I will ___ you a secret if you promise to keep it.', combi:'tell someone a secret', uit:'<b>tell</b> + persoon + wat: tell you a secret.' },
    { a:'say', b:'tell', goed:'tell', n:'kgt', zin:'Can you ___ the difference between the two photos?', combi:'tell the difference', uit:'<b>tell the difference</b>: het verschil zien.' },
    { a:'say', b:'tell', goed:'say', n:'hv', zin:'The sign ___s that the park closes at ten.', combi:'the sign says', uit:'Een bord, een brief of een tekst <b>says</b> iets: er staat.' },
    { a:'say', b:'tell', goed:'tell', n:'hv', zin:'The teacher ___ us to open our books.', combi:'tell someone to do something', uit:'<b>tell someone to</b>: iemand opdragen iets te doen. <i>Say to</i> kan hier niet.' },
    { a:'say', b:'tell', goed:'say', n:'hv', zin:'Let\'s ___ you win the lottery. What would you buy?', combi:'let\'s say', uit:'<b>let\'s say</b>: stel dat. Vaste uitdrukking met say.' },
    { a:'say', b:'tell', goed:'tell', n:'hv', zin:'I can\'t ___ whether he is joking or not.', combi:'I can\'t tell', uit:'<b>I can\'t tell</b>: ik kan het niet zien of merken.' },
    { a:'say', b:'tell', goed:'tell', n:'hv', zin:'Don\'t ___ anyone about the surprise.', combi:'tell someone about', uit:'<b>tell someone about</b>: iemand vertellen over. Na tell komt de persoon.' }
  ]
};
