/* De teksten van Reading (reading.html). Alleen inhoud: achttien teksten van
   80 tot 150 woorden, zes per niveau, elk met drie tot vier soorten vragen.

   Per tekst:
     id, n     een korte sleutel en het niveau (bb = A1-A2, kgt = A2, hv = B1)
     kop       de titel boven het tekstvak
     tekst     de tekst; een lege regel (\n\n) is een nieuwe alinea
     hoofd     de hoofdgedachte: v de vraag, o vier keuzes, g de goede (index), uit de uitleg
     detail    een of twee detailvragen: waar/onwaar ('True', 'False'), op hv ook 'Not stated'
     woord     een of twee woorden uit de context: w het woord (staat vet in de tekst), o vier betekenissen
     volgorde  vier gebeurtenissen in de goede volgorde, om te slepen
   De vragen zijn in het Engels, de uitleg in het Nederlands. Brits Engels. */
window.READING_OPGAVEN = [
  /* ================= bb: A1-A2 ================= */
  { id:'bb1', n:'bb', kop:'A new school',
    tekst:'Mia is twelve. Today is her first day at her new school. She is nervous, because she does not know anyone.\n\nAt eight o\'clock she walks into the classroom. A girl with red hair says: "Hi, I\'m Noor. You can sit next to me." Mia smiles. The first lesson is maths. Mia likes maths, so that is easy. The second lesson is English. The teacher, Mr Bell, is funny and tells a joke about his cat.\n\nAt lunch Mia and Noor eat their sandwiches in the playground. In the afternoon they have PE. Mia is good at running and wins a race. At the end of the day Mia is not nervous anymore. She thinks her new school is great.',
    hoofd:{ v:'What is the text mainly about?', o:['Mia\'s first day at a new school', 'Mia\'s favourite subject', 'A funny English teacher', 'A race in PE'], g:0, uit:'De hele tekst gaat over Mia\'s eerste dag: de klas, de lessen, de lunch en het eind van de dag. De andere antwoorden zijn maar een klein stukje.' },
    detail:[{ v:'Mia already knows some people at her new school.', o:['True', 'False'], g:1, uit:'In de tekst staat: <i>She is nervous, because she does not know anyone.</i> Ze kent dus niemand.' },
            { v:'What is the first lesson?', o:['Maths', 'English', 'PE', 'Music'], g:0, uit:'<i>The first lesson is maths.</i> Engels is de tweede les, gym is in de middag.' }],
    woord:[{ w:'nervous', o:['zenuwachtig', 'blij', 'moe', 'boos'], g:0, uit:'Mia is <i>nervous</i> omdat ze niemand kent: zenuwachtig. Aan het eind is ze het niet meer.' }],
    volgorde:{ items:['Mia walks into the classroom.', 'Mr Bell tells a joke about his cat.', 'Mia and Noor eat their sandwiches.', 'Mia wins a race.'], uit:'Eerst de klas in (acht uur), dan de Engelse les met de grap, dan de lunch, en in de middag gym met de race.' } },

  { id:'bb2', n:'bb', kop:'Football on Saturday',
    tekst:'Tom plays football every Saturday. His team is called the Blue Lions. They play in a small park near his house.\n\nLast Saturday it was raining. The grass was wet and the ball was heavy. In the first half the other team scored a goal. Tom\'s coach said: "Don\'t worry, keep going!" In the second half Tom got the ball. He ran fast, passed two players and scored. One-one!\n\nFive minutes before the end, Tom\'s friend Sam scored again. The Blue Lions won 2-1. After the match they all had hot chocolate in the clubhouse. Tom was wet and tired, but very happy.',
    hoofd:{ v:'What is the text mainly about?', o:['A football match that Tom\'s team won', 'Why football is dangerous in the rain', 'Tom\'s new football boots', 'The rules of football'], g:0, uit:'De tekst vertelt over de wedstrijd van vorige zaterdag, van de achterstand tot de winst met 2-1.' },
    detail:[{ v:'The Blue Lions scored the first goal of the match.', o:['True', 'False'], g:1, uit:'<i>In the first half the other team scored a goal.</i> De tegenstander scoorde eerst.' },
            { v:'Who scored the winning goal?', o:['Sam', 'Tom', 'The coach', 'The other team'], g:0, uit:'<i>Tom\'s friend Sam scored again.</i> Dat was het tweede doelpunt, en zo werd het 2-1.' }],
    woord:[{ w:'heavy', o:['zwaar', 'nat', 'klein', 'nieuw'], g:0, uit:'Door de regen was de bal <i>heavy</i>: zwaar. De bal wordt nat en dus zwaarder.' }],
    volgorde:{ items:['The other team scores a goal.', 'Tom scores and makes it one-one.', 'Sam scores the second goal.', 'The team drinks hot chocolate.'], uit:'Eerste helft: de tegenstander scoort. Tweede helft: Tom, daarna Sam, en na de wedstrijd de warme chocolademelk.' } },

  { id:'bb3', n:'bb', kop:'Our dog Max',
    tekst:'We have a dog. His name is Max and he is three years old. Max is brown with a white spot on his nose. He is not very big, but he is very fast.\n\nEvery morning my dad walks Max before work. In the afternoon it is my job. We go to the park and I throw a ball. Max always brings it back. He loves it.\n\nMax is scared of one thing: the vacuum cleaner. When my mum cleans the house, Max hides under my bed. When she is finished, he comes out and wants a biscuit. He is a funny dog, and we all love him.',
    hoofd:{ v:'What is the text mainly about?', o:['The writer\'s dog and what he is like', 'How to train a dog', 'Why dogs need a lot of food', 'The writer\'s dad'], g:0, uit:'De tekst beschrijft Max: hoe hij eruitziet, wat hij doet en waar hij bang voor is.' },
    detail:[{ v:'The writer walks Max in the morning.', o:['True', 'False'], g:1, uit:'<i>Every morning my dad walks Max.</i> De schrijver laat hem in de middag uit.' },
            { v:'What is Max scared of?', o:['The vacuum cleaner', 'The park', 'Biscuits', 'The writer\'s mum'], g:0, uit:'<i>Max is scared of one thing: the vacuum cleaner.</i>' }],
    woord:[{ w:'hides', o:['verstopt zich', 'blaft', 'slaapt', 'springt'], g:0, uit:'Max <i>hides</i> under the bed: hij verstopt zich, omdat hij bang is voor de stofzuiger.' }],
    volgorde:{ items:['Mum starts the vacuum cleaner.', 'Max hides under the bed.', 'Mum finishes cleaning.', 'Max comes out and wants a biscuit.'], uit:'Stofzuiger aan, Max verstopt zich, mama is klaar, Max komt tevoorschijn voor een koekje.' } },

  { id:'bb4', n:'bb', kop:'A trip to London',
    tekst:'In May my class went to London for one day. We left school at six in the morning. The bus trip was long, but we watched a film and slept a bit.\n\nIn London we first saw Big Ben and the Houses of Parliament. Then we took a boat on the river Thames. It was windy on the boat, but the view was fantastic. After lunch we visited a big museum with dinosaurs. My favourite part was the shop, where I bought a small red bus for my little brother.\n\nWe were back at school at eleven at night. Everybody was tired, but it was the best school trip ever.',
    hoofd:{ v:'What is the text mainly about?', o:['A school trip to London', 'The history of Big Ben', 'A long bus journey', 'A museum with dinosaurs'], g:0, uit:'De tekst gaat over het hele schoolreisje: de busreis, de bezienswaardigheden, het museum en de terugreis.' },
    detail:[{ v:'The class stayed in London for two days.', o:['True', 'False'], g:1, uit:'<i>My class went to London for one day.</i> Een dag, niet twee.' },
            { v:'What did the writer buy?', o:['A small red bus', 'A dinosaur', 'A boat', 'A film'], g:0, uit:'<i>I bought a small red bus for my little brother.</i>' }],
    woord:[{ w:'view', o:['uitzicht', 'boot', 'wind', 'lunch'], g:0, uit:'The <i>view</i> was fantastic: het uitzicht vanaf de boot.' }],
    volgorde:{ items:['The class leaves school by bus.', 'They see Big Ben.', 'They take a boat on the Thames.', 'They visit the museum.'], uit:'Vertrek om zes uur, eerst Big Ben, dan de boot, na de lunch het museum.' } },

  { id:'bb5', n:'bb', kop:'Pancakes for breakfast',
    tekst:'On Sunday my sister and I make pancakes for the whole family. It is easy. You need flour, two eggs, milk and a little salt.\n\nFirst, put the flour in a big bowl. Then add the eggs and the milk. Mix everything with a whisk until there are no lumps. Now heat a little butter in a pan. Pour some of the mixture into the pan and wait until you see small bubbles. Turn the pancake over with a spatula and cook the other side.\n\nWe eat our pancakes with syrup, but my dad likes cheese on his. Last Sunday we made twenty pancakes and they were all gone in ten minutes!',
    hoofd:{ v:'What is the text mainly about?', o:['How to make pancakes', 'Why breakfast is important', 'The writer\'s dad', 'Different kinds of cheese'], g:0, uit:'De tekst is een recept: wat je nodig hebt en wat je stap voor stap doet.' },
    detail:[{ v:'You need three eggs for the pancakes.', o:['True', 'False'], g:1, uit:'<i>You need flour, two eggs, milk and a little salt.</i> Twee eieren.' },
            { v:'What does the writer\'s dad like on his pancakes?', o:['Cheese', 'Syrup', 'Butter', 'Salt'], g:0, uit:'<i>My dad likes cheese on his.</i> De schrijver zelf eet ze met stroop.' }],
    woord:[{ w:'lumps', o:['klontjes', 'eieren', 'bellen', 'pannen'], g:0, uit:'Je mixt tot er geen <i>lumps</i> meer zijn: klontjes in het beslag.' }],
    volgorde:{ items:['Put the flour in a bowl.', 'Add the eggs and the milk.', 'Heat some butter in a pan.', 'Turn the pancake over.'], uit:'Eerst het meel, dan eieren en melk erbij, dan boter in de pan, en als laatste omdraaien.' } },

  { id:'bb6', n:'bb', kop:'My new phone',
    tekst:'For my birthday I got a new phone. It is not the newest model, but I love it. The camera is much better than the one on my old phone.\n\nMy parents have three rules. Rule one: no phone at the dinner table. Rule two: the phone stays downstairs at night. Rule three: I can use it for two hours a day. At first I thought that was not fair. But now I do not mind. I use the phone to chat with my friends and to take photos of my cat.\n\nMy best friend Lisa has the same phone, so we can help each other with the settings. Next week I want to make a video of our football team.',
    hoofd:{ v:'What is the text mainly about?', o:['The writer\'s new phone and the rules for using it', 'Why phones are bad for children', 'A video of a football team', 'The writer\'s cat'], g:0, uit:'De tekst gaat over de nieuwe telefoon en de drie regels van de ouders.' },
    detail:[{ v:'The writer can use the phone at night.', o:['True', 'False'], g:1, uit:'<i>The phone stays downstairs at night.</i> Dus niet.' },
            { v:'How many hours a day may the writer use the phone?', o:['Two', 'One', 'Three', 'As long as she wants'], g:0, uit:'<i>I can use it for two hours a day.</i>' }],
    woord:[{ w:'fair', o:['eerlijk', 'leuk', 'duur', 'moeilijk'], g:0, uit:'<i>I thought that was not fair</i>: niet eerlijk. De schrijver vond de regels eerst oneerlijk.' }],
    volgorde:{ items:['The writer gets a phone for her birthday.', 'Her parents make three rules.', 'She thinks the rules are not fair.', 'She wants to make a video of the team.'], uit:'Eerst de verjaardag, dan de regels, dan haar eerste reactie, en als laatste het plan voor volgende week.' } },

  /* ================= kgt: A2 ================= */
  { id:'kgt1', n:'kgt', kop:'Local teen wins swimming gold',
    tekst:'Fourteen-year-old Amber Lewis from Brighton won a gold medal at the National Youth Swimming Championships on Saturday. She finished the 100 metres freestyle in 58.4 seconds, a new record for her age group.\n\nAmber started swimming when she was six. "My mum took me to the pool because I was afraid of water," she says. "Now I can\'t stay out of it." She trains five mornings a week before school, starting at half past five.\n\nHer coach, Daniel Ortiz, says that Amber\'s biggest strength is not her speed but her attitude. "She never complains, even when the water is cold and she is tired."\n\nNext year Amber hopes to qualify for the European Junior Championships in Rome.',
    hoofd:{ v:'What is the text mainly about?', o:['A young swimmer who won a national gold medal', 'Why children should learn to swim', 'A swimming pool in Brighton', 'The European Junior Championships'], g:0, uit:'Een nieuwsbericht over Amber en haar gouden medaille, met haar achtergrond en plannen.' },
    detail:[{ v:'Amber trains every day of the week.', o:['True', 'False'], g:1, uit:'<i>She trains five mornings a week.</i> Vijf, niet zeven.' },
            { v:'According to her coach, what is Amber\'s biggest strength?', o:['Her attitude', 'Her speed', 'Her age', 'Her mum'], g:0, uit:'<i>Amber\'s biggest strength is not her speed but her attitude.</i>' }],
    woord:[{ w:'qualify', o:['zich plaatsen', 'winnen', 'trainen', 'verhuizen'], g:0, uit:'To <i>qualify for</i> a championship: je plaatsen voor, goed genoeg zijn om mee te mogen doen.' },
           { w:'complains', o:['klaagt', 'lacht', 'stopt', 'zwemt'], g:0, uit:'<i>She never complains</i>: ze klaagt nooit, ook niet als het water koud is.' }],
    volgorde:{ items:['Amber\'s mum takes her to the pool.', 'Amber starts training five mornings a week.', 'Amber wins gold at the championships.', 'Amber hopes to go to Rome.'], uit:'Eerst als klein kind naar het zwembad, dan de trainingen, zaterdag de medaille, en volgend jaar Rome.' } },

  { id:'kgt2', n:'kgt', kop:'The lost bag',
    tekst:'When Jayden got off the bus, he suddenly felt cold. His bag! He had left it on the seat, with his laptop, his keys and his wallet in it. The bus was already driving away.\n\nJayden ran after it, but the bus was faster. He stopped, out of breath, and tried to think. His phone was in his pocket, luckily. He looked up the number of the bus company and called them. A friendly woman told him to wait at the last stop, where the driver would check the bus.\n\nTwenty minutes later the bus arrived. The driver got out with Jayden\'s bag in his hand. "A lady found it and gave it to me," he said. Everything was still in it. Jayden thanked him three times and promised himself to be more careful.',
    hoofd:{ v:'What is the text mainly about?', o:['A boy who gets his lost bag back', 'A boy who misses the bus', 'A bus driver who steals a bag', 'Why you should not take a laptop to school'], g:0, uit:'Het verhaal gaat over Jayden die zijn tas op de bus laat liggen en hem terugkrijgt.' },
    detail:[{ v:'Jayden\'s phone was in the bag.', o:['True', 'False'], g:1, uit:'<i>His phone was in his pocket, luckily.</i> Daarom kon hij bellen.' },
            { v:'Who found the bag?', o:['A lady on the bus', 'The driver', 'Jayden\'s mother', 'The woman on the phone'], g:0, uit:'<i>A lady found it and gave it to me,</i> zegt de chauffeur.' }],
    woord:[{ w:'wallet', o:['portemonnee', 'jas', 'rugzak', 'boek'], g:0, uit:'A <i>wallet</i> is een portemonnee; die zat in de tas met de laptop en de sleutels.' }],
    volgorde:{ items:['Jayden gets off the bus and misses his bag.', 'He runs after the bus.', 'He calls the bus company.', 'The driver gives him the bag.'], uit:'Uitstappen, rennen, bellen, en twintig minuten later de tas terug.' } },

  { id:'kgt3', n:'kgt', kop:'The school trip that went wrong',
    tekst:'Our class trip to the beach was supposed to be simple: a bus, a picnic and a game of volleyball. It did not go as planned.\n\nFirst, the bus broke down after ten minutes. We waited an hour for a new one. When we finally arrived, the weather changed. Dark clouds came in from the sea and it started to rain. We ate our sandwiches under a bus shelter. Then Mr Khan discovered that the volleyball was still at school.\n\nSo what did we do? We built the biggest sandcastle on the beach, in the rain, with fifty-two people. A man from the local newspaper took a photo, and on Monday we were on the front page. Worst trip ever? No. It was the best.',
    hoofd:{ v:'What is the text mainly about?', o:['A school trip where everything went wrong, but which was fun anyway', 'How to build a sandcastle', 'Why buses often break down', 'A newspaper photographer'], g:0, uit:'Alles ging mis, maar het werd juist een geweldig uitje: dat is de kern van de tekst.' },
    detail:[{ v:'The class played volleyball on the beach.', o:['True', 'False'], g:1, uit:'<i>The volleyball was still at school.</i> Ze bouwden een zandkasteel in plaats daarvan.' },
            { v:'How long did the class wait for a new bus?', o:['An hour', 'Ten minutes', 'Two hours', 'The whole morning'], g:0, uit:'<i>We waited an hour for a new one.</i>' }],
    woord:[{ w:'discovered', o:['ontdekte', 'vergat', 'kocht', 'verloor'], g:0, uit:'Mr Khan <i>discovered</i> that the ball was at school: hij ontdekte het, kwam erachter.' }],
    volgorde:{ items:['The bus breaks down.', 'It starts to rain.', 'The class builds a sandcastle.', 'The class is on the front page of the newspaper.'], uit:'Eerst de bus, dan de regen bij aankomst, dan het zandkasteel, en op maandag de krant.' } },

  { id:'kgt4', n:'kgt', kop:'Penguins at the zoo',
    tekst:'Most people think penguins live in cold places. That is true for some of them, like the emperor penguin in Antarctica. But the penguins at our city zoo are African penguins, and they come from the warm beaches of South Africa.\n\nThe zoo has twenty-three of them. They cannot fly, but they are excellent swimmers: under water they can reach a speed of twenty kilometres an hour. They eat fish, mostly sardines, and each penguin gets about half a kilo a day.\n\nThe keepers know every penguin by the black spots on its chest. The pattern is different for each bird, like a fingerprint. Feeding time is at eleven and at three, and that is the best moment to visit. The penguins get very noisy when they see the bucket of fish.',
    hoofd:{ v:'What is the text mainly about?', o:['The African penguins at a zoo', 'Why penguins cannot fly', 'Emperor penguins in Antarctica', 'How to become a zookeeper'], g:0, uit:'De tekst gaat over de Afrikaanse pinguïns in de dierentuin: waar ze vandaan komen, wat ze eten, hoe je ze herkent.' },
    detail:[{ v:'All penguins live in cold places.', o:['True', 'False'], g:1, uit:'<i>That is true for some of them</i>, maar Afrikaanse pinguïns komen van warme stranden.' },
            { v:'How do the keepers recognise each penguin?', o:['By the spots on its chest', 'By its voice', 'By its size', 'By a number on its leg'], g:0, uit:'<i>The keepers know every penguin by the black spots on its chest.</i>' }],
    woord:[{ w:'pattern', o:['patroon', 'kleur', 'geluid', 'vis'], g:0, uit:'The <i>pattern</i> of spots is different for each bird: het patroon, net als een vingerafdruk.' }],
    volgorde:{ items:['The text explains where African penguins come from.', 'The text tells how fast penguins swim.', 'The text explains how keepers recognise the birds.', 'The text tells when feeding time is.'], uit:'De volgorde van de alinea\'s: herkomst, zwemmen en eten, de vlekken, de voedertijden.' } },

  { id:'kgt5', n:'kgt', kop:'Too much screen time?',
    tekst:'How many hours a day do you look at a screen? For most teenagers in the UK, the answer is more than six. That includes school work, but also games, videos and chatting.\n\nDoctors say that a lot of screen time is not good for your sleep. The light from a screen tells your brain that it is still daytime. So if you watch videos in bed, you fall asleep later and you are tired the next morning. Sitting still for hours is also bad for your back and your eyes.\n\nDoes that mean screens are bad? Not really. The problem is the amount, not the screen. The advice is simple: put your phone away an hour before you go to sleep, take a break every thirty minutes, and go outside every day.',
    hoofd:{ v:'What is the text mainly about?', o:['Why too much screen time is a problem and what you can do about it', 'Why teenagers should not play games', 'How the brain works at night', 'The best videos for teenagers'], g:0, uit:'De tekst legt uit wat te veel schermtijd doet en geeft drie adviezen. Schermen zelf zijn niet slecht, zegt de tekst.' },
    detail:[{ v:'According to the text, screens are bad and you should not use them.', o:['True', 'False'], g:1, uit:'<i>The problem is the amount, not the screen.</i>' },
            { v:'What should you do an hour before you go to sleep?', o:['Put your phone away', 'Watch a video', 'Go outside', 'Do your homework'], g:0, uit:'<i>Put your phone away an hour before you go to sleep.</i>' }],
    woord:[{ w:'amount', o:['hoeveelheid', 'kleur', 'prijs', 'grootte'], g:0, uit:'The problem is the <i>amount</i>: de hoeveelheid, hoeveel uur je op een scherm kijkt.' }],
    volgorde:{ items:['You watch videos in bed.', 'The light tells your brain it is still daytime.', 'You fall asleep later.', 'You are tired the next morning.'], uit:'Zo staat het in de tekst: scherm in bed, licht houdt je brein wakker, later in slaap, moe de volgende ochtend.' } },

  { id:'kgt6', n:'kgt', kop:'Camping in the rain',
    tekst:'Last summer my family went camping in Wales for a week. My dad had promised us sunshine, mountains and swimming in a lake. We got the mountains.\n\nOn the first day it rained for eight hours. Our tent was old and water came in through the roof. My little brother cried, my mum laughed and my dad drove to the nearest town to buy a new tent. It was green and enormous, and it took us two hours to put it up.\n\nAfter that the holiday got better. We walked up a mountain, we cooked on a campfire and one evening we saw a family of wild ponies next to our tent. The lake was too cold for swimming, but we did not care. I want to go back next year, with the same tent and a better weather forecast.',
    hoofd:{ v:'What is the text mainly about?', o:['A camping holiday that started badly but turned out well', 'Why Wales is a bad place for a holiday', 'How to put up a tent', 'Wild ponies in Wales'], g:0, uit:'Het begon met regen en een lekkende tent, maar daarna werd het een fijne vakantie.' },
    detail:[{ v:'The family swam in the lake.', o:['True', 'False'], g:1, uit:'<i>The lake was too cold for swimming.</i>' },
            { v:'Why did the family need a new tent?', o:['Water came in through the roof', 'The old tent was too small', 'The tent blew away', 'They forgot the tent at home'], g:0, uit:'<i>Our tent was old and water came in through the roof.</i>' }],
    woord:[{ w:'enormous', o:['enorm', 'goedkoop', 'nat', 'oud'], g:0, uit:'The new tent was green and <i>enormous</i>: enorm, heel groot. Daarom duurde het twee uur om hem op te zetten.' }],
    volgorde:{ items:['It rains for eight hours.', 'Dad buys a new tent.', 'The family walks up a mountain.', 'They see wild ponies.'], uit:'Eerste dag regen, dan de nieuwe tent, daarna de bergwandeling, en op een avond de pony\'s.' } },

  /* ================= hv: B1 ================= */
  { id:'hv1', n:'hv', kop:'Town centre closes to cars',
    tekst:'From next month, cars will no longer be allowed in the centre of Milford between 10 a.m. and 6 p.m. The town council took the decision on Tuesday evening after a heated debate that lasted almost three hours.\n\nSupporters of the plan point to cleaner air and safer streets. "Last year two children were hit by cars on the high street," says councillor Ruth Okafor. "That has to stop." The council also hopes that more people will cycle or walk into town.\n\nNot everyone is pleased. Shop owners fear that customers will drive to the retail park outside town instead. "People with heavy bags won\'t walk a mile," says Ian Foster, who runs a hardware shop. The council has promised free parking at the edge of the centre and a shuttle bus every ten minutes. The scheme will be reviewed after six months.',
    hoofd:{ v:'What is the text mainly about?', o:['A town that is closing its centre to cars, and the reactions to that plan', 'Two children who were hit by cars', 'A hardware shop that is closing', 'Free parking in Milford'], g:0, uit:'Een nieuwsbericht over het besluit, met de argumenten voor en tegen.' },
    detail:[{ v:'Cars will be banned from the town centre at all times.', o:['True', 'False', 'Not stated'], g:1, uit:'Alleen <i>between 10 a.m. and 6 p.m.</i>, dus niet de hele dag.' },
            { v:'The shuttle bus will be free.', o:['True', 'False', 'Not stated'], g:2, uit:'De tekst noemt gratis parkeren en een shuttlebus om de tien minuten, maar zegt niets over de prijs van de bus. Dat staat er niet.' }],
    woord:[{ w:'heated', o:['angry and full of emotion', 'short and quiet', 'warm because of the weather', 'secret'], g:0, uit:'A <i>heated</i> debate is een verhit debat: fel, met emoties. Het duurde bijna drie uur.' },
           { w:'reviewed', o:['looked at again to see if it works', 'stopped', 'made bigger', 'written in a newspaper'], g:0, uit:'<i>The scheme will be reviewed</i>: na zes maanden wordt bekeken of het plan werkt.' }],
    volgorde:{ items:['Two children are hit by cars on the high street.', 'The council debates the plan for three hours.', 'Cars are banned from the centre during the day.', 'The scheme is reviewed.'], uit:'De ongelukken (vorig jaar) waren de aanleiding, dinsdag het debat, volgende maand het verbod, na zes maanden de evaluatie.' } },

  { id:'hv2', n:'hv', kop:'The message in the bottle',
    tekst:'Ella found the bottle on the beach. It was green, half buried in the sand, and there was a piece of paper inside. She broke it with a stone to get the paper out.\n\nThe message was dated 14 March 1998. "My name is Pieter. I am eleven and I live in Den Helder, in the Netherlands. If you find this, please write to me." An address followed.\n\nElla did the maths. Pieter would be nearly forty now, Ella thought. Would he still live there? Probably not, but she wrote a letter anyway.\n\nThree weeks later an envelope arrived with a Dutch stamp. Pieter had moved, but his mother still lived at the old address. He was now a teacher with two children. "I threw that bottle into the sea when I was your age," he wrote. "I had forgotten all about it. Thank you for reminding me."',
    hoofd:{ v:'What is the text mainly about?', o:['A girl who finds an old message in a bottle and gets a reply', 'A boy from Den Helder who becomes a teacher', 'How to send a letter to the Netherlands', 'A holiday on the beach'], g:0, uit:'Het verhaal draait om de fles, de brief van Ella en het antwoord van Pieter.' },
    detail:[{ v:'Pieter still lived at the address in the bottle.', o:['True', 'False', 'Not stated'], g:1, uit:'<i>Pieter had moved, but his mother still lived at the old address.</i>' },
            { v:'Ella found the bottle in the Netherlands.', o:['True', 'False', 'Not stated'], g:2, uit:'De tekst zegt niet op welk strand Ella de fles vond. Dat staat er niet.' }],
    woord:[{ w:'buried', o:['covered, hidden under something', 'broken', 'floating', 'shining'], g:0, uit:'<i>Half buried in the sand</i>: half onder het zand, bedolven.' }],
    volgorde:{ items:['Pieter throws a bottle into the sea.', 'Ella finds the bottle on the beach.', 'Ella sends a letter to the address.', 'A letter with a Dutch stamp arrives.'], uit:'1998: de fles in zee. Dan vindt Ella hem, schrijft een brief, en drie weken later komt het antwoord.' } },

  { id:'hv3', n:'hv', kop:'Should schools ban smartphones?',
    tekst:'More and more schools in Europe are banning smartphones during the school day. France has had a national ban since 2018, and the Netherlands followed in 2024. Pupils leave their phones at home or in a locker. Is that a good idea?\n\nThe argument in favour is clear. Research shows that pupils concentrate better when their phone is out of reach, even when it is switched off. Teachers report fewer arguments, and pupils say they talk to each other more.\n\nCritics say a ban treats teenagers like children. "We should teach young people to use their phones sensibly instead of taking them away," says one head teacher. Others say phones are useful in lessons, for looking things up or recording an experiment.\n\nThe studies agree on one thing: the effect of a ban is biggest for pupils who were struggling at school. For them, a phone-free day really helps.',
    hoofd:{ v:'What is the text mainly about?', o:['The arguments for and against banning phones at school', 'Why France banned phones in 2018', 'How to use a phone in a science lesson', 'Why teenagers argue in the playground'], g:0, uit:'De tekst geeft de argumenten voor en tegen een telefoonverbod, en wat de onderzoeken zeggen.' },
    detail:[{ v:'Pupils concentrate better only when the phone is switched off.', o:['True', 'False', 'Not stated'], g:1, uit:'<i>Even when it is switched off</i>: het gaat erom dat de telefoon buiten bereik is, uit of niet.' },
            { v:'Most teachers in the Netherlands support the ban.', o:['True', 'False', 'Not stated'], g:2, uit:'De tekst zegt wat leraren melden, maar niet hoeveel Nederlandse leraren voor het verbod zijn. Dat staat er niet.' }],
    woord:[{ w:'sensibly', o:['in a wise, careful way', 'as often as possible', 'secretly', 'quickly'], g:0, uit:'<i>Use their phones sensibly</i>: verstandig, met beleid.' },
           { w:'struggling', o:['having difficulties', 'doing very well', 'being absent', 'fighting'], g:0, uit:'Pupils who were <i>struggling</i> at school: leerlingen die het moeilijk hadden. Voor hen helpt een verbod het meest.' }],
    volgorde:{ items:['France introduces a national ban.', 'The Netherlands introduces a ban.', 'The text gives the arguments in favour.', 'The text gives the arguments of the critics.'], uit:'2018 Frankrijk, 2024 Nederland; daarna in de tekst eerst de argumenten voor, dan die van de critici.' } },

  { id:'hv4', n:'hv', kop:'The runner who never gave up',
    tekst:'When Sarah Mitchell lined up for the London Marathon in April, nobody knew her story. Two years earlier she had spent six months in hospital after a car accident. Doctors had told her she might never walk without a stick again.\n\n"The first time I tried to run, I managed about fifty metres," she says. "Then I sat on a bench and cried. But the next day I did sixty." She wrote down every distance in a notebook. Within a year she could run five kilometres; within eighteen months, a half marathon.\n\nSarah finished in four hours and twelve minutes. She was not the fastest runner that day, and she did not want to be. "I just wanted to cross the line on my own two feet," she says. She raised more than £9,000 for the hospital that treated her, and has already signed up for next year.',
    hoofd:{ v:'What is the text mainly about?', o:['A woman who ran a marathon after a serious accident', 'How to train for a marathon in a year', 'The London Marathon', 'A hospital that needs money'], g:0, uit:'Het portret van Sarah: het ongeluk, de eerste vijftig meter, en de marathon.' },
    detail:[{ v:'Sarah was the fastest runner of the day.', o:['True', 'False', 'Not stated'], g:1, uit:'<i>She was not the fastest runner that day, and she did not want to be.</i>' },
            { v:'Sarah was driving the car when the accident happened.', o:['True', 'False', 'Not stated'], g:2, uit:'De tekst zegt alleen dat er een auto-ongeluk was, niet wie er reed. Dat staat er niet.' }],
    woord:[{ w:'managed', o:['succeeded in doing', 'refused', 'measured', 'ran past'], g:0, uit:'<i>I managed about fifty metres</i>: het lukte haar om vijftig meter te rennen, meer niet.' },
           { w:'raised', o:['collected', 'spent', 'lifted', 'borrowed'], g:0, uit:'<i>She raised more than £9,000</i>: ze haalde geld op, zamelde het in voor het ziekenhuis.' }],
    volgorde:{ items:['Sarah spends six months in hospital.', 'She runs fifty metres and cries on a bench.', 'She runs a half marathon.', 'She finishes the London Marathon.'], uit:'Het ongeluk en het ziekenhuis, de eerste poging, na anderhalf jaar de halve marathon, en in april de hele.' } },

  { id:'hv5', n:'hv', kop:'Why bees matter',
    tekst:'Imagine a supermarket without apples, strawberries, almonds or coffee. That is a world without bees. About a third of our food depends on insects that carry pollen from one flower to another, and honeybees and wild bees do most of that work.\n\nUnfortunately, bees are in trouble. In many European countries the number of wild bee species has dropped sharply in thirty years. Scientists point to three causes: pesticides, the loss of wild flowers and hedges, and a warmer climate that confuses the bees\' timing. When flowers open earlier than usual, bees may wake up too late to find them.\n\nThe good news: anyone can help. A balcony with a few pots of lavender is a restaurant for bees. Gardens with long grass and clover are even better. Some cities now mow their roadsides only twice a year, and the number of bees there has doubled.',
    hoofd:{ v:'What is the text mainly about?', o:['Why bees are important, why they are in danger, and how people can help', 'How to keep honeybees on a balcony', 'Why supermarkets sell fewer apples', 'The effects of a warmer climate'], g:0, uit:'Drie alinea\'s: waarom bijen belangrijk zijn, waarom ze in de problemen zitten, en wat je kunt doen.' },
    detail:[{ v:'Honeybees do all the pollination work.', o:['True', 'False', 'Not stated'], g:1, uit:'<i>Honeybees and wild bees do most of that work</i>: het meeste, niet alles, en ook wilde bijen.' },
            { v:'Lavender is the best plant for bees.', o:['True', 'False', 'Not stated'], g:2, uit:'Lavendel wordt genoemd als een klein restaurant voor bijen, maar de tekst zegt niet dat het de beste plant is. Dat staat er niet.' }],
    woord:[{ w:'sharply', o:['a lot, in a short time', 'a little bit', 'slowly', 'for the first time'], g:0, uit:'<i>Dropped sharply</i>: sterk gedaald, in korte tijd flink minder.' },
           { w:'confuses', o:['makes something go wrong', 'helps', 'warms up', 'kills'], g:0, uit:'A warmer climate <i>confuses</i> the bees\' timing: het brengt hun timing in de war.' }],
    volgorde:{ items:['Flowers open earlier than usual.', 'Bees wake up too late to find them.', 'The number of bee species drops.', 'Cities mow their roadsides less often.'], uit:'De oorzaak-gevolgketen uit de tekst: vroege bloemen, bijen te laat, minder soorten; en daarna de oplossing van de steden.' } },

  { id:'hv6', n:'hv', kop:'The truth about sugar',
    tekst:'A can of cola contains nine teaspoons of sugar. Most people know that. Fewer people know that a fruit yoghurt, a bowl of cereal or a glass of orange juice can contain almost as much.\n\nSugar is not poison. Your body needs it, and the sugar in a piece of fruit comes with fibre and vitamins. The problem is added sugar: the sugar that manufacturers put into products so they taste better and last longer. Health organisations advise a maximum of about six teaspoons of added sugar a day for teenagers. The average British teenager eats nearly three times that amount.\n\nWhat can you do? Read labels, because sugar hides under many names: glucose, syrup, dextrose, honey. Drink water instead of juice or fizzy drinks. And do not try to give up sugar completely; that rarely works. Cutting down a little every week is a habit you can keep.',
    hoofd:{ v:'What is the text mainly about?', o:['Hidden added sugar in food and how to eat less of it', 'Why cola is bad for your teeth', 'The vitamins in fruit', 'Why you should never eat sugar'], g:0, uit:'De tekst gaat over toegevoegde suiker, waar die verstopt zit en hoe je minder kunt eten. Niet: nooit meer suiker.' },
    detail:[{ v:'According to the text, you should stop eating sugar completely.', o:['True', 'False', 'Not stated'], g:1, uit:'<i>Do not try to give up sugar completely; that rarely works.</i>' },
            { v:'Orange juice contains more sugar than cola.', o:['True', 'False', 'Not stated'], g:2, uit:'De tekst zegt <i>almost as much</i>: bijna evenveel. Meer of minder precies staat er niet.' }],
    woord:[{ w:'manufacturers', o:['companies that make products', 'shops', 'doctors', 'farmers'], g:0, uit:'<i>Manufacturers</i> zijn fabrikanten: de bedrijven die de producten maken en er suiker aan toevoegen.' },
           { w:'rarely', o:['almost never', 'always', 'quickly', 'easily'], g:0, uit:'<i>That rarely works</i>: dat werkt zelden, bijna nooit.' }],
    volgorde:{ items:['The text gives the amount of sugar in a can of cola.', 'The text explains the difference between natural and added sugar.', 'The text gives the advice for teenagers.', 'The text tells you to read labels.'], uit:'De opbouw van de tekst: het voorbeeld van de cola, natuurlijke en toegevoegde suiker, het advies, en de tips.' } }
];
