/* De berichten van Formeel of informeel. In een eigen bestand zodat ze na te
   lezen zijn. Niveau n: 1 = vmbo-bb, 2 = vmbo-kgt en tl, 3 = havo en vwo.
   HERKENNEN:   [n, bericht, 'formeel' of 'informeel', uitleg met de kenmerken]
   KIES:        [n, de boodschap (wat je wilt zeggen), formele versie (goed), informele versie, informele versie, uitleg]
   HERSCHRIJVEN:[n, de informele zin, de formele zin met ___ op de plek van het woord, [goede woorden], uitleg]
   ZINNEN:      [n, zin, 'app' (appje aan een vriend), 'mail' (e-mail aan een docent) of 'brief' (sollicitatiebrief)] */
var REGISTER = (function(){
var HERKENNEN = [
  [1, 'Hoi! Kom je ff langs? Heb je game nog.', 'informeel', 'Hoi, ff en een zin zonder onderwerp: zo praat je met een vriend.'],
  [1, 'Geachte mevrouw Jansen, hierbij meld ik mijn dochter ziek voor vandaag.', 'formeel', 'Geachte, de volledige naam en een hele zin: zo schrijf je aan school.'],
  [1, 'Ben je er al?? Ik sta bij de ingang 😅', 'informeel', 'Dubbele vraagtekens en een emoji: dat is een appje, geen brief.'],
  [1, 'Beste meneer De Vries, ik kan morgen niet op de les komen omdat ik naar de tandarts moet.', 'formeel', 'Beste meneer, een reden en een hele zin: netjes en formeel.'],
  [1, 'Ja joh, komt goed. Tot zo!', 'informeel', 'Ja joh en komt goed: spreektaal voor vrienden.'],
  [1, 'Zou u mij kunnen laten weten wanneer de toets is?', 'formeel', 'U en zou u kunnen: beleefd en formeel.'],
  [1, 'Lol, wat een dag. Morgen weer?', 'informeel', 'Lol en korte flarden: informeel.'],
  [1, 'Met vriendelijke groet, Sam de Boer', 'formeel', 'Met vriendelijke groet en de volledige naam: het slot van een formele brief.'],
  [1, 'Heb je het huiswerk? Stuur ff.', 'informeel', 'Ff (even) en een bevel zonder alsjeblieft: informeel.'],
  [1, 'Wilt u mij alstublieft terugbellen op dit nummer?', 'formeel', 'U, alstublieft en een volledige vraag: formeel.'],
  [1, 'Yo, ga je mee naar de stad? 🛹', 'informeel', 'Yo en een emoji: zo praat je met een vriend.'],
  [1, 'Hartelijk dank voor uw snelle antwoord.', 'formeel', 'Hartelijk dank en uw: beleefd en formeel.'],
  [1, 'Ik ben te laat, sorry!! Trein was kapot.', 'informeel', 'Dubbele uitroeptekens en een zin zonder lidwoord: informeel.'],
  [1, 'Ik wil graag een afspraak maken met de mentor van mijn zoon.', 'formeel', 'Ik wil graag en een volledige, nette zin: formeel.'],
  [1, 'Hey, ben je morgen ook op school? 😴', 'informeel', 'Hey en een emoji: een appje aan een vriend.'],
  [1, 'Geachte heer Pieters, graag wil ik mij afmelden voor de sportdag.', 'formeel', 'Geachte heer, graag wil ik en een hele zin: formeel.'],
  [1, 'Oké top, ik neem de bal mee!', 'informeel', 'Oké top en een uitroepteken: spreektaal.'],
  [1, 'Kunt u mij vertellen in welk lokaal de les is?', 'formeel', 'Kunt u en een volledige vraag: beleefd en formeel.'],
  [1, 'Geachte heer Smit, graag wil ik een nieuw rooster ontvangen.', 'formeel', 'Geachte heer en graag wil ik: formeel.'],
  [1, 'Haha top! Zie je morgen 😄', 'informeel', 'Haha, top en een emoji: een appje aan een vriend.'],
  [1, 'Kunt u mij zeggen hoe laat de winkel opengaat?', 'formeel', 'Kunt u en een volledige vraag: beleefd en formeel.'],
  [1, 'Ff wachten, ben er zo!', 'informeel', 'Ff en een zin zonder onderwerp: informeel.'],
  [2, 'Hé, kun je me die foto’s van gister nog sturen? Thnx!', 'informeel', 'Hé, gister en thnx: afkortingen en spreektaal voor een vriend.'],
  [2, 'Naar aanleiding van uw e-mail stuur ik u hierbij de gevraagde gegevens.', 'formeel', 'Naar aanleiding van, uw en hierbij: typische formele woorden.'],
  [2, 'Ik was echt sooo moe vandaag, jij ook?', 'informeel', 'Sooo met extra letters: dat schrijf je alleen aan een vriend.'],
  [2, 'Ik zou graag willen weten of ik de toets op een ander moment mag inhalen.', 'formeel', 'Ik zou graag willen weten: een beleefde, volledige vraag.'],
  [2, 'Nee joh, dat hoeft niet, doe maar rustig aan 😊', 'informeel', 'Joh, doe maar rustig aan en een emoji: informeel.'],
  [2, 'Ik verzoek u vriendelijk om het formulier voor vrijdag terug te sturen.', 'formeel', 'Ik verzoek u vriendelijk: formeel en beleefd.'],
  [2, 'Wat ga jij doen in de vakantie? Wij gaan kamperen, best chill.', 'informeel', 'Jij, wij en chill: spreektaal.'],
  [2, 'Bij deze bevestig ik dat ik aanwezig zal zijn op de ouderavond van 12 maart.', 'formeel', 'Bij deze bevestig ik en een datum: formeel.'],
  [2, 'Haha nee, dat was een grapje. Zie je morgen!', 'informeel', 'Haha en een grapje: informeel.'],
  [2, 'Ik heb uw bericht in goede orde ontvangen en neem morgen contact met u op.', 'formeel', 'In goede orde ontvangen en contact opnemen: kantoortaal, formeel.'],
  [2, 'Kun je me het adres appen? Ik weet niet meer waar het is.', 'informeel', 'Appen en een losse toon: informeel.'],
  [2, 'Helaas moet ik de afspraak van dinsdag afzeggen wegens ziekte.', 'formeel', 'Helaas, afzeggen en wegens: formeel en volledig.'],
  [2, 'Oké maar dan neem jij de chips mee, deal?', 'informeel', 'Deal en een korte, losse zin: informeel.'],
  [2, 'Zou het mogelijk zijn om het gesprek een half uur later te laten beginnen?', 'formeel', 'Zou het mogelijk zijn: een heel beleefde vraag.'],
  [2, 'Hierbij stuur ik u de ingevulde toestemmingsverklaring voor de excursie.', 'formeel', 'Hierbij stuur ik u: formeel.'],
  [2, 'Heb je nog zin om vanavond te gamen? Ben vanaf 8 uur online.', 'informeel', 'Zin om te gamen, een zin zonder onderwerp en een losse toon: informeel.'],
  [2, 'Mag ik u vragen of de les van morgen doorgaat?', 'formeel', 'Mag ik u vragen: een beleefde, formele vraag.'],
  [2, 'Omg, heb je die nieuwe video gezien?? Echt te grappig', 'informeel', 'Omg, dubbele vraagtekens en echt te grappig: informeel.'],
  [2, 'Graag wil ik mij aanmelden voor de open dag van 18 januari.', 'formeel', 'Graag wil ik mij aanmelden en een datum: formeel.'],
  [2, 'Heb je de uitslag al? Ik durf niet te kijken 🙈', 'informeel', 'Een losse vraag aan een vriend en een emoji: informeel.'],
  [2, 'Wij verzoeken u de fiets voortaan in het rek te plaatsen.', 'formeel', 'Wij verzoeken u en voortaan: formele taal.'],
  [2, 'Lekker bezig man, echt goed gedaan!', 'informeel', 'Lekker bezig en man: spreektaal voor een vriend.'],
  [3, 'Hierbij solliciteer ik naar de functie van vakkenvuller in uw filiaal.', 'formeel', 'Hierbij solliciteer ik en uw filiaal: een sollicitatiebrief.'],
  [3, 'Nee man, die docent snapt er echt niks van 😂', 'informeel', 'Nee man, niks en een emoji: alleen voor vrienden.'],
  [3, 'Ik hoop u hiermee voldoende te hebben geïnformeerd.', 'formeel', 'Een vaste formele slotzin uit brieven en e-mails.'],
  [3, 'Kun je ff kijken of je mijn oplader nog hebt? Ben m kwijt.', 'informeel', 'Ff, m en zinnen zonder onderwerp: informeel.'],
  [3, 'Graag ontvang ik van u een bevestiging van de inschrijving.', 'formeel', 'Graag ontvang ik van u: beleefd en zakelijk.'],
  [3, 'Ik snap er niks van, die toets was echt onmogelijk, iedereen zegt dat.', 'informeel', 'Niks, echt onmogelijk en een lange spreektaalzin: informeel.'],
  [3, 'In de bijlage vindt u mijn cv en een kopie van mijn diploma.', 'formeel', 'In de bijlage vindt u: formeel, uit een sollicitatie.'],
  [3, 'Effe serieus: gaan we nou zaterdag of niet?', 'informeel', 'Effe serieus en nou: spreektaal.'],
  [3, 'Ik zie uw reactie met belangstelling tegemoet.', 'formeel', 'Een vaste, formele slotzin: ik wacht op uw antwoord.'],
  [3, 'Sws gaan we, ik heb al kaartjes 🎉', 'informeel', 'Sws (sowieso) en een emoji: informeel.'],
  [3, 'Naar mijn mening is de nieuwe regeling onvoldoende toegelicht aan de leerlingen.', 'formeel', 'Naar mijn mening en onvoldoende toegelicht: zakelijk en formeel.'],
  [3, 'Dat is echt zooo oneerlijk, waarom krijgt zij wel een herkansing?!', 'informeel', 'Zooo, echt en ?!: informeel.'],
  [3, 'Ik verneem graag of er nog plaatsen beschikbaar zijn voor de cursus.', 'formeel', 'Ik verneem graag: een formele manier om iets te vragen.'],
  [3, 'Kom je nog of hoe zit het? We wachten al een half uur hoor.', 'informeel', 'Hoe zit het en hoor: spreektaal.'],
  [3, 'Gaarne ontvang ik uiterlijk vrijdag uw reactie.', 'formeel', 'Gaarne en uiterlijk: ouderwets formele woorden uit zakelijke brieven.'],
  [3, 'Bro, die presentatie ging echt top, respect 💪', 'informeel', 'Bro, echt top en een emoji: informeel.'],
  [3, 'Ik dank u bij voorbaat voor uw medewerking.', 'formeel', 'Bij voorbaat en uw medewerking: een vaste formele slotzin.'],
  [3, 'Kun je me ff helpen met dat verslag? Ik kom er echt niet uit 😩', 'informeel', 'Ff, echt niet uit en een emoji: informeel.'],
  [3, 'Gelet op het bovenstaande verzoek ik u het besluit te heroverwegen.', 'formeel', 'Gelet op het bovenstaande en heroverwegen: zakelijk en formeel.'],
  [3, 'Ik ben echt kapot, ga pitten. Spreek je morgen!', 'informeel', 'Kapot, pitten en een zin zonder onderwerp: spreektaal.'],
  [3, 'Mocht u verhinderd zijn, dan verzoeken wij u dit tijdig te melden.', 'formeel', 'Mocht u, verhinderd en tijdig: formele woorden.'],
  [3, 'Wie heeft dat verslag gemaakt? Echt next level 🔥', 'informeel', 'Next level, echt en een emoji: informeel.']
];
var KIES = [
  [1, 'Je bent ziek en kunt niet naar school.', 'Geachte mevrouw De Groot, ik ben ziek en kan vandaag niet naar school komen.', 'Hoi, ben ziek, kom niet.', 'Yo mevrouw, ik ben ziek dus ik kom niet 🤒', 'Geachte, een hele zin en geen emoji: dat past in een bericht aan school.'],
  [1, 'Je wilt weten hoe laat de excursie begint.', 'Beste meneer Smit, kunt u mij laten weten hoe laat de excursie begint?', 'Hoe laat is die excursie?', 'Hé, hoe laat moeten we er zijn morgen?', 'Beste meneer, u en een volledige vraag: formeel.'],
  [1, 'Je bent je boek kwijt en vraagt om een nieuwe.', 'Geachte heer Bakker, ik ben mijn boek kwijt. Kan ik een nieuw exemplaar krijgen?', 'Ik ben me boek kwijt, heb je er nog een?', 'Boek kwijt 😬 nieuwe?', 'Geachte heer en kan ik: beleefd gevraagd.'],
  [1, 'Je wilt een afspraak met je mentor.', 'Beste mevrouw Ali, ik wil graag een afspraak met u maken. Wanneer komt het u uit?', 'Kun je ff afspreken?', 'Hoi, heb je tijd om te praten?', 'Ik wil graag, u en wanneer komt het u uit: formeel.'],
  [1, 'Je bedankt de bibliotheek voor de hulp.', 'Hartelijk dank voor uw hulp bij het zoeken naar de boeken.', 'Thnx voor het helpen!', 'Bedankt he, top!', 'Hartelijk dank en uw: formeel.'],
  [1, 'Je vraagt of je de toets mag inhalen.', 'Beste meneer Visser, mag ik de toets van maandag op een ander moment inhalen?', 'Mag ik die toets nog doen?', 'Kan ik die toets inhalen ofzo?', 'Beste meneer en een nette vraag: formeel.'],
  [1, 'Je meldt dat je te laat komt.', 'Geachte mevrouw Kok, ik kom later omdat mijn bus is uitgevallen.', 'Ben laat, bus kapot.', 'Sorry!! Kom later, bus is weg 😩', 'Geachte, omdat en een hele zin: formeel.'],
  [1, 'Je vraagt naar de prijs van een fiets in een winkel.', 'Geachte heer of mevrouw, kunt u mij de prijs van deze fiets laten weten?', 'Hoeveel kost die fiets?', 'Wat moet die fiets kosten?', 'Geachte heer of mevrouw gebruik je als je niet weet aan wie je schrijft.'],
  [1, 'Je zegt dat je niet naar de training kunt komen.', 'Beste trainer, helaas kan ik donderdag niet op de training komen.', 'Kom donderdag niet, sorry.', 'Skip donderdag, ok?', 'Beste trainer en helaas: netjes afgezegd.'],
  [1, 'Je wilt lid worden van de sportclub.', 'Geachte heer De Wit, ik wil graag lid worden van uw club. Hoe kan ik mij aanmelden?', 'Ik wil lid worden, hoe doe ik dat?', 'Kan ik meedoen bij jullie?', 'Ik wil graag en uw club: formeel.'],
  [1, 'Je wenst je docent beterschap.', 'Beste mevrouw Post, ik wens u van harte beterschap.', 'Beterschap he!', 'Word snel beter 🌸', 'Beste mevrouw en ik wens u: formeel.'],
  [1, 'Je vraagt om uitleg over je cijfer.', 'Beste meneer Kuipers, kunt u mij uitleggen hoe mijn cijfer tot stand is gekomen?', 'Waarom heb ik een 5?', 'Hoe kom ik aan die 5??', 'Kunt u mij uitleggen: beleefd en volledig.'],
  [1, 'Je meldt je aan voor de schoolreis.', 'Beste mevrouw Ekker, hierbij meld ik mij aan voor de schoolreis naar Parijs.', 'Ik ga mee naar Parijs!', 'Zet mij maar op de lijst voor Parijs', 'Hierbij meld ik mij aan: formeel.'],
  [1, 'Je vraagt of je iets mag lenen van de conciërge.', 'Beste meneer Pot, mag ik een pomp lenen voor mijn fiets?', 'Heb je een pomp?', 'Pomp lenen? Band leeg 😑', 'Beste meneer en mag ik lenen: netjes gevraagd.'],
  [1, 'Je vraagt je docent of hij je telefoon heeft gevonden.', 'Beste meneer Dekker, heeft u misschien mijn telefoon in lokaal 12 gevonden?', 'Heb jij mijn telefoon gezien?', 'Telefoon kwijt, ligt ie bij u?? 😭', 'Beste meneer, heeft u en een volledige vraag: formeel.'],
  [1, 'Je bedankt je mentor voor een goed gesprek.', 'Beste mevrouw Smits, bedankt voor het fijne gesprek van vandaag.', 'Thnx voor het praten!', 'Was chill om te praten, top!', 'Beste mevrouw en een hele zin: netjes bedankt.'],
  [1, 'Je vraagt of het zwembad op zondag open is.', 'Geachte heer of mevrouw, is het zwembad op zondag geopend?', 'Is het zwembad zondag open?', 'Yo, kan ik zondag komen zwemmen?', 'Geachte heer of mevrouw schrijf je als je niet weet wie de mail leest.'],
  [1, 'Je meldt je docent dat je je huiswerk vergeten bent.', 'Beste meneer Jansen, helaas ben ik mijn huiswerk vergeten. Ik neem het morgen mee.', 'Huiswerk vergeten, sorry!', 'Oeps, ben me huiswerk vergeten 🙈', 'Helaas en hele zinnen: formeel.'],
  [1, 'Je vraagt of de gymles morgen doorgaat.', 'Beste meneer Wouters, kunt u mij laten weten of de gymles morgen doorgaat?', 'Gaat gym morgen door?', 'Hé, hebben we morgen nou gym of niet?', 'Beste meneer en kunt u mij laten weten: formeel.'],
  [1, 'Je meldt dat je jas in het lokaal is blijven liggen.', 'Beste mevrouw Dijkstra, ik heb mijn jas in lokaal 8 laten liggen. Heeft u hem misschien gevonden?', 'Mijn jas ligt nog in lokaal 8.', 'Jas vergeten 🙈 heb jij m?', 'Beste mevrouw, heeft u en hele zinnen: formeel.'],
  [1, 'Je bedankt de conciërge voor het repareren van je kluisje.', 'Beste meneer Van Loon, hartelijk dank voor het repareren van mijn kluisje.', 'Thnx voor mijn kluisje!', 'Top dat je m gemaakt hebt!', 'Hartelijk dank en een hele zin: netjes bedankt.'],
  [1, 'Je vraagt of je een boek uit de klas mag lenen.', 'Beste mevrouw Veenstra, mag ik het boek over dinosaurussen een week lenen?', 'Mag ik dat boek lenen?', 'Kan ik dat dinoboek ff meenemen?', 'Beste mevrouw en mag ik: een beleefde vraag.'],
  [2, 'Je zegt dat je een afspraak wilt verzetten.', 'Geachte mevrouw Roos, zou het mogelijk zijn onze afspraak van dinsdag te verzetten naar woensdag?', 'Kan dinsdag niet, woensdag?', 'Hoi, kunnen we dinsdag verzetten naar woensdag?', 'Zou het mogelijk zijn: heel beleefd, past in een e-mail aan school.'],
  [2, 'Je bent het niet eens met een regel op school.', 'Beste directie, ik wil graag mijn bezwaar uiten tegen de nieuwe regel over telefoons.', 'Die telefoonregel slaat nergens op.', 'Wie heeft die regel bedacht?!', 'Mijn bezwaar uiten: formeel en zakelijk, ook al ben je het oneens.'],
  [2, 'Je vraagt een bedrijf of je stage mag lopen.', 'Geachte heer Van Dam, ik zou graag stage lopen bij uw bedrijf. Is daar een mogelijkheid voor?', 'Kan ik bij jullie stage lopen?', 'Hoi, hebben jullie nog een stageplek?', 'Ik zou graag en uw bedrijf: formeel.'],
  [2, 'Je bedankt na een gesprek.', 'Hartelijk dank voor het prettige gesprek van vanmiddag.', 'Thnx voor het gesprek!', 'Was een goed gesprek, bedankt he.', 'Hartelijk dank voor het prettige gesprek: een formele bedankzin.'],
  [2, 'Je meldt een fout in het rooster.', 'Beste mevrouw Hendriks, in mijn rooster staat een les dubbel. Kunt u dit nakijken?', 'Mijn rooster klopt niet.', 'Er zit een fout in mijn rooster, fix?', 'Kunt u dit nakijken: een beleefd verzoek.'],
  [2, 'Je vraagt om een uitstel voor een werkstuk.', 'Beste meneer Lam, zou ik het werkstuk een dag later mogen inleveren? Ik ben deze week ziek geweest.', 'Kan ik het werkstuk later inleveren?', 'Werkstuk later ok? Was ziek.', 'Zou ik mogen en een reden: formeel.'],
  [2, 'Je meldt dat je een pakket niet hebt ontvangen.', 'Geachte heer of mevrouw, ik heb mijn bestelling van 3 mei nog niet ontvangen. Kunt u mij laten weten waar deze is?', 'Waar blijft mijn pakket?', 'Mijn pakket is er nog steeds niet, hallo??', 'Geachte heer of mevrouw en kunt u mij laten weten: formeel aan een bedrijf.'],
  [2, 'Je vraagt of je een dag vrij mag voor een bruiloft.', 'Beste mevrouw Brink, mag ik op 14 juni vrij zijn voor de bruiloft van mijn tante?', 'Mag ik 14 juni vrij? Bruiloft.', 'Ik ben 14 juni niet op school, bruiloft 💒', 'Mag ik en een datum: netjes gevraagd.'],
  [2, 'Je bevestigt dat je op de ouderavond komt.', 'Hierbij bevestig ik dat ik op 12 maart aanwezig zal zijn op de ouderavond.', 'Ik kom 12 maart.', 'Ja, ik ben erbij op de 12e!', 'Hierbij bevestig ik: formeel.'],
  [2, 'Je vraagt om informatie over een cursus.', 'Geachte heer of mevrouw, kunt u mij informatie sturen over de cursus fotografie?', 'Heb je info over die fotocursus?', 'Wat kost die fotocursus?', 'Kunt u mij informatie sturen: formeel.'],
  [2, 'Je zegt dat je een abonnement wilt opzeggen.', 'Geachte heer of mevrouw, hierbij zeg ik mijn abonnement per 1 juli op.', 'Ik wil stoppen met mijn abonnement.', 'Zet mijn abonnement maar stop.', 'Hierbij zeg ik op en een datum: formeel.'],
  [2, 'Je vraagt je docent om een aanbevelingsbrief.', 'Beste mevrouw Kraan, zou u een aanbevelingsbrief voor mij willen schrijven voor mijn aanmelding?', 'Kun je een brief voor me schrijven?', 'Wil je iets aardigs over me schrijven voor mijn aanmelding?', 'Zou u willen: een beleefd verzoek aan een docent.'],
  [2, 'Je meldt schade aan een gehuurde fiets.', 'Geachte heer Mol, tijdens het huren is de fiets beschadigd geraakt. Ik wil dit graag met u bespreken.', 'De fiets is kapot, sorry.', 'Fiets beschadigd, wat nu?', 'Ik wil dit graag met u bespreken: formeel en netjes.'],
  [2, 'Je vraagt naar de uitslag van een sollicitatie.', 'Geachte mevrouw Sol, ik ben benieuwd of u al een beslissing heeft genomen over mijn sollicitatie.', 'Heb je al gekozen?', 'En, heb ik de baan?', 'Ik ben benieuwd of u: formeel en geduldig.'],
  [2, 'Je vraagt een sportschool naar de prijs van een jeugdabonnement.', 'Geachte heer of mevrouw, kunt u mij laten weten wat een jeugdabonnement kost?', 'Wat kost een abo bij jullie?', 'Hoi, hoeveel betaal je voor een jeugdabonnement?', 'Kunt u mij laten weten: formeel aan een bedrijf.'],
  [2, 'Je meldt je docent dat je verslag niet wil uploaden.', 'Beste meneer Hoek, het lukt mij niet om mijn verslag te uploaden. Mag ik het per e-mail sturen?', 'Uploaden lukt niet, wat nu?', 'Die site doet het weer niet 🙄', 'Het lukt mij niet en mag ik: formeel.'],
  [2, 'Je vraagt of je een boek langer mag lenen.', 'Geachte heer of mevrouw, zou ik de uitleentermijn van mijn boek met twee weken mogen verlengen?', 'Mag ik mijn boek langer houden?', 'Kan ik dat boek nog ff houden?', 'Zou ik mogen en de uitleentermijn verlengen: formeel.'],
  [2, 'Je nodigt de directeur uit voor de musical van je klas.', 'Geachte mevrouw Van Dijk, graag nodigen wij u uit voor de musical van klas 2B op vrijdag 8 maart.', 'Kom je naar onze musical?', 'Hé, vrijdag is onze musical, kom je ook?', 'Graag nodigen wij u uit: formeel.'],
  [2, 'Je vraagt de gemeente wanneer het grofvuil wordt opgehaald.', 'Geachte heer of mevrouw, kunt u mij laten weten wanneer het grofvuil in onze straat wordt opgehaald?', 'Wanneer halen jullie het grofvuil op?', 'Hoi, wanneer komt de vuilniswagen voor die oude bank?', 'Geachte heer of mevrouw en kunt u mij laten weten: formeel aan een instantie.'],
  [2, 'Je meldt je af voor een bijlesuur.', 'Beste meneer Timmer, helaas kan ik donderdag niet naar de bijles komen, omdat ik naar het ziekenhuis moet.', 'Kan donderdag niet, ziekenhuis.', 'Ik skip donderdag ff, moet naar het ziekenhuis.', 'Helaas en een reden in een hele zin: formeel.'],
  [2, 'Je vraagt een winkel wanneer een product weer op voorraad is.', 'Geachte heer of mevrouw, kunt u mij laten weten wanneer deze schoenen weer op voorraad zijn?', 'Wanneer zijn die schoenen er weer?', 'Hebben jullie die sneakers nou nog of niet?', 'Kunt u mij laten weten: formeel aan een winkel.'],
  [2, 'Je vraagt je mentor om een gesprek over je profielkeuze.', 'Beste mevrouw Hoekstra, ik wil graag met u praten over mijn profielkeuze. Wanneer zou het u schikken?', 'Kunnen we praten over mijn profiel?', 'Hé, heb je ff tijd voor mijn profielkeuze?', 'Wanneer zou het u schikken: heel beleefd.'],
  [3, 'Je solliciteert naar een bijbaan.', 'Geachte heer Van Leeuwen, met veel belangstelling heb ik uw vacature voor een weekendhulp gelezen. Graag solliciteer ik naar deze functie.', 'Ik wil graag bij jullie werken in het weekend.', 'Hoi, ik zag dat jullie iemand zoeken voor het weekend, kan ik dat doen?', 'Met veel belangstelling en graag solliciteer ik: de vaste formules van een sollicitatiebrief.'],
  [3, 'Je dient een klacht in bij een bedrijf.', 'Geachte heer of mevrouw, hierbij dien ik een klacht in over de levering van mijn bestelling.', 'Dit is echt slecht geregeld.', 'Ik heb een klacht: mijn pakket is kapot.', 'Hierbij dien ik een klacht in: formeel, zonder boze woorden.'],
  [3, 'Je vraagt om uitstel voor een deadline.', 'Beste mevrouw Ter Horst, in verband met ziekte verzoek ik u vriendelijk om uitstel van de deadline tot 20 mei.', 'Kan de deadline naar 20 mei? Was ziek.', 'Ik red 15 mei niet, mag het 20 mei worden?', 'In verband met en verzoek ik u vriendelijk: formeel.'],
  [3, 'Je bedankt een bedrijf na een stage.', 'Geachte mevrouw Oost, hartelijk dank voor de leerzame stageperiode bij uw bedrijf.', 'Bedankt voor de stage, was leuk!', 'Thanks voor alles, ik heb veel geleerd 🙏', 'Hartelijk dank voor de leerzame stageperiode: formeel slot.'],
  [3, 'Je vraagt een gemeente om informatie over een vergunning.', 'Geachte heer of mevrouw, ik zou graag informatie ontvangen over de vergunning voor een buurtfeest.', 'Hebben we een vergunning nodig voor een feest?', 'Mag ik een buurtfeest geven of moet ik iets aanvragen?', 'Ik zou graag informatie ontvangen: formeel aan een instantie.'],
  [3, 'Je reageert op een uitnodiging voor een gesprek.', 'Geachte heer Bos, hartelijk dank voor de uitnodiging. Ik bevestig hierbij mijn aanwezigheid op dinsdag 4 juni om 10.00 uur.', 'Dinsdag 10 uur is goed.', 'Top, ik ben er dinsdag!', 'Ik bevestig hierbij mijn aanwezigheid: formeel.'],
  [3, 'Je meldt dat je stopt bij een club.', 'Geachte heer Groen, hierbij zeg ik mijn lidmaatschap op per 1 september. Ik dank u voor de fijne jaren.', 'Ik stop met de club.', 'Ik kap ermee na de zomer, bedankt voor alles.', 'Hierbij zeg ik op en ik dank u: formeel en netjes.'],
  [3, 'Je vraagt een schrijver of hij op school wil komen praten.', 'Geachte mevrouw Kant, namens onze klas nodig ik u uit om over uw boek te komen vertellen op onze school.', 'Wil je bij ons op school komen praten over je boek?', 'Kom je een keer langs? We lezen je boek.', 'Namens onze klas nodig ik u uit: formeel.'],
  [3, 'Je vraagt om een kopie van je diploma.', 'Geachte heer of mevrouw, ik verzoek u mij een gewaarmerkte kopie van mijn diploma toe te sturen.', 'Kan ik een kopie van mijn diploma krijgen?', 'Ik heb een kopie van mijn diploma nodig, kun je die sturen?', 'Ik verzoek u en toe te sturen: formeel.'],
  [3, 'Je geeft een bedrijf feedback over hun website.', 'Geachte heer of mevrouw, graag wijs ik u op een fout op uw website: de openingstijden kloppen niet.', 'Jullie site klopt niet.', 'Even een tip: de tijden op jullie site zijn fout.', 'Graag wijs ik u op: formeel en behulpzaam.'],
  [3, 'Je reageert op een afwijzing.', 'Geachte mevrouw Dekker, dank voor uw bericht. Ik waardeer het dat u mij heeft geïnformeerd en wens u succes met de invulling van de functie.', 'Jammer, maar bedankt.', 'Oké, jammer dan. Toch bedankt!', 'Dank voor uw bericht en ik waardeer het: formeel, ook na slecht nieuws.'],
  [3, 'Je vraagt een docent om feedback op je verslag.', 'Beste meneer Aalbers, zou u mijn verslag willen doorlezen en mij van feedback willen voorzien?', 'Kun je even naar mijn verslag kijken?', 'Wil je mijn verslag checken?', 'Zou u willen en van feedback voorzien: formeel.'],
  [3, 'Je meldt een gevonden voorwerp bij de receptie.', 'Geachte heer of mevrouw, ik heb vanochtend in de aula een portemonnee gevonden. Ik heb deze bij de receptie afgegeven.', 'Ik heb een portemonnee gevonden, ligt bij de receptie.', 'Iemand een portemonnee kwijt? Ligt bij de balie.', 'Geachte en volledige zinnen: formeel.'],
  [3, 'Je vraagt of je een presentatie mag verplaatsen.', 'Beste mevrouw Zwart, is het mogelijk om mijn presentatie van vrijdag naar maandag te verplaatsen? Ik heb vrijdag een medische afspraak.', 'Kan mijn presentatie naar maandag?', 'Vrijdag lukt niet, maandag oké?', 'Is het mogelijk om en een reden: formeel.'],
  [3, 'Je vraagt een bedrijf om informatie voor je profielwerkstuk.', 'Geachte heer of mevrouw, voor mijn profielwerkstuk onderzoek ik duurzame verpakkingen. Zou ik u enkele vragen mogen stellen?', 'Mag ik jullie wat vragen voor school?', 'Hoi! Ik doe een werkstuk over verpakkingen, kunnen jullie helpen?', 'Zou ik u enkele vragen mogen stellen: formeel.'],
  [3, 'Je meldt de gemeente een kapotte lantaarnpaal.', 'Geachte heer of mevrouw, graag meld ik dat de lantaarnpaal bij Dorpsstraat 14 al een week niet brandt.', 'Die lantaarnpaal is kapot.', 'Kunnen jullie die lamp in de Dorpsstraat eens fixen?', 'Graag meld ik: formeel en zakelijk.'],
  [3, 'Je trekt je sollicitatie in.', 'Geachte heer Verbeek, hierbij trek ik mijn sollicitatie in, omdat ik elders een baan heb aangenomen.', 'Ik hoef de baan niet meer.', 'Laat maar zitten, ik heb al iets anders.', 'Hierbij trek ik in en een reden: formeel.'],
  [3, 'Je vraagt een oud-docent om een referentie.', 'Geachte heer Mulder, zou u bereid zijn als referentie op te treden voor mijn sollicitatie?', 'Mag ik jou opgeven als referentie?', 'Kun je iets goeds over me zeggen als ze bellen?', 'Zou u bereid zijn: een beleefd, formeel verzoek.'],
  [3, 'Je vraagt een bedrijf om een rondleiding voor je klas.', 'Geachte heer of mevrouw, namens klas 4H wil ik graag informeren of wij een rondleiding door uw bedrijf mogen krijgen.', 'Kunnen wij een rondleiding krijgen?', 'Hoi! Doen jullie ook rondleidingen voor klassen?', 'Namens klas 4H en informeren of: formeel.'],
  [3, 'Je laat een bedrijf weten dat je de aangeboden bijbaan aanneemt.', 'Geachte mevrouw Visser, hartelijk dank voor uw aanbod. Graag neem ik de functie van kassamedewerker aan.', 'Ik neem de baan aan!', 'Yes, ik doe het! Wanneer kan ik beginnen?', 'Hartelijk dank voor uw aanbod en graag neem ik aan: formeel.'],
  [3, 'Je vraagt de school om vrijstelling voor een vak.', 'Geachte heer Brouwer, graag verzoek ik u om vrijstelling voor het vak Frans, omdat ik dit vak op mijn vorige school al heb afgerond.', 'Moet ik Frans nog doen? Heb het al gehad.', 'Frans heb ik al gehaald hoor, kan ik stoppen?', 'Graag verzoek ik u en een reden: formeel.'],
  [3, 'Je vraagt een webwinkel of je een jas uit je bestelling mag ruilen.', 'Geachte heer of mevrouw, graag zou ik de jas uit mijn bestelling van 2 maart willen ruilen voor een kleinere maat.', 'Kan ik die jas ruilen?', 'Die jas is te groot, mag ik een andere?', 'Graag zou ik willen ruilen en een datum: formeel.']
];
var HERSCHRIJVEN = [
  [1, 'Hoi meneer Jansen, kun je me ff helpen?', 'Beste meneer Jansen, kunt u mij ___ helpen?', ['even'], 'Ff is een afkorting van even. In een net bericht schrijf je het woord voluit.'],
  [1, 'Hoi mevrouw De Groot, ik ben ziek.', '___ mevrouw De Groot, ik ben ziek.', ['Geachte', 'Beste'], 'Hoi is voor vrienden. Aan een docent schrijf je Geachte of Beste.'],
  [1, 'Kun je me het huiswerk sturen?', 'Kunt ___ mij het huiswerk sturen?', ['u'], 'Je wordt u: de beleefde aanspreekvorm.'],
  [1, 'Thnx voor je hulp!', '___ voor uw hulp.', ['Bedankt', 'Dank u', 'Hartelijk dank', 'Dank u wel'], 'Thnx is een afkorting van thanks. Formeel: bedankt, dank u of hartelijk dank.'],
  [1, 'Sorry, ik ben te laat.', '___, ik ben te laat.', ['Excuses', 'Mijn excuses', 'Het spijt me', 'Excuseer'], 'Sorry is spreektaal. Formeel: excuses of het spijt me.'],
  [1, 'Doei!', '___, Sam de Boer', ['Met vriendelijke groet', 'Met vriendelijke groeten', 'Hoogachtend'], 'Doei is voor vrienden. Een formeel bericht sluit je af met Met vriendelijke groet.'],
  [1, 'Ik snap het niet.', 'Ik ___ het niet.', ['begrijp'], 'Snappen is spreektaal; begrijpen is het nette woord.'],
  [1, 'Heb je nog een boek voor me?', 'Heeft u nog een boek voor ___?', ['mij'], 'Me wordt mij in geschreven, formele taal.'],
  [1, 'Ik kom effe niet.', 'Ik kom ___ niet.', ['even'], 'Effe is spreektaal voor even.'],
  [1, 'Kan je me terugbellen?', 'Kunt u ___ terugbellen?', ['mij'], 'Kan je wordt kunt u, en me wordt mij.'],
  [1, 'Ik heb geen zin om te komen.', 'Ik kan ___ niet komen.', ['helaas', 'jammer genoeg'], 'Geen zin hebben zeg je niet tegen school. Formeel zeg je dat je helaas niet kunt.'],
  [1, 'Oké, is goed.', 'Dat is ___.', ['akkoord', 'in orde', 'prima', 'goed'], 'Oké is spreektaal. Formeel: dat is akkoord of dat is in orde.'],
  [1, 'Ik ga niet naar de les, ik ben ziek.', 'Ik kan niet naar de les komen, ___ ik ben ziek.', ['omdat', 'want', 'aangezien'], 'Een formele zin legt uit waarom, met een signaalwoord als omdat of want.'],
  [1, 'Hé, wanneer is de toets?', 'Beste meneer, ___ u mij laten weten wanneer de toets is?', ['kunt', 'zou', 'wilt'], 'Hé is voor vrienden. Formeel vraag je: kunt u mij laten weten.'],
  [1, 'Ik ben ff weg.', 'Ik ben ___ afwezig.', ['even', 'tijdelijk'], 'Ff is een afkorting van even. In een net bericht schrijf je het woord voluit.'],
  [1, 'Mag ik je pen lenen?', 'Mag ik ___ pen lenen?', ['uw'], 'Je wordt uw: de beleefde vorm.'],
  [1, 'Ik vind het echt stom dat de les uitvalt.', 'Ik vind het ___ dat de les uitvalt.', ['jammer', 'vervelend', 'spijtig'], 'Stom is spreektaal; jammer of vervelend is netter.'],
  [1, 'Kun je dat nog een keer zeggen?', 'Kunt u dat ___ herhalen?', ['nog eens', 'nogmaals', 'alstublieft'], 'Nog een keer zeggen wordt: nog eens of nogmaals herhalen.'],
  [1, 'Ik ben super blij met de uitslag.', 'Ik ben ___ blij met de uitslag.', ['erg', 'heel', 'zeer'], 'Super is spreektaal. Formeel schrijf je erg blij of heel blij.'],
  [1, 'Ik ben m kwijt.', 'Ik ben ___ kwijt.', ['hem'], 'M is een afkorting van hem. In een net bericht schrijf je het woord voluit.'],
  [1, 'Ik heb een vraagje over de toets.', 'Ik heb een ___ over de toets.', ['vraag'], 'Vraagje klinkt als praten met een vriend. In een net bericht schrijf je vraag.'],
  [1, 'Hoi, ik ben Sam uit klas 1B.', 'Beste meneer, ___ naam is Sam en ik zit in klas 1B.', ['mijn'], 'Hoi, ik ben Sam is spreektaal. Formeel stel je jezelf voor met mijn naam is.'],
  [2, 'Kun je ff kijken naar mijn verslag?', 'Zou u ___ naar mijn verslag willen kijken?', ['even'], 'Ff wordt even, en kun je wordt zou u willen.'],
  [2, 'Ik heb mijn werkstuk niet af, sorry.', 'Helaas heb ik mijn werkstuk niet af. Mijn ___.', ['excuses', 'excuus', 'verontschuldigingen'], 'Sorry wordt mijn excuses.'],
  [2, 'Ik wil graag een andere dag voor de toets.', 'Ik ___ u om een andere datum voor de toets.', ['verzoek', 'vraag'], 'Ik verzoek u: de formele manier om iets te vragen.'],
  [2, 'Ik heb je mail gekregen.', 'Ik heb uw e-mail ___.', ['ontvangen'], 'Gekregen is spreektaal; formeel is ontvangen.'],
  [2, 'Dat komt niet uit, ik heb voetbal.', 'Dat komt mij niet goed uit, ___ ik dan een voetbalwedstrijd heb.', ['omdat', 'aangezien', 'want'], 'Formeel leg je met een signaalwoord uit waarom iets niet uitkomt.'],
  [2, 'Zeg maar wanneer het kan.', 'Kunt u mij ___ wanneer het u uitkomt?', ['laten weten', 'melden', 'aangeven', 'meedelen'], 'Zeg maar wordt kunt u mij laten weten.'],
  [2, 'Ik kap met de club.', 'Hierbij ___ ik mijn lidmaatschap op.', ['zeg'], 'Ik kap ermee is spreektaal. Formeel: hierbij zeg ik mijn lidmaatschap op.'],
  [2, 'Even een vraagje: kost het wat?', 'Ik wil graag weten of er ___ aan verbonden zijn.', ['kosten'], 'Kost het wat wordt: of er kosten aan verbonden zijn.'],
  [2, 'Ik vind dat een stomme regel.', 'Ik ben het niet ___ met deze regel.', ['eens'], 'Stom is spreektaal. Formeel: ik ben het niet eens met.'],
  [2, 'Ik heb je brief gelezen en ik doe mee.', 'Naar aanleiding van uw brief ___ ik u dat ik deelneem.', ['laat', 'meld', 'bericht'], 'Naar aanleiding van uw brief laat ik u weten: formeel.'],
  [2, 'Kun je dat ff fixen?', 'Zou u dit kunnen ___?', ['oplossen', 'regelen', 'herstellen', 'verhelpen'], 'Fixen is spreektaal; oplossen of regelen is formeel.'],
  [2, 'Ik zit met een probleem.', 'Ik heb een ___.', ['probleem', 'vraag'], 'Zitten met is spreektaal; formeel: ik heb een probleem of een vraag.'],
  [2, 'Ik wil best wel komen.', 'Ik ben ___ tot komen.', ['bereid', 'graag bereid'], 'Best wel is spreektaal. Formeel: ik ben bereid.'],
  [2, 'Bedankt alvast!', 'Bij ___ dank.', ['voorbaat'], 'Bedankt alvast wordt bij voorbaat dank.'],
  [2, 'Ik heb echt geen tijd.', 'Ik heb ___ geen tijd.', ['helaas', 'jammer genoeg'], 'Echt geen tijd klinkt bot; helaas is beleefder.'],
  [2, 'Ik stuur het zo.', 'Ik stuur het ___ op.', ['zo spoedig mogelijk', 'spoedig', 'zo snel mogelijk', 'binnenkort'], 'Zo is spreektaal; formeel schrijf je zo spoedig mogelijk.'],
  [2, 'Kan dat?', 'Is dat ___?', ['mogelijk'], 'Kan dat wordt in een net bericht: is dat mogelijk.'],
  [2, 'Ik snap de opdracht niet.', 'De opdracht is mij niet ___.', ['duidelijk', 'helder'], 'Snappen is spreektaal. Formeel: de opdracht is mij niet duidelijk.'],
  [2, 'Ik heb het gecheckt.', 'Ik heb het ___.', ['gecontroleerd', 'nagekeken', 'nagegaan'], 'Checken is Engelse spreektaal; formeel schrijf je controleren of nakijken.'],
  [2, 'Ik moet nog wat dingen regelen.', 'Ik moet nog enkele ___ regelen.', ['zaken'], 'Dingen is spreektaal; in een net bericht schrijf je zaken.'],
  [2, 'Ik laat het je nog weten.', 'Ik ___ u hier later over.', ['bericht', 'informeer'], 'Het je laten weten wordt formeel: ik bericht u of ik informeer u.'],
  [2, 'Ik heb een fout gemaakt, my bad.', 'Ik heb een fout gemaakt. Dat ___ mij.', ['spijt'], 'My bad is Engelse spreektaal; formeel schrijf je: dat spijt mij.'],
  [3, 'Ik heb je vacature gezien en het lijkt me wel wat.', 'Met veel ___ heb ik uw vacature gelezen.', ['belangstelling', 'interesse'], 'Het lijkt me wel wat wordt: met veel belangstelling heb ik uw vacature gelezen.'],
  [3, 'Ik kan niet komen omdat ik ziek ben.', 'In ___ met ziekte ben ik verhinderd.', ['verband'], 'In verband met is de formele versie van omdat.'],
  [3, 'Laat je nog wat weten?', 'Ik zie uw reactie met ___ tegemoet.', ['belangstelling', 'interesse'], 'Een vaste formele slotzin: ik zie uw reactie met belangstelling tegemoet.'],
  [3, 'Hierbij mijn cv.', 'In de ___ vindt u mijn cv.', ['bijlage'], 'Formeel verwijs je naar de bijlage.'],
  [3, 'Ik wil graag praten over mijn cijfer.', 'Ik zou graag een ___ met u willen maken over mijn cijfer.', ['afspraak'], 'Praten over wordt: een afspraak maken over.'],
  [3, 'Sorry dat ik zo laat reageer.', 'Mijn ___ voor de late reactie.', ['excuses', 'verontschuldigingen', 'excuus'], 'Sorry wordt mijn excuses of mijn verontschuldigingen.'],
  [3, 'Ik hoop dat je me kunt helpen.', 'Ik hoop dat u mij van ___ kunt zijn.', ['dienst'], 'Van dienst zijn: een formele uitdrukking voor helpen.'],
  [3, 'Ik heb het gelezen en het is duidelijk.', 'Ik heb kennis ___ van uw bericht.', ['genomen'], 'Kennis nemen van: een formele manier om te zeggen dat je iets gelezen hebt.'],
  [3, 'Kun je me vertellen wat de regels zijn?', 'Kunt u mij ___ over de geldende regels?', ['informeren', 'inlichten'], 'Vertellen wordt informeren of inlichten.'],
  [3, 'Ik kom niet, ik heb wat anders.', 'Helaas ben ik ___ wegens een andere verplichting.', ['verhinderd'], 'Verhinderd zijn: formeel voor niet kunnen komen.'],
  [3, 'Ik hoop dat je dit snel regelt.', 'Ik ___ erop dat u dit spoedig regelt.', ['vertrouw', 'reken'], 'Ik vertrouw erop: formeel en beleefd, zonder te dringen.'],
  [3, 'Bedankt voor het gesprek, was leuk.', 'Hartelijk dank voor het ___ gesprek.', ['prettige', 'aangename', 'plezierige', 'fijne'], 'Leuk wordt prettig of aangenaam.'],
  [3, 'Ik heb een klacht over de levering.', 'Hierbij ___ ik een klacht in over de levering.', ['dien'], 'Een klacht indienen: formeel.'],
  [3, 'Ik wil weten of er nog plek is.', 'Ik ___ graag of er nog plaatsen beschikbaar zijn.', ['verneem', 'hoor', 'wil weten'], 'Ik verneem graag: formeel voor ik wil weten.'],
  [3, 'Ik hoef die baan niet meer.', 'Hierbij ___ ik mijn sollicitatie in.', ['trek'], 'Een sollicitatie intrekken: formeel voor er niet meer mee doorgaan.'],
  [3, 'Wat moet ik nu doen?', 'Kunt u mij ___ over de vervolgstappen?', ['informeren', 'inlichten', 'adviseren'], 'Wat moet ik doen wordt: kunt u mij informeren over de vervolgstappen.'],
  [3, 'Ik kan dat heel goed.', 'Ik ben daar zeer ___ in.', ['bedreven', 'ervaren', 'vaardig', 'goed'], 'Heel goed kunnen wordt: zeer bedreven of ervaren zijn.'],
  [3, 'Laat maar weten als je vragen hebt.', 'Mocht u vragen ___, dan hoor ik dat graag.', ['hebben'], 'Mocht u vragen hebben: een vaste formele zin.'],
  [3, 'Ik wil even zeggen dat ik het er niet mee eens ben.', 'Graag ___ ik mijn bezwaar kenbaar.', ['maak'], 'Kenbaar maken is een formele manier om iets te laten weten.'],
  [3, 'Hierbij de spullen die je vroeg.', 'Hierbij stuur ik u de ___ documenten.', ['gevraagde', 'opgevraagde', 'verzochte'], 'De spullen die je vroeg wordt formeel: de gevraagde documenten.'],
  [3, 'Ik heb er veel zin in.', 'Ik kijk er met veel ___ naar uit.', ['plezier', 'genoegen', 'enthousiasme'], 'Zin hebben is spreektaal; formeel: ik kijk er met veel plezier naar uit.'],
  [3, 'Ik ben er vanaf maandag weer.', 'Vanaf maandag ben ik weer ___.', ['beschikbaar', 'aanwezig', 'bereikbaar'], 'Er weer zijn is spreektaal; formeel: weer beschikbaar of aanwezig.']
];
var ZINNEN = [
  [1, 'Yo, ben je er al?', 'app'], [1, 'Ff kijken of ik kan, laat ik je weten 👍', 'app'], [1, 'Haha nee joh, dat was een grapje', 'app'], [1, 'Kom je nog? Sta al 10 min te wachten', 'app'],
  [1, 'Thnx voor gister!', 'app'], [1, 'Lol, die docent was echt boos', 'app'], [1, 'Neem jij de chips mee?', 'app'], [1, 'Ben m kwijt, heb jij m?', 'app'],
  [1, 'Beste meneer De Vries, ik ben vandaag ziek.', 'mail'], [1, 'Kunt u mij laten weten wanneer de toets is?', 'mail'], [1, 'Met vriendelijke groet, Noor Bakker', 'mail'], [1, 'Hartelijk dank voor uw antwoord.', 'mail'],
  [1, 'Zou ik de toets op een ander moment mogen inhalen?', 'mail'], [1, 'Mag ik morgen iets eerder weg voor de tandarts?', 'mail'], [1, 'Ik kom later omdat mijn bus is uitgevallen.', 'mail'], [1, 'Hierbij meld ik mij aan voor de schoolreis.', 'mail'],
  [2, 'Sws gaan we, ik heb al kaartjes 🎉', 'app'], [2, 'Effe serieus, gaan we nou zaterdag?', 'app'], [2, 'Nee man, veel te duur', 'app'], [2, 'Kun je me het adres appen?', 'app'],
  [2, 'Was echt sooo moe vandaag', 'app'], [2, 'Deal, tot morgen!', 'app'], [2, 'Stuur ff die foto’s', 'app'],
  [2, 'Zou het mogelijk zijn onze afspraak te verzetten?', 'mail'], [2, 'Ik verzoek u vriendelijk het formulier voor vrijdag terug te sturen.', 'mail'], [2, 'In de bijlage vindt u mijn verslag.', 'mail'], [2, 'Helaas moet ik de afspraak afzeggen wegens ziekte.', 'mail'],
  [2, 'Ik hoop dat u mijn verslag wilt doorlezen.', 'mail'], [2, 'Bij voorbaat dank voor uw hulp.', 'mail'], [2, 'Ik heb uw e-mail in goede orde ontvangen.', 'mail'],
  [3, 'Kom je nog of hoe zit het?', 'app'], [3, 'Die toets was echt onmogelijk 😂', 'app'], [3, 'Oké chill, zie je dan', 'app'], [3, 'Heb je mijn oplader nog?', 'app'], [3, 'Zooo oneerlijk, waarom krijgt zij wel een herkansing?!', 'app'],
  [3, 'Zou u mijn verslag van feedback willen voorzien?', 'mail'], [3, 'Mag ik mijn presentatie naar maandag verplaatsen?', 'mail'], [3, 'Ik heb kennis genomen van de nieuwe regeling.', 'mail'], [3, 'Wanneer komt een gesprek u uit?', 'mail'], [3, 'Kunt u mij informeren over de inhaalregeling?', 'mail'],
  [3, 'Met veel belangstelling heb ik uw vacature gelezen.', 'brief'], [3, 'Graag solliciteer ik naar de functie van weekendhulp.', 'brief'], [3, 'In de bijlage vindt u mijn cv en een kopie van mijn diploma.', 'brief'], [3, 'Ik zie uw reactie met belangstelling tegemoet.', 'brief'],
  [3, 'Ik ben leergierig, precies en werk graag in een team.', 'brief'], [3, 'Tijdens mijn stage heb ik ervaring opgedaan met klantcontact.', 'brief'], [3, 'Graag licht ik mijn motivatie toe in een gesprek.', 'brief'], [3, 'Hoogachtend, Sam de Boer', 'brief'],
  [3, 'Ik ben beschikbaar op zaterdag en zondag.', 'brief'], [3, 'Uw bedrijf spreekt mij aan vanwege de aandacht voor duurzaamheid.', 'brief']
];
return { HERKENNEN: HERKENNEN, KIES: KIES, HERSCHRIJVEN: HERSCHRIJVEN, ZINNEN: ZINNEN };
})();
