/* De zinnen van Signaalwoorden en verbanden. In een eigen bestand zodat ze na
   te lezen zijn. Niveau n: 1 = vmbo-bb (de vijf basisverbanden), 2 = vmbo-kgt
   en tl (ook doel-middel en voorwaarde), 3 = havo en vwo (ook toegeving, en
   verbanden over de zinsgrens heen).
   VERBANDEN: id, naam, uit (wat het verband doet), niv (vanaf welk niveau)
   WOORDEN:   per verband de signaalwoorden voor het sorteren
   INVUL:     [n, zin met ___, goed signaalwoord, fout, fout, fout, verband, uitleg]
   WELK:      [n, zin met het signaalwoord tussen **sterretjes**, verband, uitleg]
   AFMAKEN:   [n, begin van de zin met het signaalwoord tussen **sterretjes**, goed vervolg, fout, fout, fout, verband, uitleg] */
var SIGNAALWOORDEN = (function(){
var VERBANDEN = [
  { id:'oorzaak',     naam:'oorzaak en gevolg',        uit:'het een komt door het ander',            niv:1 },
  { id:'tegenstelling', naam:'tegenstelling',          uit:'het staat tegenover elkaar',             niv:1 },
  { id:'opsomming',   naam:'opsomming',                uit:'er komt nog iets bij',                   niv:1 },
  { id:'voorbeeld',   naam:'voorbeeld',                uit:'iets algemeens wordt concreet gemaakt',  niv:1 },
  { id:'tijd',        naam:'tijd',                     uit:'wat gebeurt er eerst, wat daarna',       niv:1 },
  { id:'doel',        naam:'doel en middel',           uit:'iets gebeurt om iets anders te bereiken', niv:2 },
  { id:'voorwaarde',  naam:'voorwaarde',               uit:'het geldt alleen als',                   niv:2 },
  { id:'conclusie',   naam:'samenvatting of conclusie', uit:'dit volgt eruit, kort gezegd',          niv:2 },
  { id:'concessie',   naam:'toegeving (concessie)',    uit:'het is zo, en toch gebeurt het andere',  niv:3 }
];
var WOORDEN = {
  oorzaak:['omdat', 'doordat', 'want', 'daardoor', 'waardoor', 'daarom', 'hierdoor', 'als gevolg van'],
  tegenstelling:['maar', 'echter', 'daarentegen', 'in tegenstelling tot', 'anderzijds', 'integendeel'],
  opsomming:['ook', 'daarnaast', 'bovendien', 'verder', 'ten eerste', 'ten tweede', 'tevens', 'tot slot'],
  voorbeeld:['bijvoorbeeld', 'zoals', 'ter illustratie', 'denk aan', 'onder andere', 'neem nou'],
  tijd:['eerst', 'daarna', 'vervolgens', 'toen', 'later', 'intussen', 'nadat', 'voordat', 'uiteindelijk'],
  doel:['om te', 'daarmee', 'met behulp van', 'door middel van', 'met als doel', 'opdat', 'daartoe'],
  voorwaarde:['als', 'indien', 'mits', 'tenzij', 'wanneer', 'op voorwaarde dat', 'stel dat'],
  conclusie:['kortom', 'samengevat', 'al met al', 'concluderend', 'kort gezegd', 'met andere woorden', 'hieruit volgt'],
  concessie:['hoewel', 'ondanks', 'ofschoon', 'ook al', 'weliswaar', 'al', 'ondanks dat']
};
var INVUL = [
  [1, 'Ik neem een paraplu mee, ___ het gaat regenen.', 'want', 'maar', 'bijvoorbeeld', 'daarna', 'oorzaak', 'De regen is de reden voor de paraplu: want geeft een oorzaak of reden.'],
  [1, 'Het regende hard, ___ de wedstrijd ging niet door.', 'dus', 'omdat', 'zoals', 'ook', 'oorzaak', 'De regen kwam eerst, het afgelasten is het gevolg: dus.'],
  [1, 'Sam wilde gaan voetballen, ___ het veld was dicht.', 'maar', 'want', 'bijvoorbeeld', 'eerst', 'tegenstelling', 'Willen voetballen en een dicht veld staan tegenover elkaar: maar.'],
  [1, 'Ik hou van dieren, ___ van honden en konijnen.', 'bijvoorbeeld', 'maar', 'omdat', 'daarna', 'voorbeeld', 'Honden en konijnen zijn voorbeelden van dieren: bijvoorbeeld.'],
  [1, 'We aten eerst een pizza en ___ keken we een film.', 'daarna', 'want', 'maar', 'bijvoorbeeld', 'tijd', 'Eerst de pizza, daarna de film: een volgorde in de tijd.'],
  [1, 'Noor speelt hockey. ___ zit ze op turnen.', 'Ook', 'Want', 'Daarom', 'Toen', 'opsomming', 'Er komt nog een sport bij: ook is een opsomming.'],
  [1, 'De game is leuk, ___ hij is wel heel duur.', 'maar', 'zoals', 'dus', 'daarna', 'tegenstelling', 'Leuk en duur staan tegenover elkaar: maar.'],
  [1, 'Ik was te laat ___ mijn band lek was.', 'omdat', 'maar', 'bijvoorbeeld', 'daarna', 'oorzaak', 'De lekke band is de oorzaak van het te laat komen: omdat.'],
  [1, 'Je moet stevige schoenen aan, ___ wandelschoenen.', 'zoals', 'maar', 'want', 'daarna', 'voorbeeld', 'Wandelschoenen zijn een voorbeeld van stevige schoenen: zoals.'],
  [1, '___ ging de bel, daarna liepen we naar buiten.', 'Eerst', 'Maar', 'Bijvoorbeeld', 'Omdat', 'tijd', 'Eerst en daarna geven de volgorde in de tijd aan.'],
  [1, 'De hond is lief. ___ is hij heel slim.', 'Bovendien', 'Maar', 'Daarom', 'Zoals', 'opsomming', 'Er komt een tweede goede eigenschap bij: bovendien.'],
  [1, 'De sporthal is gesloten, ___ hebben we gym buiten.', 'daarom', 'maar', 'bijvoorbeeld', 'ook', 'oorzaak', 'De gesloten hal is de oorzaak, gym buiten het gevolg: daarom.'],
  [1, 'Mijn zus is al zestien, ___ ze mag nog niet scooter rijden.', 'toch', 'want', 'zoals', 'eerst', 'tegenstelling', 'Je verwacht dat ze mag rijden, maar het is niet zo: toch geeft een tegenstelling.'],
  [1, 'Er zijn veel bordspellen, ___ schaken en dammen.', 'bijvoorbeeld', 'want', 'daarna', 'toch', 'voorbeeld', 'Schaken en dammen zijn voorbeelden van bordspellen.'],
  [1, 'Ik had honger, ___ at ik een boterham.', 'dus', 'maar', 'zoals', 'bijvoorbeeld', 'oorzaak', 'Honger is de oorzaak, de boterham eten het gevolg: dus.'],
  [1, 'Mijn fiets is oud, ___ hij rijdt nog heel goed.', 'maar', 'want', 'dus', 'daarna', 'tegenstelling', 'Oud en toch goed rijden: maar zet het tegenover elkaar.'],
  [1, 'In de dierentuin zagen we veel dieren, ___ olifanten en giraffen.', 'zoals', 'want', 'maar', 'daarna', 'voorbeeld', 'Olifanten en giraffen zijn voorbeelden van dieren: zoals.'],
  [1, 'Ik poets eerst mijn tanden, ___ ga ik naar bed.', 'daarna', 'want', 'maar', 'zoals', 'tijd', 'Eerst tanden poetsen, daarna naar bed: een volgorde in de tijd.'],
  [1, 'Voor het kamp neem je een slaapzak mee. ___ heb je een zaklamp nodig.', 'Ook', 'Maar', 'Want', 'Zoals', 'opsomming', 'Er komt nog iets bij op de lijst: ook.'],
  [1, 'Ik maak eerst mijn huiswerk. ___ ga ik buiten spelen.', 'Daarna', 'Want', 'Maar', 'Zoals', 'tijd', 'Eerst huiswerk, daarna buiten spelen: een volgorde in de tijd.'],
  [1, 'Op het schoolfeest is er muziek. Er is ___ een fotohoek.', 'ook', 'want', 'maar', 'dus', 'opsomming', 'Er komt nog iets bij op het feest: ook.'],
  [1, 'Mijn opa is al tachtig, ___ hij fietst nog elke dag naar de markt.', 'maar', 'want', 'dus', 'zoals', 'tegenstelling', 'Tachtig jaar en toch elke dag fietsen: maar zet het tegenover elkaar.'],
  [2, 'Je mag mee naar het concert, ___ je je huiswerk af hebt.', 'mits', 'want', 'hoewel', 'bijvoorbeeld', 'voorwaarde', 'Mits betekent: alleen als. Het meegaan hangt af van het huiswerk: een voorwaarde.'],
  [2, 'De school plant bomen ___ het plein koeler te maken.', 'om', 'omdat', 'zodat', 'toen', 'doel', 'Om ... te geeft het doel aan: waarvoor de bomen geplant worden.'],
  [2, 'Het team traint hard, eet gezond en slaapt veel. ___ doet het alles om te winnen.', 'Kortom', 'Bijvoorbeeld', 'Toch', 'Daarna', 'conclusie', 'Kortom vat de drie dingen samen in één zin: een samenvatting.'],
  [2, 'De bus komt niet ___ de weg is afgesloten.', 'doordat', 'zoals', 'zodat', 'mits', 'oorzaak', 'De afgesloten weg is de oorzaak: doordat.'],
  [2, 'Veel leerlingen fietsen naar school. ___ komt een klein deel met de bus.', 'Daarentegen', 'Bovendien', 'Kortom', 'Daardoor', 'tegenstelling', 'Fietsen tegenover de bus: daarentegen zet twee groepen tegenover elkaar.'],
  [2, 'Je kunt de app niet gebruiken ___ je hem eerst bijwerkt.', 'tenzij', 'omdat', 'zodat', 'nadat', 'voorwaarde', 'Tenzij betekent: behalve als. Het bijwerken is de voorwaarde.'],
  [2, 'De brandweer kwam snel. ___ was de schade beperkt.', 'Daardoor', 'Toch', 'Bijvoorbeeld', 'Ten eerste', 'oorzaak', 'De snelle brandweer is de oorzaak, de beperkte schade het gevolg: daardoor.'],
  [2, 'De gemeente plaatst camera’s ___ de overlast in het park.', 'vanwege', 'ondanks', 'zoals', 'mits', 'oorzaak', 'De overlast is de reden voor de camera’s: vanwege geeft een oorzaak.'],
  [2, 'Ze spaart elke maand ___ een nieuwe laptop te kunnen kopen.', 'om', 'want', 'doordat', 'hoewel', 'doel', 'De laptop is het doel van het sparen: om ... te.'],
  [2, 'Veel pubers slapen te weinig. ___ zitten ze ’s ochtends moe in de klas.', 'Daardoor', 'Bovendien', 'Ter illustratie', 'Mits', 'oorzaak', 'Te weinig slaap is de oorzaak, moe in de klas het gevolg: daardoor.'],
  [2, '___ je het bewijs bij je hebt, krijg je de korting.', 'Als', 'Hoewel', 'Zodat', 'Doordat', 'voorwaarde', 'Als geeft de voorwaarde: de korting geldt alleen met het bewijs.'],
  [2, 'De film was lang. ___ verveelde niemand zich.', 'Toch', 'Daardoor', 'Zoals', 'Kortom', 'tegenstelling', 'Een lange film en toch geen verveling: dat is een tegenstelling.'],
  [2, 'De kantine wordt gezonder: minder snoep, meer fruit en water. ___ komt er geen frisdrank meer.', 'Verder', 'Toch', 'Daarom', 'Kortom', 'opsomming', 'Er komt nog een maatregel bij: verder is een opsomming.'],
  [2, 'De training is afgelast ___ het onweert.', 'omdat', 'hoewel', 'zodat', 'bijvoorbeeld', 'oorzaak', 'Het onweer is de oorzaak van het afgelasten: omdat.'],
  [2, 'Je mag de toets herkansen, ___ je cijfer lager is dan een 5,5.', 'als', 'hoewel', 'zodat', 'bovendien', 'voorwaarde', 'Als geeft de voorwaarde: alleen bij een onvoldoende mag je herkansen.'],
  [2, 'De gemeente legt drempels aan ___ auto’s langzamer te laten rijden.', 'om', 'omdat', 'hoewel', 'tenzij', 'doel', 'Om ... te geeft het doel van de drempels.'],
  [2, 'Het was warm, de zon scheen en het strand was leeg. ___, een perfecte dag.', 'Kortom', 'Daarentegen', 'Tenzij', 'Bijvoorbeeld', 'conclusie', 'Kortom vat de drie dingen samen in één oordeel.'],
  [2, 'Veel jongeren lezen weinig boeken. ___ lezen ze wel veel berichten op hun telefoon.', 'Daarentegen', 'Daardoor', 'Kortom', 'Mits', 'tegenstelling', 'Weinig boeken tegenover veel berichten: daarentegen.'],
  [2, 'Neem een regenjas mee, ___ je nat wilt worden.', 'tenzij', 'omdat', 'zodat', 'nadat', 'voorwaarde', 'Tenzij betekent: behalve als. Alleen wie nat wil worden, laat de jas thuis.'],
  [2, 'Veel vogels eten insecten, ___ de mees en de zwaluw.', 'zoals', 'mits', 'doordat', 'kortom', 'voorbeeld', 'De mees en de zwaluw zijn voorbeelden van vogels die insecten eten: zoals.'],
  [2, '___ je de oefentoets hebt gemaakt, bespreek je de antwoorden met je buurman.', 'Nadat', 'Hoewel', 'Tenzij', 'Kortom', 'tijd', 'Eerst de oefentoets, dan bespreken: nadat geeft de volgorde in de tijd.'],
  [2, 'De spelers waren fit, de tactiek klopte en het publiek juichte. ___ was de wedstrijd een groot succes.', 'Al met al', 'Daarentegen', 'Tenzij', 'Bijvoorbeeld', 'conclusie', 'Al met al trekt de conclusie uit alles wat ervoor staat.'],
  [3, '___ het hard regende, ging de wedstrijd gewoon door.', 'Hoewel', 'Omdat', 'Zodat', 'Zodra', 'concessie', 'Hoewel geeft een toegeving: je verwacht afgelasting door de regen, maar het gaat toch door.'],
  [3, 'De onderzoekers vonden geen verband. ___ blijven ze de metingen herhalen.', 'Desondanks', 'Daardoor', 'Bijvoorbeeld', 'Kortom', 'concessie', 'Geen verband gevonden en toch doorgaan: desondanks is een toegeving.'],
  [3, 'Het bedrijf verlaagde de prijzen ___ meer klanten te trekken.', 'teneinde', 'doordat', 'terwijl', 'mits', 'doel', 'Teneinde is een formeel woord voor om ... te: het doel van de verlaging.'],
  [3, 'De uitslag is ___ onverwacht, maar niet onverklaarbaar.', 'weliswaar', 'tenzij', 'kortom', 'bijvoorbeeld', 'concessie', 'Weliswaar ... maar: de schrijver geeft iets toe en zet er dan iets tegenover.'],
  [3, 'De maatregel werkt alleen ___ iedereen eraan meedoet.', 'indien', 'hoewel', 'zodat', 'terwijl', 'voorwaarde', 'Indien is een formeel woord voor als: de voorwaarde voor het werken van de maatregel.'],
  [3, 'Het rapport bevat fouten en ontbrekende cijfers. ___ is het niet bruikbaar.', 'Al met al', 'Daarentegen', 'Ter illustratie', 'Ondanks', 'conclusie', 'Al met al trekt de conclusie uit wat ervoor staat.'],
  [3, 'De wolf is beschermd. ___ wordt er soms illegaal op gejaagd.', 'Toch', 'Daardoor', 'Kortom', 'Zoals', 'concessie', 'Beschermd, en toch bejaagd: toch geeft hier een toegeving over de zinsgrens heen.'],
  [3, 'De app slaat je locatie op, ___ je zoekgeschiedenis en je contacten.', 'evenals', 'ondanks', 'tenzij', 'daardoor', 'opsomming', 'Evenals voegt nog twee dingen toe aan de lijst: een opsomming.'],
  [3, 'De stad werd hitte-eiland ___ de vele stenen en het gebrek aan groen.', 'als gevolg van', 'ondanks', 'met als doel', 'in tegenstelling tot', 'oorzaak', 'Stenen en geen groen zijn de oorzaak van de hitte: als gevolg van.'],
  [3, '___ de kritiek werd het plan zonder wijzigingen aangenomen.', 'Ondanks', 'Vanwege', 'Zoals', 'Nadat', 'concessie', 'Ondanks geeft een toegeving: er was kritiek, en toch veranderde er niets.'],
  [3, 'De sporter trainde jaren op hoogte, ___ haar uithoudingsvermogen te vergroten.', 'met als doel', 'als gevolg van', 'in tegenstelling tot', 'ondanks', 'doel', 'Het grotere uithoudingsvermogen is het doel van de hoogtetraining.'],
  [3, 'Sommige dieren zijn nachtdieren, ___ uilen en vleermuizen.', 'zoals', 'mits', 'hoewel', 'daardoor', 'voorbeeld', 'Uilen en vleermuizen zijn voorbeelden van nachtdieren.'],
  [3, '___ de verbouwing klaar was, ging de school weer open.', 'Nadat', 'Hoewel', 'Doordat', 'Mits', 'tijd', 'Nadat geeft de volgorde in de tijd: eerst de verbouwing, dan de opening.'],
  [3, 'De chatbot klinkt overtuigend. ___ verzint hij regelmatig bronnen.', 'Niettemin', 'Daardoor', 'Ter illustratie', 'Samengevat', 'concessie', 'Niettemin is een toegeving over de zinsgrens heen: hij klinkt goed, en toch klopt het niet.'],
  [3, '___ de trein vertraging had, haalde ze haar aansluiting toch.', 'Hoewel', 'Omdat', 'Zodat', 'Tenzij', 'concessie', 'Hoewel geeft een toegeving: je verwacht dat ze de aansluiting mist, maar dat gebeurt niet.'],
  [3, 'Het onderzoek toont aan dat bewegen helpt tegen stress. ___ blijkt dat wandelen al genoeg is.', 'Bovendien', 'Desondanks', 'Daarentegen', 'Tenzij', 'opsomming', 'Bovendien voegt een tweede uitkomst toe: een opsomming over de zinsgrens heen.'],
  [3, 'De gemeente sluit de binnenstad voor auto’s, ___ de luchtkwaliteit te verbeteren.', 'teneinde', 'ondanks', 'hoewel', 'doordat', 'doel', 'Teneinde is formeel voor om ... te: het doel van de afsluiting.'],
  [3, 'De schade aan de dijk ontstond ___ de aanhoudende regen van de afgelopen weken.', 'als gevolg van', 'ondanks', 'met als doel', 'in plaats van', 'oorzaak', 'De regen is de oorzaak van de schade: als gevolg van.'],
  [3, 'De cijfers stijgen al drie jaar en de klachten nemen af. ___ werkt de aanpak.', 'Kortom', 'Niettemin', 'Tenzij', 'Daarentegen', 'conclusie', 'Kortom trekt de conclusie uit de twee gegevens ervoor.'],
  [3, '___ hij de beste van de klas was, voelde hij zich onzeker voor het examen.', 'Ofschoon', 'Doordat', 'Zodat', 'Mits', 'concessie', 'Ofschoon is een formeel woord voor hoewel: je verwacht zelfvertrouwen, en toch is hij onzeker.'],
  [3, 'Leerlingen die voldoende slapen, halen hogere cijfers. ___ onthouden zij de lesstof beter.', 'Tevens', 'Desondanks', 'Tenzij', 'Daarentegen', 'opsomming', 'Tevens is een formeel woord voor ook: er komt een tweede uitkomst bij.'],
  [3, '___ zijn broer houdt Daan helemaal niet van sport.', 'In tegenstelling tot', 'Als gevolg van', 'Met als doel', 'Op voorwaarde dat', 'tegenstelling', 'Daan en zijn broer staan tegenover elkaar: in tegenstelling tot.']
];
var WELK = [
  [1, 'Ik kan niet komen, **want** ik ben ziek.', 'oorzaak', 'Want geeft de reden of oorzaak: ziek zijn is waarom ik niet kan komen.'],
  [1, 'Het is koud, **maar** de zon schijnt.', 'tegenstelling', 'Maar zet koud en zon tegenover elkaar: een tegenstelling.'],
  [1, 'We gingen naar de dierentuin. **Daarna** aten we een ijsje.', 'tijd', 'Daarna zegt wat er later gebeurde: een volgorde in de tijd.'],
  [1, 'Er zijn veel sporten, **zoals** hockey en judo.', 'voorbeeld', 'Zoals kondigt voorbeelden aan: hockey en judo zijn voorbeelden van sporten.'],
  [1, 'Ik hou van pizza. **Ook** lust ik graag pasta.', 'opsomming', 'Ook voegt iets toe aan de lijst: een opsomming.'],
  [1, 'De weg was glad, **daardoor** viel ik.', 'oorzaak', 'De gladde weg is de oorzaak, het vallen het gevolg: daardoor.'],
  [1, '**Eerst** doe je de helm op, dan stap je op de fiets.', 'tijd', 'Eerst en dan geven de volgorde in de tijd.'],
  [1, 'Onze kat is oud, **toch** speelt ze nog elke dag.', 'tegenstelling', 'Je verwacht dat een oude kat niet speelt, maar het is wel zo: toch is een tegenstelling.'],
  [1, 'Neem iets warms mee, **bijvoorbeeld** een trui.', 'voorbeeld', 'De trui is een voorbeeld van iets warms.'],
  [1, 'Sam speelt gitaar. **Bovendien** zingt hij goed.', 'opsomming', 'Bovendien voegt nog iets toe: een opsomming.'],
  [1, 'De school was dicht **omdat** de verwarming kapot was.', 'oorzaak', 'De kapotte verwarming is de oorzaak: omdat.'],
  [1, 'Ik wilde slapen, **maar** de buren hadden een feest.', 'tegenstelling', 'Slapen willen en een feest naast je: maar zet het tegenover elkaar.'],
  [1, '**Toen** de bel ging, renden we naar buiten.', 'tijd', 'Toen geeft aan wanneer iets gebeurde: tijd.'],
  [1, 'Je moet je spullen meenemen: je boek, je schrift **en** je pen.', 'opsomming', 'En verbindt de dingen in een lijstje: een opsomming.'],
  [1, 'Ik blijf thuis, **want** het sneeuwt heel hard.', 'oorzaak', 'Want geeft de reden: de sneeuw is waarom ik thuisblijf.'],
  [1, 'Tom is lang, **maar** zijn broer is klein.', 'tegenstelling', 'Maar zet lang en klein tegenover elkaar.'],
  [1, 'In de zomer kun je veel doen, **bijvoorbeeld** zwemmen of kamperen.', 'voorbeeld', 'Zwemmen en kamperen zijn voorbeelden van wat je in de zomer kunt doen.'],
  [1, 'We kochten eerst kaartjes. **Daarna** gingen we de bioscoop in.', 'tijd', 'Daarna vertelt wat er later gebeurde: een volgorde in de tijd.'],
  [1, 'Mijn oma kan goed koken. **Ook** bakt ze heerlijke taarten.', 'opsomming', 'Ook voegt nog iets toe: een opsomming.'],
  [1, 'Ik neem mijn zwemspullen mee, **want** we gaan naar het zwembad.', 'oorzaak', 'Want geeft de reden: we gaan zwemmen, daarom neem ik zwemspullen mee.'],
  [1, 'Op de markt koop je van alles, **zoals** kaas, vis en bloemen.', 'voorbeeld', 'Zoals kondigt voorbeelden aan van wat je op de markt koopt.'],
  [1, 'We keken eerst de film. **Later** praatten we er in de klas over.', 'tijd', 'Later zegt wat er na de film gebeurde: een volgorde in de tijd.'],
  [2, 'De school begint later **om** leerlingen uitgeslapen in de les te krijgen.', 'doel', 'Om ... te geeft het doel: waarvoor de school later begint.'],
  [2, 'Je krijgt de korting **als** je je schoolpas laat zien.', 'voorwaarde', 'Als geeft de voorwaarde: alleen met de pas is er korting.'],
  [2, 'Het regende, het waaide en het was koud. **Kortom**, het was rotweer.', 'conclusie', 'Kortom vat de drie dingen samen: een samenvatting.'],
  [2, 'De brug is gesloten **vanwege** een inspectie.', 'oorzaak', 'De inspectie is de reden voor de sluiting: vanwege.'],
  [2, 'In de stad is het druk. Op het platteland is het **daarentegen** rustig.', 'tegenstelling', 'Daarentegen zet stad en platteland tegenover elkaar.'],
  [2, 'Ze traint elke dag **om** de marathon te halen.', 'doel', 'Om ... te geeft het doel van het trainen.'],
  [2, 'De training gaat door, **tenzij** het onweert.', 'voorwaarde', 'Tenzij betekent: behalve als. Het onweer is de voorwaarde voor afgelasting.'],
  [2, 'Bijen zijn belangrijk. **Ten eerste** bestuiven ze bloemen. **Ten tweede** maken ze honing.', 'opsomming', 'Ten eerste en ten tweede tellen de redenen op: een opsomming.'],
  [2, 'De vissen gingen dood **doordat** de fabriek afval loosde.', 'oorzaak', 'Het lozen is de oorzaak, de dode vissen het gevolg: doordat.'],
  [2, 'Veel steden planten bomen, **onder andere** Utrecht en Nijmegen.', 'voorbeeld', 'Onder andere kondigt voorbeelden aan van steden.'],
  [2, '**Nadat** de wedstrijd was afgelopen, ging het publiek naar huis.', 'tijd', 'Nadat geeft de volgorde: eerst de wedstrijd, dan naar huis.'],
  [2, 'De gemeente plaatst hekken **met als doel** de schapen te beschermen.', 'doel', 'Met als doel zegt letterlijk waarvoor de hekken zijn.'],
  [2, 'De prijzen stegen. **Hierdoor** kochten minder mensen een kaartje.', 'oorzaak', 'Hierdoor: de prijsstijging is de oorzaak van de lagere verkoop.'],
  [2, 'Het plan is goed doordacht en betaalbaar. **Al met al** verdient het steun.', 'conclusie', 'Al met al trekt de conclusie uit de argumenten ervoor.'],
  [2, 'We gaan morgen naar het strand, **mits** het niet regent.', 'voorwaarde', 'Mits betekent: alleen als. Het droge weer is de voorwaarde.'],
  [2, 'Hij oefent elke avond op zijn gitaar **om** in de schoolband te komen.', 'doel', 'Om ... te geeft het doel van het oefenen.'],
  [2, 'De bus was te laat, mijn telefoon was leeg en het regende. **Kortom**, een rotochtend.', 'conclusie', 'Kortom vat alles samen in één zin.'],
  [2, 'De wedstrijd werd stilgelegd **vanwege** vuurwerk op het veld.', 'oorzaak', 'Vanwege geeft de reden voor het stilleggen: het vuurwerk.'],
  [2, 'Veel vogels trekken in de winter naar het zuiden, **zoals** de zwaluw en de ooievaar.', 'voorbeeld', 'Zoals kondigt voorbeelden van trekvogels aan.'],
  [2, '**Als** je te laat bent, moet je je melden bij de conciërge.', 'voorwaarde', 'Als geeft de voorwaarde: alleen wie te laat is, meldt zich.'],
  [2, 'De sportschool geeft korting **om** meer jongeren te laten sporten.', 'doel', 'Om ... te geeft het doel van de korting.'],
  [2, 'De les begon laat, de beamer deed het niet en de helft van de klas was ziek. **Samengevat**: een mislukte les.', 'conclusie', 'Samengevat kondigt een samenvatting aan van wat ervoor staat.'],
  [3, '**Hoewel** het onderzoek klein was, zijn de resultaten duidelijk.', 'concessie', 'Hoewel geeft een toegeving: het onderzoek was klein, en toch zijn de resultaten duidelijk.'],
  [3, 'De prijzen zijn gestegen. **Desondanks** is de zaal elke avond vol.', 'concessie', 'Desondanks: ondanks de hogere prijzen toch vol. Een toegeving over de zinsgrens heen.'],
  [3, 'De app is **weliswaar** gratis, maar hij verkoopt je gegevens.', 'concessie', 'Weliswaar ... maar: de schrijver geeft iets toe en zet er een bezwaar tegenover.'],
  [3, 'De regels zijn streng. **Niettemin** worden ze nauwelijks gehandhaafd.', 'concessie', 'Niettemin is een toegeving over de zinsgrens heen: de regels zijn streng, en toch gebeurt er weinig mee.'],
  [3, 'De maatregel werkt **mits** iedereen meedoet.', 'voorwaarde', 'Mits betekent: alleen als. De deelname is de voorwaarde.'],
  [3, 'Het bedrijf verhuisde naar het buitenland **teneinde** belasting te besparen.', 'doel', 'Teneinde is een formeel woord voor om ... te: het doel van de verhuizing.'],
  [3, 'De metingen zijn onvolledig en deels onbetrouwbaar. **Concluderend** kan het rapport niet worden gebruikt.', 'conclusie', 'Concluderend kondigt de conclusie aan die uit de gegevens volgt.'],
  [3, 'Het ijs smelt **als gevolg van** de opwarming van de aarde.', 'oorzaak', 'Als gevolg van wijst de oorzaak aan: de opwarming.'],
  [3, 'Sommige dieren zien in het donker. **Denk aan** katten en uilen.', 'voorbeeld', 'Denk aan geeft voorbeelden, in een nieuwe zin.'],
  [3, 'De stad werd groter. **Intussen** verdwenen de weilanden eromheen.', 'tijd', 'Intussen zegt dat het tegelijk gebeurde: een tijdsverband over de zinsgrens heen.'],
  [3, 'De speelster is jong en onervaren. **Anderzijds** is ze razendsnel.', 'tegenstelling', 'Anderzijds zet een nadeel en een voordeel tegenover elkaar.'],
  [3, 'Wolven zijn beschermd. **Bovendien** vergoedt de overheid schade aan vee.', 'opsomming', 'Bovendien voegt een tweede feit toe: een opsomming over de zinsgrens heen.'],
  [3, '**Ook al** regent het, de wedstrijd gaat door.', 'concessie', 'Ook al is een toegeving: de regen is er, en toch gaat het door.'],
  [3, 'De school wil later beginnen. **Op voorwaarde dat** de bussen aansluiten, gaat het plan door.', 'voorwaarde', 'Op voorwaarde dat zegt letterlijk waar het van afhangt.'],
  [3, '**Ondanks** de goede voorbereiding ging de presentatie mis.', 'concessie', 'Ondanks: je verwacht dat het goed gaat, en toch ging het mis. Een toegeving.'],
  [3, 'De stad investeert in fietspaden **teneinde** het autoverkeer te verminderen.', 'doel', 'Teneinde is formeel voor om ... te: het doel van de investering.'],
  [3, '**Indien** u vragen heeft, kunt u contact opnemen met de administratie.', 'voorwaarde', 'Indien is formeel voor als: alleen bij vragen neem je contact op.'],
  [3, 'De ene helft van de klas wil een excursie. De andere helft wil **daarentegen** een filmmiddag.', 'tegenstelling', 'Daarentegen zet de twee wensen tegenover elkaar.'],
  [3, 'Het onderzoek was klein en duurde kort. **Al met al** zijn de resultaten voorzichtig op te vatten.', 'conclusie', 'Al met al trekt de conclusie uit wat ervoor staat.'],
  [3, '**Ofschoon** de voorspellingen somber waren, groeide de economie.', 'concessie', 'Ofschoon is een formeel woord voor hoewel: een toegeving.'],
  [3, 'Het museum is gerenoveerd. **Tevens** is er een nieuw restaurant geopend.', 'opsomming', 'Tevens is formeel voor ook: er komt iets bij, over de zinsgrens heen.'],
  [3, 'Vroeger reisde men per koets. **Vervolgens** kwamen de trein en de auto.', 'tijd', 'Vervolgens geeft aan wat daarna kwam: een volgorde in de tijd.']
];
var AFMAKEN = [
  [1, 'Het regende hard, **dus** …', 'de wedstrijd ging niet door.', 'we gingen lekker buiten spelen.', 'de zon scheen fel.', 'ik had geen jas nodig.', 'oorzaak', 'Dus kondigt een gevolg aan. Van harde regen is een afgelaste wedstrijd het logische gevolg.'],
  [1, 'Ik ben moe, **want** …', 'ik heb slecht geslapen.', 'ik ga straks naar bed.', 'ik heb zin in gym.', 'ik voel me fit.', 'oorzaak', 'Want geeft de reden. Slecht slapen is de reden dat je moe bent.'],
  [1, 'Sam wilde buiten spelen, **maar** …', 'het regende de hele dag.', 'de zon scheen lekker.', 'zijn vrienden waren er ook.', 'hij pakte zijn bal.', 'tegenstelling', 'Maar kondigt iets aan wat tegen het eerste ingaat: regen staat tegenover buiten spelen.'],
  [1, 'Ik hou van sport, **bijvoorbeeld** …', 'voetbal en zwemmen.', 'omdat het gezond is.', 'maar niet elke dag.', 'daarna ga ik douchen.', 'voorbeeld', 'Na bijvoorbeeld komen voorbeelden van sport: voetbal en zwemmen.'],
  [1, 'Eerst deden we de toets, **daarna** …', 'keken we een film.', 'omdat het moest.', 'want het was maandag.', 'bijvoorbeeld rekenen.', 'tijd', 'Daarna vertelt wat er later gebeurde: een volgorde in de tijd.'],
  [1, 'Noor speelt hockey. **Ook** …', 'zit ze op turnen.', 'is hockey een sport.', 'omdat ze het leuk vindt.', 'gaat de wedstrijd niet door.', 'opsomming', 'Ook voegt nog iets toe: een tweede sport erbij.'],
  [1, 'Mijn broer is klein, **toch** …', 'is hij heel sterk.', 'is hij niet zo lang.', 'past hij in een kleine jas.', 'is hij de jongste.', 'tegenstelling', 'Toch kondigt iets aan wat je niet verwacht: klein en toch sterk.'],
  [1, 'De band was lek, **daarom** …', 'kwam ik te laat.', 'was de band lek.', 'ging ik lekker fietsen.', 'was ik op tijd.', 'oorzaak', 'Daarom kondigt een gevolg aan: te laat komen door de lekke band.'],
  [1, 'Je moet een warme jas aan, **zoals** …', 'een winterjas.', 'want het is koud.', 'maar het is koud.', 'dan ga je naar buiten.', 'voorbeeld', 'Zoals kondigt een voorbeeld aan van een warme jas.'],
  [1, 'De kat sliep de hele dag. **Bovendien** …', 'at ze bijna niets.', 'was ze moe.', 'daarom sliep ze.', 'is een kat een dier.', 'opsomming', 'Bovendien voegt nog iets toe aan wat de kat deed.'],
  [1, 'De sporthal is dicht, **dus** …', 'hebben we gym buiten.', 'is de sporthal open.', 'gaan we lekker binnen sporten.', 'want hij wordt verbouwd.', 'oorzaak', 'Dus geeft het gevolg: dicht, dus buiten gym.'],
  [1, 'De game is leuk, **maar** …', 'hij is wel erg duur.', 'ik speel hem elke dag.', 'mijn vrienden vinden hem ook leuk.', 'daarom speel ik hem.', 'tegenstelling', 'Maar zet er iets tegenover: leuk, maar duur.'],
  [1, '**Toen** de bel ging, …', 'liepen we naar buiten.', 'omdat het pauze was.', 'bijvoorbeeld om half elf.', 'maar het was pauze.', 'tijd', 'Toen ... , dan gebeurt er iets: een volgorde in de tijd.'],
  [1, 'We aten pizza, patat **en** …', 'een ijsje toe.', 'daarom hadden we honger.', 'maar geen pizza.', 'want het was feest.', 'opsomming', 'En voegt het laatste item van de lijst toe.'],
  [1, 'Ik had mijn jas vergeten, **dus** …', 'had ik het heel koud.', 'was het lekker warm.', 'had ik mijn jas aan.', 'scheen de zon.', 'oorzaak', 'Dus kondigt een gevolg aan: zonder jas krijg je het koud.'],
  [1, 'De toets was moeilijk, **maar** …', 'ik haalde toch een voldoende.', 'ik vond de vragen lastig.', 'de vragen waren moeilijk.', 'ik snapte er niets van.', 'tegenstelling', 'Maar zet er iets tegenover: moeilijk, maar toch een voldoende.'],
  [1, 'Er zijn veel soorten fruit, **zoals** …', 'appels en bananen.', 'want fruit is gezond.', 'maar ik eet geen fruit.', 'daarna eten we een toetje.', 'voorbeeld', 'Zoals kondigt voorbeelden aan: appels en bananen.'],
  [1, 'Eerst doen we de afwas, **daarna** …', 'kijken we televisie.', 'omdat het vies is.', 'bijvoorbeeld de borden.', 'maar we hebben geen zin.', 'tijd', 'Eerst ... daarna: een volgorde in de tijd.'],
  [1, 'Mijn zus kan goed zwemmen. **Bovendien** …', 'kan ze heel hard rennen.', 'zwemt ze heel goed.', 'daarom zwemt ze.', 'is zwemmen een sport.', 'opsomming', 'Bovendien voegt nog iets toe: iets anders waar ze goed in is.'],
  [1, 'Het was heel warm, **daarom** …', 'gingen we naar het strand.', 'trokken we een dikke jas aan.', 'was het heel warm.', 'bleven we in bed met een kruik.', 'oorzaak', 'Daarom kondigt een gevolg aan: bij warmte ga je naar het strand.'],
  [1, 'Ik lees graag boeken, **zoals** …', 'strips en spannende verhalen.', 'want lezen is leuk.', 'maar niet op school.', 'daarna ga ik slapen.', 'voorbeeld', 'Zoals kondigt voorbeelden aan van boeken.'],
  [1, 'Eerst smeer je de boterham, **daarna** …', 'leg je er kaas op.', 'pak je het brood.', 'omdat je honger hebt.', 'bijvoorbeeld met jam.', 'tijd', 'Daarna zegt wat je doet na het smeren; het brood pak je juist eerder.'],
  [2, 'De school plant bomen **om** …', 'het plein koeler te maken.', 'want het is warm.', 'daardoor is het koeler.', 'het plein is warm.', 'doel', 'Om ... te geeft het doel: waarvoor de bomen zijn.'],
  [2, 'Je krijgt korting, **mits** …', 'je je schoolpas laat zien.', 'de korting is groot.', 'daarom ga je naar de winkel.', 'de winkel is dicht.', 'voorwaarde', 'Mits betekent alleen als: de pas is de voorwaarde.'],
  [2, 'Het regende, het waaide en het was koud. **Kortom**, …', 'het was rotweer.', 'de zon scheen.', 'daarna werd het warm.', 'bijvoorbeeld in de herfst.', 'conclusie', 'Kortom vat alles samen in één zin.'],
  [2, 'De brug is dicht **doordat** …', 'er een inspectie is.', 'de auto’s omrijden.', 'het verkeer vastloopt.', 'de brug open is.', 'oorzaak', 'Doordat kondigt de oorzaak aan: de inspectie is de reden dat de brug dicht is.'],
  [2, 'In de stad is het druk. Op het platteland is het **daarentegen** …', 'rustig.', 'ook druk.', 'daarom druk.', 'een dorp.', 'tegenstelling', 'Daarentegen zet twee dingen tegenover elkaar: druk tegenover rustig.'],
  [2, 'De training gaat door, **tenzij** …', 'het onweert.', 'de zon schijnt.', 'we mooi weer hebben.', 'iedereen komt.', 'voorwaarde', 'Tenzij betekent behalve als: bij onweer gaat het niet door.'],
  [2, 'Bijen zijn belangrijk. **Ten eerste** bestuiven ze bloemen. **Ten tweede** …', 'maken ze honing.', 'daardoor bestuiven ze bloemen.', 'zijn bloemen belangrijk.', 'omdat ze bestuiven.', 'opsomming', 'Ten tweede voegt een tweede reden toe aan de opsomming.'],
  [2, 'De prijzen stegen. **Hierdoor** …', 'kochten minder mensen een kaartje.', 'werden de prijzen hoger.', 'bleven de prijzen gelijk.', 'bijvoorbeeld bij de bioscoop.', 'oorzaak', 'Hierdoor kondigt het gevolg aan van de prijsstijging.'],
  [2, 'Veel steden planten bomen, **onder andere** …', 'Utrecht en Nijmegen.', 'omdat het koeler wordt.', 'daarom is het groen.', 'maar niet overal.', 'voorbeeld', 'Onder andere kondigt voorbeelden aan.'],
  [2, '**Nadat** de wedstrijd was afgelopen, …', 'ging het publiek naar huis.', 'omdat het laat was.', 'want de wedstrijd was leuk.', 'bijvoorbeeld de scheidsrechter.', 'tijd', 'Nadat geeft de volgorde: na de wedstrijd gebeurt er iets.'],
  [2, 'De gemeente plaatst hekken **zodat** …', 'de schapen veilig zijn.', 'er wolven zijn.', 'de hekken duur zijn.', 'omdat er wolven zijn.', 'doel', 'Zodat geeft hier het doel van de hekken: veilige schapen.'],
  [2, 'Het plan is goed doordacht en betaalbaar. **Al met al** …', 'verdient het steun.', 'is het duur.', 'bijvoorbeeld het budget.', 'daarna komt er een ander plan.', 'conclusie', 'Al met al trekt de conclusie uit de argumenten ervoor.'],
  [2, 'Ze spaart elke maand **om** …', 'een laptop te kunnen kopen.', 'want ze heeft geld.', 'daardoor heeft ze geld.', 'ze heeft een laptop.', 'doel', 'Om ... te: de laptop is het doel van het sparen.'],
  [2, 'De uitslag was slecht. **Toch** …', 'bleef de trainer positief.', 'was iedereen teleurgesteld.', 'verloor het team.', 'daarom was de trainer boos.', 'tegenstelling', 'Toch kondigt iets aan wat je niet verwacht na een slechte uitslag.'],
  [2, 'Je mag op het schoolfeest komen, **mits** …', 'je een kaartje hebt gekocht.', 'het feest leuk is.', 'daarom kom je.', 'het is vrijdag.', 'voorwaarde', 'Mits betekent alleen als: het kaartje is de voorwaarde.'],
  [2, 'Hij zet elke dag een wekker **om** …', 'op tijd op school te zijn.', 'want hij is vaak te laat.', 'daardoor is hij op tijd.', 'hij wordt wakker.', 'doel', 'Om ... te geeft het doel van de wekker.'],
  [2, 'De zaal was vol, het publiek zong mee en de band speelde twee uur. **Kortom**, …', 'het was een geweldig concert.', 'de zaal was leeg.', 'bijvoorbeeld de zanger.', 'daarna gingen we naar huis.', 'conclusie', 'Kortom vat alles samen in één oordeel.'],
  [2, 'De voetballer raakte geblesseerd **doordat** …', 'hij verkeerd op zijn enkel landde.', 'hij drie weken niet kon spelen.', 'de trainer hem wisselde.', 'hij toch doorspeelde.', 'oorzaak', 'Doordat kondigt de oorzaak aan: de verkeerde landing.'],
  [2, 'Je kunt de film vanavond zien, **tenzij** …', 'hij is uitverkocht.', 'je een kaartje hebt.', 'de bioscoop open is.', 'daarom ga je.', 'voorwaarde', 'Tenzij betekent behalve als: als hij uitverkocht is, lukt het niet.'],
  [2, 'Je mag op het plein voetballen, **tenzij** …', 'de bel al is gegaan.', 'je een bal hebt.', 'het pauze is.', 'daarom speel je buiten.', 'voorwaarde', 'Tenzij betekent behalve als: na de bel mag het niet meer.'],
  [2, 'De bibliotheek is langer open **om** …', 'scholieren rustig te laten studeren.', 'want er zijn veel scholieren.', 'daardoor is het druk.', 'de boeken zijn nieuw.', 'doel', 'Om ... te geeft het doel van de langere openingstijden.'],
  [2, 'Mijn broer houdt van drukte en feesten. Mijn zus is **daarentegen** …', 'liever alleen thuis met een boek.', 'ook dol op feesten.', 'daarom vaak op feestjes.', 'bijvoorbeeld op een verjaardag.', 'tegenstelling', 'Daarentegen zet de zus tegenover de broer: rust tegenover drukte.'],
  [3, '**Hoewel** het onderzoek klein was, …', 'zijn de resultaten duidelijk.', 'is het niet betrouwbaar.', 'deden er weinig mensen mee.', 'daarom klopt het niet.', 'concessie', 'Hoewel is een toegeving: ondanks het kleine onderzoek zijn de resultaten toch duidelijk.'],
  [3, 'De prijzen zijn gestegen. **Desondanks** …', 'is de zaal elke avond vol.', 'komen er minder mensen.', 'zijn de kaartjes duurder.', 'daarom blijft de zaal leeg.', 'concessie', 'Desondanks: ondanks de hogere prijzen toch vol.'],
  [3, 'De app is **weliswaar** gratis, **maar** …', 'hij verkoopt je gegevens.', 'je hoeft niets te betalen.', 'daarom downloadt iedereen hem.', 'hij kost niets.', 'concessie', 'Weliswaar ... maar: de schrijver geeft iets toe en noemt dan het bezwaar.'],
  [3, 'De maatregel werkt **mits** …', 'iedereen meedoet.', 'niemand meedoet.', 'daardoor werkt hij.', 'hij werkt goed.', 'voorwaarde', 'Mits: de maatregel werkt alleen als iedereen meedoet.'],
  [3, 'Het bedrijf verhuisde **teneinde** …', 'belasting te besparen.', 'want het was duur.', 'daardoor bespaarde het geld.', 'het bespaarde belasting.', 'doel', 'Teneinde is formeel voor om ... te: het doel van de verhuizing.'],
  [3, 'De metingen zijn onvolledig en onbetrouwbaar. **Concluderend** …', 'is het rapport niet bruikbaar.', 'zijn de metingen goed.', 'bijvoorbeeld de temperatuur.', 'daarna volgen nieuwe metingen.', 'conclusie', 'Concluderend trekt de conclusie uit de gegevens.'],
  [3, 'Het ijs smelt **als gevolg van** …', 'de opwarming van de aarde.', 'de zeespiegel stijgt.', 'ondanks de kou.', 'de ijsberen.', 'oorzaak', 'Als gevolg van wijst de oorzaak aan.'],
  [3, 'Sommige dieren zien in het donker. **Denk aan** …', 'katten en uilen.', 'omdat ze goede ogen hebben.', 'daarom jagen ze ’s nachts.', 'hoewel het donker is.', 'voorbeeld', 'Denk aan geeft voorbeelden.'],
  [3, 'De stad werd groter. **Intussen** …', 'verdwenen de weilanden eromheen.', 'omdat er meer mensen kwamen.', 'bijvoorbeeld Utrecht.', 'daarom groeide de stad.', 'tijd', 'Intussen: tegelijkertijd gebeurde er iets anders.'],
  [3, 'De speelster is jong en onervaren. **Anderzijds** …', 'is ze razendsnel.', 'heeft ze weinig wedstrijden gespeeld.', 'is ze pas zestien.', 'daarom speelt ze niet.', 'tegenstelling', 'Anderzijds zet een voordeel tegenover de nadelen.'],
  [3, 'Wolven zijn beschermd. **Bovendien** …', 'vergoedt de overheid schade aan vee.', 'zijn wolven beschermd.', 'daarom mag je er niet op jagen.', 'hoewel ze beschermd zijn.', 'opsomming', 'Bovendien voegt een tweede feit toe.'],
  [3, '**Ook al** regent het, …', 'de wedstrijd gaat door.', 'de wedstrijd wordt afgelast.', 'daarom blijven we binnen.', 'want het is nat.', 'concessie', 'Ook al is een toegeving: de regen is er, en toch gaat het door.'],
  [3, 'Er is geen bewijs voor de theorie. **Niettemin** …', 'geloven veel mensen erin.', 'wordt ze verworpen.', 'daarom klopt ze niet.', 'is er geen bewijs.', 'concessie', 'Niettemin: geen bewijs, en toch geloof. Een toegeving over de zinsgrens heen.'],
  [3, 'De school wil later beginnen, **op voorwaarde dat** …', 'de bussen aansluiten.', 'daarom rijden de bussen later.', 'de school later begint.', 'omdat pubers slecht slapen.', 'voorwaarde', 'Op voorwaarde dat zegt waar het plan van afhangt.'],
  [3, '**Hoewel** de spits drie kansen miste, …', 'won zijn team toch met 2-0.', 'verloor zijn team.', 'was hij slecht in vorm.', 'daarom werd hij gewisseld.', 'concessie', 'Hoewel is een toegeving: ondanks de gemiste kansen won het team toch.'],
  [3, 'De gemeente plaatste extra afvalbakken **teneinde** …', 'het zwerfafval te verminderen.', 'want er lag veel afval.', 'daardoor was het schoon.', 'ondanks het vele afval.', 'doel', 'Teneinde is formeel voor om ... te: het doel van de afvalbakken.'],
  [3, 'Het museum trekt veel bezoekers. **Desondanks** …', 'maakt het elk jaar verlies.', 'is het erg populair.', 'komen er veel mensen.', 'daarom is het druk.', 'concessie', 'Desondanks: veel bezoekers, en toch verlies. Een toegeving over de zinsgrens heen.'],
  [3, 'Het rapport bevat fouten, verouderde cijfers en geen bronnen. **Concluderend** …', 'is het onbruikbaar voor ons onderzoek.', 'is het een betrouwbaar rapport.', 'bijvoorbeeld de cijfers uit 2010.', 'ondanks de fouten.', 'conclusie', 'Concluderend trekt de conclusie uit de opgesomde gebreken.'],
  [3, 'De schade aan de oogst ontstond **als gevolg van** …', 'de lange periode van droogte.', 'de boeren minder verdienden.', 'ondanks de regen.', 'de prijzen stegen.', 'oorzaak', 'Als gevolg van wijst de oorzaak aan: de droogte.'],
  [3, '**Ofschoon** de trainer tevreden was over het spel, …', 'was hij teleurgesteld over de uitslag.', 'was hij blij met het spel.', 'speelde het team goed.', 'daarom won het team.', 'concessie', 'Ofschoon is een toegeving: tevreden over het spel, en toch teleurgesteld over de uitslag.'],
  [3, 'Veel dieren houden een winterslaap, **onder andere** …', 'egels en vleermuizen.', 'omdat het koud is.', 'hoewel het winter is.', 'daardoor overleven ze.', 'voorbeeld', 'Onder andere kondigt voorbeelden aan van dieren met een winterslaap.'],
  [3, 'De leerlingen verzamelden eerst gegevens. **Vervolgens** …', 'verwerkten ze die in een grafiek.', 'omdat ze gegevens nodig hadden.', 'hadden ze nog geen gegevens.', 'ondanks de gegevens.', 'tijd', 'Vervolgens geeft de volgende stap: eerst verzamelen, dan verwerken.']
];
return { VERBANDEN: VERBANDEN, WOORDEN: WOORDEN, INVUL: INVUL, WELK: WELK, AFMAKEN: AFMAKEN };
})();
