/* De alinea's van de Tekstdetective. Gedeeld door het spel (tekstdetective.html)
   en het werkblad (werkblad.html); daarom in een eigen bestand en onder een
   eigen naam, zodat NIVEAUS en SOORTEN niet botsen met die van de vragenbank. */
var TEKSTOPGAVEN = (function(){
/* ============================================================================
   DE ALINEA'S
   Elke alinea heeft: t = de tekst, met het signaalwoord tussen [rechte haken],
   h = de vier keuzes voor de hoofdgedachte met g = welke goed is, v = het
   verband dat het signaalwoord aangeeft, u = de uitleg, s = soort tekst.
   Een alinea toevoegen: zet er een blok bij in ALINEAS. Zet precies een woord
   of woordgroep tussen haken; dat wordt de knop die goed is.
   ============================================================================ */
var VERBANDEN = [
  { id:'oorzaak',     naam:'oorzaak en gevolg', uit:'het een komt door het ander' },
  { id:'tegenstel',   naam:'tegenstelling',     uit:'het staat tegenover elkaar' },
  { id:'opsomming',   naam:'opsomming',         uit:'er komt nog iets bij' },
  { id:'vergelijk',   naam:'vergelijking',      uit:'het lijkt op elkaar of wordt afgezet' },
  { id:'tijd',        naam:'tijdsverband',      uit:'het gaat over wanneer' },
  { id:'voorwaarde',  naam:'voorwaarde',        uit:'het geldt alleen als' },
  { id:'doel',        naam:'doel',              uit:'het gebeurt om iets te bereiken' },
  { id:'toelichting', naam:'toelichting',       uit:'er komt een voorbeeld of uitleg' },
  { id:'conclusie',   naam:'conclusie',         uit:'dit volgt eruit' }
];
var SOORTEN = [
  { id:'info', naam:'informatie' }, { id:'betoog', naam:'betoog' }, { id:'verhaal', naam:'verhaal' }, { id:'nieuws', naam:'nieuws' },
  { id:'instructie', naam:'instructie' }, { id:'reclame', naam:'reclame' }
];
/* Het schrijfdoel, precies de zes uit de syllabus Nederlands vmbo (NE/K/6).
   Staat er bij een alinea geen doel, dan volgt het uit de tekstsoort. */
var DOELEN = [
  { id:'info',     naam:'informatie geven',        uit:'de schrijver wil dat je iets te weten komt' },
  { id:'overtuig', naam:'overtuigen',              uit:'de schrijver wil dat je het met hem eens wordt' },
  { id:'mening',   naam:'een mening geven',        uit:'de schrijver vertelt wat hij ervan vindt' },
  { id:'aanzet',   naam:'tot handelen aanzetten',  uit:'de schrijver wil dat je iets gaat doen' },
  { id:'amuseer',  naam:'amuseren',                uit:'de schrijver wil je vermaken' },
  { id:'gevoel',   naam:'gevoelens oproepen',      uit:'de schrijver wil dat je iets voelt' }
];
var DOEL_VAN_SOORT = { info:'info', nieuws:'info', betoog:'overtuig', verhaal:'amuseer', instructie:'aanzet', reclame:'aanzet' };
var LEERJAREN = [
  { id:'12', naam:'leerjaar 1 en 2', uit:'Alinea\u2019s over dingen dichtbij.' },
  { id:'34', naam:'leerjaar 3 en 4', uit:'Ook langere examenteksten, zoals op het centraal examen vmbo.' }
];
var ALINEAS = [
  { s:'info', n:1, v:'oorzaak',
    t:'De meeste scholen beginnen om half negen. Veel leerlingen zijn dan nog niet wakker, [doordat] hun biologische klok in de puberteit een paar uur opschuift. Ze vallen later in slaap en worden later uitgerust.',
    h:['Pubers zijn lui in de ochtend.', 'Scholen beginnen te vroeg voor de slaapklok van pubers.', 'Iedereen valt laat in slaap.', 'Half negen is een prima begintijd.'], g:2,
    u:'De alinea legt uit waardoor het komt dat pubers slaperig zijn, niet dat ze lui zijn.' },
  { s:'info', n:1, v:'opsomming',
    t:'Een fiets heeft weinig onderhoud nodig. Je moet de banden op spanning houden en de ketting af en toe smeren. [Daarnaast] controleer je een keer per jaar de remblokjes.',
    h:['Fietsen is gezond.', 'Een fiets gaat maar kort mee.', 'Onderhoud aan een fiets is beperkt en bestaat uit een paar vaste klusjes.', 'Remblokjes zijn duur.'], g:3,
    u:'Alle zinnen noemen klusjes op. Samen vormen ze het beperkte onderhoud.' },
  { s:'nieuws', n:1, v:'tegenstel',
    t:'De gemeente wil een nieuw zwembad bouwen aan de rand van het dorp. De sportclubs zijn blij met de plannen. [Maar] omwonenden vrezen drukte en zoeken naar parkeerplaatsen.',
    h:['Het zwembad komt er zeker.', 'Sportclubs en omwonenden denken verschillend over het nieuwe zwembad.', 'Er zijn te weinig parkeerplaatsen in het dorp.', 'De gemeente heeft geen geld.'], g:2,
    u:'Twee groepen staan tegenover elkaar. Dat is de kern van de alinea.' },
  { s:'betoog', n:2, v:'conclusie',
    t:'Telefoons in de klas leiden af. Onderzoek laat zien dat leerlingen zonder telefoon meer onthouden van de les en sneller weer aan het werk gaan na een onderbreking. [Dus] hoort de telefoon in de kluis.',
    h:['Telefoons zijn slecht voor je ogen.', 'Onderzoek is vaak onbetrouwbaar.', 'Omdat telefoons afleiden, kun je ze beter uit de klas houden.', 'Leerlingen mogen zelf kiezen.'], g:3,
    u:'De laatste zin trekt de conclusie uit de argumenten ervoor. Dat is de hoofdgedachte.' },
  { s:'info', n:2, v:'vergelijk',
    t:'Een vulkaanuitbarsting en een aardbeving hebben dezelfde oorsprong: de bewegende platen van de aardkorst. [Net als] bij een aardbeving bouwt zich eerst druk op, die er daarna in een keer uit komt.',
    h:['Vulkanen zijn gevaarlijker dan aardbevingen.', 'Vulkanen en aardbevingen ontstaan allebei door opgebouwde druk in de aardkorst.', 'De aardkorst beweegt nooit.', 'Aardbevingen duren langer.'], g:2,
    u:'De alinea zet twee verschijnselen naast elkaar en wijst op wat hetzelfde is.' },
  { s:'verhaal', n:2, v:'tijd',
    t:'Sam controleerde nog een keer of de deur op slot zat. [Vervolgens] liep hij de trap af, zette zijn capuchon op en stapte de regen in zonder om te kijken.',
    h:['Sam vertrekt en kijkt niet meer om.', 'Sam is bang voor de regen.', 'De deur zat niet op slot.', 'Sam woont op de begane grond.'], g:1,
    u:'De alinea beschrijft een reeks handelingen na elkaar. De kern is dat hij weggaat.' },
  { s:'betoog', n:2, v:'voorwaarde',
    t:'Een schooltuin kan veel opleveren. Leerlingen leren waar hun eten vandaan komt en werken buiten. [Alleen als] er elke week iemand verantwoordelijk is, blijft de tuin er netjes bij.',
    h:['Schooltuinen zijn zonde van de ruimte.', 'Een schooltuin werkt alleen met vaste zorg, maar levert dan veel op.', 'Leerlingen weten niets over eten.', 'Buiten werken is ongezond.'], g:2,
    u:'De laatste zin noemt de voorwaarde waaronder het voordeel overeind blijft.' },
  { s:'info', n:2, v:'doel',
    t:'In veel steden komen groene daken op flats en scholen. De planten houden regenwater vast [om] het riool te ontlasten bij een hoosbui. Daarnaast blijft het gebouw eronder koeler.',
    h:['Groene daken zijn duur.', 'Planten hebben veel water nodig.', 'Groene daken houden regenwater vast en houden het gebouw koel.', 'Het riool is kapot.'], g:3,
    u:'Het signaalwoord wijst op het doel: waarvoor het water wordt vastgehouden.' },
  { s:'nieuws', n:2, v:'toelichting',
    t:'Steeds meer supermarkten halen kleine plastic verpakkingen uit de schappen. [Zo] verdwenen de plastic zakjes bij de groente en liggen komkommers nu los.',
    h:['Komkommers bederven sneller.', 'Supermarkten verkopen minder groente.', 'Supermarkten schrappen kleine plastic verpakkingen, bijvoorbeeld bij groente.', 'Plastic is verboden.'], g:3,
    u:'De tweede zin geeft een voorbeeld van de eerste. Het voorbeeld is niet de hoofdgedachte.' },
  { s:'betoog', n:3, v:'tegenstel',
    t:'Het klinkt logisch om de maximumsnelheid overal te verlagen: minder uitstoot, minder ongelukken. [Toch] blijkt de winst klein zolang vrachtverkeer en industrie op volle kracht doordraaien, terwijl de weerstand bij automobilisten groot is.',
    h:['Snelheid verlagen helpt altijd.', 'Vrachtverkeer moet harder rijden.', 'De verwachte winst van lagere snelheid valt tegen tegenover het verzet dat het oproept.', 'Automobilisten rijden te hard.'], g:3,
    u:'Het eerste deel geeft de verwachting, na het signaalwoord komt de tegenwerping. Die tegenwerping draagt de alinea.' },
  { s:'info', n:3, v:'oorzaak',
    t:'Tussen 1845 en 1850 stierf in Ierland ruim een miljoen mensen. De aardappelziekte vernietigde de oogst, [waardoor] gezinnen die vrijwel alleen van aardappels leefden van het ene op het andere jaar zonder voedsel zaten.',
    h:['Ierland had te veel inwoners.', 'Aardappels zijn ongezond.', 'Doordat een eenzijdig gewas mislukte, viel de voedselvoorziening van hele gezinnen weg.', 'De oogst van 1850 was goed.'], g:3,
    u:'De alinea verklaart de sterfte uit de mislukte oogst en de afhankelijkheid van een gewas.' },
  { s:'betoog', n:3, v:'conclusie',
    t:'Wie een vak wil leren, moet fouten kunnen maken. In een werkplaats kost een fout hout of tijd, in een ziekenhuis kost een fout veel meer. [Daarom] oefenen artsen eerst jarenlang op poppen, simulaties en onder toezicht.',
    h:['Artsen maken nooit fouten.', 'Omdat fouten in de zorg te duur zijn, wordt het leren daar verschoven naar een veilige oefenplek.', 'Werkplaatsen zijn gevaarlijk.', 'Simulaties zijn te duur.'], g:2,
    u:'De slotzin volgt uit de vergelijking ervoor. Let op: de vergelijking is de opstap, niet de kern.' },
  { s:'info', n:3, v:'vergelijk',
    t:'Een algoritme kiest wat je op sociale media ziet. [Vergeleken met] een krantenredactie, die haar keuzes verantwoordt in een colofon, blijft bij zo\u2019n algoritme onzichtbaar waarom juist dit bericht bovenaan staat.',
    h:['Kranten zijn saai.', 'Algoritmes werken sneller dan redacties.', 'Anders dan bij een krantenredactie is bij een algoritme niet te zien waarom iets wordt getoond.', 'Sociale media hebben geen redactie nodig.'], g:3,
    u:'De vergelijking dient om het verschil scherp te maken: zichtbare verantwoording tegenover onzichtbare keuze.' },
  { s:'verhaal', n:3, v:'tijd',
    t:'Jarenlang had het huis leeggestaan. De ramen waren dichtgetimmerd, in de goot groeide een berkje. [Sinds] de nieuwe eigenaren er zijn, staat er elke zaterdag een container voor de deur en klinkt er geklop tot in de avond.',
    h:['Het huis is gesloopt.', 'De buurt klaagt over het geluid.', 'Na jaren leegstand wordt het huis nu opgeknapt.', 'Berken groeien snel.'], g:3,
    u:'De alinea zet twee periodes tegenover elkaar in de tijd. Het keerpunt is de hoofdgedachte.' },
  { s:'nieuws', n:3, v:'voorwaarde',
    t:'Het museum kan de collectie in eigen huis houden. De provincie legt geld bij en de gemeente verlengt de huur, [mits] het museum zelf een kwart van de kosten ophaalt bij donateurs.',
    h:['De collectie wordt verkocht.', 'De provincie betaalt alles.', 'Het museum blijft alleen open als het zelf een deel van het geld binnenhaalt.', 'Donateurs zijn niet welkom.'], g:3,
    u:'Het signaalwoord koppelt de steun aan een eis. Die eis bepaalt of het doorgaat.' },
  { s:'betoog', n:3, v:'opsomming',
    t:'Een vierdaagse schoolweek klinkt aantrekkelijk voor leerlingen. Docenten zouden minder reizen, roosters worden compacter. [Bovendien] blijft er een dag over voor stage, sport of bijles, die nu tussen de lessen door moet worden gepropt.',
    h:['Leerlingen willen minder huiswerk.', 'De vierdaagse week levert winst op voor rooster, reistijd en ruimte voor andere activiteiten.', 'Docenten reizen graag.', 'Stages zijn verplicht.'], g:2,
    u:'De alinea stapelt voordelen. De hoofdgedachte vat die stapel samen.' },
  { s:'info', n:1, v:'toelichting',
    t:'Niet al het afval hoort in dezelfde bak. Karton, glas en gft gaan apart. [Bijvoorbeeld] een pizzadoos met vetvlekken hoort juist bij het restafval, want vet verpest het oud papier.',
    h:['Pizzadozen zijn altijd karton.', 'Afval scheiden luistert nauw, ook binnen een soort materiaal.', 'Glas mag in de gft-bak.', 'Restafval bestaat niet meer.'], g:2,
    u:'Het voorbeeld ondersteunt de eerste zin. De eerste zin is de hoofdgedachte.' },
  { s:'verhaal', n:1, v:'oorzaak',
    t:'Nadia keek nog een keer op haar telefoon. Geen bericht. [Omdat] ze niet wist of de afspraak nog doorging, bleef ze maar op het bankje bij de ingang zitten.',
    h:['Nadia wacht omdat ze geen duidelijkheid heeft.', 'Nadia is te laat.', 'De afspraak ging niet door.', 'Nadia heeft geen telefoon.'], g:1,
    u:'Het signaalwoord verbindt de onzekerheid met haar wachten.' },
  { s:'nieuws', n:2, v:'oorzaak',
    t:'De veerboot naar het eiland voer dit weekend niet. Door een storing aan de stuurinrichting moest de boot naar de werf, [zodat] honderden dagjesmensen op de kade bleven staan.',
    h:['Het eiland is gesloten.', 'Een technische storing legde de veerdienst stil en strandde de reizigers.', 'De werf is failliet.', 'Er komen te veel toeristen.'], g:2,
    u:'De storing is de oorzaak, de gestrande reizigers zijn het gevolg.' },
  { s:'betoog', n:1, v:'doel',
    t:'Op steeds meer scholen staat een waterkraan in de gang. Leerlingen kunnen hun eigen fles bijvullen [om] te voorkomen dat ze in de pauze een blikje frisdrank kopen.',
    h:['Frisdrank is verboden.', 'Waterkranen op school moeten zorgen dat leerlingen minder frisdrank drinken.', 'Leerlingen hebben geen flessen.', 'Water is duur.'], g:2,
    u:'Het signaalwoord noemt waarvoor de kraan er hangt.' },
  /* ---- vmbo-bb ---- */
  { s:'instructie', n:1, v:'tijd', d:'aanzet',
    t:'Zet de pan met water op het vuur en wacht tot het kookt. [Daarna] doe je de pasta erin en zet je het vuur wat lager. Roer af en toe, anders plakt de pasta aan elkaar.',
    h:['Pasta koken gaat in een vaste volgorde.', 'Pasta plakt altijd.', 'Je moet het vuur hoog zetten.', 'Water koken duurt lang.'], g:1,
    u:'Een instructie zegt wat je in welke volgorde doet. Het plakken is een waarschuwing, niet de kern.' },
  { s:'reclame', n:1, v:'voorwaarde', d:'aanzet',
    t:'Deze week bij de Sportshop: koop een paar voetbalschoenen en krijg een bal cadeau. [Als] je de bon uit de folder meeneemt, krijg je ook nog tien procent korting. Alleen deze week, op is op.',
    h:['De Sportshop verkoopt alleen ballen.', 'De Sportshop wil dat je deze week schoenen komt kopen.', 'Voetbalschoenen zijn duur.', 'De folder is gratis.'], g:2,
    u:'Alles in de tekst duwt je naar de winkel: cadeau, korting, deze week. Dat is waar reclame voor is.' },
  { s:'info', n:1, v:'tegenstel', d:'info',
    t:'Een kameel kan dagen zonder water. In zijn bulten zit geen water, [maar] vet. Dat vet gebruikt zijn lijf als er even geen eten is.',
    h:['Kamelen drinken nooit.', 'In de bulten van een kameel zit vet, geen water.', 'Kamelen eten vet.', 'Een kameel heeft altijd honger.'], g:2,
    u:'De alinea zet iets recht wat veel mensen denken: geen water in de bult, maar vet.' },
  { s:'nieuws', n:1, v:'oorzaak', d:'info',
    t:'De ijsbaan in het park is dit weekend dicht. [Door] de regen van vrijdag ligt er een laag water op het ijs, en dat is te gevaarlijk om op te schaatsen.',
    h:['Schaatsen is gevaarlijk.', 'Het park is gesloten.', 'De ijsbaan is dicht omdat er water op het ijs ligt.', 'Het regent elk weekend.'], g:3,
    u:'Het signaalwoord verbindt de regen met de dichte ijsbaan: oorzaak en gevolg.' },
  { s:'verhaal', n:1, v:'tegenstel', d:'gevoel',
    t:'Sem had de hele week geoefend voor zijn spreekbeurt. Hij kende elk woord uit zijn hoofd. [Toch] begon zijn stem te trillen toen de juf zijn naam noemde.',
    h:['Sem had niet geoefend.', 'De juf was streng.', 'Ondanks al zijn oefenen was Sem toch zenuwachtig.', 'Sem vergat zijn tekst.'], g:3,
    u:'Toch draait de verwachting om: goed voorbereid en toch zenuwen. Dat is waar het verhaal om gaat.' },
  { s:'betoog', n:1, v:'conclusie', d:'overtuig',
    t:'In de pauze ligt het plein vol met blikjes en wikkels. De prullenbakken staan er wel, maar niemand loopt ernaartoe. [Daarom] moeten er meer bakken komen, vlak bij de bankjes.',
    h:['Het plein is te klein.', 'Er moeten meer prullenbakken bij de bankjes komen.', 'Leerlingen eten te veel snoep.', 'De pauze is te lang.'], g:2,
    u:'De laatste zin is de conclusie en meteen het standpunt van de schrijver.' },
  { s:'info', n:1, v:'opsomming', d:'info',
    t:'Een bijenkoningin legt elke dag wel duizend eitjes. De werkbijen halen nectar, maken honing en houden de korf schoon. [Ook] beschermen ze de ingang tegen wespen.',
    h:['Bijen maken alleen honing.', 'Wespen zijn gevaarlijk.', 'De koningin doet al het werk.', 'In een bijenkorf heeft elke bij een taak.'], g:4,
    u:'De alinea somt taken op: koningin, werkbijen, bewaking. Samen: iedereen heeft een taak.' },
  { s:'instructie', n:1, v:'voorwaarde', d:'aanzet',
    t:'Laad de powerbank eerst helemaal op voordat je hem gebruikt. Sluit je telefoon aan met de korte kabel. [Wanneer] het lampje groen wordt, is je telefoon vol en kun je de kabel losmaken.',
    h:['Powerbanks gaan snel kapot.', 'Zo gebruik je de powerbank: opladen, aansluiten, wachten op groen.', 'Het lampje is altijd groen.', 'Je hebt een lange kabel nodig.'], g:2,
    u:'De tekst vertelt stap voor stap hoe je het ding gebruikt; het groene lampje is het teken om te stoppen.' },
  { s:'nieuws', n:1, v:'tijd', d:'info',
    t:'De nieuwe fietsbrug over het kanaal is klaar. [Vanaf] maandag mogen fietsers erover en hoeven ze niet meer om te rijden via de drukke weg. De wethouder knipt om acht uur het lint door.',
    h:['De brug is nog niet klaar.', 'Vanaf maandag kunnen fietsers de nieuwe brug gebruiken.', 'De wethouder fietst elke dag.', 'De drukke weg gaat dicht.'], g:2,
    u:'Het nieuws is dat de brug opengaat, en wanneer. Het lint is een bijzaak.' },
  { s:'betoog', n:1, v:'toelichting', d:'mening',
    t:'Ik vind dat elke klas een eigen plant moet hebben. Een plant maakt het lokaal gezelliger. [Bijvoorbeeld] de klas van meneer De Vries: daar staat een grote palm en iedereen wil er zitten.',
    h:['Palmen zijn de mooiste planten.', 'Meneer De Vries is aardig.', 'Een plant in de klas maakt het lokaal gezelliger.', 'Elke klas is even gezellig.'], g:3,
    u:'De palm is het voorbeeld dat de mening ondersteunt. De mening zelf is de kern.' },
  { s:'verhaal', n:1, v:'oorzaak', d:'amuseer',
    t:'Opa wilde de hond wassen in de tuin. Hij pakte de tuinslang en draaide de kraan open. [Doordat] de slang los lag, spoot het water alle kanten op, behalve op de hond. Opa was drijfnat, de hond kurkdroog.',
    h:['Honden houden niet van water.', 'Opa kan niet met een tuinslang omgaan.', 'Omdat de slang los lag, werd opa nat en de hond niet.', 'De kraan was kapot.'], g:3,
    u:'De losse slang is de oorzaak van de natte opa. Dat is de grap van het verhaal.' },
  { s:'reclame', n:1, v:'opsomming', d:'aanzet',
    t:'Kom naar de open dag van het zwembad! Er is een springkussen in het water, een wedstrijd wie het langst onder water blijft [en] om drie uur een duik van de badmeester van de hoge duikplank. Toegang gratis.',
    h:['Het zwembad is gratis.', 'De badmeester kan goed duiken.', 'Op de open dag van het zwembad is van alles te doen.', 'Springkussens zijn gevaarlijk.'], g:3,
    u:'De tekst somt op wat er te doen is, om je over te halen te komen.' },
  { s:'info', n:1, v:'vergelijk', d:'info',
    t:'Een e-bike lijkt op een gewone fiets, maar een motortje helpt je bij het trappen. [Net als] bij een gewone fiets moet je zelf blijven trappen, anders doet het motortje niets.',
    h:['Een e-bike trapt vanzelf.', 'Op een e-bike trap je zelf, het motortje helpt alleen.', 'Een e-bike is een brommer.', 'Gewone fietsen zijn beter.'], g:2,
    u:'De vergelijking met de gewone fiets maakt duidelijk wat de e-bike wel en niet doet.' },
  { s:'nieuws', n:1, v:'conclusie', d:'info',
    t:'Bij de tellingen op het schoolplein bleek dat er elke dag zeshonderd fietsen staan, terwijl er maar vierhonderd rekken zijn. [Dus] gaat de school na de vakantie tweehonderd rekken bijplaatsen.',
    h:['Er zijn te veel fietsen op school.', 'De school plaatst rekken bij omdat er te weinig zijn.', 'Leerlingen moeten lopend komen.', 'De vakantie duurt lang.'], g:2,
    u:'De cijfers zijn de reden, het bijplaatsen is de conclusie die de school trekt.' },
  { s:'betoog', n:1, v:'tegenstel', d:'overtuig',
    t:'Sommige mensen zeggen dat je een klein hondje niet hoeft uit te laten, omdat hij toch niet ver komt. [Maar] ook een klein hondje wil snuffelen, rennen en andere honden zien. Laat hem dus elke dag uit.',
    h:['Kleine hondjes zijn lui.', 'Grote honden zijn beter.', 'Ook een klein hondje moet elke dag uitgelaten worden.', 'Snuffelen is slecht voor honden.'], g:3,
    u:'De schrijver zet de tegenwerping neer en gaat er dan tegenin. Na maar komt zijn standpunt.' },

  /* ---- vmbo-kgt en tl ---- */
  { s:'info', n:2, v:'oorzaak', d:'info',
    t:'Steeds meer winkels in het centrum staan leeg. Mensen bestellen kleding en boeken online, [waardoor] kleine winkeliers te weinig klanten overhouden om de huur te betalen. Wat blijft, zijn vooral kappers, cafés en supermarkten.',
    h:['Kappers verdienen het meest.', 'Winkels staan leeg doordat mensen online kopen.', 'De huur in het centrum is te hoog.', 'Kleding is online goedkoper.'], g:2,
    u:'Online kopen is de oorzaak, de lege winkels het gevolg. De laatste zin beschrijft alleen wat er overblijft.' },
  { s:'betoog', n:2, v:'conclusie', d:'overtuig',
    t:'Een schoolreis naar een pretpark is leuk, maar iedereen is er al eens geweest. Een dag zeilen kost hetzelfde, en bijna niemand heeft dat ooit gedaan. [Daarom] zou onze klas dit jaar moeten kiezen voor het water.',
    h:['Pretparken zijn te duur.', 'Zeilen is gevaarlijk.', 'De klas moet gaan zeilen in plaats van naar een pretpark.', 'Schoolreizen zijn overbodig.'], g:3,
    u:'De schrijver vergelijkt, en trekt in de laatste zin zijn conclusie: dat is zijn standpunt.' },
  { s:'nieuws', n:2, v:'tijd', d:'info', lj:3,
    t:'De gemeente gaat de oude bibliotheek verbouwen tot jongerencentrum. [Nadat] de laatste boeken in maart naar het nieuwe pand zijn verhuisd, beginnen de aannemers met het slopen van de binnenmuren. De opening staat gepland voor het najaar.',
    h:['De bibliotheek gaat dicht.', 'De oude bibliotheek wordt na de verhuizing verbouwd tot jongerencentrum.', 'Aannemers slopen het pand.', 'Jongeren lezen geen boeken meer.'], g:2,
    u:'Het nieuws is de verbouwing; de tijdwoorden ordenen de stappen: verhuizen, slopen, openen.' },
  { s:'instructie', n:2, v:'voorwaarde', d:'aanzet',
    t:'Controleer voor je vertrekt de bandenspanning van je scooter. Staat de druk onder de aanbevolen waarde, pomp de banden dan bij. [Mits] de banden goed op spanning staan, rem je korter en verbruik je minder benzine.',
    h:['Scooters verbruiken veel benzine.', 'Goede bandenspanning zorgt voor korter remmen en minder verbruik.', 'Banden oppompen is moeilijk.', 'Je moet elke dag tanken.'], g:2,
    u:'De instructie zegt wat je doet, en waarom: het gevolg geldt alleen als de banden op spanning zijn.' },
  { s:'reclame', n:2, v:'vergelijk', d:'overtuig',
    t:'Waarom zou je een uur in de rij staan voor een pretpark? Bij Klimbos Het Hoge Hout ben je [net zo] snel boven in de bomen als je je kaartje hebt gescand. Twintig parcoursen, van makkelijk tot pittig, en na afloop een pannenkoek op het terras.',
    h:['Pretparken zijn beter dan klimbossen.', 'Het klimbos wil je overhalen te komen door zich af te zetten tegen het pretpark.', 'Pannenkoeken zijn lekker.', 'Er zijn twintig bomen.'], g:2,
    u:'De vergelijking met de rij bij het pretpark is de lokroep: bij ons geen wachten.' },
  { s:'info', n:2, v:'toelichting', d:'info',
    t:'Sommige dieren houden een winterslaap om de koude maanden door te komen. Hun hartslag en ademhaling gaan dan sterk omlaag, zodat ze bijna geen energie verbruiken. [Zo] daalt de hartslag van een egel van tweehonderd slagen per minuut naar ongeveer twintig.',
    h:['Egels zijn de enige dieren met winterslaap.', 'In de winterslaap zakken hartslag en ademhaling, zodat een dier weinig energie verbruikt.', 'Dieren slapen in de winter omdat het donker is.', 'Een egel heeft een hartslag van twintig.'], g:2,
    u:'De egel is het voorbeeld bij de algemene uitspraak. Een voorbeeld is nooit de hoofdgedachte.' },
  { s:'verhaal', n:2, v:'tegenstel', d:'gevoel',
    t:'Op de dag van de uitslag bleef Yara thuis. Haar moeder belde drie keer om te vragen of ze al gekeken had. [Hoewel] de brief al uren op tafel lag, durfde ze de envelop niet open te maken; ze wist niet of ze het antwoord wilde weten.',
    h:['Yara is gezakt.', 'Yara durfde de uitslag niet te lezen, hoewel de brief er al lag.', 'Yara\u2019s moeder is ongeduldig.', 'De brief was kwijt.'], g:2,
    u:'Het verhaal gaat over de spanning van het niet-durven; of ze geslaagd is, zegt de tekst niet.' },
  { s:'betoog', n:2, v:'voorwaarde', d:'mening', lj:3,
    t:'Veel scholen verbieden de telefoon in de les, en dat begrijp ik. [Alleen als] een docent de telefoon zelf inzet, voor een quiz of om iets op te zoeken, hoort hij op tafel. In alle andere gevallen is de tas de beste plek, want de verleiding om te scrollen is groter dan de wil om op te letten.',
    h:['Telefoons horen altijd in de tas.', 'De telefoon mag alleen op tafel als de docent hem in de les gebruikt.', 'Docenten gebruiken te vaak een quiz.', 'Scrollen is verboden.'], g:2,
    u:'De schrijver geeft zijn mening met een voorwaarde erin: alleen als de docent de telefoon inzet.' },
  { s:'nieuws', n:2, v:'opsomming', d:'info',
    t:'De storm van vannacht heeft in de regio veel schade aangericht. In Dronten waaide het dak van een schuur, in Emmeloord vielen twee bomen op de weg [en] in Urk raakte een vissersboot los van de kade. Gewonden zijn er niet.',
    h:['De storm was de zwaarste ooit.', 'De storm richtte op verschillende plekken schade aan, zonder gewonden.', 'Urk is een vissersdorp.', 'Bomen zijn gevaarlijk bij storm.'], g:2,
    u:'De alinea somt de schade per plaats op. De kern: veel schade, geen gewonden.' },
  { s:'instructie', n:2, v:'doel', d:'aanzet',
    t:'Sla je wachtwoorden nooit op in een notitie op je telefoon. Gebruik een wachtwoordmanager, die versleutelt alles en vult het vanzelf in. Zet daarnaast tweestapsverificatie aan, [zodat] iemand met alleen je wachtwoord nog steeds niet in je account komt.',
    h:['Wachtwoorden zijn ouderwets.', 'Met een wachtwoordmanager en tweestapsverificatie bescherm je je accounts.', 'Notities op je telefoon zijn handig.', 'Je moet elke week een nieuw wachtwoord kiezen.'], g:2,
    u:'De instructie noemt twee maatregelen, en het signaalwoord zegt waar de tweede voor dient.' },
  { s:'info', n:2, v:'vergelijk', d:'info', lj:3,
    t:'Een orkaan en een tornado worden vaak door elkaar gehaald. Een orkaan ontstaat boven warm zeewater en kan honderden kilometers breed zijn; hij draait dagenlang rond. Een tornado is [daarentegen] een smalle slurf boven land die meestal binnen een half uur weer verdwenen is, maar ter plekke nog harder waait.',
    h:['Tornado\u2019s zijn ongevaarlijk.', 'Orkanen komen alleen in Amerika voor.', 'Een orkaan is groot en duurt lang, een tornado is smal en kort maar plaatselijk heviger.', 'Een tornado ontstaat boven zee.'], g:3,
    u:'De alinea zet de twee naast elkaar: omvang, duur en kracht. De vergelijking is de kern.' },
  { s:'reclame', n:2, v:'oorzaak', d:'aanzet',
    t:'Sinds we onze broodjes bakken in de eigen oven, ruikt de hele straat naar vers brood. Klanten komen [daardoor] al voor achten binnen, en om tien uur is de eerste lading op. Kom dus vroeg, of bestel je broodjes de avond ervoor via de app.',
    h:['De bakker heeft een nieuwe oven.', 'De broodjes zijn snel op, dus kom vroeg of bestel vooraf.', 'De straat ruikt lekker.', 'De app is gratis.'], g:2,
    u:'De geur lokt klanten (oorzaak en gevolg), en het doel van de tekst is dat jij ook komt of bestelt.' },
  { s:'betoog', n:2, v:'toelichting', d:'overtuig', lj:3,
    t:'Jongeren zouden vanaf zestien jaar moeten mogen stemmen bij de gemeenteraadsverkiezingen. Veel besluiten van de gemeente gaan juist over hen. [Denk aan] het sluiten van een skatebaan, het schrappen van de nachtbus of de bouw van een jongerencentrum. Wie de gevolgen draagt, hoort mee te beslissen.',
    h:['Zestienjarigen weten meer van politiek dan volwassenen.', 'Gemeenten sluiten te veel skatebanen.', 'Zestienjarigen moeten mogen stemmen, omdat gemeentebesluiten hen raken.', 'De nachtbus moet blijven rijden.'], g:3,
    u:'De skatebaan en de nachtbus zijn voorbeelden bij het argument. Het standpunt staat in de eerste zin.' },
  { s:'verhaal', n:2, v:'tijd', d:'amuseer',
    t:'Het was de laatste dag voor de vakantie en niemand lette meer op. [Terwijl] meneer Jansen de tafel van zeven uitlegde, bouwde de achterste rij een toren van gummen die tot boven de tafel kwam. Pas toen de toren omviel, keek hij om.',
    h:['Meneer Jansen kan niet uitleggen.', 'Op de laatste dag voor de vakantie lette niemand op de uitleg.', 'Gummen zijn goed om mee te bouwen.', 'De tafel van zeven is moeilijk.'], g:2,
    u:'Het tijdsverband zet de uitleg en de toren naast elkaar: dat tegelijk is de grap.' },
  { s:'nieuws', n:2, v:'voorwaarde', d:'info', lj:3,
    t:'Het zwembad blijft deze zomer langer open, tot negen uur \u2019s avonds. De gemeente stelt wel een voorwaarde: [zolang] er na acht uur minstens dertig bezoekers zijn, blijft het bad open. Zijn het er drie weken achter elkaar minder, dan gaat de sluitingstijd terug naar zeven uur.',
    h:['Het zwembad sluit om zeven uur.', 'De langere openingstijd blijft alleen als er genoeg bezoekers komen.', 'De gemeente heeft geen geld voor het zwembad.', 'Na acht uur is zwemmen gratis.'], g:2,
    u:'Het nieuws zit in de voorwaarde: langer open, maar alleen zolang er genoeg mensen komen.' },
  { s:'info', n:2, v:'conclusie', d:'info',
    t:'Uit onderzoek onder duizend leerlingen blijkt dat wie zijn huiswerk in de bibliotheek maakt, gemiddeld een half uur sneller klaar is dan wie het thuis doet. Thuis liggen telefoon, koelkast en bank binnen handbereik. [Kortom:] de plek waar je werkt, bepaalt hoe lang je erover doet.',
    h:['Bibliotheken zijn stil.', 'Leerlingen hebben te veel huiswerk.', 'Waar je werkt, bepaalt hoe snel je klaar bent.', 'Thuis werken is onmogelijk.'], g:3,
    u:'Kortom kondigt de samenvatting aan, en die is meteen de hoofdgedachte.' },

  /* ---- havo en vwo ---- */
  { s:'betoog', n:3, v:'tegenstel', d:'overtuig', lj:3,
    t:'Het lijkt logisch om leerlingen die spieken direct een 1 te geven: straf werkt. [Echter,] wie spiekt doet dat zelden uit luiheid en meestal uit angst voor het cijfer. Een 1 vergroot juist die angst. Beter is een gesprek en de toets opnieuw, want dan leert de leerling nog iets.',
    h:['Spieken moet altijd een 1 opleveren.', 'Spiekers zijn lui.', 'Een gesprek en een herkansing werken beter tegen spieken dan een 1.', 'Toetsen zorgen voor angst.'], g:3,
    u:'De schrijver noemt eerst de gangbare mening en gaat er na echter tegenin. Zijn standpunt staat daarna.' },
  { s:'info', n:3, v:'oorzaak', d:'info', lj:3,
    t:'De zeespiegel stijgt niet alleen doordat er ijs smelt. Water zet uit als het warmer wordt, en de oceanen nemen het grootste deel van de extra warmte op. [Vandaar] dat de zeespiegel ook stijgt in jaren waarin het smelten meevalt: het water zelf wordt groter.',
    h:['Het ijs op de polen smelt niet.', 'De zeespiegel stijgt ook doordat warmer water uitzet.', 'De oceanen worden kouder.', 'Smeltend ijs is de enige oorzaak van de zeespiegelstijging.'], g:2,
    u:'De alinea legt een tweede oorzaak uit. Vandaar verbindt de uitzetting met de stijging.' },
  { s:'nieuws', n:3, v:'conclusie', d:'info', lj:3,
    t:'De provincie liet een jaar lang tellen hoeveel auto\u2019s de nieuwe rondweg gebruiken. Overdag reden er minder dan verwacht, [terwijl] de oude weg door het dorp juist drukker werd, omdat navigatie-apps hem nog steeds als kortste route aanwijzen. De provincie concludeert dat de rondweg pas werkt als de apps hun kaarten aanpassen.',
    h:['De rondweg is overbodig.', 'Navigatie-apps zijn onbetrouwbaar.', 'De rondweg helpt pas als navigatie-apps hun route aanpassen.', 'Het dorp wil de oude weg afsluiten.'], g:3,
    u:'De tellingen zijn de aanleiding; de conclusie van de provincie is de kern van het bericht.' },
  { s:'verhaal', n:3, v:'voorwaarde', d:'gevoel',
    t:'Haar opa zei het elke zondag, half voor de grap: [als] ze ooit de marathon zou lopen, zou hij bij de finish staan met een bord. Toen ze eindelijk het startnummer had, stond er niemand bij de finish. Ze liep de laatste kilometer met het bord in haar hoofd.',
    h:['Opa hield niet van hardlopen.', 'Ze haalde de finish niet.', 'De belofte van haar overleden opa droeg haar over de finish.', 'Marathons zijn te lang voor beginners.'], g:3,
    u:'Het verhaal zegt niet dat opa dood is, maar laat het je voelen: niemand bij de finish, het bord alleen nog in haar hoofd.' },
  { s:'betoog', n:3, v:'doel', d:'aanzet', lj:3,
    t:'Scholen zouden verplicht een lesuur per week aan geld moeten besteden. Niet om leerlingen te leren beleggen, [maar om] ze te laten zien hoe een abonnement stilletjes doorloopt, hoe rente op een lening oploopt en waarom een lening voor een telefoon uiteindelijk het duurste toestel is dat je ooit koopt.',
    h:['Beleggen moet een schoolvak worden.', 'Een wekelijks lesuur over geld moet leerlingen leren wat abonnementen en leningen echt kosten.', 'Telefoons zijn te duur.', 'Rente is verboden.'], g:2,
    u:'Het signaalwoord noemt het doel van het lesuur. De opsomming daarna zijn de dingen die je dan leert.' },
  { s:'info', n:3, v:'vergelijk', d:'info',
    t:'Een goede leugendetector bestaat niet. Het apparaat meet hartslag, zweet en ademhaling, en die reageren op spanning. [Evenzo] reageert het lichaam van iemand die de waarheid spreekt maar bang is niet geloofd te worden. De naald slaat dus uit bij zenuwen, niet bij leugens.',
    h:['Leugenaars zweten meer.', 'Een leugendetector meet spanning, niet of iemand liegt.', 'Zenuwachtige mensen liegen vaker.', 'De politie gebruikt geen leugendetectors.'], g:2,
    u:'De vergelijking tussen de leugenaar en de bange eerlijke laat zien dat het apparaat geen verschil ziet.' },
  { s:'reclame', n:3, v:'toelichting', d:'overtuig', lj:3,
    t:'Kies voor een refurbished laptop. Hij is nagekeken, schoongemaakt en heeft een nieuwe accu, [zoals] elke laptop die onze werkplaats verlaat. Je betaalt de helft van de nieuwprijs en er komt geen nieuw apparaat bij op een planeet die er al genoeg heeft.',
    h:['Nieuwe laptops zijn beter.', 'Een refurbished laptop is nagekeken, goedkoper en beter voor het milieu.', 'De werkplaats maakt accu\u2019s.', 'Laptops gaan maar kort mee.'], g:2,
    u:'De tekst geeft de argumenten om te kopen; de werkplaats is de toelichting bij nagekeken.' },
  { s:'nieuws', n:3, v:'opsomming', d:'info', lj:3,
    t:'Het Rijksmuseum heeft een tot nu toe onbekende brief van Rembrandt gekocht. De brief, drie regels lang, bevestigt wat kenners al vermoedden: dat de schilder in 1639 geld leende voor zijn huis, dat hij de rente te laat betaalde [en] dat de verkoper daarover klaagde bij de notaris.',
    h:['Rembrandt was arm.', 'Het museum kocht een brief die drie vermoedens over Rembrandts geldzaken bevestigt.', 'Notarissen bewaarden alles.', 'Rembrandt schreef veel brieven.'], g:2,
    u:'Het nieuws is de aankoop en wat de brief bevestigt; het signaalwoord rijgt de drie feiten aan elkaar.' },
  { s:'instructie', n:3, v:'tegenstel', d:'aanzet', lj:3,
    t:'Schrijf een samenvatting nooit terwijl je de tekst voor het eerst leest. Lees eerst alles, streep dan per alinea de kern aan en schrijf pas daarna, in je eigen woorden. [Anders] wordt je samenvatting een verzameling losse zinnen die je hebt overgeschreven, en juist die vergeet je het snelst.',
    h:['Samenvatten is overbodig.', 'Overschrijven werkt het best.', 'Lees eerst, streep aan en schrijf daarna in eigen woorden; anders wordt het overschrijven.', 'Een samenvatting mag maar drie zinnen zijn.'], g:3,
    u:'De instructie zegt wat je doet en waarschuwt na anders voor wat er gebeurt als je het niet zo doet.' },
  { s:'betoog', n:3, v:'conclusie', d:'mening',
    t:'Een boek verfilmen kan nooit hetzelfde zijn als het boek. De lezer maakt zelf de beelden; de kijker krijgt ze opgelegd. Toch klagen we vooral als de film afwijkt van het boek, en niet als hij er slaafs op lijkt. [Blijkbaar] willen we niet dat de film ons verrast, maar dat hij bevestigt wat we al zagen.',
    h:['Films zijn beter dan boeken.', 'Kijkers willen dat een verfilming bevestigt wat ze al in hun hoofd hadden.', 'Boeken moeten niet verfilmd worden.', 'Lezers hebben meer fantasie.'], g:2,
    u:'Blijkbaar kondigt de gevolgtrekking aan: de schrijver leest uit ons klagen af wat we willen.' },
  { s:'info', n:3, v:'tijd', d:'info', lj:3,
    t:'Tot ver in de negentiende eeuw had elke stad zijn eigen tijd, afgelezen aan de zon. [Pas toen] de treinen gingen rijden, werd dat een probleem: een dienstregeling met tientallen plaatselijke tijden was niet te maken. Zo kwam er in Nederland in 1909 één tijd voor het hele land.',
    h:['Treinen reden vroeger te laat.', 'De spoorwegen maakten één landelijke tijd nodig.', 'De zon staat overal even hoog.', 'In 1909 werden de eerste klokken gemaakt.'], g:2,
    u:'Het tijdsverband markeert de omslag: met de treinen werd de eigen tijd van elke stad onhoudbaar.' },
  { s:'verhaal', n:3, v:'oorzaak', d:'amuseer',
    t:'De koffieautomaat in de lerarenkamer maakte sinds maandag alleen nog thee, wat je ook indrukte. [Omdat] niemand wist wie hem gerepareerd moest krijgen, dronk het hele team een week lang thee, en kwam de conrector erachter dat de vergaderingen opeens een kwartier korter duurden.',
    h:['Thee is gezonder dan koffie.', 'Doordat de automaat alleen thee gaf, ontdekte de school dat vergaderingen korter konden.', 'De conrector hield van thee.', 'Niemand kan een koffieautomaat repareren.'], g:2,
    u:'De kapotte automaat is de oorzaak, de kortere vergaderingen het onverwachte gevolg: daar zit de grap.' },
  { s:'betoog', n:3, v:'voorwaarde', d:'overtuig', lj:3,
    t:'Kunstmatige intelligentie mag best huiswerk helpen maken, [op voorwaarde dat] de leerling kan uitleggen wat er staat. Wie een opstel inlevert dat hij niet zelf kan navertellen, heeft niets geleerd, en dat is uiteindelijk het enige waar school voor is. De regel moet dus niet zijn: geen AI, maar: laat zien dat je het snapt.',
    h:['AI moet op school verboden worden.', 'AI mag helpen, mits de leerling kan uitleggen wat hij inlevert.', 'Opstellen zijn ouderwets.', 'Leerlingen leren niets van huiswerk.'], g:2,
    u:'Het standpunt heeft een voorwaarde in zich; de laatste zin herhaalt het als regel.' },
  { s:'nieuws', n:3, v:'doel', d:'info', lj:3,
    t:'Supermarkten gaan de houdbaarheidsdatum op groente en fruit schrappen. De datum wordt vervangen door de tekst kijk, ruik en proef, [om] te voorkomen dat mensen goede appels weggooien alleen omdat er een datum op de sticker staat. Volgens de branche belandt zo jaarlijks een derde minder fruit in de bak.',
    h:['Appels zijn na de datum giftig.', 'De datum op groente en fruit verdwijnt om verspilling tegen te gaan.', 'Supermarkten verkopen minder fruit.', 'Stickers zijn slecht voor het milieu.'], g:2,
    u:'Het signaalwoord noemt het doel van de maatregel; de kern is de maatregel plus dat doel.' },
  { s:'info', n:3, v:'toelichting', d:'info',
    t:'Woorden slijten. Wat ooit sterk was, wordt gewoon, en dan moet er iets sterkers komen. [Neem] het woord vreselijk: het betekende letterlijk dat je ervan beefde, en nu zeg je het over een lange rij bij de kassa. Elke generatie vindt daarom nieuwe woorden uit voor wat echt erg is.',
    h:['Jongeren gebruiken te veel nieuwe woorden.', 'Sterke woorden verliezen hun kracht, dus ontstaan er steeds nieuwe.', 'Vreselijk betekent beven.', 'Rijen bij de kassa zijn vreselijk.'], g:2,
    u:'Vreselijk is het voorbeeld bij de eerste zin. De algemene uitspraak is de kern.' },
  { s:'reclame', n:3, v:'opsomming', d:'aanzet',
    t:'Word vrijwilliger bij de bibliotheek. Je helpt kinderen die thuis geen boeken hebben aan hun eerste eigen leeskaart, je zet de voorleesochtend op poten [en] je krijgt er een team bij dat elke vrijdag samen luncht. Twee uur per week, wij regelen de rest.',
    h:['De bibliotheek zoekt vrijwilligers en somt op wat je ervoor terugkrijgt.', 'Kinderen lezen te weinig.', 'De lunch is gratis.', 'Vrijwilligers werken twee uur per dag.'], g:1,
    u:'Alles in de tekst is bedoeld om jou over te halen; de opsomming maakt het aantrekkelijk.' }
];
var NIVEAUS = [
  { id:1, naam:'vmbo-bb',        uit:'Korte alinea\u2019s met een duidelijk signaalwoord.' },
  { id:2, naam:'vmbo-kgt en tl', uit:'Langere alinea\u2019s, ook betoog en nieuws.' },
  { id:3, naam:'havo en vwo',    uit:'Alinea\u2019s waarin de kern pas na een tegenwerping komt.' }
];

return { VERBANDEN:VERBANDEN, SOORTEN:SOORTEN, DOELEN:DOELEN, DOEL_VAN_SOORT:DOEL_VAN_SOORT, LEERJAREN:LEERJAREN, ALINEAS:ALINEAS, NIVEAUS:NIVEAUS };
})();
