/* De stof van Voedselketen en voedselweb: de organismen, de ketens, de webben
   en de begripsvragen. voedselweb.html tekent de pictogrammen en maakt er
   opgaven van; dit bestand is alleen de inhoud, zodat je het na kunt lezen.
   Elke keten begint met een producent; elke pijl wijst in de richting van de
   energie (van wie gegeten wordt naar wie eet). */
var VOEDSELWEB_DATA = (function(){
  'use strict';

  /* ---------- organismen ----------
     e: enkelvoud met lidwoord, m: meervoud met lidwoord, n: naam op een kaartje,
     rol: producent, herbivoor, carnivoor, omnivoor of afbreker; ico: het pictogram;
     twijfel: de rol is in de praktijk niet zwart-wit (niet in de havo/vwo-vraag
     naar herbivoor, carnivoor en omnivoor). */
  var ORG = {
    gras:       { n:'gras', e:'het gras', m:'het gras', rol:'producent', ico:'gras' },
    klaver:     { n:'klaver', e:'de klaver', m:'de klaver', rol:'producent', ico:'klaver' },
    eik:        { n:'eik (eikels)', e:'de eik', m:'de eiken', rol:'producent', ico:'boom' },
    eikenblad:  { n:'eikenblad', e:'het eikenblad', m:'de eikenbladeren', rol:'producent', ico:'blad' },
    braam:      { n:'braamstruik', e:'de braamstruik', m:'de braamstruiken', rol:'producent', ico:'bes' },
    waterplant: { n:'waterplant', e:'de waterplant', m:'de waterplanten', rol:'producent', ico:'waterplant' },
    alg:        { n:'alg', e:'de alg', m:'de algen', rol:'producent', ico:'alg' },
    plankton:   { n:'plantaardig plankton', e:'het plantaardig plankton', m:'het plantaardig plankton', rol:'producent', ico:'alg' },
    mos:        { n:'mos', e:'het mos', m:'het mos', rol:'producent', ico:'mos' },
    korstmos:   { n:'korstmos', e:'het korstmos', m:'de korstmossen', rol:'producent', ico:'mos' },
    blad:       { n:'bladeren', e:'het blad', m:'de bladeren', rol:'producent', ico:'blad' },
    vijg:       { n:'vijgenboom', e:'de vijgenboom', m:'de vijgenbomen', rol:'producent', ico:'vruchtboom' },
    acacia:     { n:'acacia', e:'de acacia', m:'de acacia’s', rol:'producent', ico:'boom' },

    rups:       { n:'rups', e:'de rups', m:'de rupsen', rol:'herbivoor', ico:'rups' },
    sprinkhaan: { n:'sprinkhaan', e:'de sprinkhaan', m:'de sprinkhanen', rol:'herbivoor', ico:'sprinkhaan' },
    slak:       { n:'slak', e:'de slak', m:'de slakken', rol:'herbivoor', ico:'slak' },
    konijn:     { n:'konijn', e:'het konijn', m:'de konijnen', rol:'herbivoor', ico:'konijn' },
    haas:       { n:'haas', e:'de haas', m:'de hazen', rol:'herbivoor', ico:'konijn' },
    muis:       { n:'muis', e:'de muis', m:'de muizen', rol:'herbivoor', ico:'muis', twijfel:true },
    veldmuis:   { n:'veldmuis', e:'de veldmuis', m:'de veldmuizen', rol:'herbivoor', ico:'muis' },
    bosmuis:    { n:'bosmuis', e:'de bosmuis', m:'de bosmuizen', rol:'omnivoor', ico:'muis', twijfel:true },
    ree:        { n:'ree', e:'de ree', m:'de reeën', rol:'herbivoor', ico:'hert' },
    rendier:    { n:'rendier', e:'het rendier', m:'de rendieren', rol:'herbivoor', ico:'hert' },
    lemming:    { n:'lemming', e:'de lemming', m:'de lemmingen', rol:'herbivoor', ico:'muis' },
    watervlo:   { n:'watervlo', e:'de watervlo', m:'de watervlooien', rol:'herbivoor', ico:'watervlo' },
    muglarve:   { n:'muggenlarve', e:'de muggenlarve', m:'de muggenlarven', rol:'herbivoor', ico:'larve', twijfel:true },
    garnaal:    { n:'garnaal', e:'de garnaal', m:'de garnalen', rol:'omnivoor', ico:'garnaal', twijfel:true },
    krill:      { n:'krill', e:'het krill', m:'het krill', rol:'herbivoor', ico:'garnaal' },
    mossel:     { n:'mossel', e:'de mossel', m:'de mosselen', rol:'herbivoor', ico:'mossel', twijfel:true },
    zebra:      { n:'zebra', e:'de zebra', m:'de zebra’s', rol:'herbivoor', ico:'zebra' },
    gazelle:    { n:'gazelle', e:'de gazelle', m:'de gazellen', rol:'herbivoor', ico:'gazelle' },
    giraffe:    { n:'giraffe', e:'de giraffe', m:'de giraffen', rol:'herbivoor', ico:'giraffe' },
    termiet:    { n:'termiet', e:'de termiet', m:'de termieten', rol:'herbivoor', ico:'mier', twijfel:true },
    parelhoen:  { n:'parelhoen', e:'het parelhoen', m:'de parelhoenders', rol:'omnivoor', ico:'hoen', twijfel:true },
    aap:        { n:'aap', e:'de aap', m:'de apen', rol:'omnivoor', ico:'aap' },
    papegaai:   { n:'papegaai', e:'de papegaai', m:'de papegaaien', rol:'herbivoor', ico:'papegaai' },
    kever:      { n:'kever', e:'de kever', m:'de kevers', rol:'herbivoor', ico:'kever', twijfel:true },
    bladmier:   { n:'bladsnijdersmier', e:'de bladsnijdersmier', m:'de bladsnijdersmieren', rol:'herbivoor', ico:'mier' },
    eend:       { n:'wilde eend', e:'de wilde eend', m:'de wilde eenden', rol:'omnivoor', ico:'eend' },
    zwijn:      { n:'wild zwijn', e:'het wilde zwijn', m:'de wilde zwijnen', rol:'omnivoor', ico:'zwijn' },
    beer:       { n:'bruine beer', e:'de bruine beer', m:'de bruine beren', rol:'omnivoor', ico:'beer' },

    koolmees:   { n:'koolmees', e:'de koolmees', m:'de koolmezen', rol:'omnivoor', ico:'vogel', twijfel:true },
    merel:      { n:'merel', e:'de merel', m:'de merels', rol:'omnivoor', ico:'vogel', twijfel:true },
    spreeuw:    { n:'spreeuw', e:'de spreeuw', m:'de spreeuwen', rol:'omnivoor', ico:'vogel', twijfel:true },
    lijster:    { n:'lijster', e:'de lijster', m:'de lijsters', rol:'omnivoor', ico:'vogel', twijfel:true },
    sperwer:    { n:'sperwer', e:'de sperwer', m:'de sperwers', rol:'carnivoor', ico:'roofvogel' },
    buizerd:    { n:'buizerd', e:'de buizerd', m:'de buizerds', rol:'carnivoor', ico:'roofvogel' },
    torenvalk:  { n:'torenvalk', e:'de torenvalk', m:'de torenvalken', rol:'carnivoor', ico:'roofvogel' },
    arend:      { n:'arend', e:'de arend', m:'de arenden', rol:'carnivoor', ico:'roofvogel' },
    slangenarend:{ n:'slangenarend', e:'de slangenarend', m:'de slangenarenden', rol:'carnivoor', ico:'roofvogel' },
    harpij:     { n:'harpij (arend)', e:'de harpij', m:'de harpijen', rol:'carnivoor', ico:'roofvogel' },
    uil:        { n:'uil', e:'de uil', m:'de uilen', rol:'carnivoor', ico:'uil' },
    bosuil:     { n:'bosuil', e:'de bosuil', m:'de bosuilen', rol:'carnivoor', ico:'uil' },
    sneeuwuil:  { n:'sneeuwuil', e:'de sneeuwuil', m:'de sneeuwuilen', rol:'carnivoor', ico:'uil' },
    vos:        { n:'vos', e:'de vos', m:'de vossen', rol:'carnivoor', ico:'vos', twijfel:true },
    poolvos:    { n:'poolvos', e:'de poolvos', m:'de poolvossen', rol:'carnivoor', ico:'vos' },
    jakhals:    { n:'jakhals', e:'de jakhals', m:'de jakhalzen', rol:'carnivoor', ico:'vos', twijfel:true },
    wolf:       { n:'wolf', e:'de wolf', m:'de wolven', rol:'carnivoor', ico:'wolf' },
    wezel:      { n:'wezel', e:'de wezel', m:'de wezels', rol:'carnivoor', ico:'wezel' },
    hermelijn:  { n:'hermelijn', e:'de hermelijn', m:'de hermelijnen', rol:'carnivoor', ico:'wezel' },
    egel:       { n:'egel', e:'de egel', m:'de egels', rol:'carnivoor', ico:'egel', twijfel:true },
    das:        { n:'das', e:'de das', m:'de dassen', rol:'omnivoor', ico:'das' },
    kikker:     { n:'kikker', e:'de kikker', m:'de kikkers', rol:'carnivoor', ico:'kikker' },
    ringslang:  { n:'ringslang', e:'de ringslang', m:'de ringslangen', rol:'carnivoor', ico:'slang' },
    slang:      { n:'slang', e:'de slang', m:'de slangen', rol:'carnivoor', ico:'slang' },
    hagedis:    { n:'hagedis', e:'de hagedis', m:'de hagedissen', rol:'carnivoor', ico:'hagedis' },
    reiger:     { n:'reiger', e:'de reiger', m:'de reigers', rol:'carnivoor', ico:'reiger' },
    libellelarve:{ n:'libellenlarve', e:'de libellenlarve', m:'de libellenlarven', rol:'carnivoor', ico:'larve' },
    stekelbaars:{ n:'stekelbaars', e:'de stekelbaars', m:'de stekelbaarzen', rol:'carnivoor', ico:'vis' },
    snoek:      { n:'snoek', e:'de snoek', m:'de snoeken', rol:'carnivoor', ico:'visgroot' },
    haring:     { n:'haring', e:'de haring', m:'de haringen', rol:'carnivoor', ico:'vis' },
    makreel:    { n:'makreel', e:'de makreel', m:'de makrelen', rol:'carnivoor', ico:'vis' },
    schol:      { n:'schol', e:'de schol', m:'de schollen', rol:'carnivoor', ico:'platvis' },
    kabeljauw:  { n:'kabeljauw', e:'de kabeljauw', m:'de kabeljauwen', rol:'carnivoor', ico:'visgroot' },
    poolvis:    { n:'poolvis', e:'de poolvis', m:'de poolvissen', rol:'carnivoor', ico:'vis' },
    zeester:    { n:'zeester', e:'de zeester', m:'de zeesterren', rol:'carnivoor', ico:'zeester' },
    meeuw:      { n:'meeuw', e:'de meeuw', m:'de meeuwen', rol:'omnivoor', ico:'meeuw' },
    zeehond:    { n:'zeehond', e:'de zeehond', m:'de zeehonden', rol:'carnivoor', ico:'zeehond' },
    zeeluipaard:{ n:'zeeluipaard', e:'de zeeluipaard', m:'de zeeluipaarden', rol:'carnivoor', ico:'zeehond' },
    bruinvis:   { n:'bruinvis', e:'de bruinvis', m:'de bruinvissen', rol:'carnivoor', ico:'walvis' },
    orka:       { n:'orka', e:'de orka', m:'de orka’s', rol:'carnivoor', ico:'orka' },
    walvis:     { n:'baleinwalvis', e:'de baleinwalvis', m:'de baleinwalvissen', rol:'carnivoor', ico:'walvis' },
    pinguin:    { n:'pinguïn', e:'de pinguïn', m:'de pinguïns', rol:'carnivoor', ico:'pinguin' },
    ijsbeer:    { n:'ijsbeer', e:'de ijsbeer', m:'de ijsberen', rol:'carnivoor', ico:'ijsbeer' },
    leeuw:      { n:'leeuw', e:'de leeuw', m:'de leeuwen', rol:'carnivoor', ico:'leeuw' },
    jachtluipaard:{ n:'jachtluipaard', e:'het jachtluipaard', m:'de jachtluipaarden', rol:'carnivoor', ico:'kat' },
    hyena:      { n:'hyena', e:'de hyena', m:'de hyena’s', rol:'carnivoor', ico:'hyena' },
    jaguar:     { n:'jaguar', e:'de jaguar', m:'de jaguars', rol:'carnivoor', ico:'kat' },
    miereneter: { n:'miereneter', e:'de miereneter', m:'de miereneters', rol:'carnivoor', ico:'miereneter' },
    gordeldier: { n:'gordeldier', e:'het gordeldier', m:'de gordeldieren', rol:'carnivoor', ico:'gordeldier', twijfel:true },
    vleermuis:  { n:'vleermuis', e:'de vleermuis', m:'de vleermuizen', rol:'carnivoor', ico:'vleermuis' },
    spin:       { n:'spin', e:'de spin', m:'de spinnen', rol:'carnivoor', ico:'spin' },

    bacterie:   { n:'bacterie', e:'de bacterie', m:'de bacteriën', rol:'afbreker', ico:'bacterie' },
    schimmel:   { n:'schimmel', e:'de schimmel', m:'de schimmels', rol:'afbreker', ico:'schimmel' },
    paddenstoel:{ n:'paddenstoel (schimmel)', e:'de paddenstoel', m:'de paddenstoelen', rol:'afbreker', ico:'schimmel' }
  };

  var ECO = {
    bos: 'het bos', weiland: 'het weiland', sloot: 'de sloot', noordzee: 'de Noordzee',
    savanne: 'de savanne', pool: 'het poolgebied', regenwoud: 'het tropisch regenwoud'
  };
  /* welke afbrekers passen bij een ecosysteem (voor de rollen-opgave) */
  var AFBREKERS = { bos:['paddenstoel', 'bacterie', 'schimmel'], weiland:['bacterie', 'schimmel'], sloot:['bacterie'], noordzee:['bacterie'], savanne:['bacterie', 'schimmel'], pool:['bacterie'], regenwoud:['schimmel', 'bacterie'] };

  /* ---------- ketens: producent vooraan, dan wie hem eet, enzovoort ---------- */
  var KETENS = [
    { eco:'bos', k:['eikenblad', 'rups', 'koolmees', 'sperwer'] },
    { eco:'bos', k:['eik', 'bosmuis', 'wezel', 'bosuil'] },
    { eco:'bos', k:['gras', 'sprinkhaan', 'kikker', 'ringslang', 'buizerd'] },
    { eco:'bos', k:['braam', 'slak', 'egel', 'das'] },
    { eco:'bos', k:['eikenblad', 'rups', 'koolmees', 'bosuil'] },
    { eco:'weiland', k:['gras', 'veldmuis', 'wezel', 'buizerd'] },
    { eco:'weiland', k:['gras', 'sprinkhaan', 'kikker', 'reiger'] },
    { eco:'weiland', k:['klaver', 'rups', 'koolmees', 'sperwer'] },
    { eco:'weiland', k:['gras', 'slak', 'lijster', 'sperwer'] },
    { eco:'weiland', k:['gras', 'rups', 'spreeuw', 'torenvalk'] },
    { eco:'sloot', k:['alg', 'watervlo', 'stekelbaars', 'snoek'] },
    { eco:'sloot', k:['alg', 'watervlo', 'stekelbaars', 'reiger'] },
    { eco:'sloot', k:['waterplant', 'slak', 'kikker', 'reiger'] },
    { eco:'sloot', k:['alg', 'muglarve', 'kikker', 'ringslang', 'reiger'] },
    { eco:'sloot', k:['alg', 'watervlo', 'libellelarve', 'stekelbaars', 'snoek'] },
    { eco:'noordzee', k:['plankton', 'garnaal', 'haring', 'zeehond'] },
    { eco:'noordzee', k:['plankton', 'krill', 'haring', 'kabeljauw', 'zeehond'] },
    { eco:'noordzee', k:['plankton', 'garnaal', 'schol', 'zeehond'] },
    { eco:'noordzee', k:['alg', 'mossel', 'zeester', 'meeuw'] },
    { eco:'noordzee', k:['plankton', 'garnaal', 'makreel', 'bruinvis'] },
    { eco:'savanne', k:['gras', 'sprinkhaan', 'hagedis', 'slang', 'arend'] },
    { eco:'savanne', k:['gras', 'muis', 'slang', 'arend'] },
    { eco:'savanne', k:['gras', 'sprinkhaan', 'parelhoen', 'jakhals'] },
    { eco:'savanne', k:['gras', 'sprinkhaan', 'hagedis', 'slangenarend'] },
    { eco:'pool', k:['plankton', 'krill', 'poolvis', 'zeehond', 'ijsbeer'] },
    { eco:'pool', k:['plankton', 'krill', 'pinguin', 'zeeluipaard', 'orka'] },
    { eco:'pool', k:['plankton', 'krill', 'poolvis', 'pinguin'] },
    { eco:'pool', k:['plankton', 'krill', 'poolvis', 'zeehond'] },
    { eco:'pool', k:['mos', 'lemming', 'hermelijn', 'sneeuwuil'] },
    { eco:'regenwoud', k:['blad', 'rups', 'kikker', 'slang', 'harpij'] },
    { eco:'regenwoud', k:['blad', 'bladmier', 'miereneter', 'jaguar'] },
    { eco:'regenwoud', k:['vijg', 'kever', 'kikker', 'slang', 'harpij'] },
    { eco:'regenwoud', k:['blad', 'sprinkhaan', 'hagedis', 'slang'] }
  ];

  /* ---------- webben: knopen en pijlen [gegeten, eter] ---------- */
  var WEBBEN = [
    { eco:'bos', n:['eik', 'gras', 'bosmuis', 'konijn', 'rups', 'vos', 'bosuil'],
      p:[['eik', 'bosmuis'], ['gras', 'konijn'], ['gras', 'rups'], ['bosmuis', 'vos'], ['konijn', 'vos'], ['bosmuis', 'bosuil'], ['rups', 'bosmuis']] },
    { eco:'bos', n:['eikenblad', 'braam', 'rups', 'slak', 'koolmees', 'egel', 'sperwer'],
      p:[['eikenblad', 'rups'], ['braam', 'slak'], ['braam', 'koolmees'], ['rups', 'koolmees'], ['slak', 'egel'], ['rups', 'egel'], ['koolmees', 'sperwer']] },
    { eco:'weiland', n:['gras', 'klaver', 'veldmuis', 'sprinkhaan', 'haas', 'torenvalk', 'vos'],
      p:[['gras', 'veldmuis'], ['klaver', 'haas'], ['gras', 'sprinkhaan'], ['gras', 'haas'], ['veldmuis', 'torenvalk'], ['sprinkhaan', 'torenvalk'], ['veldmuis', 'vos'], ['haas', 'vos']] },
    { eco:'weiland', n:['gras', 'sprinkhaan', 'slak', 'kikker', 'lijster', 'reiger', 'buizerd'],
      p:[['gras', 'sprinkhaan'], ['gras', 'slak'], ['sprinkhaan', 'kikker'], ['slak', 'lijster'], ['sprinkhaan', 'lijster'], ['kikker', 'reiger'], ['lijster', 'buizerd'], ['kikker', 'buizerd']] },
    { eco:'sloot', n:['alg', 'waterplant', 'watervlo', 'slak', 'stekelbaars', 'kikker', 'snoek', 'reiger'],
      p:[['alg', 'watervlo'], ['waterplant', 'slak'], ['watervlo', 'stekelbaars'], ['slak', 'kikker'], ['stekelbaars', 'snoek'], ['stekelbaars', 'reiger'], ['kikker', 'reiger'], ['kikker', 'snoek']] },
    { eco:'sloot', n:['alg', 'watervlo', 'muglarve', 'libellelarve', 'stekelbaars', 'kikker', 'reiger'],
      p:[['alg', 'watervlo'], ['alg', 'muglarve'], ['watervlo', 'libellelarve'], ['muglarve', 'libellelarve'], ['libellelarve', 'stekelbaars'], ['muglarve', 'kikker'], ['stekelbaars', 'reiger'], ['kikker', 'reiger']] },
    { eco:'noordzee', n:['plankton', 'garnaal', 'krill', 'haring', 'makreel', 'schol', 'zeehond', 'bruinvis'],
      p:[['plankton', 'garnaal'], ['plankton', 'krill'], ['krill', 'haring'], ['garnaal', 'schol'], ['garnaal', 'makreel'], ['haring', 'makreel'], ['haring', 'zeehond'], ['schol', 'zeehond'], ['makreel', 'bruinvis'], ['haring', 'bruinvis']] },
    { eco:'noordzee', n:['alg', 'plankton', 'mossel', 'krill', 'zeester', 'haring', 'meeuw', 'zeehond'],
      p:[['alg', 'mossel'], ['plankton', 'krill'], ['mossel', 'zeester'], ['krill', 'haring'], ['zeester', 'meeuw'], ['mossel', 'meeuw'], ['haring', 'zeehond'], ['haring', 'meeuw']] },
    { eco:'savanne', n:['gras', 'acacia', 'zebra', 'gazelle', 'giraffe', 'leeuw', 'hyena'],
      p:[['gras', 'zebra'], ['gras', 'gazelle'], ['acacia', 'giraffe'], ['zebra', 'leeuw'], ['gazelle', 'leeuw'], ['giraffe', 'leeuw'], ['gazelle', 'hyena'], ['zebra', 'hyena']] },
    { eco:'savanne', n:['gras', 'sprinkhaan', 'muis', 'hagedis', 'parelhoen', 'slang', 'arend'],
      p:[['gras', 'sprinkhaan'], ['gras', 'muis'], ['sprinkhaan', 'hagedis'], ['sprinkhaan', 'parelhoen'], ['hagedis', 'slang'], ['muis', 'slang'], ['slang', 'arend'], ['parelhoen', 'arend']] },
    { eco:'pool', n:['plankton', 'krill', 'poolvis', 'pinguin', 'zeehond', 'orka', 'walvis'],
      p:[['plankton', 'krill'], ['krill', 'poolvis'], ['krill', 'walvis'], ['krill', 'pinguin'], ['poolvis', 'pinguin'], ['poolvis', 'zeehond'], ['pinguin', 'orka'], ['zeehond', 'orka']] },
    { eco:'pool', n:['plankton', 'krill', 'poolvis', 'zeehond', 'ijsbeer', 'poolvos'],
      p:[['plankton', 'krill'], ['krill', 'poolvis'], ['poolvis', 'zeehond'], ['zeehond', 'ijsbeer'], ['poolvis', 'poolvos']] },
    { eco:'regenwoud', n:['blad', 'vijg', 'rups', 'aap', 'papegaai', 'kikker', 'slang', 'jaguar'],
      p:[['blad', 'rups'], ['vijg', 'aap'], ['vijg', 'papegaai'], ['rups', 'kikker'], ['rups', 'aap'], ['kikker', 'slang'], ['aap', 'jaguar'], ['slang', 'jaguar'], ['papegaai', 'slang']] },
    { eco:'regenwoud', n:['blad', 'bladmier', 'kever', 'miereneter', 'gordeldier', 'hagedis', 'jaguar'],
      p:[['blad', 'bladmier'], ['blad', 'kever'], ['bladmier', 'miereneter'], ['bladmier', 'gordeldier'], ['kever', 'hagedis'], ['kever', 'gordeldier'], ['miereneter', 'jaguar'], ['gordeldier', 'jaguar']] }
  ];

  /* ---------- begrippen: meerkeuze; het goede antwoord staat vooraan (de motor hussselt)
     n: voor welke niveaus; b: welk beeld erbij hoort ---------- */
  var BEGRIPPEN = [
    { n:['bb', 'kgt', 'hv'], b:'keten', v:'Hoe heet een rij organismen waarin elk organisme het vorige eet?', o:['een voedselketen', 'een voedselweb', 'een kringloop', 'een piramide'], u:'Een voedselketen is een rij: gras wordt gegeten door het konijn, het konijn door de vos. Elke pijl betekent ‘wordt gegeten door’.' },
    { n:['bb', 'kgt', 'hv'], b:'web', v:'Hoe heet een tekening waarin meerdere voedselketens aan elkaar vastzitten?', o:['een voedselweb', 'een voedselketen', 'een stamboom', 'een kringloop'], u:'In een voedselweb eet een dier meer dan één ding, en wordt het door meer dan één dier gegeten. Zo zitten de ketens aan elkaar vast.' },
    { n:['bb', 'kgt', 'hv'], b:'producent', v:'Wat is een producent?', o:['een organisme dat zelf voedsel maakt met licht', 'een dier dat planten eet', 'een dier dat andere dieren eet', 'een organisme dat dode resten opruimt'], u:'Producenten zijn planten en algen. Met licht, water en koolstofdioxide maken ze hun eigen voedsel: fotosynthese.' },
    { n:['bb', 'kgt', 'hv'], b:'keten', v:'Waar begint elke voedselketen?', o:['bij een producent (een plant of alg)', 'bij een roofdier', 'bij een planteneter', 'bij een afbreker'], u:'Alle energie in een keten komt van de zon. Alleen producenten kunnen die energie vastleggen, dus zij staan altijd vooraan.' },
    { n:['bb', 'kgt', 'hv'], b:'consument', v:'Wat is een consument?', o:['een organisme dat andere organismen eet', 'een organisme dat zelf voedsel maakt', 'een plant zonder bladgroen', 'een steen of ander niet-levend ding'], u:'Consumenten kunnen geen voedsel maken en eten daarom planten of dieren. Alle dieren zijn consumenten.' },
    { n:['bb', 'kgt', 'hv'], b:'afbreker', v:'Wat doen afbrekers, zoals bacteriën en schimmels?', o:['ze breken dode resten af tot voedingsstoffen voor planten', 'ze maken voedsel met zonlicht', 'ze jagen op kleine dieren', 'ze eten alleen levende planten'], u:'Afbrekers (reducenten) halen dode planten, dieren en uitwerpselen uit elkaar. De voedingsstoffen die vrijkomen gebruiken planten weer.' },
    { n:['bb', 'kgt', 'hv'], b:'afbreker', v:'Welke organismen zijn afbrekers?', o:['bacteriën en schimmels', 'vossen en uilen', 'gras en algen', 'konijnen en muizen'], u:'Bacteriën en schimmels (waaronder paddenstoelen) zijn de afbrekers. Zonder hen zou het bos vol dode bladeren blijven liggen.' },
    { n:['bb', 'kgt', 'hv'], b:'keten', v:'Wat betekent de pijl in een voedselketen?', o:['wordt gegeten door', 'eet', 'is groter dan', 'woont bij'], u:'De pijl wijst van wie gegeten wordt naar wie eet. Zo wijst hij ook de kant op waar de energie heen gaat.' },
    { n:['bb', 'kgt', 'hv'], b:'keten', v:'Hoe noem je een dier dat planten eet?', o:['een planteneter of herbivoor', 'een vleeseter of carnivoor', 'een afbreker', 'een producent'], u:'Een herbivoor eet planten, een carnivoor eet dieren, een omnivoor eet allebei.' },
    { n:['bb', 'kgt', 'hv'], b:'keten', v:'Hoe noem je een dier dat andere dieren eet?', o:['een vleeseter of carnivoor', 'een planteneter of herbivoor', 'een producent', 'een afbreker'], u:'Carnivoren zoals de vos en de uil eten andere dieren. Ze staan verder in de keten dan planteneters.' },
    { n:['bb', 'kgt', 'hv'], b:'keten', v:'Hoe noem je een dier dat planten én dieren eet?', o:['een alleseter of omnivoor', 'een carnivoor', 'een herbivoor', 'een afbreker'], u:'Een omnivoor eet allebei, zoals de das, de bruine beer en de mens.' },
    { n:['bb', 'kgt', 'hv'], b:'zon', v:'Waar komt de energie in een voedselketen oorspronkelijk vandaan?', o:['van de zon', 'van de bodem', 'van het water', 'van de afbrekers'], u:'Planten vangen zonlicht op en zetten het om in energie in hun voedsel. Die energie geven ze door aan wie hen eet.' },
    { n:['bb', 'kgt', 'hv'], b:'piramideAantal', v:'Waarom zijn er in een weiland veel meer sprinkhanen dan buizerds?', o:['bij elke schakel gaat het grootste deel van de energie verloren', 'buizerds leggen minder eieren dan sprinkhanen', 'sprinkhanen zijn kleiner en passen er dus meer', 'buizerds eten geen sprinkhanen'], u:'Elk dier gebruikt het meeste van zijn energie om te leven en te bewegen. Maar een klein deel gaat door naar de volgende schakel. Bovenin de piramide is dus weinig over.' },
    { n:['bb', 'kgt', 'hv'], b:'piramideAantal', v:'Wat laat een piramide van aantallen zien?', o:['hoeveel organismen er van elke schakel in de keten zijn', 'hoe groot elk dier is', 'hoe oud de dieren worden', 'welke dieren de mooiste zijn'], u:'Onderin staan de producenten, dat zijn er het meest. Elke laag erboven is kleiner: minder planteneters, nog minder roofdieren.' },
    { n:['bb', 'kgt', 'hv'], b:'piramideAantal', v:'Welke schakel staat onderin een piramide van aantallen?', o:['de producenten', 'de roofdieren', 'de afbrekers', 'de planteneters'], u:'De producenten vormen de brede onderkant: van hen zijn er de meeste. Bovenin staat het roofdier, daar zijn er het minst van.' },
    { n:['kgt', 'hv'], b:'keten', v:'Hoe noem je het dier dat in een voedselketen de producent eet?', o:['de consument van de eerste orde', 'de consument van de tweede orde', 'de consument van de derde orde', 'de afbreker'], u:'De eerste consument in de keten (de planteneter) is de consument van de eerste orde. Wie hem eet is van de tweede orde, enzovoort.' },
    { n:['kgt', 'hv'], b:'keten', v:'In de keten gras → konijn → vos: wat is de vos?', o:['een consument van de tweede orde', 'een consument van de eerste orde', 'een producent', 'een afbreker'], u:'Het konijn eet de producent en is de eerste orde. De vos eet het konijn en is de tweede orde.' },
    { n:['kgt', 'hv'], b:'kringloop', v:'Wat is een kringloop van stoffen?', o:['stoffen gaan van planten naar dieren en via afbrekers weer terug naar de planten', 'dieren lopen elke dag hetzelfde rondje', 'water stroomt van de rivier naar de zee', 'het gras groeit elk jaar opnieuw'], u:'Planten bouwen stoffen in, dieren eten planten, afbrekers halen dode resten uit elkaar, en de voedingsstoffen komen weer bij de planten. Een kringloop.' },
    { n:['kgt', 'hv'], b:'kringloop', v:'Waarom is een kringloop van stoffen zonder afbrekers niet compleet?', o:['dan komen de voedingsstoffen uit dode resten niet terug in de bodem', 'dan hebben de roofdieren niets te eten', 'dan groeien de planten te snel', 'dan is er te veel zonlicht'], u:'Afbrekers maken de kring rond: zij geven de voedingsstoffen uit dode planten en dieren weer terug aan de bodem, waar planten ze opnemen.' },
    { n:['kgt', 'hv'], b:'biomassa', v:'Wat is biomassa?', o:['het totale gewicht van alle organismen van een soort in een gebied', 'het aantal soorten in een gebied', 'de hoeveelheid zonlicht die een plant opvangt', 'de grootte van het grootste dier'], u:'Biomassa is de massa van al het levende materiaal, bijvoorbeeld alle konijnen in een weiland bij elkaar gewogen.' },
    { n:['kgt', 'hv'], b:'energie', v:'Wat gebeurt er met het grootste deel van de energie die een konijn uit gras haalt?', o:['het konijn gebruikt het om te bewegen, te groeien en warm te blijven', 'het gaat helemaal door naar de vos die het konijn eet', 'het wordt opgeslagen in de bodem', 'het gaat terug naar de zon'], u:'Een dier verbruikt de meeste energie zelf. Alleen wat in zijn lichaam blijft zitten, kan door naar de volgende schakel.' },
    { n:['kgt', 'hv'], b:'web', v:'Waarom is een voedselweb een betere weergave van de natuur dan één voedselketen?', o:['de meeste dieren eten meer dan één soort voedsel', 'een web is makkelijker te tekenen', 'in een keten staan geen planten', 'in een web staan geen pijlen'], u:'Een vos eet konijnen, maar ook muizen en bessen. Alle ketens samen vormen een web, dat laat zien hoe alles met elkaar te maken heeft.' },
    { n:['kgt', 'hv'], b:'producent', v:'Hoe heet het proces waarmee producenten hun eigen voedsel maken?', o:['fotosynthese', 'verbranding', 'vertering', 'ademhaling'], u:'Bij fotosynthese maakt de plant met licht uit water en koolstofdioxide glucose en zuurstof. Dat gebeurt in het bladgroen.' },
    { n:['kgt', 'hv'], b:'keten', v:'Welke rij is een goede voedselketen?', o:['alg → watervlo → stekelbaars → snoek', 'snoek → stekelbaars → watervlo → alg', 'watervlo → alg → snoek → stekelbaars', 'alg → snoek → watervlo → stekelbaars'], u:'De producent (de alg) staat vooraan, dan de planteneter (de watervlo), dan de dieren die hem eten. De pijl wijst naar wie eet.' },
    { n:['kgt', 'hv'], b:'afbreker', v:'Een dood blad op de bosbodem verdwijnt na een tijd. Wie doet dat?', o:['afbrekers zoals schimmels en bacteriën', 'de zon', 'de regen', 'de roofvogels'], u:'Schimmels en bacteriën breken het blad af. Wat overblijft zijn voedingsstoffen in de bodem, die de boom weer opneemt.' },
    { n:['kgt', 'hv'], b:'piramideAantal', v:'Waarom heeft een voedselketen bijna nooit meer dan vijf schakels?', o:['na elke schakel blijft er te weinig energie over voor nog een schakel', 'er zijn niet genoeg dieren om zes schakels te maken', 'roofdieren willen niet gegeten worden', 'planten groeien niet hoog genoeg'], u:'Elke schakel houdt maar ongeveer een tiende van de energie over. Na vier of vijf keer is er te weinig om nog een roofdier van te laten leven.' },
    { n:['hv'], b:'energie', v:'Hoeveel van de energie van een schakel komt ongeveer terecht in de volgende schakel?', o:['ongeveer 10%', 'ongeveer 50%', 'ongeveer 90%', 'alles'], u:'Ongeveer 90% gaat verloren aan bewegen, warmte en onverteerbare resten. Maar ongeveer een tiende gaat door naar wie het organisme eet.' },
    { n:['hv'], b:'energie', v:'Hoeveel procent van de energie gaat er per schakel ongeveer verloren?', o:['ongeveer 90%', 'ongeveer 10%', 'ongeveer 50%', 'niets'], u:'Bijna alle energie wordt gebruikt om te leven of verlaat het dier als warmte en uitwerpselen. Slechts ongeveer 10% blijft over voor de volgende schakel.' },
    { n:['hv'], b:'piramideBiomassa', v:'Wat laat een piramide van biomassa zien?', o:['het totale gewicht van de organismen per schakel', 'hoeveel organismen er per schakel zijn', 'hoeveel energie de zon geeft', 'hoe hoog de planten groeien'], u:'Niet het aantal, maar de massa per schakel. Ook die neemt per schakel af, omdat er steeds energie verloren gaat.' },
    { n:['hv'], b:'piramideBiomassa', v:'Een eik met een miljoen rupsen erop: waarom is de piramide van aantallen dan omgekeerd, maar de piramide van biomassa niet?', o:['één eik weegt veel meer dan alle rupsen bij elkaar', 'rupsen zijn geen consumenten', 'de eik is een consument', 'rupsen eten geen bladeren'], u:'Bij aantallen telt één boom als één. Bij biomassa telt zijn gewicht, en dat is veel groter dan dat van alle rupsen. Daarom klopt de piramide van biomassa wel.' },
    { n:['hv'], b:'piramideBiomassa', v:'Waarom is een piramide van biomassa meestal eerlijker dan een piramide van aantallen?', o:['een groot organisme telt dan mee naar zijn gewicht, niet als één stuk', 'biomassa is makkelijker te tellen', 'er staan dan meer dieren in', 'de zon staat er dan ook in'], u:'Een boom of een walvis is één organisme, maar bevat enorm veel energie. Wegen in plaats van tellen laat dat zien.' },
    { n:['hv'], b:'web', v:'Wat gebeurt er in een voedselweb meestal als een roofdier bovenaan verdwijnt?', o:['zijn prooidieren nemen toe en eten de planten kaal', 'de planten sterven meteen uit', 'de afbrekers verdwijnen ook', 'er verandert niets'], u:'Zonder roofdier groeit het aantal prooidieren snel. Ze eten meer planten op dan er bijgroeien, en later stort hun aantal weer in.' },
    { n:['hv'], b:'kringloop', v:'Welke stof nemen planten op uit de lucht om biomassa te maken?', o:['koolstofdioxide', 'zuurstof', 'stikstofgas', 'waterdamp'], u:'Bij fotosynthese wordt koolstofdioxide uit de lucht ingebouwd in glucose. Zo komt koolstof in de voedselketen terecht.' },
    { n:['hv'], b:'kringloop', v:'Hoe komt de koolstof uit een dood dier weer in de lucht?', o:['afbrekers ademen het uit als koolstofdioxide', 'het verdampt in de zon', 'planten blazen het uit', 'het blijft altijd in de bodem'], u:'Afbrekers breken het dode dier af en ademen daarbij koolstofdioxide uit. Dat is de koolstofkringloop.' },
    { n:['hv'], b:'keten', v:'In de keten plankton → krill → vis → zeehond → ijsbeer: van welke orde is de zeehond?', o:['de derde orde', 'de tweede orde', 'de eerste orde', 'de vierde orde'], u:'Krill is de eerste orde, de vis de tweede, de zeehond de derde en de ijsbeer de vierde.' },
    { n:['hv'], b:'energie', v:'Er zit 5000 kJ energie in het gras van een weiland. Hoeveel komt er ongeveer in de vossen terecht (gras → konijn → vos)?', o:['ongeveer 50 kJ', 'ongeveer 500 kJ', 'ongeveer 2500 kJ', 'ongeveer 5000 kJ'], u:'Twee schakels verder: 5000 × 0,1 = 500 kJ in de konijnen, 500 × 0,1 = 50 kJ in de vossen.' },
    { n:['hv'], b:'web', v:'Wat is de rol van een toppredator (het roofdier bovenaan) in een ecosysteem?', o:['hij houdt de aantallen van zijn prooidieren in evenwicht', 'hij maakt voedsel voor de planten', 'hij breekt dode resten af', 'hij zorgt voor meer zonlicht'], u:'Doordat de toppredator prooidieren eet, blijven die niet eindeloos toenemen. Zo blijft het hele web in balans.' },
    { n:['hv'], b:'consument', v:'Waarom is een omnivoor niet altijd van dezelfde orde?', o:['hij eet zowel planten (eerste orde) als dieren (hogere orde)', 'omnivoren tellen niet mee in een keten', 'hij is altijd de laatste schakel', 'hij is eigenlijk een producent'], u:'Een das die bessen eet is consument van de eerste orde. Dezelfde das die een egel eet is van een hogere orde. Het hangt af van de keten die je bekijkt.' },
    { n:['bb', 'kgt', 'hv'], b:'consument', v:'Welk organisme is een consument?', o:['de vos', 'het gras', 'de alg', 'de eik'], u:'Een vos eet andere dieren: hij is een consument. Gras, algen en bomen maken hun eigen voedsel: dat zijn producenten.' },
    { n:['bb', 'kgt', 'hv'], b:'producent', v:'Welk organisme is een producent?', o:['de alg', 'de haring', 'de zeehond', 'de garnaal'], u:'Algen maken hun voedsel met zonlicht. Alle dieren in de zee leven uiteindelijk van algen en ander plantaardig plankton.' },
    { n:['bb', 'kgt', 'hv'], b:'web', v:'In een voedselweb gaat een pijl van de muis naar de uil. Wat betekent dat?', o:['de uil eet de muis', 'de muis eet de uil', 'de muis en de uil eten hetzelfde', 'de uil is kleiner dan de muis'], u:'De pijl wijst altijd naar wie eet: van de muis naar de uil betekent dat de uil de muis eet.' },
    { n:['bb', 'kgt'], b:'keten', v:'Wat hoort er op de plek van het vraagteken: gras → ? → vos', o:['konijn', 'uil', 'paddenstoel', 'eik'], u:'Tussen het gras en de vos hoort een planteneter die de vos eet, zoals het konijn.' },
    { n:['bb', 'kgt'], b:'keten', v:'Wat hoort er op de plek van het vraagteken: alg → watervlo → ?', o:['stekelbaars', 'gras', 'schimmel', 'konijn'], u:'Na de watervlo komt een dier dat watervlooien eet, zoals de stekelbaars. Gras en konijnen leven niet in de sloot.' },
    { n:['bb', 'kgt', 'hv'], b:'afbreker', v:'Een paddenstoel op een dode boomstam: welke rol heeft hij?', o:['afbreker', 'producent', 'consument van de eerste orde', 'roofdier'], u:'Een paddenstoel is een schimmel. Hij leeft van het dode hout en breekt het af tot voedingsstoffen.' },
    { n:['kgt', 'hv'], b:'piramideAantal', v:'In een sloot zijn er meer watervlooien dan stekelbaarzen, en meer stekelbaarzen dan snoeken. Hoe heet zo’n opbouw?', o:['een piramide van aantallen', 'een voedselweb', 'een kringloop', 'een stamboom'], u:'Elke schakel is kleiner in aantal dan de schakel eronder. Getekend als lagen ziet dat eruit als een piramide.' }
  ];

  return { ORG: ORG, ECO: ECO, AFBREKERS: AFBREKERS, KETENS: KETENS, WEBBEN: WEBBEN, BEGRIPPEN: BEGRIPPEN };
})();
if (typeof module !== 'undefined' && module.exports) module.exports = VOEDSELWEB_DATA;
