/* De woorden van Woordenschat in context. In een eigen bestand zodat ze na te
   lezen zijn. Niveau n: 1 = vmbo-bb (alledaags maar lastig), 2 = vmbo-kgt en
   tl (schooltaal), 3 = havo en vwo (abstract).
   UIT:    [n, zin met het woord tussen **sterretjes** en het contextsignaal tussen {accolades}, goed, fout, fout, fout, uitleg]
   GAT:    [n, zin met ___ als gat, goed, fout, fout, fout, uitleg]
   SCHOOL: [n, schooltaalwoord, pictogram, wat er gevraagd wordt (goed), fout, fout, fout, uitleg]
   SYN:    [n, woord, [betekent hetzelfde], [betekent het tegenovergestelde], uitleg] */
var WOORDENSCHAT = (function(){
var UIT = [
  [1, 'Na de wedstrijd was Sam **uitgeput**: {hij kon geen stap meer zetten}.', 'heel erg moe', 'heel blij', 'boos op de trainer', 'een beetje verkouden', 'De zin erna zegt dat hij geen stap meer kon zetten: dat is het signaal dat hij heel moe was.'],
  [1, 'De hond was **schuw**: {hij kroop weg zodra er iemand binnenkwam}.', 'bang en verlegen', 'agressief', 'heel oud', 'erg speels', 'Wegkruipen als er iemand komt, is het gedrag van een bang dier.'],
  [1, 'Het kapotte scherm was een **strop**: {het kostte haar al haar spaargeld}.', 'een flinke tegenslag', 'een mooie kans', 'een grap', 'een klein foutje', 'Al je spaargeld kwijt: de zin legt uit dat het een tegenslag was.'],
  [1, 'De game was **verslavend**: {hij kon er niet mee stoppen}.', 'je wilt steeds doorgaan', 'heel moeilijk', 'saai', 'gratis', 'Niet kunnen stoppen is precies wat verslavend betekent.'],
  [1, 'De docent was **mild** {en gaf toch een voldoende}.', 'niet streng', 'heel boos', 'ziek', 'te laat', 'Toch een voldoende geven, terwijl het niet helemaal goed was: dat is niet streng zijn.'],
  [1, 'De kat is **behoedzaam**: {ze zet eerst een pootje op het ijs voordat ze erop stapt}.', 'voorzichtig', 'lui', 'snel', 'nieuwsgierig', 'Eerst voelen en dan pas stappen is voorzichtig gedrag.'],
  [1, 'Het nieuws over de sluiting kwam **onverwacht**: {niemand had het zien aankomen}.', 'plotseling, als een verrassing', 'veel te laat', 'op de radio', 'heel langzaam', 'Niemand had het zien aankomen: dat betekent dat het plotseling kwam.'],
  [1, 'Zijn kamer was een **puinhoop**: {overal kleren en lege bekers}.', 'een grote rommel', 'heel netjes', 'leeg', 'klein', 'Overal kleren en bekers: de zin beschrijft een rommel.'],
  [1, 'De trainer **prees** Noor, {want ze had heel goed gespeeld}.', 'zei iets aardigs tegen haar', 'gaf haar straf', 'wisselde haar', 'vergat haar', 'Omdat ze goed speelde, zei de trainer iets aardigs. Prijzen is een compliment geven.'],
  [1, 'Het pad was **glibberig** {door de regen, dus we vielen bijna}.', 'glad', 'lang', 'steil', 'donker', 'Door regen bijna vallen: het pad was glad.'],
  [1, 'De winkel had **uitverkoop**: {alles was de helft goedkoper}.', 'alles is goedkoper', 'de winkel is dicht', 'er is niets meer', 'alleen nieuwe spullen', 'De helft goedkoper: dat is uitverkoop.'],
  [1, 'De jongen was **brutaal**: {hij gaf de docent een grote mond}.', 'onbeleefd', 'verlegen', 'slim', 'grappig', 'Een grote mond geven is onbeleefd gedrag.'],
  [1, 'Het konijn zat **roerloos** in het gras, {zonder een spier te bewegen}.', 'helemaal stil', 'diep in slaap', 'te eten', 'gewond', 'Zonder een spier te bewegen: helemaal stil.'],
  [1, 'De pizza was **overheerlijk**: {we aten hem tot de laatste kruimel op}.', 'heel lekker', 'te heet', 'veel te groot', 'koud', 'Tot de laatste kruimel opeten doe je alleen als iets heel lekker is.'],
  [1, 'De bus had **vertraging**, {dus we kwamen te laat op school}.', 'kwam later dan gepland', 'reed niet', 'was vol', 'was kapot', 'Te laat komen doordat de bus later was: dat is vertraging.'],
  [1, 'Mijn opa is erg **vergeetachtig**: {hij weet vaak niet meer waar zijn sleutels liggen}.', 'vergeet snel dingen', 'heel streng', 'erg grappig', 'slecht ter been', 'Niet meer weten waar je sleutels liggen: je vergeet snel dingen.'],
  [1, 'Het water in het meer was **ijskoud**: {na een minuut kon ik mijn tenen niet meer voelen}.', 'heel erg koud', 'heel diep', 'vies', 'lekker warm', 'Je tenen niet meer voelen gebeurt als het water heel koud is.'],
  [1, 'Lisa was **jaloers** op haar zus: {die kreeg een nieuwe telefoon en zij niet}.', 'wilde ook hebben wat een ander had', 'blij voor iemand', 'bang voor iemand', 'boos op zichzelf', 'Haar zus kreeg iets en zij niet, en dat wilde Lisa ook: dat is jaloers.'],
  [1, 'De film was **saai**: {halverwege viel de helft van de klas in slaap}.', 'niet leuk of spannend', 'heel eng', 'te kort', 'grappig', 'In slaap vallen bij een film doe je als er niets spannends gebeurt.'],
  [2, 'De sporthal wordt **gerenoveerd**: {er komt een nieuwe vloer en nieuwe verlichting}.', 'opgeknapt', 'afgebroken', 'verkocht', 'verhuurd', 'Een nieuwe vloer en verlichting: de hal wordt opgeknapt, niet afgebroken.'],
  [2, 'De uitslag was **verbijsterend**: {de kampioen verloor met 6-0}.', 'heel verrassend', 'zoals verwacht', 'oneerlijk', 'saai', 'Een kampioen die met 6-0 verliest, is een grote verrassing.'],
  [2, 'De game is **compatibel** met oudere telefoons, {dus je hoeft geen nieuwe te kopen}.', 'werkt erop', 'is gratis', 'is te zwaar', 'is beveiligd', 'Geen nieuwe telefoon nodig: de game werkt ook op oude toestellen.'],
  [2, 'Het bos is een **kwetsbaar** gebied: {een paar droge zomers kunnen het al beschadigen}.', 'gemakkelijk te beschadigen', 'heel groot', 'goed beschermd', 'onbekend', 'Al kapot na een paar droge zomers: dat betekent kwetsbaar.'],
  [2, 'De directeur was **stellig**: {er komt geen tweede kans, punt uit}.', 'heel zeker van zijn zaak', 'twijfelend', 'vriendelijk', 'afwezig', '“Punt uit” laat zien dat hij heel zeker van zijn zaak was.'],
  [2, 'De uitleg was **beknopt**: {in drie zinnen was alles gezegd}.', 'kort', 'ingewikkeld', 'onduidelijk', 'saai', 'Alles in drie zinnen: kort.'],
  [2, 'De nieuwe speler was **veelbelovend**: {op zijn zestiende scoorde hij al in het eerste elftal}.', 'zal waarschijnlijk heel goed worden', 'duur', 'vaak geblesseerd', 'onbekend', 'Al zo jong scoren in het eerste elftal: er wordt veel van hem verwacht.'],
  [2, 'De leraar **negeerde** het geklets {en ging gewoon door met de les}.', 'deed alsof hij het niet merkte', 'werd boos over', 'lachte om', 'schreef op', 'Gewoon doorgaan is doen alsof je het niet merkt.'],
  [2, 'Het reisverslag was **gedetailleerd**: {zelfs de kleur van de deur van het hostel stond erin}.', 'met heel veel kleine dingen erin', 'te kort', 'spannend', 'verzonnen', 'Zelfs de kleur van de deur: dat zijn kleine details.'],
  [2, 'De wetenschapper was **sceptisch**: {ze wilde eerst bewijs zien}.', 'twijfelde en wilde bewijs', 'enthousiast', 'boos', 'onzeker over zichzelf', 'Eerst bewijs willen zien is twijfelen.'],
  [2, 'De koala is **inheems** in Australië: {hij komt van nature alleen daar voor}.', 'komt daar van nature voor', 'is daar beschermd', 'is daar uitgestorven', 'is daar ingevoerd', 'Van nature alleen daar: dat is inheems.'],
  [2, 'De app **verzamelt** je gegevens, {zoals je locatie en je zoekopdrachten}.', 'slaat op en bewaart', 'verkoopt', 'wist', 'controleert', 'De opsomming zegt wat de app bewaart: locatie en zoekopdrachten.'],
  [2, 'De discussie liep **hoog op**: {er werd geschreeuwd en met deuren geslagen}.', 'werd heftig', 'duurde lang', 'ging over geld', 'eindigde snel', 'Schreeuwen en met deuren slaan: heftig.'],
  [2, 'De brug is **provisorisch** gerepareerd {tot de echte reparatie volgende maand}.', 'tijdelijk', 'grondig', 'duur', 'onzichtbaar', 'Tot de echte reparatie: dit is een tijdelijke oplossing.'],
  [2, 'Zijn antwoord was **ontwijkend**: {hij zei wel iets, maar gaf geen antwoord op de vraag}.', 'ging om de vraag heen', 'heel duidelijk', 'te lang', 'brutaal', 'Wel iets zeggen maar de vraag niet beantwoorden: om de vraag heen praten.'],
  [2, 'De verkoper was erg **opdringerig**: {hij bleef maar praten, ook toen we zeiden dat we alleen keken}.', 'bleef aandringen', 'behulpzaam', 'verlegen', 'kortaf', 'Blijven doorpraten als iemand nee zegt: dat is opdringerig.'],
  [2, 'Het plan is **haalbaar**: {we hebben genoeg tijd, geld en mensen om het uit te voeren}.', 'het kan echt lukken', 'het is te duur', 'het is geheim', 'het is al klaar', 'Genoeg tijd, geld en mensen: het plan kan lukken.'],
  [2, 'De kapitein was **besluiteloos**: {hij kon maar niet kiezen welke kant het schip op moest}.', 'kon geen keuze maken', 'heel dapper', 'erg boos', 'zeeziek', 'Niet kunnen kiezen is besluiteloos zijn.'],
  [2, 'De zwemster was **teleurgesteld**: {na maanden trainen werd ze maar vierde}.', 'baalde omdat het tegenviel', 'trots', 'opgelucht', 'verbaasd en blij', 'Maanden trainen en toch maar vierde: het viel tegen.'],
  [3, 'Haar houding tegenover de nieuwe regels was **ambivalent**: {ze zag de voordelen, maar had ook grote bezwaren}.', 'met tegenstrijdige gevoelens', 'heel negatief', 'onverschillig', 'enthousiast', 'Voordelen zien en bezwaren hebben tegelijk: tegenstrijdige gevoelens.'],
  [3, 'De trainer is **consequent**: {wie te laat komt, zit op de bank, wie het ook is}.', 'doet altijd hetzelfde', 'streng maar eerlijk in wisselende mate', 'onvoorspelbaar', 'zachtaardig', 'Altijd dezelfde regel, voor iedereen: consequent.'],
  [3, 'De kritiek was **impliciet**: {hij zei niet dat het slecht was, maar iedereen begreep het}.', 'niet letterlijk gezegd', 'heel hard', 'openlijk uitgesproken', 'onterecht', 'Niet gezegd, wel begrepen: dat is impliciet.'],
  [3, 'Het bewijs was **overtuigend**: {zelfs de grootste twijfelaars gingen akkoord}.', 'zo sterk dat iedereen het gelooft', 'onduidelijk', 'vervalst', 'te uitgebreid', 'Als zelfs twijfelaars akkoord gaan, is het bewijs sterk.'],
  [3, 'Het plan was **utopisch**: {mooi op papier, maar in de praktijk onhaalbaar}.', 'te mooi om waar te kunnen zijn', 'goedkoop', 'praktisch', 'ouderwets', 'Mooi maar onhaalbaar: utopisch.'],
  [3, 'De rechter was **onpartijdig**: {ze luisterde naar beide kanten zonder een voorkeur te laten merken}.', 'koos geen kant', 'streng', 'traag', 'onervaren', 'Beide kanten horen zonder voorkeur: geen kant kiezen.'],
  [3, 'De maatregel bleek **contraproductief**: {het aantal te laat komende leerlingen steeg juist}.', 'werkte averechts', 'werkte meteen', 'was duur', 'was populair', 'Het probleem werd juist erger: de maatregel werkte averechts.'],
  [3, 'De theorie is **plausibel**: {alle metingen tot nu toe kloppen ermee}.', 'geloofwaardig', 'bewezen', 'achterhaald', 'ingewikkeld', 'Als alle metingen kloppen, is de theorie geloofwaardig, al is dat nog geen bewijs.'],
  [3, 'Het virus is **hardnekkig**: {na drie behandelingen was het nog niet weg}.', 'moeilijk kwijt te raken', 'besmettelijk', 'nieuw', 'ongevaarlijk', 'Na drie behandelingen nog niet weg: moeilijk kwijt te raken.'],
  [3, 'De spreker was **welbespraakt**: {de zaal hing aan haar lippen}.', 'kon heel goed praten', 'praatte te snel', 'was nerveus', 'was beroemd', 'Als een zaal aan je lippen hangt, kun je goed spreken.'],
  [3, 'De cijfers zijn **representatief**: {er deden leerlingen van alle scholen en niveaus mee}.', 'geven een goed beeld van het geheel', 'geheim', 'verrassend hoog', 'afgerond', 'Alle scholen en niveaus deden mee, dus de cijfers zeggen iets over het geheel.'],
  [3, 'Zijn reactie was **gelaten**: {hij haalde zijn schouders op en liep door}.', 'berustend, zonder verzet', 'woedend', 'opgelucht', 'verbaasd', 'Schouders ophalen en doorlopen: hij legde zich erbij neer.'],
  [3, 'De regels zijn **rigide**: {er wordt nooit een uitzondering gemaakt}.', 'star en onbuigzaam', 'nieuw', 'onduidelijk', 'soepel', 'Nooit een uitzondering: star.'],
  [3, 'Het onderzoek was **grondig**: {elke bron werd twee keer gecontroleerd}.', 'heel zorgvuldig', 'snel', 'geheim', 'overbodig', 'Elke bron twee keer controleren is zorgvuldig werken.'],
  [3, 'Het argument was **irrelevant**: {het ging over het weer, terwijl de discussie over het budget ging}.', 'deed er niet toe', 'heel sterk', 'onbeleefd', 'te lang', 'Over het weer praten in een discussie over geld: dat doet er niet toe.'],
  [3, 'De minister gaf een **cryptisch** antwoord: {niemand begreep wat ze nu eigenlijk bedoelde}.', 'raadselachtig, moeilijk te begrijpen', 'kort en duidelijk', 'onbeleefd', 'grappig', 'Niemand begreep wat ze bedoelde: het antwoord was raadselachtig.'],
  [3, 'Zijn optimisme bleek **ongegrond**: {er was geen enkele reden om te denken dat het goed zou gaan}.', 'zonder goede reden', 'terecht', 'besmettelijk', 'tijdelijk', 'Geen enkele reden: het optimisme had geen grond, geen basis.'],
  [3, 'Het succes van de band was **kortstondig**: {na één hit hoorde niemand meer iets van ze}.', 'duurde maar kort', 'enorm groot', 'onverdiend', 'wereldwijd', 'Na één hit was het voorbij: het succes duurde kort.'],
  [3, 'De leerling was **nonchalant**: {hij leverde zijn werkstuk te laat in en haalde zijn schouders op}.', 'onverschillig en slordig', 'zenuwachtig', 'overdreven netjes', 'woedend', 'Te laat inleveren en je schouders ophalen: het kan hem niet schelen.']
];
var GAT = [
  [1, 'De trein had een uur ___, dus we misten de aansluiting.', 'vertraging', 'voorsprong', 'pauze', 'haast', 'Als je een aansluiting mist, was de trein te laat: vertraging.'],
  [1, 'Ik ben ___ op spinnen: ik ren gillend weg.', 'bang', 'dol', 'trots', 'jaloers', 'Gillend wegrennen doe je als je bang bent.'],
  [1, 'De winkel is op zondag ___, dus je kunt dan niets kopen.', 'gesloten', 'druk', 'open', 'goedkoop', 'Niets kunnen kopen: de winkel is gesloten.'],
  [1, 'Zet je telefoon op ___ tijdens de les, anders hoort iedereen hem.', 'stil', 'vol', 'wit', 'zwaar', 'Anders hoort iedereen hem: je zet hem op stil.'],
  [1, 'De weg was ___ door het ijs, dus veel fietsers vielen.', 'glad', 'breed', 'leeg', 'nieuw', 'Fietsers vallen op ijs omdat het glad is.'],
  [1, 'Hij was zo ___ dat hij in de klas in slaap viel.', 'moe', 'blij', 'sterk', 'snel', 'In slaap vallen doe je als je moe bent.'],
  [1, 'Het pakje was ___: ik kon het zo optillen.', 'licht', 'zwaar', 'duur', 'nat', 'Zo optillen kun je iets wat licht is.'],
  [1, 'De puppy was nog ___ en paste in mijn twee handen.', 'klein', 'oud', 'wild', 'ziek', 'In twee handen passen: klein.'],
  [1, 'Het was zo ___ buiten dat we een muts en handschoenen droegen.', 'koud', 'warm', 'stil', 'laat', 'Muts en handschoenen draag je tegen de kou.'],
  [1, 'De uitleg was ___: iedereen snapte het meteen.', 'duidelijk', 'lang', 'moeilijk', 'grappig', 'Iedereen snapte het meteen, dus de uitleg was duidelijk.'],
  [1, 'Ze is heel ___: ze helpt altijd iedereen.', 'behulpzaam', 'sportief', 'nieuwsgierig', 'rijk', 'Altijd iedereen helpen is behulpzaam.'],
  [1, 'Het concert was ___: er was geen kaartje meer te krijgen.', 'uitverkocht', 'afgelast', 'gratis', 'begonnen', 'Geen kaartje meer: uitverkocht.'],
  [1, 'De vis is ___, dus eet hem vandaag nog op.', 'vers', 'gebakken', 'zout', 'groot', 'Vandaag nog opeten, omdat hij vers is en niet lang goed blijft.'],
  [1, 'Mijn broer is ___ voor katten: hij begint meteen te niezen.', 'allergisch', 'bang', 'gek', 'geschikt', 'Niezen bij katten is een allergie.'],
  [1, 'De film was zo ___ dat ik de hele tijd moest lachen.', 'grappig', 'lang', 'eng', 'oud', 'De hele tijd lachen: de film was grappig.'],
  [1, 'Ik heb mijn sleutel ___, dus ik kan de deur niet openmaken.', 'verloren', 'gevonden', 'gekocht', 'gepoetst', 'Als je de deur niet open kunt maken, heb je je sleutel niet meer: verloren.'],
  [1, 'De soep is nog te ___: wacht even tot hij is afgekoeld.', 'heet', 'koud', 'zout', 'dik', 'Afkoelen doet iets wat heet is.'],
  [1, 'Na het sporten had ik veel ___, dus ik dronk twee flessen water.', 'dorst', 'honger', 'pijn', 'haast', 'Water drink je als je dorst hebt.'],
  [1, 'De bibliotheek is een ___ plek: je mag er niet praten.', 'stille', 'drukke', 'natte', 'donkere', 'Als je niet mag praten, is het er stil.'],
  [2, 'De fabriek ___ het afval in de rivier, waardoor de vissen doodgingen.', 'loosde', 'kocht', 'verzamelde', 'filterde', 'Afval in de rivier laten lopen heet lozen; de dode vissen zijn het gevolg.'],
  [2, 'Het is nog ___ of het schoolfeest doorgaat; morgen horen we meer.', 'onzeker', 'verplicht', 'duidelijk', 'verboden', 'Morgen horen we meer, dus nu is het nog onzeker.'],
  [2, 'De brandweer kon het vuur snel ___, zodat de schade beperkt bleef.', 'blussen', 'aansteken', 'ontdekken', 'melden', 'Beperkte schade komt doordat het vuur snel geblust is.'],
  [2, 'Na de ___ van de nieuwe wet mogen scooters niet meer op het fietspad.', 'invoering', 'afschaffing', 'verkiezing', 'vertaling', 'Een wet die iets nieuws verbiedt, is ingevoerd.'],
  [2, 'De game kreeg een ___: nieuwe levels en minder fouten.', 'update', 'korting', 'waarschuwing', 'recensie', 'Nieuwe levels en minder fouten: dat brengt een update.'],
  [2, 'De ___ van de school besloot dat de kantine gezonder wordt.', 'directie', 'conciërge', 'buurt', 'klas', 'Zulke besluiten neemt de leiding van de school: de directie.'],
  [2, 'Het team speelde met veel ___: ze gaven niet op, ook niet bij 0-3.', 'doorzettingsvermogen', 'geluk', 'tegenzin', 'twijfel', 'Niet opgeven bij een achterstand: doorzettingsvermogen.'],
  [2, 'De uitslag van het onderzoek is ___: eerst willen ze de metingen nog een keer controleren.', 'voorlopig', 'definitief', 'openbaar', 'geheim', 'Nog een keer controleren betekent dat de uitslag voorlopig is.'],
  [2, 'De docent gaf een ___ van de stof: alleen de hoofdpunten in tien minuten.', 'samenvatting', 'uitbreiding', 'vertaling', 'beoordeling', 'Alleen de hoofdpunten in korte tijd: een samenvatting.'],
  [2, 'Veel dieren ___ in de winter: ze slapen maandenlang.', 'overwinteren', 'verhuizen', 'jagen', 'groeien', 'Maandenlang slapen in de winter: overwinteren.'],
  [2, 'De school ___ leerlingen om met de fiets te komen door een gratis fietsbeurt.', 'stimuleert', 'verbiedt', 'dwingt', 'straft', 'Een beloning geven om iets te doen: stimuleren.'],
  [2, 'Het ___ voor het schoolplein was te klein: het groen moest goedkoper.', 'budget', 'hek', 'rooster', 'verslag', 'Als iets goedkoper moet, is er te weinig geld: het budget.'],
  [2, 'De twee vrienden ___ zich weer na een lange ruzie.', 'verzoenden', 'verdedigden', 'verhuisden', 'vergisten', 'Na een ruzie weer goedmaken: je verzoenen.'],
  [2, 'Het dorp is ___: er is geen winkel, geen school en geen bus.', 'afgelegen', 'toeristisch', 'druk', 'beroemd', 'Geen winkel, school of bus: het dorp ligt ver van alles af.'],
  [2, 'De ___ van de sporthal duurt een jaar; zo lang gymmen we buiten.', 'verbouwing', 'opening', 'verhuur', 'schoonmaak', 'Een jaar lang niet bruikbaar: een verbouwing.'],
  [2, 'Meedoen aan de sportdag is ___: niemand is verplicht.', 'vrijwillig', 'verplicht', 'afgelast', 'duur', 'Niemand is verplicht: je doet vrijwillig mee.'],
  [2, 'De dokter stelde een ___: je hebt griep.', 'diagnose', 'recept', 'afspraak', 'operatie', 'Zeggen wat iemand mankeert, heet een diagnose stellen.'],
  [2, 'Door de ___ in de winkel moesten we een halfuur in de rij staan.', 'drukte', 'stilte', 'verlichting', 'kou', 'Lang in de rij staan komt door de drukte.'],
  [2, 'De wedstrijd eindigde in een ___: het werd 2-2.', 'gelijkspel', 'overwinning', 'nederlaag', 'strafschop', 'Bij 2-2 wint niemand: een gelijkspel.'],
  [3, 'De schrijver ___ in zijn boek dat iedereen zich gelukkig veinst op sociale media.', 'suggereert', 'ontkent', 'meet', 'negeert', 'Een idee naar voren brengen zonder het hard te stellen: suggereren.'],
  [3, 'De maatregel had een ___ effect: minder files en schonere lucht tegelijk.', 'gunstig', 'onbedoeld', 'tijdelijk', 'vreemd', 'Twee voordelen tegelijk: een gunstig effect.'],
  [3, 'Het bewijs was zo ___ dat de rechter geen andere keuze had.', 'overtuigend', 'onduidelijk', 'omvangrijk', 'oud', 'Geen andere keuze hebben: het bewijs was overtuigend.'],
  [3, 'De ___ tussen arm en rijk in de stad wordt groter, blijkt uit het rapport.', 'kloof', 'samenwerking', 'gelijkenis', 'afstand in kilometers', 'Een groot verschil tussen twee groepen noem je een kloof.'],
  [3, 'Zijn mening is ___: hij zegt vandaag dit en morgen precies het tegenovergestelde.', 'inconsequent', 'onderbouwd', 'onafhankelijk', 'gematigd', 'Elke dag iets anders zeggen is inconsequent.'],
  [3, 'De onderzoekers ___ hun conclusie op drie jaar aan metingen.', 'baseren', 'wantrouwen', 'verzwijgen', 'afronden', 'Een conclusie steunt op metingen: baseren op.'],
  [3, 'De gemeente ___ de bouw van het zwembad: de vergunning is ingetrokken.', 'blokkeert', 'financiert', 'versnelt', 'bespreekt', 'Een ingetrokken vergunning zet de bouw stil: blokkeren.'],
  [3, 'De twee theorieën zijn ___: ze kunnen niet allebei waar zijn.', 'onverenigbaar', 'vergelijkbaar', 'bewezen', 'verouderd', 'Niet allebei waar kunnen zijn: onverenigbaar.'],
  [3, 'Het artikel is ___: de schrijver laat alleen de argumenten zien die haar uitkomen.', 'eenzijdig', 'objectief', 'uitgebreid', 'actueel', 'Alleen de argumenten van één kant: eenzijdig.'],
  [3, 'Er is een ___ tussen sportuur en cijfers: leerlingen die sporten, scoren iets hoger.', 'verband', 'verschil', 'conflict', 'tegenstelling', 'Het een hangt samen met het ander: een verband.'],
  [3, 'De ___ van het probleem ligt bij het rooster, niet bij de leerlingen.', 'oorzaak', 'oplossing', 'uitkomst', 'omvang', 'Waar het probleem vandaan komt, is de oorzaak.'],
  [3, 'De regel wordt niet strikt ___: wie een goede reden heeft, mag later inleveren.', 'gehandhaafd', 'uitgelegd', 'begrepen', 'afgeschaft', 'Een regel die uitzonderingen kent, wordt niet strikt gehandhaafd.'],
  [3, 'Haar antwoord was ___: het ging alle kanten op, behalve naar de vraag.', 'ontwijkend', 'beknopt', 'eerlijk', 'juist', 'Om de vraag heen praten is ontwijkend antwoorden.'],
  [3, 'De reclame is ___: hij wekt de indruk dat je met dit drankje sneller leert.', 'misleidend', 'informatief', 'goedkoop', 'kort', 'Een valse indruk wekken is misleiden.'],
  [3, 'De twee steden zijn ___ groot: allebei ongeveer 150.000 inwoners.', 'vrijwel even', 'totaal niet', 'nauwelijks', 'steeds minder', 'Allebei ongeveer evenveel inwoners: vrijwel even groot.'],
  [3, 'De cijfers zijn ___: ze zijn opgesteld door een onafhankelijk bureau en twee keer gecontroleerd.', 'betrouwbaar', 'verouderd', 'vertrouwelijk', 'omstreden', 'Onafhankelijk en dubbel gecontroleerd: je kunt erop vertrouwen.'],
  [3, 'Het plan stuitte op veel ___: bewoners, ondernemers en de oppositie waren allemaal tegen.', 'weerstand', 'steun', 'begrip', 'belangstelling', 'Als iedereen tegen is, stuit een plan op weerstand.'],
  [3, 'De schrijver ___ zijn standpunt met cijfers uit drie onderzoeken.', 'onderbouwt', 'verzwijgt', 'herroept', 'relativeert', 'Cijfers als steun voor een standpunt: onderbouwen.'],
  [3, 'De verandering ging zo ___ dat bijna niemand het merkte.', 'geleidelijk', 'abrupt', 'drastisch', 'luidruchtig', 'Als bijna niemand het merkt, ging het stap voor stap: geleidelijk.']
];
var SCHOOL = [
  [1, 'Noem', 'lijst', 'Schrijf op wat gevraagd wordt, zonder uitleg.', 'Leg uit waarom het zo is.', 'Geef je mening.', 'Vergelijk twee dingen.', 'Bij noem hoef je alleen op te schrijven wat het is, bijvoorbeeld drie namen. Geen uitleg.'],
  [1, 'Leg uit', 'lamp', 'Vertel hoe of waarom iets zo is.', 'Noem alleen het antwoord.', 'Teken het na.', 'Kies het beste antwoord.', 'Bij leg uit moet je laten zien hoe of waarom iets werkt, in een paar zinnen.'],
  [1, 'Beschrijf', 'oog', 'Vertel hoe iets eruitziet of gaat, stap voor stap.', 'Geef je mening.', 'Reken het uit.', 'Vat het samen.', 'Beschrijven is vertellen hoe iets eruitziet of hoe het gaat, alsof de ander het niet ziet.'],
  [1, 'Vergelijk', 'weegschaal', 'Zeg wat hetzelfde is en wat anders.', 'Kies de beste.', 'Leg uit waarom het gebeurt.', 'Noem een voorbeeld.', 'Vergelijken is twee dingen naast elkaar leggen: overeenkomsten en verschillen.'],
  [1, 'Geef een voorbeeld', 'pijl', 'Noem iets uit het echte leven dat erbij past.', 'Geef de regel.', 'Leg uit waarom.', 'Reken het na.', 'Een voorbeeld is een concreet geval dat laat zien wat je bedoelt.'],
  [1, 'Onderstreep', 'lijn', 'Zet een streep onder het goede woord of de goede zin.', 'Schrijf het over.', 'Schrap het.', 'Vertaal het.', 'Onderstrepen is een streep eronder zetten, niet doorstrepen.'],
  [1, 'Vul in', 'gat', 'Zet het goede woord of getal op de open plek.', 'Leg uit waarom.', 'Kies uit twee.', 'Schrijf de hele tekst over.', 'Bij vul in staat er een open plek waar precies één antwoord past.'],
  [1, 'Wat is de oorzaak', 'oorzaak', 'Waardoor komt het?', 'Wat is het gevolg?', 'Wat vind je ervan?', 'Wanneer gebeurde het?', 'De oorzaak is waardoor iets komt; het gevolg is wat er daarna gebeurt.'],
  [1, 'Wat is het gevolg', 'gevolg', 'Wat gebeurt er daardoor?', 'Waardoor komt het?', 'Wat is de betekenis?', 'Wie deed het?', 'Het gevolg is wat er gebeurt doordat iets anders gebeurde.'],
  [1, 'Zet in de goede volgorde', 'volgorde', 'Zet de stappen achter elkaar zoals ze horen.', 'Kies de belangrijkste stap.', 'Leg elke stap uit.', 'Streep de foute stap door.', 'Op volgorde zetten is de stappen in de juiste rij zetten, van eerst naar laatst.'],
  [1, 'Wat betekent', 'boek', 'Zeg in andere woorden wat het woord wil zeggen.', 'Schrijf het woord over.', 'Geef een voorbeeldzin.', 'Zeg of het goed gespeld is.', 'De betekenis geven is uitleggen wat een woord wil zeggen, in je eigen woorden.'],
  [1, 'Kies', 'vink', 'Wijs het antwoord aan dat past.', 'Schrijf een eigen antwoord.', 'Leg uit waarom.', 'Reken het uit.', 'Bij kies staan de antwoorden er al; je wijst het goede aan.'],
  [1, 'Bereken', 'reken', 'Reken het uit en schrijf de berekening op.', 'Schat het.', 'Meet het op.', 'Kies het grootste getal.', 'Berekenen is uitrekenen, en meestal wil de docent de berekening zien.'],
  [1, 'Wat is de hoofdgedachte', 'kern', 'Waar gaat de tekst vooral over, in één zin?', 'Wat is het eerste woord?', 'Wat vind je van de tekst?', 'Hoe lang is de tekst?', 'De hoofdgedachte is de kern van de hele tekst in één zin.'],
  [1, 'Omcirkel', 'kern', 'Zet een rondje om het goede antwoord.', 'Zet een streep onder het antwoord.', 'Streep het antwoord door.', 'Schrijf het antwoord over.', 'Omcirkelen is een rondje om iets heen tekenen.'],
  [1, 'Streep door', 'kruis', 'Zet een streep door wat niet klopt.', 'Zet een streep onder wat klopt.', 'Schrijf het opnieuw.', 'Leg uit waarom het fout is.', 'Doorstrepen is een streep dwars door iets zetten, zodat het niet meer telt.'],
  [1, 'Kruis aan', 'vink', 'Zet een kruisje in het hokje bij het goede antwoord.', 'Streep het foute antwoord door.', 'Schrijf het antwoord op.', 'Omcirkel het goede woord.', 'Bij aankruisen zet je een kruisje in een hokje.'],
  [1, 'Verbind', 'verband', 'Trek een lijn tussen wat bij elkaar hoort.', 'Zet ze op volgorde.', 'Kies er één uit.', 'Schrijf ze onder elkaar.', 'Verbinden is een lijn trekken tussen twee dingen die bij elkaar horen.'],
  [1, 'Schat', 'reken', 'Geef ongeveer het antwoord, zonder precies te rekenen.', 'Reken het precies uit.', 'Meet het op met een liniaal.', 'Zoek het op.', 'Schatten is ongeveer bepalen hoeveel het is, zonder precies uit te rekenen.'],
  [2, 'Verklaar', 'lamp', 'Leg uit waardoor of waarom het zo is.', 'Beschrijf hoe het eruitziet.', 'Geef je oordeel.', 'Noem het antwoord.', 'Verklaren is de oorzaak of de reden geven, niet alleen beschrijven.'],
  [2, 'Noem een kenmerk', 'label', 'Noem iets waaraan je het herkent.', 'Noem een gevolg.', 'Noem een voorbeeld van iets anders.', 'Noem een oorzaak.', 'Een kenmerk is een eigenschap waaraan je iets herkent, bijvoorbeeld: een zoogdier heeft haar.'],
  [2, 'Trek een conclusie', 'conclusie', 'Zeg wat uit de gegevens volgt.', 'Zeg wat je verwacht.', 'Herhaal de gegevens.', 'Noem een oorzaak.', 'Een conclusie is wat je uit de gegevens kunt afleiden: de gegevens zijn de argumenten, de conclusie is de uitkomst.'],
  [2, 'Beargumenteer', 'argument', 'Geef redenen waarom je dat vindt.', 'Vat het samen.', 'Beschrijf het.', 'Noem het antwoord.', 'Beargumenteren is je standpunt onderbouwen met redenen (argumenten).'],
  [2, 'Vat samen', 'kern', 'Noem alleen de hoofdzaken, kort.', 'Schrijf de tekst over.', 'Geef je mening.', 'Leg elk woord uit.', 'Samenvatten is de tekst inkorten tot de hoofdzaken.'],
  [2, 'Wat is het doel', 'doel', 'Wat wil de schrijver bereiken?', 'Wat is het onderwerp?', 'Wie is de schrijver?', 'Waar staat de tekst?', 'Het doel is wat de schrijver wil bereiken: informeren, overtuigen, amuseren.'],
  [2, 'Onderbouw', 'argument', 'Geef bewijs of redenen voor je antwoord.', 'Geef alleen het antwoord.', 'Zet het in een tabel.', 'Teken het.', 'Onderbouwen is je antwoord steunen met bewijs of redenen.'],
  [2, 'Wat is het verband', 'verband', 'Hoe hangen de twee dingen samen?', 'Wat is het verschil?', 'Welke is beter?', 'Wat gebeurde eerst?', 'Bij een verband zeg je hoe het een met het ander samenhangt: oorzaak, gevolg, tegenstelling.'],
  [2, 'Licht toe', 'lamp', 'Maak het duidelijker met uitleg of een voorbeeld.', 'Maak het korter.', 'Zeg of het waar is.', 'Zet het op volgorde.', 'Toelichten is extra uitleg of een voorbeeld geven zodat het duidelijker wordt.'],
  [2, 'Motiveer je antwoord', 'argument', 'Zeg waarom je dat antwoord geeft.', 'Herhaal je antwoord.', 'Geef een ander antwoord.', 'Schrijf het netjes over.', 'Motiveren is de reden geven voor je keuze.'],
  [2, 'Formuleer', 'pen', 'Schrijf het in een goede, volledige zin op.', 'Reken het uit.', 'Kies uit de lijst.', 'Teken het.', 'Formuleren is iets in woorden zetten, in een goede zin.'],
  [2, 'Wat is de functie', 'tandwiel', 'Waar dient het voor, wat doet het?', 'Hoe ziet het eruit?', 'Wanneer is het gemaakt?', 'Wat kost het?', 'De functie is waar iets voor dient: de functie van het hart is bloed rondpompen.'],
  [2, 'Geef aan', 'vink', 'Laat zien of schrijf op wat gevraagd wordt.', 'Leg uitgebreid uit.', 'Geef je mening.', 'Reken het na.', 'Geef aan betekent: maak duidelijk wat er gevraagd wordt, kort en precies.'],
  [2, 'Wat is het standpunt', 'standpunt', 'Wat vindt de schrijver van het onderwerp?', 'Waar gaat de tekst over?', 'Welke bronnen gebruikt hij?', 'Hoe lang is de tekst?', 'Het standpunt is de mening van de schrijver over het onderwerp.'],
  [2, 'Toon aan', 'vink', 'Laat met bewijs of een berekening zien dat het klopt.', 'Zeg alleen of het klopt.', 'Geef je mening erover.', 'Beschrijf hoe het eruitziet.', 'Aantonen is bewijzen dat iets waar is, met gegevens of een berekening.'],
  [2, 'Citeer', 'boek', 'Schrijf de zin letterlijk over uit de tekst.', 'Zeg het in je eigen woorden.', 'Vat de tekst samen.', 'Leg de zin uit.', 'Citeren is woord voor woord overnemen, tussen aanhalingstekens.'],
  [2, 'Wat is het onderwerp', 'label', 'Waar gaat de tekst over, in een paar woorden?', 'Wat vindt de schrijver ervan?', 'Wat wil de schrijver bereiken?', 'Wie heeft de tekst geschreven?', 'Het onderwerp is waar de tekst over gaat, meestal in een paar woorden.'],
  [2, 'Leid af', 'conclusie', 'Haal uit de gegevens iets wat er niet letterlijk staat.', 'Schrijf de gegevens over.', 'Zoek het op in een ander boek.', 'Geef je eigen mening.', 'Afleiden is uit gegevens iets opmaken wat er niet letterlijk staat.'],
  [2, 'Wat is het verschil', 'weegschaal', 'Waarin zijn de twee dingen anders?', 'Waarin zijn ze hetzelfde?', 'Welke vind je beter?', 'Hoe hangen ze samen?', 'Bij het verschil noem je waarin twee dingen van elkaar afwijken.'],
  [3, 'Analyseer', 'loep', 'Haal het uit elkaar en bekijk de delen en hun samenhang.', 'Vat het kort samen.', 'Geef je mening.', 'Schrijf het over.', 'Analyseren is iets in delen splitsen en kijken hoe die samenhangen.'],
  [3, 'Interpreteer', 'lamp', 'Zeg wat het betekent of hoe je het kunt opvatten.', 'Meet het precies op.', 'Vertaal het letterlijk.', 'Noem de feiten.', 'Interpreteren is betekenis geven aan iets dat niet letterlijk zo gezegd is.'],
  [3, 'Nuanceer', 'weegschaal', 'Laat zien dat het niet zo zwart-wit is.', 'Maak het stelliger.', 'Vat het samen.', 'Herhaal het.', 'Nuanceren is een uitspraak minder absoluut maken: het klopt, maar niet altijd.'],
  [3, 'Definieer', 'boek', 'Geef een precieze omschrijving van het begrip.', 'Geef een voorbeeld.', 'Geef je mening.', 'Vertaal het.', 'Een definitie zegt precies wat een begrip is, zodat het niet met iets anders verward kan worden.'],
  [3, 'Beoordeel', 'ster', 'Geef een oordeel en onderbouw dat.', 'Beschrijf het alleen.', 'Vat het samen.', 'Noem de oorzaak.', 'Beoordelen is zeggen hoe goed of slecht iets is, met redenen.'],
  [3, 'Weerleg', 'kruis', 'Laat met argumenten zien dat het niet klopt.', 'Ondersteun het.', 'Herhaal het.', 'Vat het samen.', 'Weerleggen is aantonen dat een bewering niet klopt.'],
  [3, 'Wat is de strekking', 'kern', 'Wat is de kern van wat er gezegd wordt?', 'Hoe lang is het?', 'Wie zegt het?', 'Welke woorden zijn moeilijk?', 'De strekking is de kern of de bedoeling van een tekst of uitspraak.'],
  [3, 'Wat is de implicatie', 'gevolg', 'Wat volgt hier logisch uit, ook al staat het er niet?', 'Wat staat er letterlijk?', 'Wat is de oorzaak?', 'Wat is het onderwerp?', 'Een implicatie is wat ergens uit volgt zonder dat het letterlijk gezegd wordt.'],
  [3, 'Verifieer', 'vink', 'Controleer of het klopt.', 'Verzin een voorbeeld.', 'Vat het samen.', 'Geef je mening.', 'Verifiëren is nagaan of iets waar is, bijvoorbeeld met een tweede bron.'],
  [3, 'Wat is de relevantie', 'verband', 'Waarom doet dit ertoe voor het onderwerp?', 'Wat kost het?', 'Wie heeft het gezegd?', 'Wanneer is het gebeurd?', 'Relevantie is of iets belangrijk is voor de vraag of het onderwerp.'],
  [3, 'Categoriseer', 'lijst', 'Deel het in groepen in.', 'Zet het op volgorde van grootte.', 'Kies het beste.', 'Leg elk item uit.', 'Categoriseren is indelen in groepen met dezelfde eigenschappen.'],
  [3, 'Relativeer', 'weegschaal', 'Laat zien dat het minder erg of minder belangrijk is dan het lijkt.', 'Maak het erger.', 'Bewijs het.', 'Beschrijf het.', 'Relativeren is iets in verhouding zien: het is minder groot of belangrijk dan het lijkt.'],
  [3, 'Evalueer', 'ster', 'Kijk terug wat goed en minder goed ging en trek daar lessen uit.', 'Vertel alleen wat er gebeurde.', 'Vat het in één zin samen.', 'Zet het op volgorde.', 'Evalueren is terugkijken en de waarde bepalen: wat werkte, wat niet, en wat doe je volgende keer anders.'],
  [3, 'Parafraseer', 'pen', 'Zeg hetzelfde in je eigen woorden.', 'Schrijf het letterlijk over.', 'Maak het korter tot de hoofdzaak.', 'Geef er je mening over.', 'Parafraseren is iets in eigen woorden weergeven, zonder de betekenis te veranderen.'],
  [3, 'Reflecteer', 'oog', 'Kijk kritisch terug op je eigen werk of aanpak.', 'Beoordeel het werk van een ander.', 'Geef een samenvatting van de stof.', 'Zoek bronnen op.', 'Reflecteren is nadenken over je eigen aanpak: wat deed je, waarom, en wat leer je ervan.'],
  [3, 'Specificeer', 'loep', 'Maak het preciezer en noem de details.', 'Maak het algemener.', 'Vat het kort samen.', 'Geef er een oordeel over.', 'Specificeren is iets precies en in detail aangeven.'],
  [3, 'Wat is de aanname', 'argument', 'Wat neemt de schrijver als vanzelfsprekend aan zonder het te bewijzen?', 'Wat is de conclusie van de tekst?', 'Welke bronnen worden genoemd?', 'Wat is het onderwerp?', 'Een aanname is iets wat als waar wordt beschouwd zonder dat het bewezen wordt.'],
  [3, 'Concretiseer', 'pijl', 'Maak het tastbaar met een voorbeeld of een precieze maatregel.', 'Maak het abstracter.', 'Weerleg het.', 'Zet het in een schema.', 'Concretiseren is iets algemeens concreet en tastbaar maken.']
];
var SYN = [
  [1, 'groot', ['enorm', 'reusachtig', 'fors'], ['klein', 'piepklein', 'nietig'], 'Enorm, reusachtig en fors zeggen allemaal dat iets groot is; klein, piepklein en nietig het tegenovergestelde.'],
  [1, 'blij', ['vrolijk', 'opgewekt', 'tevreden'], ['verdrietig', 'somber', 'chagrijnig'], 'Vrolijk en opgewekt lijken op blij; somber en chagrijnig zijn het tegenovergestelde.'],
  [1, 'snel', ['vlug', 'rap', 'gezwind'], ['langzaam', 'traag', 'sloom'], 'Vlug en rap betekenen snel; traag en sloom zijn het tegenovergestelde.'],
  [1, 'moedig', ['dapper', 'stoer', 'onverschrokken'], ['laf', 'bang', 'angstig'], 'Dapper is hetzelfde als moedig; laf en bang zijn het tegenovergestelde.'],
  [1, 'slim', ['pienter', 'intelligent', 'knap'], ['dom', 'onnozel', 'sullig'], 'Pienter en intelligent betekenen slim; dom en onnozel het tegenovergestelde.'],
  [1, 'rijk', ['welgesteld', 'vermogend', 'bemiddeld'], ['arm', 'berooid', 'behoeftig'], 'Welgesteld en vermogend betekenen rijk; arm en berooid het tegenovergestelde.'],
  [1, 'schoon', ['proper', 'netjes', 'fris'], ['vies', 'smerig', 'vuil'], 'Proper en netjes betekenen schoon; vies en smerig het tegenovergestelde.'],
  [1, 'moe', ['uitgeput', 'afgemat', 'doodop'], ['uitgerust', 'fit', 'energiek'], 'Uitgeput en doodop betekenen heel moe; fit en uitgerust het tegenovergestelde.'],
  [1, 'beginnen', ['starten', 'aanvangen', 'van start gaan'], ['stoppen', 'eindigen', 'ophouden'], 'Starten en aanvangen betekenen beginnen; stoppen en eindigen het tegenovergestelde.'],
  [1, 'zacht', ['zachtjes', 'stil', 'gedempt'], ['hard', 'luid', 'oorverdovend'], 'Bij geluid betekent zacht hetzelfde als stil of gedempt; hard en luid zijn het tegenovergestelde.'],
  [1, 'lelijk', ['afzichtelijk', 'onooglijk', 'foeilelijk'], ['mooi', 'prachtig', 'schitterend'], 'Afzichtelijk en foeilelijk betekenen heel lelijk; mooi en prachtig het tegenovergestelde.'],
  [1, 'vriendelijk', ['aardig', 'hartelijk', 'lief'], ['onaardig', 'bot', 'onbeschoft'], 'Aardig en hartelijk betekenen vriendelijk; bot en onbeschoft het tegenovergestelde.'],
  [1, 'goedkoop', ['voordelig', 'betaalbaar', 'spotgoedkoop'], ['duur', 'prijzig', 'peperduur'], 'Voordelig en betaalbaar betekenen goedkoop; duur en prijzig het tegenovergestelde.'],
  [1, 'gevaarlijk', ['riskant', 'link', 'hachelijk'], ['veilig', 'ongevaarlijk', 'onschadelijk'], 'Riskant en hachelijk betekenen gevaarlijk; veilig en onschadelijk het tegenovergestelde.'],
  [1, 'oud', ['bejaard', 'op leeftijd', 'hoogbejaard'], ['jong', 'jeugdig', 'piepjong'], 'Bejaard en op leeftijd betekenen oud (bij mensen); jong en jeugdig het tegenovergestelde.'],
  [1, 'nat', ['vochtig', 'doorweekt', 'drijfnat'], ['droog', 'kurkdroog', 'uitgedroogd'], 'Doorweekt en drijfnat betekenen heel nat; droog en kurkdroog het tegenovergestelde.'],
  [1, 'warm', ['heet', 'zomers', 'broeierig'], ['koud', 'kil', 'ijzig'], 'Heet en broeierig betekenen (heel) warm; koud en ijzig het tegenovergestelde.'],
  [1, 'boos', ['kwaad', 'woedend', 'nijdig'], ['tevreden', 'vrolijk', 'goedgehumeurd'], 'Kwaad en woedend betekenen boos; tevreden en goedgehumeurd het tegenovergestelde.'],
  [1, 'dun', ['mager', 'slank', 'tenger'], ['dik', 'gezet', 'mollig'], 'Mager en slank betekenen dun; dik en mollig het tegenovergestelde.'],
  [2, 'toenemen', ['stijgen', 'groeien', 'oplopen'], ['afnemen', 'dalen', 'slinken'], 'Stijgen en groeien betekenen toenemen; afnemen, dalen en slinken het tegenovergestelde.'],
  [2, 'verplicht', ['noodzakelijk', 'vereist', 'gedwongen'], ['vrijwillig', 'facultatief', 'optioneel'], 'Vereist en gedwongen lijken op verplicht; vrijwillig en optioneel zijn het tegenovergestelde.'],
  [2, 'tijdelijk', ['voorlopig', 'provisorisch', 'kortstondig'], ['blijvend', 'permanent', 'definitief'], 'Voorlopig en kortstondig betekenen tijdelijk; blijvend en permanent het tegenovergestelde.'],
  [2, 'eerlijk', ['oprecht', 'betrouwbaar', 'openhartig'], ['oneerlijk', 'leugenachtig', 'bedrieglijk'], 'Oprecht en openhartig betekenen eerlijk; leugenachtig en bedrieglijk het tegenovergestelde.'],
  [2, 'nauwkeurig', ['precies', 'zorgvuldig', 'exact'], ['slordig', 'onnauwkeurig', 'grof'], 'Precies en zorgvuldig betekenen nauwkeurig; slordig en grof het tegenovergestelde.'],
  [2, 'toestaan', ['toelaten', 'goedkeuren', 'veroorloven'], ['verbieden', 'weigeren', 'afkeuren'], 'Toelaten en goedkeuren betekenen toestaan; verbieden en weigeren het tegenovergestelde.'],
  [2, 'zeldzaam', ['uitzonderlijk', 'ongewoon', 'schaars'], ['gewoon', 'alledaags', 'veelvoorkomend'], 'Ongewoon en schaars betekenen zeldzaam; alledaags en veelvoorkomend het tegenovergestelde.'],
  [2, 'kalm', ['rustig', 'bedaard', 'ontspannen'], ['onrustig', 'nerveus', 'opgewonden'], 'Rustig en bedaard betekenen kalm; nerveus en opgewonden het tegenovergestelde.'],
  [2, 'vermoeden', ['veronderstellen', 'aannemen', 'gissen'], ['weten', 'vaststellen', 'zeker zijn'], 'Veronderstellen en aannemen betekenen vermoeden; weten en vaststellen zijn het tegenovergestelde.'],
  [2, 'uitbreiden', ['vergroten', 'verruimen', 'uitbouwen'], ['inkrimpen', 'verkleinen', 'beperken'], 'Vergroten en verruimen betekenen uitbreiden; inkrimpen en beperken het tegenovergestelde.'],
  [2, 'overeenkomst', ['gelijkenis', 'gemeenschappelijk kenmerk', 'parallel'], ['verschil', 'tegenstelling', 'contrast'], 'Gelijkenis en parallel betekenen overeenkomst; verschil en contrast het tegenovergestelde.'],
  [2, 'winst', ['opbrengst', 'profijt', 'voordeel'], ['verlies', 'tekort', 'schade'], 'Opbrengst en profijt lijken op winst; verlies en tekort zijn het tegenovergestelde.'],
  [2, 'helder', ['duidelijk', 'begrijpelijk', 'glashelder'], ['vaag', 'onduidelijk', 'verwarrend'], 'Duidelijk en begrijpelijk betekenen helder; vaag en verwarrend het tegenovergestelde.'],
  [2, 'aanwezig', ['present', 'erbij', 'ter plaatse'], ['afwezig', 'absent', 'weg'], 'Present en erbij betekenen aanwezig; afwezig en absent het tegenovergestelde.'],
  [2, 'voordeel', ['pluspunt', 'sterk punt', 'gunstige kant'], ['nadeel', 'minpunt', 'zwak punt'], 'Pluspunt en sterk punt betekenen voordeel; nadeel en minpunt het tegenovergestelde.'],
  [2, 'ondersteunen', ['helpen', 'steunen', 'bijstaan'], ['tegenwerken', 'dwarsbomen', 'hinderen'], 'Helpen en bijstaan betekenen ondersteunen; tegenwerken en dwarsbomen het tegenovergestelde.'],
  [2, 'openbaar', ['publiek', 'toegankelijk', 'openlijk'], ['geheim', 'besloten', 'vertrouwelijk'], 'Publiek en toegankelijk betekenen openbaar; geheim en besloten het tegenovergestelde.'],
  [2, 'bescheiden', ['nederig', 'ingetogen', 'terughoudend'], ['opschepperig', 'arrogant', 'verwaand'], 'Nederig en ingetogen betekenen bescheiden; opschepperig en verwaand het tegenovergestelde.'],
  [2, 'bekend', ['beroemd', 'vermaard', 'befaamd'], ['onbekend', 'anoniem', 'obscuur'], 'Beroemd en befaamd betekenen (heel) bekend; onbekend en anoniem het tegenovergestelde.'],
  [3, 'impliciet', ['onuitgesproken', 'verborgen', 'tussen de regels'], ['expliciet', 'uitdrukkelijk', 'letterlijk gezegd'], 'Impliciet is niet letterlijk gezegd; expliciet en uitdrukkelijk zijn het tegenovergestelde.'],
  [3, 'consequent', ['consistent', 'standvastig', 'principieel'], ['inconsequent', 'wispelturig', 'grillig'], 'Consistent en standvastig betekenen consequent; wispelturig en grillig het tegenovergestelde.'],
  [3, 'objectief', ['neutraal', 'onpartijdig', 'zakelijk'], ['subjectief', 'partijdig', 'gekleurd'], 'Neutraal en onpartijdig betekenen objectief; subjectief en gekleurd het tegenovergestelde.'],
  [3, 'abstract', ['theoretisch', 'ongrijpbaar', 'algemeen'], ['concreet', 'tastbaar', 'specifiek'], 'Theoretisch en algemeen liggen dicht bij abstract; concreet en tastbaar zijn het tegenovergestelde.'],
  [3, 'ambivalent', ['tweeslachtig', 'dubbel', 'tegenstrijdig'], ['eenduidig', 'ondubbelzinnig', 'helder'], 'Tweeslachtig en dubbel betekenen ambivalent; eenduidig en ondubbelzinnig het tegenovergestelde.'],
  [3, 'plausibel', ['aannemelijk', 'geloofwaardig', 'waarschijnlijk'], ['onwaarschijnlijk', 'ongeloofwaardig', 'absurd'], 'Aannemelijk en geloofwaardig betekenen plausibel; ongeloofwaardig en absurd het tegenovergestelde.'],
  [3, 'relevant', ['ter zake', 'belangrijk', 'van toepassing'], ['irrelevant', 'onbelangrijk', 'bijkomstig'], 'Ter zake en van toepassing betekenen relevant; irrelevant en bijkomstig het tegenovergestelde.'],
  [3, 'complex', ['ingewikkeld', 'gecompliceerd', 'veelzijdig'], ['eenvoudig', 'simpel', 'overzichtelijk'], 'Ingewikkeld en gecompliceerd betekenen complex; simpel en eenvoudig het tegenovergestelde.'],
  [3, 'authentiek', ['echt', 'oorspronkelijk', 'origineel'], ['nagemaakt', 'vals', 'nep'], 'Echt en oorspronkelijk betekenen authentiek; nagemaakt en vals het tegenovergestelde.'],
  [3, 'optimistisch', ['hoopvol', 'positief', 'zonnig'], ['pessimistisch', 'somber', 'zwartgallig'], 'Hoopvol en positief betekenen optimistisch; pessimistisch en somber het tegenovergestelde.'],
  [3, 'rationeel', ['verstandelijk', 'logisch', 'beredeneerd'], ['emotioneel', 'irrationeel', 'gevoelsmatig'], 'Logisch en beredeneerd betekenen rationeel; emotioneel en gevoelsmatig het tegenovergestelde.'],
  [3, 'progressief', ['vooruitstrevend', 'vernieuwend', 'modern'], ['conservatief', 'behoudend', 'traditioneel'], 'Vooruitstrevend en vernieuwend betekenen progressief; conservatief en behoudend het tegenovergestelde.'],
  [3, 'homogeen', ['gelijksoortig', 'uniform', 'eenvormig'], ['heterogeen', 'gemengd', 'divers'], 'Gelijksoortig en uniform betekenen homogeen; heterogeen en divers het tegenovergestelde.'],
  [3, 'chronisch', ['langdurig', 'aanhoudend', 'blijvend'], ['acuut', 'plotseling', 'kortdurend'], 'Langdurig en aanhoudend betekenen chronisch; acuut en kortdurend het tegenovergestelde.'],
  [3, 'essentieel', ['wezenlijk', 'onmisbaar', 'cruciaal'], ['bijkomstig', 'overbodig', 'onbelangrijk'], 'Wezenlijk en onmisbaar betekenen essentieel; bijkomstig en overbodig het tegenovergestelde.'],
  [3, 'transparant', ['doorzichtig', 'open', 'inzichtelijk'], ['ondoorzichtig', 'geheimzinnig', 'schimmig'], 'Open en inzichtelijk betekenen transparant; ondoorzichtig en schimmig het tegenovergestelde.'],
  [3, 'pragmatisch', ['praktisch', 'realistisch', 'doelgericht'], ['idealistisch', 'theoretisch', 'dogmatisch'], 'Praktisch en realistisch betekenen pragmatisch; idealistisch en dogmatisch staan er tegenover.'],
  [3, 'arbitrair', ['willekeurig', 'toevallig', 'eigenmachtig'], ['weloverwogen', 'gegrond', 'beredeneerd'], 'Willekeurig en toevallig betekenen arbitrair; weloverwogen en gegrond het tegenovergestelde.'],
  [3, 'tolerant', ['verdraagzaam', 'ruimdenkend', 'open'], ['intolerant', 'onverdraagzaam', 'bekrompen'], 'Verdraagzaam en ruimdenkend betekenen tolerant; onverdraagzaam en bekrompen het tegenovergestelde.']
];
return { UIT: UIT, GAT: GAT, SCHOOL: SCHOOL, SYN: SYN };
})();
